<div class="page-header">
    <h1><?= __('UI', 'genericMessage', 'translations') ?></h1>
</div>

<h2>Systèmes d'unités</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\UnitSystem',
         'name',
         'datagrids_translate_unit-system-name',
         'unit'
     )->simple(false);
?>

<h2>Grandeurs physiques</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\PhysicalQuantity',
         'name',
         'datagrids_translate_physical-quantity-name',
         'unit'
     )->simple(false);
?>

<h2>Unités standards (nom)</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\Unit\StandardUnit',
         'name',
         'datagrids_translate_standard-unit-name',
         'unit'
     )->simple(false);
?>

<h2>Unités standards (symbole)</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\StandardUnit',
         'symbol',
         'datagrids_translate_standard-unit-symbol',
         'unit'
     )->simple(false);
?>

<h2>Extensions (nom)</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\UnitExtension',
         'name',
         'datagrids_translate_extension-name',
         'unit'
     )->simple(false);
?>

<h2>Extensions (symbole)</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\UnitExtension',
         'symbol',
         'datagrids_translate_extension-symbol',
         'unit'
     )->simple(false);
?>

<h2>Unités étendues (nom)</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\ExtendedUnit',
         'name',
         'datagrids_translate_extended-unit-name',
         'unit'
     )->simple(false);
?>

<h2>Unités étendues (symbole)</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\ExtendedUnit',
         'symbol',
         'datagrids_translate_extended-unit-symbol',
         'unit'
     )->simple(false);
?>

<h2>Unités discrètes</h2>

<?php
echo $this->translateDatagrid(
         'Unit\Domain\DiscreteUnit',
         'name',
         'datagrids_translate_discrete-unit-name',
         'unit'
     )->simple(false);
?>
