<?php
use User\Domain\User;

/** @var $user User */
$user = $this->user;
if ($this->editSelfEmail) {
    $pageTitle = __('User', 'editProfile', 'pageTitleMyAccount');
} else {
    $pageTitle = __('User', 'editProfile', 'pageTitleSomeoneElsesAccount') . $user->getName();
}
?>

<div class="page-header">
    <h1>
        <i class="fa fa-fw fa-envelope"></i>
        <?=$pageTitle . __('User', 'editEmail', 'pageTitleSuffix')?>
    </h1>
</div>


<div class="well">
    <form id="editEmail" class="form-horizontal" method="post"
          action="user/profile/edit-email?id=<?=$user->getId()?>">

        <?php if ($this->editSelfEmail) : ?>
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    <?=__('User', 'editEmail', 'password')?>
                </label>
                <div class="col-sm-10">
                    <input name="password" type="password" class="form-control" required autocomplete="off">
                </div>
            </div>
        <?php endif; ?>

        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('User', 'editEmail', 'newEmail')?>
            </label>
            <div class="col-sm-10">
                <input name="email" type="email" class="form-control" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">
                    <?=__('UI', 'verb', 'save')?>
                </button>
                <a class="btn btn-default" href="user/profile/edit/id/<?=$user->getId()?>">
                    <?=__('UI', 'other', 'backButton')?>
                </a>
            </div>
        </div>

    </form>
</div>

<script>
    $(function() {
        new AjaxForm('#editEmail');
    })
</script>
