<?php
/** @var $user User\Domain\User */
$user = $this->user;
?>

<div class="page-header">
    <h1>
        <i class="fa fa-fw fa-lock"></i>
        <?=__('User', 'editProfile', 'pageTitleMyAccount') . __('User', 'editPassword', 'pageTitleSuffix')?>
    </h1>
</div>

<div class="well">
    <form id="editPassword" class="form-horizontal" method="post"
          action="user/profile/edit-password?id=<?=$user->getId()?>">

        <div class="form-group">
            <label for="oldPassword" class="col-sm-2 control-label">
                <?=__('User', 'editPassword', 'oldPassword')?>
            </label>
            <div class="col-sm-10">
                <input name="oldPassword" id="oldPassword" type="password" class="form-control" required>
            </div>
        </div>

        <div class="form-group">
            <label for="password" class="col-sm-2 control-label">
                <?=__('User', 'editPassword', 'newPassword')?>
            </label>
            <div class="col-sm-10">
                <input name="password" id="password" type="password" class="form-control" required>
            </div>
        </div>

        <div class="form-group">
            <label for="password2" class="col-sm-2 control-label">
                <?=__('User', 'editPassword', 'confirmNewPassword')?>
            </label>
            <div class="col-sm-10">
                <input name="password2" id="password2" type="password" class="form-control" required>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">
                    <?=__('UI', 'verb', 'save')?>
                </button>
                <a class="btn btn-default" href="user/profile/edit/id/<?=$user->getId()?>">
                    <?=__('UI', 'other', 'backButton')?>
                </a>
            </div>
        </div>

    </form>
</div>

<script>
    $(function() {
        new AjaxForm('#editPassword');
    })
</script>
