<?php
use User\Domain\User;

/** @var $user User */
$user = $this->user;
?>

<div class="page-header">
    <h1><?=__('User', 'editProfile', 'pageTitleMyAccount') . __('User', 'editPassword', 'pageTitleSuffix')?></h1>
</div>

<?php
$form = new UI_Form('editPassword');
$form->setAction('user/profile/edit-password/id/'.$user->getId());
$form->setAjax(true, 'passwordUpdated');

$oldPassword = new UI_Form_Element_Password('oldPassword');
$oldPassword->setLabel(__('User', 'editPassword', 'oldPassword'));
$oldPassword->setRequired();
$form->addElement($oldPassword);

$password = new UI_Form_Element_Password('password');
$password->setLabel(__('User', 'editPassword', 'newPassword'));
$password->setRequired();
$form->addElement($password);

$password2 = new UI_Form_Element_Password('password2');
$password2->setLabel(__('User', 'editPassword', 'confirmNewPassword'));
$password2->setRequired();
$form->addElement($password2);

$form->addSubmitButton();
$form->display();
?>

<script>
    $.fn.passwordUpdated = function (o) {
        window.location = "<?=$this->baseUrl('user/profile/edit/id/' . $user->getId())?>";
    };
</script>
