<?php
use MyCLabs\MUIH\Button;
use User\Domain\User;

/** @var $user User */
$user = $this->user;
if ($this->editSelf) {
    $pageTitle = __('User', 'editProfile', 'pageTitleMyAccount');
} else {
    $pageTitle = __('User', 'editProfile', 'pageTitleSomeoneElsesAccount') . $user->getName();
}
?>

<div class="page-header">
    <h1>
        <i class="fa fa-fw fa-user"></i>
        <?=$pageTitle?>
    </h1>
</div>

<?php
$editLabel = __('UI', 'verb', 'edit');


$form = new UI_Form('userProfile');
$form->setAction('user/profile/edit-submit/id/' . $user->getId());

// Email
$html = <<<HTML
    <div class="input-append">
        <input type="text" id="inputEmail" value="{$user->getEmail()}" disabled class="form-control">
        <a href="{$this->baseUrl()}/user/profile/edit-email/id/{$user->getId()}" class="btn btn-default">
            $editLabel</a>
    </div>
HTML;
$editEmail = new UI_Form_Element_HTML('email', $html);
$editEmail->setLabel( __('User', 'user', 'emailAddress'));
$form->addElement($editEmail);

// Password
if ($this->canEditPassword) {
    $html = <<<HTML
        <a href="{$this->baseUrl()}/user/profile/edit-password/id/{$user->getId()}" class="btn btn-default">
            $editLabel</a>
HTML;
    $editPassword = new UI_Form_Element_HTML('password', $html);
    $editPassword->setLabel(__('User', 'login', 'password'));
    $form->addElement($editPassword);
}

// Prénom
$firstName = new UI_Form_Element_Text('firstName');
$firstName->setLabel(__('User', 'user', 'firstName'));
$firstName->setValue($user->getFirstName());
$form->addElement($firstName);

// Nom
$lastName = new UI_Form_Element_Text('lastName');
$lastName->setLabel(__('User', 'user', 'lastName'));
$lastName->setValue($user->getLastName());
$form->addElement($lastName);

$form->addSubmitButton();

// Désactivation du compte
if ($user->isEnabled() && $this->canDisable) {
    $disableButtonHtml = new UI_Form_Element_HTML('disableButton');
    $disableButton = new Button(__('User', 'editProfile', 'disable'), Button::TYPE_DANGER);
    $disableButton->addClass('disableButton');
    $disableButton->link($this->baseUrl('/user/profile/disable/id/' . $user->getId()));
    $disableButtonHtml->content = $disableButton->render();
    $form->addActionElement($disableButtonHtml);
}

// Réactivation du compte
if (!$user->isEnabled() && $this->canEnable) {
    $disableButtonHtml = new UI_Form_Element_HTML('enableButton');
    $disableButton = new Button(__('User', 'editProfile', 'enable'), Button::TYPE_DANGER);
    $disableButton->addClass('enableButton');
    $disableButton->link($this->baseUrl('/user/profile/enable/id/' . $user->getId()));
    $disableButtonHtml->content = $disableButton->render();
    $form->addActionElement($disableButtonHtml);
}

$form->display();
?>

<script>
    $(function() {
        $(".disableButton").confirm({
            text: "<?=__('User', 'editProfile', 'confirmDisableUser')?>",
            cancelButton: "<?=__('UI', 'verb', 'cancel')?>",
            confirmButton: "<?=__('UI', 'verb', 'confirm')?>"
        });
        $(".enableButton").confirm({
            text: "<?=__('User', 'editProfile', 'confirmEnableUser')?>",
            cancelButton: "<?=__('UI', 'verb', 'cancel')?>",
            confirmButton: "<?=__('UI', 'verb', 'confirm')?>"
        });
    })
</script>
