<?php
use User\Domain\User;
use User\Domain\ACL\AdminRole;
use Account\Domain\ACL\AccountAdminRole;
use Orga\Domain\ACL\WorkspaceAdminRole;
use Orga\Domain\ACL\AbstractCellRole;

/** @var $user User */
$user = $this->user;
if ($this->editSelf) {
    $pageTitle = __('User', 'editProfile', 'pageTitleMyAccount');
} else {
    $pageTitle = __('User', 'editProfile', 'pageTitleSomeoneElsesAccount') . $user->getName();
}
?>

<div class="page-header">
    <h1>
        <i class="fa fa-fw fa-user"></i>
        <?=$pageTitle?>
    </h1>
</div>

<div class="well">
    <form id="editProfile" class="form-horizontal" action="user/profile/edit-submit/id/<?=$user->getId()?>">

        <fieldset>
            <div class="form-group">
                <label for="inputEmail" class="col-sm-2 control-label">
                    <?=__('User', 'user', 'emailAddress')?>
                </label>
                <div class="col-sm-10">
                    <div class="input-group">
                        <input type="email" class="form-control" id="inputEmail" disabled
                               value="<?=$user->getEmail()?>">
                        <span class="input-group-btn">
                            <a class="btn btn-default" href="user/profile/edit-email/id/<?=$user->getId()?>">
                                <?=__('UI', 'verb', 'edit')?>
                            </a>
                        </span>
                    </div>
                </div>
            </div>

            <?php if ($this->canEditPassword) : ?>
                <div class="form-group">
                    <label for="inputPassword" class="col-sm-2 control-label">
                        <?=__('User', 'login', 'password')?>
                    </label>
                    <div class="col-sm-10">
                        <div class="input-group">
                            <input type="password" class="form-control" id="inputPassword" disabled>
                            <span class="input-group-btn">
                                <a class="btn btn-default" href="user/profile/edit-password/id/<?=$user->getId()?>">
                                    <?=__('UI', 'verb', 'edit')?>
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </fieldset>

        <fieldset>
            <div class="form-group">
                <label for="inputFirstName" class="col-sm-2 control-label">
                    <?=__('User', 'user', 'firstName')?>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="firstName" class="form-control" id="inputFirstName"
                           value="<?=$user->getFirstName()?>">
                </div>
            </div>

            <div class="form-group">
                <label for="inputLastName" class="col-sm-2 control-label">
                    <?=__('User', 'user', 'lastName')?>
                </label>
                <div class="col-sm-10">
                    <input type="text" name="lastName" class="form-control" id="inputLastName"
                           value="<?=$user->getLastName()?>">
                </div>
            </div>
        </fieldset>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary"><?=__('UI', 'verb', 'save')?></button>

                <?php if ($user->isEnabled() && $this->canDisable) : ?>
                    <a class="btn btn-danger disableButton" href="user/profile/disable/id/<?=$user->getId()?>">
                        <?=__('User', 'editProfile', 'disable')?>
                    </a>
                <?php endif; ?>
                <?php if (!$user->isEnabled() && $this->canEnable) : ?>
                    <a class="btn btn-danger enableButton" href="user/profile/enable/id/<?=$user->getId()?>">
                        <?=__('User', 'editProfile', 'enable')?>
                    </a>
                <?php endif; ?>
            </div>
        </div>

    </form>
</div>

<?php if ($this->editSelf) : ?>
<div class="page-header">
    <h2>
        <i class="fa fa-fw fa-key"></i>
        <?=__('User', 'editProfile', 'pageSecondTitleMyAccount')?>
    </h2>
</div>
<div class="well">
    <dl class="dl-horizontal">
        <?php foreach ($user->getRoles() as $role) : ?>
            <?php if ($role instanceof AdminRole) : ?>
                <dt>
                </dt>
                <dd>
                    <?=$role->getLabel()?>
                </dd>
            <?php endif; ?>
            <?php if ($role instanceof AccountAdminRole) : ?>
                <dt>
                    <?=$role->getLabel()?>
                </dt>
                <dd>
                    <a href="account/dashboard?id=<?=$role->getAccount()->getId()?>/">
                        <?=$role->getAccount()->getName()?>
                    </a>
                </dd>
            <?php endif; ?>
            <?php if ($role instanceof WorkspaceAdminRole) : ?>
                <dt>
                    <?=$role->getLabel()?>
                </dt>
                <dd>
                    <a href="orga/worksapce/view/workspace/<?=$role->getWorkspace()->getId()?>/">
                        <?=$this->translate($role->getWorkspace()->getLabel())?>
                    </a>
                </dd>
            <?php endif; ?>
            <?php if ($role instanceof AbstractCellRole) : ?>
                <dt>
                    <?=$role->getLabel()?>
                </dt>
                <dd>
                    <a href="orga/cell/view/cell/<?=$role->getCell()->getId()?>/">
                        <?=$this->translate($role->getCell()->getLabel())?>
                    </a>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
    </dl>
</div>
<?php endif; ?>

<script>
    $(function() {
        new AjaxForm('#editProfile');

        $(".disableButton").confirm({
            text: "<?=__('User', 'editProfile', 'confirmDisableUser')?>",
            cancelButton: "<?=__('UI', 'verb', 'cancel')?>",
            confirmButton: "<?=__('UI', 'verb', 'confirm')?>"
        });

        $(".enableButton").confirm({
            text: "<?=__('User', 'editProfile', 'confirmEnableUser')?>",
            cancelButton: "<?=__('UI', 'verb', 'cancel')?>",
            confirmButton: "<?=__('UI', 'verb', 'confirm')?>"
        });
    })
</script>
