<?php
/**
 * @author valentin.claras
 * @author Sidoine.Tardieu
 * @package Classification
 * Contenu de l'onglet des axes
 */
?>
<div class="page-header">
	<h1><?=__('Classification', 'axis', 'pageTitle')?></h1>
</div>
<?
    $treeEdit = new UI_Tree('editAxis', 'tree_axis', 'classification');

    // Caractéristiques du popup d'édition
    $editElements = array();
    $editElements['label'] = new UI_Form_Element_Text('editAxis_label');
    $editElements['label']->setLabel(__('UI', 'name', 'label'));
    $editElements['ref'] = new UI_Form_Element_Text('editAxis_ref');
    $editElements['ref']->setLabel(__('UI', 'name', 'identifier'));
    $editElements['ref']->setAttrib('required', true);

    $addForm = new UI_Form('addAxis');

    $addLabelElement = new UI_Form_Element_Text('label');
    $addLabelElement->setLabel(__('UI', 'name', 'label'));
    $addForm->addElement($addLabelElement);

    $addRefElement = new UI_Form_Element_Text('ref');
    $addRefElement->setLabel(__('UI', 'name', 'identifier'));
    $addRefElement->setAttrib('required', true);
    $addForm->addElement($addRefElement);

    $addParentElement = new UI_Form_Element_Select('refParent');
    $addParentElement->setLabel(__('Classification', 'axis', 'parentAxisLabel'));
    $addParentElement->addNullOption('');
    foreach ($this->listParents as $parentAxis) {
        $optionAxis = new UI_Form_Element_Option($parentAxis->getRef());
        $optionAxis->value = $parentAxis->getRef();
        $optionAxis->label = $parentAxis->getLabel();
        $addParentElement->addOption($optionAxis);
    }
    $addForm->addElement($addParentElement);

    $treeEdit->setEditNode(true, true, $editElements);
    $treeEdit->addPanelTitle = __('Classification', 'axis', 'addPanelTitle');
    $treeEdit->editPanelTitle = __('Classification', 'axis', 'editPanelTitle');
    $treeEdit->changeParentLabel = __('Classification', 'axis', 'parentAxisLabel');
    $treeEdit->addNode = true;
    $treeEdit->addPanelForm = $addForm;
    $treeEdit->deleteNode = true;
    $treeEdit->expandAll = false;
    $treeEdit->collapseAll = false;
    $treeEdit->display();

    $script = '';
    $script .= '$(\'#editAxis_element\').change(function(e) {';
    $script .= 'var idNode = $(this).val();';
    $script .= '$.get(';
    $script .= '\'classification/tree_axis/getinfoedit?idNode=\' + idNode, ';
    $script .= 'function(o){';
    $script .= '$(\'#editAxis_ref\').val(o.ref);';
    $script .= '$(\'#editAxis_label\').val(o.label);';
    $script .= '}';
    $script .= ').error(function(o) {';
    $script .= 'errorHandler(o);';
    $script .= '});';
    $script .= '});';
    $script .= '$(\'#editAxis_addPanel\').on(\'show\', function(e) {';
    $script .= '$.get(';
    $script .= '\'classification/tree_axis/getlistparents?idNode=\', ';
    $script .= 'function(o){';
    $script .= '$(\'#refParent\').formActionSetOptions(o);';
    $script .= '}';
    $script .= ').error(function(o) {';
    $script .= 'errorHandler(o);';
    $script .= '});';
    $script .= '});';
    $script .= 'refFromLabel(\'label\', \'ref\');';
    $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
?>
