<?php
// Popup de reset des Project.
?>
<p>
    <?=__('Orga', 'organizationList', 'analysisDataStatus').__('UI', 'other', ':')?>
    <?php
    if ($this->areProjectDWCubesUpToDate) {
        echo '<i class="icon-ok"></i> '.__('UI', 'property', 'upToDate');
    } else {
        echo '<i class="icon-remove"></i> '.__('UI', 'property', 'notUpToDate');
    }
    ?>
</p>
<p>
    <?=__('Orga', 'organizationList', 'projectRebuildWarningMessage')?>
</p>

<?= $this->button(__('Orga', 'organizationList', 'projectRebuildButton'), 'ok icon-white', array('id' => 'resetDWCubes', 'class' => 'btn-primary')) ?>

<script type="text/javascript">
    $('#resetDWCubes').click(function() {
        $('#listProjects_resetDWCubesAndDatasUpToDate_popup').modal('hide');
        setMask(true);
        $.post(
            'orga/project/resetdwcubes/idProject/<?=$this->idProject?>',
            function(data, textStatus, jqXHR){
                setMask(false);
                addMessage(data.message, 'success');
            }
        ).error(
            function(o) {setMask(false);errorHandler(o);}
        );
    });
</script>
