<?php
// Liste des Project.
?>
<div class="page-header">
    <h1>
        <?=__('Orga', 'name', 'project')?>
    </h1>
</div>

<?php
$datagridProject = new UI_Datagrid('projects', 'datagrid_project', 'orga');

$columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$columnLabel->addable = true;
$datagridProject->addCol($columnLabel);

$columnRootAxes = new UI_Datagrid_Col_Text('rootAxes', __('Orga', 'name', 'rootAxes'));
$columnRootAxes->addable = false;
$datagridProject->addCol($columnRootAxes);

$columnGranularityForInventoryStatus = new UI_Datagrid_Col_Text('granularityForInventoryStatus', __('Orga', 'projectList', 'granularityForInventoryStatus'));
$columnGranularityForInventoryStatus->addable = false;
$datagridProject->addCol($columnGranularityForInventoryStatus);

$columnDetails = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$columnDetails->addable = false;
$datagridProject->addCol($columnDetails);

$datagridProject->deleteElements = $this->isConnectedUserAbleToDeleteProjects;
$datagridProject->pagination = false;
$datagridProject->addElements = $this->isConnectedUserAbleToCreateProjects;
$datagridProject->addPanelTitle = __('Orga', 'projectList', 'addPanelTitle');

$datagridProject->display();