<div class="page-header">
    <h1><?= __('UI', 'genericMessage', 'translations') ?></h1>
</div>

<h2>Systèmes d'unités</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_System',
         'name',
         'datagrids_translate_unit-system-name',
         'unit'
     )->simple(false);
?>

<h2>Grandeurs physiques</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_PhysicalQuantity',
         'name',
         'datagrids_translate_physical-quantity-name',
         'unit'
     )->simple(false);
?>

<h2>Unités standards (nom)</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_Standard',
         'name',
         'datagrids_translate_standard-unit-name',
         'unit'
     )->simple(false);
?>

<h2>Unités standards (symbole)</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_Standard',
         'symbol',
         'datagrids_translate_standard-unit-symbol',
         'unit'
     )->simple(false);
?>

<h2>Extensions (nom)</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_Extension',
         'name',
         'datagrids_translate_extension-name',
         'unit'
     )->simple(false);
?>

<h2>Extensions (symbole)</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_Extension',
         'symbol',
         'datagrids_translate_extension-symbol',
         'unit'
     )->simple(false);
?>

<h2>Unités étendues (nom)</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_Extended',
         'name',
         'datagrids_translate_extended-unit-name',
         'unit'
     )->simple(false);
?>

<h2>Unités étendues (symbole)</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_Extended',
         'symbol',
         'datagrids_translate_extended-unit-symbol',
         'unit'
     )->simple(false);
?>

<h2>Unités discrètes</h2>

<?php
echo $this->translateDatagrid(
         'Unit_Model_Unit_Discrete',
         'name',
         'datagrids_translate_discrete-unit-name',
         'unit'
     )->simple(false);
?>
