<?php
/**
 * @author valentin.claras
 * @author cyril.perraud
 * @package Classif
 * Contenu de l'onglet des membres
 */
?>
<div class="page-header">
	<h1><?=__('Classif', 'contextIndicator', 'contextIndicators')?></h1>
</div>
<?
    $datagrid = new UI_Datagrid('editContextIndicators', 'datagrid_contextindicator', 'classif');

    $columnContext = new UI_Datagrid_Col_List('context', __('Classif', 'name', 'context'));
    $columnContext->list = $this->listContexts;
    $columnContext->editable = false;
    $columnContext->filterName = Classif_Model_Context::QUERY_LABEL;
    $columnContext->entityAlias = Classif_Model_Context::getAlias();
    $datagrid->addCol($columnContext);

    $columnIndicator = new UI_Datagrid_Col_List('indicator', __('Classif', 'name', 'indicator'));
    $columnIndicator->list = $this->listIndicators;
    $columnIndicator->editable = false;
    $columnIndicator->filterName = Classif_Model_Indicator::QUERY_LABEL;
    $columnIndicator->entityAlias = Classif_Model_Indicator::getAlias();
    $datagrid->addCol($columnIndicator);

    $columnAxes = new UI_Datagrid_Col_List('axes', __('UI', 'name', 'axes'));
    $columnAxes->list = $this->listAxes;
    $columnAxes->multiple = true;
    $columnAxes->withEmptyElement = false;
    $columnAxes->editable = true;
    $datagrid->addCol($columnAxes);

    $datagrid->deleteElements = true;
    $datagrid->addElements = true;
    $datagrid->addPanelTitle = __('Classif', 'contextIndicator', 'addPanelTitle');
    $datagrid->display();