<?php
use AF\Domain\Action\Action;
use AF\Domain\Action\SetAlgoValue;
use AF\Domain\Action\SetValue\SetNumericFieldValue;
use AF\Domain\Action\SetValue\SetCheckboxValue;
use AF\Domain\Action\SetValue\Select\SetSelectSingleValue;
use AF\Domain\Component\Select\SelectSingle;
use AF\Domain\Algorithm\Numeric\NumericAlgo;

/** @var $action Action */
$action = $this->action;
$af = $action->getTargetComponent()->getAf();

$locale = Core_Locale::loadDefault();
?>

<form class="form-horizontal" method="post"
      action="af/edit_actions/update-action-submit?idAF=<?=$af->getId()?>&idAction=<?=$action->getId()?>">


    <?php if ($action instanceof SetNumericFieldValue) : ?>
        <?php /** @var $action SetNumericFieldValue */ ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('AF', 'configInteractionDatagrid', 'valueToBeAssignedLabel')?>
            </label>
            <div class="col-sm-10">
                <input name="numericValue" type="text" class="form-control"
                    value="<?=$locale->formatNumberForInput($action->getValue()->getDigitalValue())?>">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('AF', 'configInteractionDatagrid', 'uncertaintyToBeAssignedLabel')?>
            </label>
            <div class="col-sm-10">
                <input name="numericUncertainty" type="text" class="form-control"
                       value="<?=$action->getValue()->getRelativeUncertainty()?>">
            </div>
        </div>
    <?php endif; ?>


    <?php if ($action instanceof SetCheckboxValue) : ?>
        <?php /** @var $action SetCheckboxValue */ ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
            </label>
            <div class="col-sm-10">
                <select name="checkboxValue" class="form-control">
                    <option value="1" <?=$action->getChecked() ? 'selected' : ''?>>
                        <?=__('UI', 'property', 'checked')?>
                    </option>
                    <option value="0" <?=!$action->getChecked() ? 'selected' : ''?>>
                        <?=__('UI', 'property', 'unchecked')?>
                    </option>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <?php if ($action instanceof SetSelectSingleValue) : ?>
        <?php
        /** @var $action SetSelectSingleValue */
        /** @var $selectField SelectSingle */
        $selectField = $action->getTargetComponent();
        $selectedOption = $action->getOption() ? $action->getOption()->getId() : null;
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('AF', 'configInteractionDatagrid', 'valueToBeAssignedLabel')?>
            </label>
            <div class="col-sm-10">
                <select name="selectOptionValue" class="form-control">
                    <option value="" <?=$selectedOption == null ? 'selected' : ''?>></option>
                    <?php foreach ($selectField->getOptions() as $option) : ?>
                        <option value="<?=$option->getId()?>"
                                <?=$selectedOption == $option->getId() ? 'selected' : ''?>>
                            <?=$option->getLabel()?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <?php if ($action instanceof SetAlgoValue) : ?>
        <?php
        /** @var $action SetAlgoValue */
        $selectedAlgo = $action->getAlgo() ? $action->getAlgo()->getId() : null;
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('AF', 'configInteractionDatagrid', 'algorithmToBeAssignedLabel')?>
            </label>
            <div class="col-sm-10">
                <select name="algoSelect" class="form-control">
                    <option value="" <?=$selectedAlgo == null ? 'selected' : ''?>></option>
                    <?php foreach ($af->getAlgos() as $algo) : ?>
                        <?php if ($algo instanceof NumericAlgo) : ?>
                            <option value="<?=$algo->getId()?>"
                                    <?=$selectedAlgo == $algo->getId() ? 'selected' : ''?>>
                                <?=$algo->getLabel()?>
                            </option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary"><?=__('UI', 'verb', 'save')?></button>
        </div>
    </div>

</form>
