<?php
/** @var $user User_Model_User */
$user = $this->user;
if ($this->editSelfEmail) {
    $pageTitle = __('User', 'editProfile', 'pageTitleMyAccount');
} else {
    $pageTitle = __('User', 'editProfile', 'pageTitleSomeoneElsesAccount') . $user->getName();
}
?>

<div class="page-header">
    <h1><?=$pageTitle . __('User', 'editEmail', 'pageTitleSuffix')?></h1>
</div>

<?php
$form = new UI_Form('editEmail');
$form->setAction('user/profile/edit-email/id/'.$user->getId());
$form->setAjax(true, 'emailUpdated');

$oldEmail = new UI_Form_Element_Pattern_Email('oldEmail');
$oldEmail->setLabel(__('User', 'editEmail', 'oldEmail'));
$oldEmail->setAttrib('readonly', 'readonly');
$oldEmail->setValue($user->getEmail());
$form->addElement($oldEmail);

if ($this->editSelfEmail) {
    $pwd = new UI_Form_Element_Password('password');
    $pwd->setLabel(__('User', 'editEmail', 'password'));
    $pwd->setRequired();
    $form->addElement($pwd);
}

$email = new UI_Form_Element_Pattern_Email('email');
$email->setLabel(__('User', 'editEmail', 'newEmail'));
$email->setRequired();
$form->addElement($email);

$email2 = new UI_Form_Element_Pattern_Email('email2');
$email2->setLabel(__('User', 'editEmail', 'confirmNewEmail'));
$email2->setRequired();
$form->addElement($email2);

$form->addSubmitButton();
$form->display();
?>

<script>
    $.fn.emailUpdated = function (o) {
        window.location = "<?=$this->baseUrl('user/profile/edit/id/' . $user->getId())?>";
    };
</script>
