<h2><?=__('User', 'list', 'pageTitle')?></h2>

<?php
$datagrid = new UI_Datagrid('users', 'datagrid_user-list', 'user');
$datagrid->pagination = true;
$datagrid->setDefaultSorting('creationDate', UI_Datagrid::TYPE_SORT_DESC);
if ($this->canCreateUsers) {
    $datagrid->addElements = true;
    $datagrid->addPanelTitle = __('User', 'list', 'addPanelTitle');
    $datagrid->addButtonLabel = __('UI', 'verb', 'add');
}

// Prénom
$colFirstName = new UI_Datagrid_Col_Text('prenom', __('User', 'name', 'firstName'));
$colFirstName->filterName = User_Model_User::QUERY_FIRSTNAME;
$colFirstName->sortName = User_Model_User::QUERY_FIRSTNAME;
$datagrid->addCol($colFirstName);

// Nom
$colLastName = new UI_Datagrid_Col_Text('nom', __('User', 'name', 'lastName'));
$colLastName->filterName = User_Model_User::QUERY_LASTNAME;
$colLastName->sortName = User_Model_User::QUERY_LASTNAME;
$datagrid->addCol($colLastName);

// Courriel
$colEmail = new UI_Datagrid_Col_Text('email', __('UI', 'name', 'emailAddress'));
$colEmail->filterName = User_Model_User::QUERY_EMAIL;
$colEmail->sortName = User_Model_User::QUERY_EMAIL;
$datagrid->addCol($colEmail);

// Date de création
$colCreationDate = new UI_Datagrid_Col_Date('creationDate', __('UI', 'name', 'creationDate'));
$colCreationDate->sortName = User_Model_User::QUERY_CREATIONDATE;
$colCreationDate->filterName = User_Model_User::QUERY_CREATIONDATE;
$colCreationDate->addable = false;
$datagrid->addCol($colCreationDate);

// 1ère connexion
$colEmailValidated = new UI_Datagrid_Col_Bool('emailValidated', __('User', 'list', 'firstConnectionHeader'));
$colEmailValidated->addable = false;
$colEmailValidated->valueTrue = '<i class="icon-ok"></i> '.__('User', 'property', 'performedFem');
$colEmailValidated->valueFalse = '<i class="icon-remove"></i> '.__('User', 'property', 'notPerformedFem');
$datagrid->addCol($colEmailValidated);

// Compte activé
$colEnabled = new UI_Datagrid_Col_Bool('enabled', __('UI', 'name', 'activation'));
$colEnabled->addable = false;
$colEnabled->valueTrue = '<i class="icon-ok"></i> '.__('UI', 'property', 'enabled');
$colEnabled->valueFalse = '<i class="icon-remove"></i> '.__('UI', 'property', 'disabled');
$datagrid->addCol($colEnabled);

// Rôles
$colRoles = new UI_Datagrid_Col_Text('roles', __('User', 'name', 'roles'));
$colRoles->addable = false;
$datagrid->addCol($colRoles);

// Details vers la page du compte utilisateur
$colDetailsUser = new UI_Datagrid_Col_Link('detailsUser', __('UI', 'name', 'edition'));
$datagrid->addCol($colDetailsUser);

$datagrid->display();
