<?php
/**
 * @author matthieu.napoli
 * @package Techno
 */

/** @var $element Techno_Model_Element_Coeff|Techno_Model_Element_Process */
$element = $this->element;

if ($element instanceof Techno_Model_Element_Process) {
    $title = __('Techno', 'name', 'emissionFactor');
} else {
    $title = __('Techno', 'name', 'coefficient');
}
?>

<div class="page-header">
    <h1><?=$title?></h1>
</div>

<?php
$editForm = new UI_Form('editElement');
$editForm->setAction($this->baseUrl('techno/element/edit-submit'));
$editForm->setAjax(true);

// Unité
$unitField = new UI_Form_Element_Text('unit');
$unitField->setLabel(__('Unit', 'name', 'unit'));
$unitField->setValue($element->getUnit()->getRef());
$editForm->addElement($unitField);

// Valeur
$digitalValueField = new UI_Form_Element_Text('digitalValue');
$digitalValueField->setLabel(__('UI', 'name', 'value'));
$digitalValueField->setValue($element->getValue()->digitalValue);
$editForm->addElement($digitalValueField);

// Incertitude
$uncertaintyField = new UI_Form_Element_Text('uncertainty');
$uncertaintyField->setLabel(__('UI', 'name', 'uncertainty'));
$uncertaintyField->setValue($element->getValue()->relativeUncertainty);
$editForm->addElement($uncertaintyField);

// Documentation
$documentationField = new UI_Form_Element_Textarea('documentation');
$documentationField->setLabel(__('UI', 'name', 'documentation'));
$documentationField->setValue($element->getDocumentation());
$documentationField->setAttrib('rows', 7);
$editForm->addElement($documentationField);

// Valeur
$elementIdField = new UI_Form_Element_Hidden('id');
$elementIdField->setValue($element->getId());
$editForm->addElement($elementIdField);

$editForm->addSubmitButton();
$editForm->addResetButton();
$editForm->display();
