<?php
/**
 * @author valentin.claras
 * @package Techno
 * Traduction des Family
 */
?>

<div class="page-header">
    <h1>
        <?= __('Techno', 'translate', 'familyDocumentations') ?>
        <small><?=__('UI', 'name', 'translations')?></small>
    </h1>
</div>

<?php
echo $this->translateDatagrid(
    'Techno\Domain\Family\Family',
    'label',
    'datagrid_translate_families_documentation',
    'techno'
)->addIdentifierCol()->addLanguagesLongTextCols();
