<?php
// Fichier contenant le fil d'arian de l'application.
$breadcrumb = array();
?>
<?php if (!empty($breadcrumb)) { ?>
        <ul class="breadcrumb">
<?php   foreach ($breadcrumb as $node) {
            if ($node == end($breadcrumb)) {
                $activeClass = ' class="active"';
                $dividerSpan = '';
            } else {
                $activeClass = '';
                $dividerSpan = '<span class="divider">/</span>';
            }
?>
            <li<?=$activeClass?>><a href="<?=$node['url']?>"><?=$node['name']?></a><?=$dividerSpan?></li>
<?php   } ?>
        </ul>
<?php } ?>
