<?php
if (Zend_Auth::getInstance()->hasIdentity()) {
    try {
        /** @var User_Model_User $connectedUser */
        $connectedUser = User_Model_User::load(Zend_Auth::getInstance()->getIdentity());
    } catch (Core_Exception_NotFound $e) {
        $connectedUser = null;
    }
} else {
    $connectedUser = null;
}
?>
<footer>

    <div class="feedback-form"></div>
    <script>
        $(function() {
            var url = "<?=$this->baseUrl('feedback/submit')?>";
            <?php
            if ($connectedUser) {
                $userEmail = $connectedUser->getEmail();
                echo "var data = {user: '$userEmail'};";
            } else {
                echo "var data = {};";
            }
            ?>
            $(".feedback-form").feedbackForm(url, data);
        });
    </script>

</footer>
