<?php
use Orga\Domain\ACL\AbstractCellRole;
/** @var AbstractCellRole[] $cellUsers */
$cellUsers = $this->cellUsers;
?>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                <?=___('User', 'user', 'firstName')?>
            </th>
            <th>
                <?=___('User', 'user', 'lastName')?>
            </th>
            <th>
                <?=___('User', 'user', 'emailAddress')?>
            </th>
            <th>
                <?=___('User', 'role', 'role')?>
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($cellUsers as $cellRole): ?>
        <tr>
            <td>
                <?=$cellRole->getSecurityIdentity()->getFirstName()?>
            </td>
            <td>
                <?=$cellRole->getSecurityIdentity()->getLastName()?>
            </td>
            <td>
                <?=$cellRole->getSecurityIdentity()->getEmail()?>
            </td>
            <td>
                <?=$cellRole->getLabel()?>
            </td>
            <td>
                <a href="orga/cell/edit-user/cell/<?=$this->cellId?>/role/<?=$cellRole->getId()?>/"
                   class="edit-user withTooltip"
                   title="<?=___('Orga', 'role', 'editRole')?>"
                   data-firstname="<?=$cellRole->getSecurityIdentity()->getFirstName()?>"
                   data-lastname="<?=$cellRole->getSecurityIdentity()->getLastName()?>">
                    <i class="fa fa-pencil-square-o"></i>
                </a>
                <a href="orga/cell/remove-user/cell/<?=$this->cellId?>/role/<?=$cellRole->getId()?>/"
                   class="delete-user withTooltip"
                   title="<?=___('Orga', 'role', 'deleteRole')?>">
                    <i class="fa fa-trash-o"></i>
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script>
    $('#users<?=$this->cellId?> .withTooltip').tooltip({placement: 'left'});
</script>
