<?php
/**
 * @author matthieu.napoli
 * @author hugo.charbonnier
 * @package AF
 */
/** @var $af AF_Model_AF */
$af = $this->af;
$script = '';


// Groupes
$groups = new UI_HTML_Collapse('groups');
$groups->foldedByDefault = true;
$groups->title = __('AF', 'configComponentCollapse', 'groupCollapse');
$groups->body = $this->partial('edit/components/groups.phtml', array('af' => $this->af));
echo $groups->render();

$script .= <<<JS
$('#groups').on('show', function(e) {
    if ($(e.target).attr('id') == 'groups_wrapper') {
        groupDatagrid.filter();
    }
});
JS;


// Sous-formulaires
$subAF = new UI_HTML_Collapse('subAF');
$subAF->foldedByDefault = true;
$subAF->title = __('AF', 'configComponentCollapse', 'subFormCollapse');
$subAF->body = $this->partial('edit/components/sub-af.phtml', array('af' => $this->af));
echo $subAF->render();

$script .= <<<JS
$('#subAF').on('show', function(e) {
    if ($(e.target).attr('id') == 'subAF_wrapper') {
        subAfDatagrid.filter();
    }
});
JS;


// Champs numériques
$numericFields = new UI_HTML_Collapse('numericFields');
$numericFields->foldedByDefault = true;
$numericFields->title = __('AF', 'configComponentCollapse', 'numericInputFieldCollapse');
$numericFields->body = $this->partial('edit/components/numeric-fields.phtml', array('af' => $this->af));
echo $numericFields->render();

$script .= <<<JS
$('#numericFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'numericFields_wrapper') {
        numericFieldDatagrid.filter();
    }
});
JS;


// Champs de sélection simple
$selectSingleFields = new UI_HTML_Collapse('selectSingleFields');
$selectSingleFields->foldedByDefault = true;
$selectSingleFields->title = __('AF', 'configComponentCollapse', 'singleSelectionFieldCollapse');
$selectSingleFields->body = $this->partial('edit/components/select-single-fields.phtml', array('af' => $this->af));
echo $selectSingleFields->render();

$script .= <<<JS
$('#selectSingleFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'selectSingleFields_wrapper') {
        selectSingleFieldDatagrid.filter();
    }
});
JS;


// Champs de sélection multiple
$selectMultiFields = new UI_HTML_Collapse('selectMultiFields');
$selectMultiFields->foldedByDefault = true;
$selectMultiFields->title = __('AF', 'configComponentCollapse', 'multipleSelectionFieldCollapse');
$selectMultiFields->body = $this->partial('edit/components/select-multi-fields.phtml', array('af' => $this->af));
echo $selectMultiFields->render();

$script .= '$(\'#selectMultiFields\').on(\'show\', function(e) {';
$script .= 'if ($(e.target).attr(\'id\') == \'selectMultiFields_wrapper\') {';
$script .= 'selectMultiFieldDatagrid.filter();';
$script .= '}';
$script .= '});';

$script .= <<<JS
$('#selectSingleFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'selectSingleFields_wrapper') {
        selectSingleFieldDatagrid.filter();
    }
});
JS;


// Checkbox
$checkboxFields = new UI_HTML_Collapse('checkboxFields');
$checkboxFields->foldedByDefault = true;
$checkboxFields->title = __('AF', 'configComponentCollapse', 'booleanFieldCollapse');
$checkboxFields->body = $this->partial('edit/components/checkbox-fields.phtml', array('af' => $this->af));
echo $checkboxFields->render();

$script .= <<<JS
$('#checkboxFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'checkboxFields_wrapper') {
        checkboxFieldDatagrid.filter();
    }
});
JS;


echo '<script type="text/javascript">/*<![CDATA[*/'.$script.'/*]]>*/</script>';
