<?php
use Orga\Application\Service\Workspace\WorkspaceService;
?>

<style>
    #workspaceSteps .step-separator { color: #999999; line-height: 20px; padding: 9px 10px 10px; }
    .navigation-buttons { margin: 10px 0; }
</style>

<form class="form form-horizontal" id="addWorkspace" action="orga/workspace/add-submit/account/<?=$this->account?>/">
    <ul class="nav nav-tabs" id="workspaceSteps">
        <li class="active"><a href="#workspace"><?=___('Orga', 'add', 'workspace')?></a></li>
        <li class="step-separator hide">>>></li>
        <li class="disabled hide"><a href="#axes"><?=___('Orga', 'add', 'axes')?></a></li>
        <li class="step-separator hide">>>></li>
        <li class="disabled hide"><a href="#members"><?=___('Orga', 'add', 'members')?></a></li>
        <li class="step-separator hide">>>></li>
        <li class="disabled hide"><a href="#inventory"><?=___('Orga', 'add', 'inventory')?></a></li>
        <li class="step-separator hide">>>></li>
        <li class="disabled hide"><a href="#acl"><?=___('Orga', 'add', 'acl')?></a></li>
        <li class="step-separator hide">>>></li>
        <li class="disabled hide"><a href="#reports"><?=___('Orga', 'add', 'reports')?></a></li>
        <li class="step-separator">>>></li>
        <li class="disabled"><a href="#validation"><?=___('Orga', 'add', 'validation')?></a></li>
    </ul>

    <div>

        <div class="navigation-buttons">
            <button class="btn btn-default btn-sm navigation-previous hide" type="button">
                <i class="fa fa-chevron-left"></i> <?=___('Orga', 'add', 'navigationPrevious')?>
            </button>
            <button class="btn btn-primary btn-sm navigation-next" type="button">
                <?=___('Orga', 'add', 'navigationNext')?> <i class="fa fa-chevron-right"></i>
            </button>
            <button class="btn btn-primary btn-sm navigation-end hide" type="button">
                <?=___('Orga', 'add', 'navigationEnd')?> <i class="fa fa-check"></i>
            </button>
        </div>

        <div class="tab-content">
            <div class="tab-pane active" id="workspace">
                <div class="form-group">
                    <label class="control-label col-sm-2" for="workspaceLabel">
                        <?=___('Orga', 'add', 'workspaceLabel')?>
                    </label>
                    <div class="col-sm-10">
                        <input type="text" id="workspaceLabel" name="workspaceLabel" placeholder="<?=___('Orga', 'add', 'workspaceLabelPlaceholder')?>" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="workspaceTemplate">
                        <?=___('Orga', 'add', 'workspaceTemplate')?>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="<?=___('Orga', 'add', 'workspaceTemplateExplanation')?>">
                            <i class="fa fa-question-circle"></i>
                        </a>
                    </label>
                    <div class="col-sm-10">
                        <select id="workspaceTemplate" name="workspaceTemplate" class="form-control">
                            <?php foreach ($this->templates as $templateRef => $templateName) : ?>
                            <option value="<?=$templateRef?>"><?=$templateName?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="axes">
                <div class="alert alert-warning">
                    <strong><?=___('Orga', 'add', 'warning')?> :</strong>
                    <?=___('Orga', 'add', 'resetAfterAxesStep')?>
                </div>
                <fieldset>
                    <legend><?=___('Orga', 'add', 'workspaceMainAxisTitle')?></legend>
                    <div class="form-group" data-level="1">
                        <label class="control-label col-sm-2" for="mainAxis">
                            <?=___('Orga', 'add', 'workspaceMainAxisLabel')?>
                        </label>
                        <div class="col-sm-10">
                            <div class="input-group">
                                <input type="text" id="mainAxis" name="mainAxis" placeholder="<?=___('Orga', 'add', 'workspaceMainAxisPlaceholder')?>" class="form-control" required>
                                <span class="input-group-btn">
                                    <button class="btn btn-default addAggregation"><i class="fa fa-plus"></i> <?=___('Orga', 'add', 'workspaceAddMainSubAxis')?></button>
                                </span>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend><?=___('Orga', 'add', 'workspaceTimeAxisTitle')?></legend>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="timeAxis"><?=___('Orga', 'add', 'workspaceTimeAxisLabel')?></label>
                        <div class="col-sm-10">
                            <input type="text" id="timeAxis" name="timeAxis" placeholder="<?=___('Orga', 'add', 'workspaceTimeAxisPlaceholder')?>" class="form-control" required>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend><?=___('Orga', 'add', 'workspaceInputsAxisTitle')?></legend>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="subdivisionAxis"><?=___('Orga', 'add', 'workspaceInputsAxisLabel')?></label>
                        <div class="col-sm-10">
                            <input type="text" id="subdivisionAxis" name="subdivisionAxis" placeholder="<?=___('Orga', 'add', 'workspaceInputsAxisPlaceholder')?>" class="form-control">
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="tab-pane" id="members">
            </div>
            <div class="tab-pane" id="inventory">
                <fieldset>
                    <legend><?=___('Orga', 'add', 'inventoryGranularityTitle')?></legend>
                    <div class="form-group">
                        <div class="col-sm-12"></div>
                    </div>
                </fieldset>
            </div>
            <div class="tab-pane" id="acl">
                <fieldset>
                    <legend><?=___('Orga', 'add', 'aclGranularitiesTitle')?></legend>
                    <div>
                        <div class="form-group">
                            <div class="col-sm-12"></div>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="tab-pane" id="reports">
                <fieldset>
                    <legend><?=___('Orga', 'add', 'reportsGranularitiesTitle')?></legend>
                    <div class="form-group">
                        <div class="col-sm-12"></div>
                    </div>
                </fieldset>
            </div>
            <div class="tab-pane" id="validation">
                <div class="alert alert-info"><?=___('Orga', 'add', 'addValidationMessage')?></div>
                <fieldset class="workspace-summary">
                    <legend><?=___('Orga', 'add', 'addValidationTitle')?></legend>
                    <ul>
                    </ul>
                </fieldset>
                <div class="members-summary">
                </div>
                <div class="granularities-summary">
                </div>
            </div>
        </div>

        <div class="navigation-buttons">
            <button class="btn btn-default btn-sm navigation-previous hide" type="button">
                <i class="fa fa-chevron-left"></i> <?=___('Orga', 'add', 'navigationPrevious')?>
            </button>
            <button class="btn btn-primary btn-sm navigation-next" type="button">
                <?=___('Orga', 'add', 'navigationNext')?> <i class="fa fa-chevron-right"></i>
            </button>
            <button class="btn btn-primary btn-sm navigation-end hide" type="button">
                <?=___('Orga', 'add', 'navigationEnd')?> <i class="fa fa-check"></i>
            </button>
        </div>

    </div>
</form>

<div id="workspaceBuilding" class="modal fade" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3><?=___('Orga', 'add', 'workspaceBuildingPopupTitle')?></h3>
            </div>
            <div class="modal-body">
                <div class="alert alert-info">
                    <i class="fa fa-spinner fa-spin"></i>
                    <?=___('Orga', 'add', 'workspaceBuildingMessage')?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var globalAxisCounter = 0;
    var globalMemberCounter = 0;

    $('#workspaceSteps a').click(function(e) { e.preventDefault(); });

    $('#addWorkspace .navigation-previous').on('click', function(e) {
        e.preventDefault();
        $('#workspaceSteps li.active').addClass('disabled');
        $('#workspaceSteps li.active').prevAll(':not(.hide):not(.step-separator):first').children('a').tab('show');
        $('#workspaceSteps li.active').removeClass('disabled');
        $("html, body").animate({ scrollTop: 0 }, "slow");
    });
    $('#addWorkspace .navigation-next').on('click', function(e) {
        e.preventDefault();
        if (validateActiveTab()) {
            $('#workspaceSteps li.active').addClass('disabled');
            $('#workspaceSteps li.active').nextAll(':not(.hide):not(.step-separator):first').children('a').tab('show');
            $('#workspaceSteps li.active').removeClass('disabled');
            $("html, body").animate({ scrollTop: 0 }, "slow");
        }
    });
    $('#addWorkspace .navigation-end').on('click', function(e) {
        e.preventDefault();
        $('#workspaceBuilding').modal('show');
        $.ajax({
            url: $('#addWorkspace').attr('action'),
            type: 'POST',
            data: parseFormData(),
            success: function(data){
                $('#addWorkspace').parseFormValidation(data);
                $('#workspaceBuilding .modal-content .modal-body').html(
                    '<div class="alert alert-' + data.type + '">' +
                        data.message +
                    '</div>' +
                    '<hr />' +
                    '<p>' + data.info + '</p>'
                );
                $('#workspaceBuilding .modal-content').append(
                    '<div class="modal-footer">' +
                        '<a class="btn btn-primary pull-left" href="account/dashboard/">' +
                            '<i class="fa fa-home"></i> ' +
                            '<?=___('Orga', 'add', 'workspaceBuildingGoHome')?>' +
                        '</a> ' +
                        '<a class="btn btn-default pull-right" href="orga/workspace/add/account/<?=$this->account?>/">' +
                            '<i class="fa fa-plus"></i> ' +
                            '<?=___('Orga', 'add', 'workspaceBuildingAddMore')?>' +
                        '</a> ' +
                    '</div>'
                );
            },
            error: function(jqXHR) {
                $('#addWorkspace').parseFormErrors(jqXHR);
                var response = $.parseJSON(jqXHR.responseText);

                var errorType = 'error';
                if (typeof(response.typeError) == 'string') {
                    errorType = response.typeError;
                }
                var message = '<?=___('Orga', 'add', 'errorWhileCreatingWorkspace')?>';
                if (typeof(response.message) == 'string') {
                    message = response.message;
                }
                var complementaryInfo = '<?=___('Orga', 'add', 'workspaceTryAgainOrContactAdministrators')?>';
                if (typeof(response.info) == 'string') {
                    complementaryInfo = response.complementary;
                }
                $('#workspaceBuilding .modal-body').html(
                    '<div class="alert alert-' + errorType + '">' +
                        message +
                    '</div>' +
                    '<hr />' +
                    '<p>' + complementaryInfo + '</p>' +
                    '<a class="btn btn-warning pull-right" href="#workspaceBuilding" data-dismiss="modal">' +
                        '<i class="fa fa-minus"></i> ' +
                        '<?=___('Orga', 'add', 'workspaceBuildingClosePopup')?>' +
                    '</a>' +
                    '<a class="btn btn-primary pull-left" href="orga/workspace">' +
                        '<i class="fa fa-home"></i> ' +
                        '<?=___('Orga', 'add', 'workspaceBuildingGoHome')?>' +
                    '</a>'
                );
            }
        });
    });
    $('#workspaceBuilding').on('hidden.bs.modal', function() {
        $('#workspaceBuilding .modal-body').html(
            '<div class="alert alert-info">' +
                '<i class="fa fa-spinner fa-spin"></i>' +
                ' <?=___('Orga', 'add', 'workspaceBuildingMessage')?>' +
            '</div>'
        );
    });

    $('#workspaceSteps a').on('shown.bs.tab', function (e) {
        var currentTab = $(this);
        var firstTab = $('#workspaceSteps li:first a');
        var lastTab = $('#workspaceSteps li:not(.hide):last a');
        var previousButton = $('.navigation-previous');
        var nextButton = $('.navigation-next');
        var endButton = $('.navigation-end');
        previousButton.removeClass('hide');
        nextButton.removeClass('hide');
        endButton.removeClass('hide');
        if (currentTab[0] == firstTab[0]) {
            previousButton.addClass('hide');
            endButton.addClass('hide');
        } else if (currentTab[0] == lastTab[0]) {
            nextButton.addClass('hide');
        } else {
            endButton.addClass('hide');
        }
    });

    $('#workspaceTemplate').on('change', function() {
        var axesStep = $('#workspaceSteps li a[href="#axes"]').parent();
        var membersStep = $('#workspaceSteps li a[href="#members"]').parent();
        var inventoryStep = $('#workspaceSteps li a[href="#inventory"]').parent();
        var aclStep = $('#workspaceSteps li a[href="#acl"]').parent();
        var reportsStep = $('#workspaceSteps li a[href="#reports"]').parent();

        var workspaceTemplate = $('#workspaceTemplate').val();

        axesStep.removeClass('hide');
        axesStep.prev().removeClass('hide');
        membersStep.removeClass('hide');
        membersStep.prev().removeClass('hide');
        inventoryStep.removeClass('hide');
        inventoryStep.prev().removeClass('hide');
        aclStep.removeClass('hide');
        aclStep.prev().removeClass('hide');
        reportsStep.removeClass('hide');
        reportsStep.prev().removeClass('hide');

        if ((workspaceTemplate != '<?=WorkspaceService::TEMPLATE_USER_INVENTORY?>')
            && (workspaceTemplate != '<?=WorkspaceService::TEMPLATE_USER_REPORTING?>')) {
            axesStep.addClass('hide');
            axesStep.prev().addClass('hide');
            membersStep.addClass('hide');
            membersStep.prev().addClass('hide');
            inventoryStep.addClass('hide');
            inventoryStep.prev().addClass('hide');
            aclStep.addClass('hide');
            aclStep.prev().addClass('hide');
            reportsStep.addClass('hide');
            reportsStep.prev().addClass('hide');
        }

        if (workspaceTemplate == '<?=WorkspaceService::TEMPLATE_USER_INVENTORY?>') {
            reportsStep.addClass('hide');
            reportsStep.prev().addClass('hide');
        }
    });

    $('#addWorkspace').on('click', '.addAggregation', function(e) {
        e.preventDefault();
        globalAxisCounter++;
        var row = $(this).closest('.form-group');
        var parentAxisId = $('input[type="text"]', row).attr('id');
        var level = row.attr('data-level') * 1;
        var identifier = 'mainAxis' + globalAxisCounter;
        row.after(
            '<div class="form-group" data-level="' + (level + 1) + '">' +
                '<label class="control-label col-sm-2 col-sm-offset-' + level + '" for="' + identifier + '"><?=___('Orga', 'add', 'workspaceMainSubAxisLabel')?></label>' +
                '<div class="col-sm-' + (10 - level) + '">' +
                    '<input type="hidden" id="' + identifier + '" name="' + identifier + '-parent" value="' + parentAxisId + '">' +
                    '<div class="input-group">' +
                        '<input type="text" id="' + identifier + '" name="' + identifier + '" placeholder="<?=___('Orga', 'add', 'workspaceMainSubAxisPlaceholder')?>" class="form-control">' +
                        '<span class="input-group-btn">' +
                            '<button class="btn btn-default removeAggregation"><i class="fa fa-minus"></i></button>' +
                        '</span>' +
                        ((level < 8) ?
                            (
                            '<span class="input-group-btn">' +
                                '<button class="btn btn-default addAggregation"><i class="fa fa-plus"></i></button>' +
                            '</span>'
                            )
                            : ''
                        ) +
                    '</div>' +
                '</div>' +
            '</div>'
        );
    });
    $('#addWorkspace').on('click', '.removeAggregation', function(e) {
        e.preventDefault();
        var row = $(this).closest('.form-group');
        row.nextUntil('[data-level="' + row.attr('data-level') + '"]').each(function() {
            if ($(this).attr('data-level') >= row.attr('data-level')) {
                $(this).attr('data-level', ($(this).attr('data-level') * 1 - 1));
                var label = $('label', $(this));
                label.removeClass('col-sm-offset-' + $(this).attr('data-level'));
                label.addClass('col-sm-offset-' + ($(this).attr('data-level') * 1 - 1));
                var div = $('div.col-sm-' + (10 - $(this).attr('data-level') * 1), $(this));
                div.removeClass('col-sm-' + (10 - $(this).attr('data-level') * 1));
                div.addClass('col-sm-' + (10 - $(this).attr('data-level') * 1 + 1));
                if ($('.addAggregation', $(this)).length == 0) {
                    $('div.input-group', $(this)).append(
                        '<span class="input-group-btn">' +
                            '<button class="btn btn-default addAggregation"><i class="fa fa-plus"></i></button>' +
                        '</span>'
                    );
                }
            }
        });
        row.remove();
    });
    $('#addWorkspace').on('click', '.addMember', function(e) {
        e.preventDefault();
        globalMemberCounter++;
        var row = $(this).closest('.form-group');
        var identifier = 'member' + globalMemberCounter;
        var parentMembersNumber = 0;
        var parentMembers = '';
        $.each($(this).attr('data-parent-axes').split('|'), function() {
            if (this != '') {
                parentMembersNumber++;
                parentMembers +=
                    '<div class="col-sm-2">' +
                        '<select data-axis="' + this + '" name="' + identifier+ '-parent][' + this + '" class="form-control">' +
                        '</select>' +
                    '</div>';
            }
        });
        row.before(
            '<div class="form-group">' +
                '<div class="col-sm-' + (12 - 2 * parentMembersNumber) + '">' +
                    '<input type="text" name="' + identifier + '" class="form-control">' +
                '</div>' +
                parentMembers +
            '</div>'
        );
        $.each($(this).attr('data-parent-axes').split('|'), function() {
            if (this != '') {
                $('#members fieldset[data-axis="' + this + '"] input').trigger('change');
            }
        });
    });
    $('#members').on('change', 'input', function(e) {
        var fieldset = $(this).closest('fieldset');
        if ($('#members select[data-axis="' + fieldset.attr('data-axis') + '"]').length > 0) {
            var options = '<option value=""></option>';
            $('input', fieldset).each(function() {
                if ($(this).val() != '') {
                    options += '<option value="' + $(this).attr('name') + '">' + $(this).val() + '</option>';
                }
            });
            $('#members select[data-axis="' + fieldset.attr('data-axis') + '"]').each(function() {
                var previousVal = $(this).val();
                $(this).html(options);
                $(this).val(previousVal);
            });
        }
    });

    var validateActiveTab = function () {
        $('form span.help-block').remove();
        $('#addWorkspace div.form-group').removeClass('has-error');
        $('#addWorkspace div.form-group').removeClass('has-warning');

        var workspaceTemplate = $('#workspaceTemplate').val();

        var state = true;
        switch ($('#workspaceSteps li.active a').attr('href')) {

            case '#workspace':
                var workspace = $('#workspaceLabel');
                if (workspace.val() == '') {
                    workspace.closest('.form-group').addClass('has-error');
                    workspace.closest('.col-sm-10').append('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                    state = false;
                }

                if (state == true) {
                    $('#validation .workspace-summary ul').html('');
                    $('#validation .members-summary').html('');
                    $('#validation .granularities-summary').html('');
                    $('#validation .workspace-summary ul').prepend(
                        '<li class="workspaceLabel">' +
                            '<strong><?=___('Orga', 'add', 'workspaceLabel')?> : </strong>' +
                            $('#workspaceLabel').val() +
                        '</li>'
                    );
                    if (workspaceTemplate == '<?=WorkspaceService::TEMPLATE_DEMO?>') {
                        alert('Résumé de validation non développé pour les templates');
                    }
                }
            break;

            case '#axes':
                var mainAxis = $('#mainAxis');
                if (mainAxis.val() == '') {
                    mainAxis.closest('.form-group').addClass('has-error');
                    mainAxis.closest('.col-sm-10').append('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                    state = false;
                }
                $('input[id!="mainAxis"]', mainAxis.closest('fieldset')).each(function() {
                    if ($(this).val() == '') {
                        var input = $(this);
                        var formGroup = input.closest('.form-group');
                        formGroup.nextUntil('[data-level="' + formGroup.attr('data-level') + '"]').each(function() {
                            var parentInput = $('input', $(this));
                            if (parentInput.val() != '') {
                                formGroup.addClass('has-warning');
                                input.closest('.col-sm-' + (10 - formGroup.attr('data-level') * 1 + 1)).append('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                                state = false;
                                return false;
                            }
                        });
                        if (!formGroup.hasClass('has-warning') && (formGroup.attr('data-level') != '1')) {
                            formGroup.nextUntil('[data-level="' + formGroup.attr('data-level') + '"]').remove();
                            formGroup.remove();
                        }
                    }
                });
                var timeAxis = $('#timeAxis');
                if (timeAxis.val() == '') {
                    timeAxis.closest('.form-group').addClass('has-error');
                    timeAxis.closest('.col-sm-10').append('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                    state = false;
                }

                if (state == true) {
                    $('#members').html('');
                    $('#axes input[type="text"]').each(function() {
                        if ($(this).val() != '') {
                            var parentAxesNumber = 0;
                            var parentAxes = '';
                            var parentMembersSelect = '';
                            var formGroup = $(this).closest('.form-group');
                            formGroup.nextUntil('[data-level="' + formGroup.attr('data-level') + '"]', '[data-level="' + (formGroup.attr('data-level') * 1 + 1) + '"]').each(function() {
                                parentAxesNumber++;
                                var parentAxis = $('input', $(this)).attr('id');
                                parentAxes += parentAxis + '|';
                                parentMembersSelect +=
                                    '<div class="col-sm-2">' +
                                        '<select data-axis="' + parentAxis + '" name="member' + globalMemberCounter + '-parent][' + parentAxis + '" class="form-control">' +
                                        '</select>' +
                                    '</div>'
                            });
                            if (parentAxesNumber > 0) {
                                parentAxes = parentAxes.substr(0, parentAxes.length - 1);
                            }
                            $('#members').prepend(
                                '<fieldset data-axis="' + $(this).attr('id') + '">' +
                                    '<legend>' + $(this).val() + '</legend>' +
                                    '<div class="form-group">' +
                                        '<div class="col-sm-' + (12 - 2 * parentAxesNumber) + '">' +
                                            '<input type="text" name="member' + globalMemberCounter + '" class="form-control">' +
                                        '</div>' +
                                        parentMembersSelect +
                                    '</div>' +
                                    '<div class="form-group">' +
                                        '<div class="col-sm-12">' +
                                            '<button class="btn btn-default addMember" data-parent-axes="' + parentAxes + '">' +
                                                '<i class="fa fa-plus"></i> <?=___('Orga', 'add', 'addMember')?>' +
                                            '</button>' +
                                        '</div>' +
                                    '</div>' +
                                '</fieldset>'
                            );
                            globalMemberCounter++;
                        }
                    });

                    var inventoryGranularitiesList = [];
                    var aclGranularitiesList = [];
                    var reportsGranularitiesList = [];
                    aclGranularitiesList.push({ 'ref': "global", 'label': "<?=___('Orga', 'granularity', 'labelGlobalGranularity')?>   "});
                    reportsGranularitiesList.push({ 'ref': "global", 'label': "<?=___('Orga', 'granularity', 'labelGlobalGranularity')?>   "});
                    var timeAxisRef = 'timeAxis';
                    var timeAxisLabel = $('#timeAxis').val();
                    inventoryGranularitiesList.push({ 'ref': timeAxisRef, 'label': timeAxisLabel, 'checked': ' checked="checked"'});
                    if ($('#subdivisionAxis').val() != '') {
                        var subdivisionAxisRef = '|subdivisionAxis';
                        var subdivisionAxisLabel = ' | ' + $('#subdivisionAxis').val();
                    } else {
                        var subdivisionAxisRef = '';
                        var subdivisionAxisLabel = '';
                    }
                    var level = 1;
                    while ($('#axes div[data-level="' + level + '"]').length > 0) {
                        var granularityAxes = '';
                        var granularityLabel = '';
                        $('#axes div[data-level="' + level + '"]').each(function() {
                            inventoryGranularitiesList.push({ 'ref': $('input[type="text"]', $(this)).attr('name') + '|' + timeAxisRef, 'label': $('input[type="text"]', $(this)).val() + ' | ' + timeAxisLabel, 'checked': ''});
                            granularityAxes += $('input[type="text"]', $(this)).attr('name') + '|';
                            granularityLabel += $('input[type="text"]', $(this)).val() + ' | ';
                        });
                        aclGranularitiesList.push({ 'ref': granularityAxes.substr(0, (granularityAxes.length - 1)), 'label': granularityLabel.substr(0, (granularityLabel.length - 3))});
                        reportsGranularitiesList.push({ 'ref': granularityAxes.substr(0, (granularityAxes.length - 1)), 'label': granularityLabel.substr(0, (granularityLabel.length - 3))});
                        level++;
                    }
                    $('#inventory .col-sm-12').html('');
                    $(inventoryGranularitiesList).each(function() {
                        $('#inventory .col-sm-12').append(
                            '<div class="radio">' +
                                '<label>' +
                                    '<input name="inventoryGranularity" type="radio" value="' + this.ref  + '"' + this.checked + '>' +
                                    '<span>' + this.label + '</span>' +
                                '</label>' +
                            '</div>'
                        );
                    });
                    $('#acl .col-sm-12').html('');
                    $(aclGranularitiesList).each(function() {
                        $('#acl .col-sm-12').append(
                            '<div class="checkbox">' +
                                '<label>' +
                                    '<input name="aclGranularities[]" type="checkbox" value="' + this.ref  + '">' +
                                    '<span>' + this.label + '</span>' +
                                '</label>' +
                            '</div>'
                        );
                    });
                    $('#reports .col-sm-12').html('');
                    $(reportsGranularitiesList).each(function() {
                        $('#reports .col-sm-12').append(
                            '<div class="checkbox">' +
                                '<label>' +
                                    '<input name="reportsGranularities[]" type="checkbox" value="' + this.ref  + '">' +
                                    '<span>' + this.label + '</span>' +
                                '</label>' +
                            '</div>'
                        );
                    });
                }
            break;

            case '#members':
                $('#members select').each(function() {
                    var inputVal = $(this).val();
                    if (($('input', $(this).closest('.form-group')).val() != '') && ((inputVal == '') || (inputVal == null))) {
                        $(this).closest('.form-group').addClass('has-error');
                        $(this).after('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                        state = false;
                    } else if ($('input[name="' + $(this).val() + '"]').val() == '') {
                        $(this).closest('.form-group').addClass('has-warning');
                        $(this).after('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                        $('input[name="' + $(this).val() + '"]').closest('.form-group').addClass('has-warning');
                        $('input[name="' + $(this).val() + '"]').after('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                        state = false;
                    }
                });

                if (state == true) {
                    $('#validation .members-summary').html(
                        '<fieldset>' +
                            '<legend><?=___('Orga', 'add', 'members')?></legend>' +
                            '<ul>' +
                            '</ul>' +
                        '</fieldset>'
                    );
                    $('#axes input[type="text"]').each(function() {
                        if ($(this).val() != '') {
                            var members = '';
                            $('fieldset[data-axis="' + $(this).attr('name') + '"] input').each(function() {
                                if ($(this).val() != '') {
                                    members += $(this).val();
                                    var parentMembers = '';
                                    $('select', $(this).closest('.form-group')).each(function () {
                                        parentMembers += $('input[name="' + $(this).val() + '"]').val() + ', ';
                                    });
                                    if (parentMembers.length > 0) {
                                        members += ' (' + parentMembers.substr(0, (parentMembers.length - 2)) + ')'
                                    }
                                    members += ', '
                                }
                            });
                            if (members.length > 0) {
                                members = members.substr(0, (members.length - 2))
                            }
                            $('#validation .members-summary ul').append(
                                '<li>' +
                                    '<strong>' + $(this).val() + ' : </strong>'
                                    + members +
                                '</li>'
                            );
                        }
                    });
                }
            break;

            case '#inventory':
                var inventoryGranularity = $('#inventory input[name="inventoryGranularity"]:checked');
                if (inventoryGranularity.length == 0) {
                    $('#inventory .form-group').addClass('has-error');
                    $('#inventory .form-group .col-sm-12').append('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                    state = false;
                }

                if (state == true) {
                    $('#validation .workspace-summary ul li.inventory-granularity').remove();
                    $('#validation .workspace-summary ul').append(
                        '<li class="inventory-granularity">' +
                            '<strong><?=___('Orga', 'add', 'inventoryGranularityLabel')?> : </strong>' +
                            $('#inventory input[name="inventoryGranularity"]:checked').next().html() +
                        '</li>'
                    );
                }
            break;

            case '#acl':
                var aclGranularity = $('#acl input[name="aclGranularities[]"]:checked');
                if (aclGranularity.length == 0) {
                    $('#acl .form-group').addClass('has-error');
                    $('#acl .form-group .col-sm-12').append('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                    state = false;
                }

                if (state == true) {
                    $('#reports input[name="reportsGranularities[]"]').prop('checked', false);

                    var aclGranularities = '';
                    $('#acl input[name="aclGranularities[]"]:checked').each(function() {
                        $('#reports input[name="reportsGranularities[]"][value="' + $(this).val() + '"]').prop('checked', true);
                        aclGranularities += '<li>' + $(this).next().html() + '</li>';
                    });
                    $('#validation .granularities-summary .acl-granularities').remove();
                    $('#validation .granularities-summary').append(
                        '<fieldset class="acl-granularities">' +
                            '<legend><?=___('Orga', 'add', 'aclGranularitiesLabel')?></legend>' +
                            '<ul>' +
                                aclGranularities +
                            '</ul>' +
                        '</fieldset>'
                    );
                }
            break;

            case '#reports':
                var reportsGranularity = $('#reports input[name="reportsGranularities[]"]:checked');
                if (reportsGranularity.length == 0) {
                    $('#reports .form-group').addClass('has-error');
                    $('#reports .form-group .col-sm-12').append('<span class="help-block"><?=___('UI', 'formValidation', 'emptyRequiredField')?></span>');
                    state = false;
                }

                if (state == true) {
                    var reportsGranularities = '';
                    $('#reports input[name="reportsGranularities[]"]:checked').each(function() {
                        reportsGranularities += '<li>' + $(this).next().html() + '</li>';
                    });
                    $('#validation .granularities-summary .reports-granularities').remove();
                    $('#validation .granularities-summary').append(
                        '<fieldset class="reports-granularities">' +
                            '<legend><?=___('Orga', 'add', 'reportsGranularitiesLabel')?></legend>' +
                            '<ul>' +
                            reportsGranularities +
                            '</ul>' +
                        '</fieldset>'
                    );
                }
            break;

        }
        return state;
    };

    var parseFormData = function ()
    {
        var data = $('#addWorkspace .tab-content > div[id!="axes"][id!="members"] :input').serialize();
        $('#addWorkspace .tab-content > div[id="axes"] :input:not(:button)').each(function() {
            if ($(this).val() != '') {
                data += '&axes[' + $(this).attr('name') + ']=' + $(this).val();
            }
        });
        $('#addWorkspace .tab-content > div[id="members"] fieldset').each(function() {
            var axisId = $(this).attr('data-axis');
            $('input, select', $(this)).each(function() {
                data += '&members[' + axisId + '][' + $(this).attr('name') + ']=' + $(this).val();
            });
        });
        return data;
    };

    $().ready(function() {
        $('#addWorkspace a[data-toggle="tooltip"]').tooltip();
    });
</script>