<?php
/**
 * Vue générale d'un workspace
 * @author valentin.claras
 * @package Orga
 */

/** @var \Account\Application\ViewModel\WorkspaceView $workspace */
$workspace = $this->workspace;
$workspaceBanner = null;
$file = glob(APPLICATION_PATH . '/../public/workspaceBanners/' . $workspace->id . '.*');
if (count($file) > 0) {
    $workspaceBanner = 'workspaceBanners/' . pathinfo(array_pop($file))['basename'];
}
?>
<style>
    .workspace h1 img { max-height: 125px; }
    .workspace h1 .pull-right small a { letter-spacing: normal; }
</style>

<div class="workspace page-header">
    <h1>
        <?php if ($workspace->canBeEdited) : ?>
            <div class="pull-right">
                <small>
                    <a class="editWorkspace btn btn-sm btn-default"
                       href="orga/workspace/view/workspace/<?=$workspace->id?>">
                        <i class="fa fa-external-link"></i>
                        <?=___('UI', 'name', 'data')?>
                    </a>
                </small>
            </div>
        <?php endif; ?>
        <?php if ($workspaceBanner === null) : ?>
            <?=$workspace->label?>
        <?php else : ?>
            <img src="<?=$workspaceBanner?>">
        <?php endif; ?>
    </h1>
</div>
<?php
$this->tabView->display();
?>

<script>
    $('#relevance').on('granularityAdded', $('#addGranularity<?=$this->workspace->id?>_relevance'), function(e, data) {
        addMessage(data.message, 'success');
        $('#relevance').html($('#relevance').attr('data-loading'));
        $('#relevance').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
    $('#inventory').on('successSubmit', $('#workspaceInventory<?=$this->workspace->id?>'), function(e, data) {
        if (data.data.updated) {
            $('#inventory').html($('#inventory').attr('data-loading'));
            $('#inventory').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
        }
    });
    $('#inventory').on('granularityAdded', $('#addGranularity<?=$this->workspace->id?>_inventory'), function(e, data) {
        addMessage(data.message, 'success');
        $('#inventory').html($('#inventory').attr('data-loading'));
        $('#inventory').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
    $('#afs').on('granularityAdded', $('#addGranularity<?=$this->workspace->id?>_afs'), function(e, data) {
        addMessage(data.message, 'success');
        $('#afs').html($('#afs').attr('data-loading'));
        $('#afs').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
    $('#acl').on('granularityAdded', $('#addGranularity<?=$this->workspace->id?>_acl'), function(e, data) {
        addMessage(data.message, 'success');
        $('#acl').html($('#acl').attr('data-loading'));
        $('#acl').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
    $('#reports').on('granularityAdded', $('#addGranularity<?=$this->workspace->id?>_reports'), function(e, data) {
        addMessage(data.message, 'success');
        $('#reports').html($('#reports').attr('data-loading'));
        $('#reports').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
</script>
