<fieldset class="wrapper">
    <legend style="cursor: default;">
        <?=___('Orga', 'role', 'workspaceAdministrators')?>
    </legend>
<?php
$datagridUsers = new UI_Datagrid(
    'datagridUsers'.$this->workspace->getId(),
    'datagrid_workspace_acl',
    'orga'
);

$columnFirstName = new UI_Datagrid_Col_Text('firstName', ___('User', 'user', 'firstName'));
$columnFirstName->addable = false;
$datagridUsers->addCol($columnFirstName);

$columnLastName = new UI_Datagrid_Col_Text('lastName', ___('User', 'user', 'lastName'));
$columnLastName->addable = false;
$datagridUsers->addCol($columnLastName);

$columnEmail = new UI_Datagrid_Col_Text('email', ___('User', 'user', 'emailAddress'));
$columnEmail->addable = true;
$datagridUsers->addCol($columnEmail);

$datagridUsers->addParam('workspace', $this->workspace->getId());
$datagridUsers->addElements = true;
$datagridUsers->deleteElements = true;
$datagridUsers->pagination = false;

if ($this->display === false) {
    echo $datagridUsers->render();
} else {
    $datagridUsers->display();
}
?>
</fieldset>
<fieldset class="wrapper">
    <legend style="cursor: default;">
        <?=___('Orga', 'granularity', 'aclGranularities')?>
    </legend>
<ul>
<?php foreach ($this->aclGranularities as $aclGranularity) : ?>
    <li><?=$this->translate($aclGranularity->getLabel())?></li>
<?php endforeach; ?>
</ul>
</fieldset>
<hr>
<?php
if (count($this->granularities) > 0) :
echo '<hr>';
endif;
echo '<h4>'.__('Orga', 'granularity', 'addGranularityAcl').'</h4>';
echo $this->partial(
    'granularity/add.phtml',
    [
        'workspace' => $this->workspace,
        'purpose' => 'acl',
        'complementaryFields' => '',
        'selectAxesPlaceholder' => ___('Orga', 'granularity', 'addGranularitySelectAxesAclLevel')
    ]
);
if ($this->display === true) :
?>
<script>
    $('#addGranularity<?=$this->workspace->getId()?>_acl').on('granularityAdded', function(e) {
        location.reload(true);
    });
</script>
<?php
endif;
?>
