<fieldset class="wrapper">
    <legend style="cursor: default;">
        <?=___('Orga', 'inventory', 'editInventories')?>
    </legend>
    <form id="workspaceInventory<?=$this->workspace->getId()?>" class="form-horizontal" method="POST" action="orga/workspace/edit-inventory-submit/workspace/<?=$this->workspace->getId()?>">
        <div class="form-group">
            <label for="workspace_granularityForInventoryStatus" class="control-label col-xs-2 withTooltip" title="<?=___('Orga', 'inventory', 'editInventoryExplanation')?>">
                <?=___('Orga', 'granularity', 'inventoryGranularity')?>
                <i class="fa fa-question-circle"></i>
            </label>
            <div class="col-xs-10">
                <select id="workspace_granularityForInventoryStatus" name="granularityForInventoryStatus" class="form-control">
                    <option value=""></option>
                    <?php foreach ($this->workspace->getGranularities() as $granularity) : ?>
                        <option value="<?=$granularity->getId()?>"<?php if ($granularity === $this->granularityForInventoryStatus): ?> selected<?php endif; ?>>
                            <?=$this->translate($granularity->getLabel())?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-10 col-xs-offset-2">
                <button type="submit" class="btn btn-primary"><?=__('UI', 'verb', 'save')?></button>
            </div>
        </div>

        <script type="text/javascript">
            $(document).ready(function() {
                new AjaxForm('#workspaceInventory<?=$this->workspace->getId()?>');
            });
        </script>
    </form>
</fieldset>
<fieldset class="wrapper">
    <legend style="cursor: default;">
        <?=___('Orga', 'inventory', 'viewInventories')?>
    </legend>
<ul>
<?php foreach ($this->inventoryGranularities as $inventoryGranularity) : ?>
    <li><?=$this->translate($inventoryGranularity->getLabel())?></li>
<?php endforeach; ?>
</ul>
</fieldset>
<hr>
<?php
if (count($this->granularities) > 0) :
echo '<hr>';
endif;
echo '<h4>'.__('Orga', 'granularity', 'addGranularityInventory').'</h4>';
echo $this->partial(
    'granularity/add.phtml',
    [
        'workspace' => $this->workspace,
        'purpose' => 'inventory',
        'complementaryFields' => '',
        'selectAxesPlaceholder' => ___('Orga', 'granularity', 'addGranularitySelectAxesInventoryLevel')
    ]
);
?>
<script>
<?php if ($this->display === true) : ?>
    $('#workspaceInventory<?=$this->workspace->getId()?>').on('successSubmit', function(e, data) {
        if (data.data.updated) {
            location.reload(true);
        }
    });
    $('#addGranularity<?=$this->workspace->getId()?>_inventory').on('granularityAdded', function(e) {
        location.reload(true);
    });
<?php else : ?>
    $('#workspaceInventory<?=$this->workspace->getId()?>').on('successSubmit', function(e, data) {
        $(this).parent().trigger('successSubmit', data);
    });
<?php endif; ?>
</script>
