<?php
use Orga\Application\ViewModel\CellView;
use Account\Application\ViewModel\WorkspaceView;

/** @var \Account\Application\ViewModel\WorkspaceView $workspace */
$workspace = $this->workspace;
$workspaceBanner = null;
$file = glob(APPLICATION_PATH . '/../public/workspaceBanners/' . $workspace->id . '.*');
if (count($file) > 0) {
    $workspaceBanner = 'workspaceBanners/' . pathinfo(array_pop($file))['filename'];
}
/** @var CellView[] $cells */
$cells = $this->cells;
?>
<style>
    .workspace h1 img { max-height: 125px; }
    .workspace h1 .pull-right small a { letter-spacing: normal; }
</style>

<div class="workspace page-header">
    <h1>
        <?php if ($workspace->canBeEdited) : ?>
            <div class="pull-right">
                <small>
                    <a class="editWorkspace btn btn-sm btn-default"
                       href="orga/workspace/edit/workspace/<?=$workspace->id?>">
                        <i class="fa fa-wrench"></i>
                        <?=___('UI', 'name', 'configurationOrga')?>
                    </a>
                </small>
            </div>
        <?php endif; ?>
        <?php if ($workspaceBanner === null) : ?>
            <?=$workspace->label?>
        <?php else : ?>
            <img src="<?=$workspaceBanner?>">
        <?php endif; ?>
    </h1>
</div>

<?php foreach ($cells as $cell) : ?>
<div class="well">
    <h2>
        <a href="orga/cell/view/cell/<?=$cell->id?>">
            <?=$this->cellsAccess[$cell->id]?>
            <?=$cell->extendedLabel?>
            <small>
                <i class="fa fa-external-link"></i>
                <?=___('Orga', 'workspaceList', 'goToData')?>
            </small>
        </a>
    </h2>
</div>
<?php endforeach; ?>
<?php if (count($this->cells) === 0) : ?>
<p><?=___('UI', 'message', 'noAccess')?></p>
<?php endif; ?>
