<div class="page-header">
    <h1><?=__('Unit', 'name', 'discreteUnits')?></h1>
</div>

<?php
$datagrid = new UI_Datagrid('discreteUnits', 'datagrids_discreteunits', 'unit');

$labelColumn = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$datagrid->addCol($labelColumn);

$idColumn = new UI_Datagrid_Col_Text('id', __('UI', 'name', 'identifier'));
$datagrid->addCol($idColumn);

$datagrid->pagination = false;
$datagrid->display();
