<?php
/**
 * Liste les ExtendedUnit.
 * @author valentin.claras
 * @package Unit
 * @subpackage View
 */

?>
<div class="page-header">
	<h1><?=__('Unit', 'name', 'extendedUnits')?></h1>
</div>
<?

    $datagrid = new UI_Datagrid('ListExtendedUnit', 'datagrids_extendedunits', 'unit');

    $nameColumn = new UI_Datagrid_Col_Text('name', __('UI', 'name', 'label'));
    $datagrid->addCol($nameColumn);

    $refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
    $datagrid->addCol($refColumn);

    $symbolColumn = new UI_Datagrid_Col_Text('symbol', __('Unit', 'name', 'symbol'));
    $datagrid->addCol($symbolColumn);

    $multiplierColumn = new UI_Datagrid_Col_Number('multiplier', __('Unit', 'name', 'multiplier'));
    $datagrid->addCol($multiplierColumn);

    $datagrid->pagination = false;
    $datagrid->display();