<div class="page-header">
    <h1><?=__('Unit', 'name', 'standardUnits')?></h1>
</div>

<?
$datagrid = new UI_Datagrid ('ListStandardUnits', 'datagrids_standardunits', 'unit');

$nameColumn = new UI_Datagrid_Col_Text('name', __('UI', 'name', 'label'));
$datagrid->addCol($nameColumn);

$refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$datagrid->addCol($refColumn);

$symbolColumn = new UI_Datagrid_Col_Text('symbol', __('Unit', 'name', 'symbol'));
$datagrid->addCol($symbolColumn);

$physicalQuantityColumn = new UI_Datagrid_Col_Text('physicalQuantity', __('Unit', 'name', 'physicalQuantity'));
$datagrid->addCol($physicalQuantityColumn);

$unitSystemColumn = new UI_Datagrid_Col_Text('unitSystem', __('Unit', 'name', 'unitSystem'));
$datagrid->addCol($unitSystemColumn);

$datagrid->pagination = false;
$datagrid->display();
