<?php
/** @var $comments Social_Model_Comment[] */
$comments = $this->comments;

$endpointAdd = $this->endpointAdd;
$endpointDelete = $this->endpointDelete;
?>

<div class="commentList">
    <?php
    foreach ($comments as $comment) {
        echo $this->partial('comment/view.phtml', 'social', array('comment' => $comment));
    }

    if (count($comments) === 0) {
        ?>
        <p class="muted noComments">
            <?=__('Social', 'comment', 'noComment')?>.
        </p>
        <?php
    }
    ?>
</div>

<?php
// Désactivation de l'ajout de commentaires
if ($endpointAdd === null) {
    return;
}
?>

<p>
    <button class="addComment btn" type="button"><?=__('Social', 'comment', 'addComment')?></button>
</p>

<?php
$form = new UI_Form('addComment');
$form->setAction($endpointAdd);
$form->setAjax(true, 'addCommentSuccess');
$form->addClass('hide');

$contentField = new UI_Form_Element_Textarea('content');
$contentField->setWithMarkItUp(true);
$form->addElement($contentField);

$form->addSubmitButton(__('UI', 'verb', 'add'));
$form->addResetButton(__('UI', 'verb', 'cancel'));
echo $form->render();
?>

<script>
    // Add a comment
    $(".addComment").click(function() {
        $("#addComment").show(400)
            .find("#content").focus();
    });
    // Add a comment success callback
    $.fn.addCommentSuccess = function(response) {
        $("#addComment")[0].reset();
        var commentList = $(".commentList");
        commentList.find(".noComments").remove();
        commentList.append($(response.data));
    };
    // Cancel add a comment
    $("form#addComment").on("reset", function() {
        $("#addComment").hide(400);
    });

    // Delete a comment
    $(".deleteComment").click(function() {
        var commentBlock = $(this).closest("blockquote");
        var commentId = commentBlock.data('comment-id');
        setMask(true);
        $.post("<?=$endpointDelete?>", {'id': commentId})
            .done(function() {
                setMask(false);
                commentBlock.hide(400, function(){
                    commentBlock.remove();
                });
            });
    });
</script>
