<?php
use User\Domain\ACL\Action\DefaultAction;

/** @var $comment Social_Model_Comment */
$comment = $this->comment;
$locale = Core_Locale::loadDefault();

$canEdit = $this->isAllowed(DefaultAction::EDIT(), $comment);
$canDelete = $this->isAllowed(DefaultAction::DELETE(), $comment);
?>

<blockquote id="comment<?=$comment->getId()?>" data-comment-id="<?=$comment->getId()?>">
    <p>
        <?=Core_Tools::textile($comment->getText())?>
    </p>
    <small>
        <?=__('Social', 'comment', 'by')?> <strong><?=$comment->getAuthor()->getName()?></strong>
        <?=__('Social', 'comment', 'dated')?> <?=$comment->getCreationDate()->format('d M Y')?>

        <?php if ($canEdit) : ?>
            <button type="button" class="editComment btn btn-mini">
                <i class="icon-edit"></i>
                <?=__('UI', 'verb', 'edit')?>
            </button>
        <?php endif; ?>

        <?php if ($canDelete) : ?>
            <button type="button" class="deleteComment btn btn-mini">
                <i class="icon-trash"></i>
                <?=__('UI', 'verb', 'delete')?>
            </button>
        <?php endif; ?>
    </small>
</blockquote>
