<?php
/** @var $comment Social_Model_Comment */
$comment = $this->comment;
$locale = Core_Locale::loadDefault();
?>
<blockquote>
    <p>
        <?=Core_Tools::textile($comment->getText())?>
    </p>
    <small>
        <?=__('Social', 'comment', 'by')?> <strong><?=$comment->getAuthor()->getName()?></strong>
        <?=__('Social', 'comment', 'dated')?> <?=$comment->getCreationDate()->format('d M Y')?>
    </small>
</blockquote>
