<?php
/** @var $comment Social_Model_Comment */
$comment = $this->comment;

$canEdit = ($comment->getAuthor() === $this->currentUser);
?>

<blockquote id="comment<?=$comment->getId()?>" data-comment-id="<?=$comment->getId()?>">
    <p>
        <?=Core_Tools::textile($comment->getText())?>
    </p>
    <small>
        <?=__('Social', 'comment', 'by')?> <strong><?=$comment->getAuthor()->getName()?></strong>
        <?=__('Social', 'comment', 'dated')?> <?=$comment->getCreationDate()->format('d M Y')?>

        <?php if ($canEdit) : ?>
            <button type="button" class="editComment btn btn-default btn-xs">
                <i class="fa fa-pencil-square-o"></i>
                <?=__('UI', 'verb', 'edit')?>
            </button>
            <button type="button" class="deleteComment btn btn-default btn-xs">
                <i class="fa fa-trash-o"></i>
                <?=__('UI', 'verb', 'delete')?>
            </button>
        <?php endif; ?>
    </small>
</blockquote>
