<?php

$locale = Core_Locale::loadDefault();

$coordinates = $this->coordinates;

/** @var $value Calc_Value */
$value = $this->value;
?>

<form id="editElement" class="form-horizontal" method="post"
      action="parameter/element/edit-submit?id=<?=$this->family->getId()?>">

    <div class="form-group">
        <label for="digitalValue" class="col-sm-2 control-label"><?=__('UI', 'name', 'value')?></label>
        <div class="col-sm-10">
            <input id="digitalValue" name="digitalValue" type="text" class="form-control" required
                   value="<?=$locale->formatNumberForInput($value->getDigitalValue())?>">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label"><?=__('Unit', 'name', 'unit')?></label>
        <div class="col-sm-10">
            <input type="text" class="form-control" disabled
                   value="<?=$this->translate($this->family->getUnit()->getSymbol())?>">
        </div>
    </div>

    <div class="form-group">
        <label for="uncertainty" class="col-sm-2 control-label"><?=__('UI', 'name', 'uncertainty')?></label>
        <div class="col-sm-10">
            <input id="uncertainty" name="uncertainty" type="text" class="form-control"
                   value="<?=$locale->formatNumberForInput($value->getRelativeUncertainty())?>">
        </div>
    </div>

    <input type="hidden" name="coordinates" value="<?=htmlspecialchars(json_encode($coordinates))?>">

</form>

<script>
    var form = new AjaxForm('#editElement');
    form.onSuccess = function(response) {
        addMessage(response.message, response.type);
        $('#elements tbody tr td a[data-element="' + response.data.elementId + '"]').html(
            response.data.value + ' ± ' + response.data.uncertainty
        );
        $('#element_edit').modal('hide');
    };
</script>
