<?php

$locale = Core_Locale::loadDefault();

$coordinates = $this->coordinates;

/** @var $value Calc_Value */
$value = $this->value;

$title = __('Parameter', 'element', 'element');
?>

<script type="text/javascript">
    $('#element_edit div.modal-header h4').html(<?=json_encode($title)?>);
</script>

<?php
$editForm = new UI_Form('element_editForm');
$editForm->setAction('parameter/element/edit-submit?id=' . $this->family->getId());
$editForm->setAjax(true, 'elementEditSuccess');

// Valeur
$digitalValueField = new UI_Form_Element_Text('digitalValue');
$digitalValueField->setLabel(__('UI', 'name', 'value'));
$digitalValueField->setValue($locale->formatNumberForInput($value->getDigitalValue()));
$digitalValueField->setRequired(true);
$editForm->addElement($digitalValueField);

// Unité
$unitField = new UI_Form_Element_HTML('unit');
$unitField->setLabel(__('Unit', 'name', 'unit'));
$unitField->content = $this->family->getUnit()->getSymbol();
$editForm->addElement($unitField);

// Incertitude
$uncertaintyField = new UI_Form_Element_Text('uncertainty');
$uncertaintyField->setLabel(__('UI', 'name', 'uncertainty'));
$uncertaintyField->setValue($locale->formatNumberForInput($value->getRelativeUncertainty()));
$editForm->addElement($uncertaintyField);

// Famille
$familyField = new UI_Form_Element_Hidden('idFamily');
$familyField->setValue($this->family->getId());
$editForm->addElement($familyField);

// Coordonnées
$coordinatesField = new UI_Form_Element_Hidden('coordinates');
$coordinatesField->setValue(json_encode($coordinates));
$editForm->addElement($coordinatesField);

echo $editForm->render();
