<div class="page-header">
    <h1><?=__('User', 'resetPassword', 'pageTitle')?></h1>
</div>
<p><?=__('User', 'resetPassword', 'comment')?></p>

<?php
$form = new UI_Form('passwordForgotten');
$form->setAction('user/password/forgotten');

$email = new UI_Form_Element_Pattern_Email('email');
$email->setLabel(__('UI', 'name', 'emailAddress'));
$email->setRequired();
$form->addElement($email);

$captcha = new UI_Form_Element_Captcha('captcha', 'user/captcha/newimage');
$captcha->setLabel(__('User', 'resetPassword', 'captchaFieldLabel'));
$captcha->setRequired();
$form->addElement($captcha);

$form->addSubmitButton(__('UI', 'verb', 'validate'));

$form->display();
