<div class="page-header">
    <h1><?=__('User', '', 'Modification du mot de passe')?></h1>
</div>
<p><?=__('User', 'resetPasswordCode', 'Vous pouvez modifier votre mot de passe.')?></p>

<?php
$form = new UI_Form('editPassword');
$form->setAction('user/password/reset-submit/');
$form->setAjax(false);

$password1 = new UI_Form_Element_Password('password1');
$password1->setLabel(__('User', 'editPassword', 'newPassword'));
$password1->setRequired();
$form->addElement($password1);

$password2 = new UI_Form_Element_Password('password2');
$password2->setLabel(__('User', 'editPassword', 'confirmNewPassword'));
$password2->setRequired();
$form->addElement($password2);

$code = new UI_Form_Element_Hidden('code');
$code->setValue($this->code);
$form->addElement($code);

$form->addSubmitButton();
$form->display();
