<div class="page-header">
    <h1><?=__('User', 'typeResettedPassword', 'pageTitle')?></h1>
</div>
<p><?=__('User', 'typeResettedPassword', 'introductionSentence')?></p>

<?php
$form = new UI_Form('editPassword');
$form->setAction('user/password/reset-submit/code/' . $this->code);
$form->setAjax(true, 'passwordUpdated');

$password1 = new UI_Form_Element_Password('password1');
$password1->setLabel(__('User', 'editPassword', 'newPassword'));
$password1->setRequired();
$form->addElement($password1);

$password2 = new UI_Form_Element_Password('password2');
$password2->setLabel(__('User', 'editPassword', 'confirmNewPassword'));
$password2->setRequired();
$form->addElement($password2);

$form->addSubmitButton();
$form->display();
?>

<script>
    $.fn.passwordUpdated = function () {
        window.location.href = "<?=$this->baseUrl()?>/";
    };
</script>
