<?php
/**
 *Page d'accueil du package TEC.
 * @package TEC
 */

ob_start()
?>
    <div id="help">
		<p><?=__('TEC', 'interpreter', 'authorizedCharactersInOperands')?></p>
        <p><?=__('TEC', 'interpreter', 'arithmeticExpression')?></p>
        <p><?=__('TEC', 'interpreter', 'booleanExpression')?></p>
        <p><?=__('TEC', 'interpreter', 'selectionExpression')?></p>
    </div>
<?php
    $helpContent = ob_get_contents();
    ob_end_clean();

    $formExpression = new UI_Form('expression');
    $formExpression->setAction('tec/expression/read');
    $formExpression->setAjax(false);


    $selectType = new UI_Form_Element_Radio('typeExpression');
    $selectType->setLabel(__('TEC', 'interpreter', 'expressionTypeLabel'));

    $optionNumeric = new UI_Form_Element_Option('numeric', 'numeric', __('TEC', 'property', 'arithmetic'));
    $selectType->addOption($optionNumeric);
    $optionLogical = new UI_Form_Element_Option('logical', 'logical', __('TEC', 'property', 'booleanFem'));
    $selectType->addOption($optionLogical);
    $optionExecution = new UI_Form_Element_Option('select', 'select', __('TEC', 'name', 'selection'));
    $selectType->addOption($optionExecution);
    $selectType->setValue($this->typeExpression);

    $formExpression->addElement($selectType);


    $input = new UI_Form_Element_Textarea('input');
    $input->setLabel(__('TEC', 'name', 'expression'));
    $input->setValue($this->input);

    $formExpression->addElement($input);


    $formExpression->addSubmitButton(__('UI', 'verb', 'interpret'));
    $formExpression->addResetButton(__('UI', 'verb', 'reset'));
?>
  	<h1><?=__('TEC', 'interpreter', 'pageTitle')?></h1>
  	<?=$this->collapse('help', __('UI', 'name', 'help'), $helpContent)->collapsed();?>
  	<hr />
<?php
    $formExpression->display();
?>

<?php if ($this->displayResult) { ?>
    <?php if (count($this->errors) > 0) { ?>

    <div class="alert alert-error">
    	<button type="button" class="close" data-dismiss="alert">&times;</button>
    	<?=__('TEC', 'interpreter', 'incorrectExpressionMessage')?>
	</div>
	<fieldset>
        <legend><?=__('UI', 'name', 'errors')?></legend>
        <ul>
        <?php foreach ($this->errors as $error) { ?>
            <li><?=$error?></li>
        <?php } ?>
        </ul>
    </fieldset>

    <?php } else { ?>

    <div class="alert alert-success">
    	<button type="button" class="close" data-dismiss="alert">&times;</button>
    	<?=__('TEC', 'interpreter', 'correctExpressionMessage')?>
	</div>
	<fieldset>
        <legend><?=__('TEC', 'interpreter', 'returnExpressionLabel')?></legend>
    <p><?=$this->correctedExpression?></p>
    <div id="chart"></div>
        <script type='text/javascript' src='http://www.google.com/jsapi'></script>
        <script type="text/javascript">
            var table = [<?=$this->graphExpression?>];
            google.load('visualization', '1', {packages:['orgchart']});
            google.setOnLoadCallback(drawChart);
            function drawChart() {
                var data = new google.visualization.DataTable();
                data.addColumn('string', 'Feuille');
                data.addColumn('string', 'Noeud');
                data.addColumn('string', 'Attribut');
                data.addRows([<?=$this->graphExpression?>]);
                var chart = new google.visualization.OrgChart(document.getElementById('chart'));
                chart.draw(data, {allowHtml:true, allowCollapse:true});
            }
        </script>
	</fieldset>

    <?php } ?>
<?php } ?>