<?php

$resetSelectParentFieldScript = '';
foreach ($this->axes as $axis) {
    /** @var $axis Orga_Model_Axis */

    $datagridAxisMembers = new UI_Datagrid('listMembers'.$axis->getRef(), 'datagrid_member', 'orga');

    // Label du membre de l'axe.
    $columnLabel = new UI_Datagrid_Col_Text('label', ___('UI', 'name', 'label'));
    $columnLabel->editable = true;
    $datagridAxisMembers->addCol($columnLabel);

    // Ref du membre de l'axe.
    $columnRef = new UI_Datagrid_Col_Text('ref', ___('UI', 'name', 'identifier'));
    $columnRef->editable = true;
    $datagridAxisMembers->addCol($columnRef);

    // Membres broaders pour chaque axe broader.
    foreach ($axis->getDirectBroaders() as $broaderAxis) {
        // Construction de la liste de membres.
        $columnBroader = new UI_Datagrid_Col_List('broader'.$broaderAxis->getRef(), $broaderAxis->getLabel());
        $columnBroader->list = 'orga/datagrid_member/get-parents/refParentAxis/'.$broaderAxis->getRef();
        $columnBroader->dynamicList = true;
        $columnBroader->editable = true;
        $columnBroader->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
        $datagridAxisMembers->addCol($columnBroader);

        $resetSelectParentFieldScript .= '$(\'#listMembers'.$axis->getRef().'_addPanel\').on(\'hide\', function() {';
        $resetSelectParentFieldScript .= '$(\'#listMembers'.$axis->getRef().'_broader'.$broaderAxis->getRef().'_addForm\').select2(\'data\', {id: \'\', text: \'\'});';
        $resetSelectParentFieldScript .= '});';
    }

    $datagridAxisMembers->deleteElements = true;
    if (!$this->isUserAllowToEditAllMembers) {
        $datagridAxisMembers->pagination = false;
    }
    $datagridAxisMembers->addParam('idOrganization', $this->idOrganization);
    $datagridAxisMembers->addParam('refAxis', $axis->getRef());
    $datagridAxisMembers->initialLoading = false;
    $datagridAxisMembers->addElements = true;
    $datagridAxisMembers->addPanelTitle = ___('Orga', 'member', 'addPanelTitle', array('AXIS_LABEL' => $axis->getLabel()));

    echo $this->collapse('members'.$axis->getRef(), $axis->getLabel(), $datagridAxisMembers->getHTML())->collapsed();

    $script = '';
    $script .= '$(\'#members'.$axis->getRef().'\').on(\'show\', function(e) {';
    $script .= 'if ($(e.target).attr(\'id\') == \'members'.$axis->getRef().'_wrapper\') {';
    $script .= 'listMembers'.$axis->getRef().'.filter();';
    $script .= '}';
    $script .= '});';
    $script .= 'refFromLabel(\'listMembers'.$axis->getRef().'_label_addForm\', \'listMembers'.$axis->getRef().'_ref_addForm\');';

    if ($this->display === false) {
        echo '<script type="text/javascript">'.$datagridAxisMembers->getScript().$script.'</script>';
    } else {
        UI_Datagrid::addHeader($datagridAxisMembers);
        $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
    }

    if ($resetSelectParentFieldScript !== '') {
        echo '<script type="text/javascript">'.$resetSelectParentFieldScript.'</script>';
    }
}