<?php foreach ($this->acls as $granularityLabel => $roles) : ?>
    <fieldset class="wrapper">
        <legend style="cursor: default"><?=$granularityLabel?></legend>
        <div>
            <?php foreach ($roles as $roleLabel => $usersRoles) : ?>
                <fieldset class="wrapper">
                    <legend style="cursor: default"><?=$roleLabel?></legend>
                    <div>
                        <pre><?php
                            $lastUserEmail = end($usersRoles);
                            foreach ($usersRoles as $userEmail) {
                                echo $userEmail;
                                if ($userEmail !== $lastUserEmail) {
                                    echo "\n";
                                }
                            }
                        ?></pre>
                    </div>
                </fieldset>
            <?php endforeach; ?>
        </div>
    </fieldset>
<?php endforeach; ?>

<script>
    $('#inventories<?=$this->idGranularity?>_users_popup .modal-header h3').html("<?=$this->labelPopup?>");
</script>