<?php
/**
 * @author valentin.claras
 * @package Orga
 * @subpackage View
 */
echo __('Orga', 'inventory', 'involvedUsers');

foreach ($this->acls as $granularityLabel => $roles) {
?>
    <fieldset class="wrapper">
        <legend style="cursor: default"><?=$granularityLabel?></legend>
        <div>
<?php
    foreach ($roles as $roleLabel => $usersRoles) {
?>
            <fieldset class="wrapper">
                <legend style="cursor: default"><?=__('Orga', 'role', $roleLabel)?></legend>
                <div>
                    <pre>
<?php
        $lastUserEmail = end($usersRoles);
        foreach ($usersRoles as $userEmail) {
            echo $userEmail;
            if ($userEmail !== $lastUserEmail) {
                echo "\n";
            }
        }
?>
                    </pre>
                </div>
            </fieldset>
<?php
    }
?>
        </div>
    </fieldset>
<?php
}