<?php foreach ($this->acls as $granularityLabel => $roles) : ?>
    <fieldset class="wrapper">
        <legend style="cursor: default"><?=$granularityLabel?></legend>
        <div>
            <?php foreach ($roles as $roleLabel => $usersRoles) : ?>
            <fieldset class="wrapper">
                <legend style="cursor: default"><?=$roleLabel?></legend>
                <div>
                    <pre><?=implode("\n", $usersRoles);?></pre>
                </div>
            </fieldset>
            <?php endforeach; ?>
        </div>
    </fieldset>
<?php endforeach; ?>

<script>
    $('#inventories<?=$this->idGranularity?>_users_popup .modal-header h3').html("<?=$this->labelPopup?>");
</script>