<div class="page-header">
	<h1><?=__('Classification', 'control', 'pageTitle')?></h1>
</div>
<?php
$datagrid = new UI_Datagrid('coherence', 'datagrid_consistency', 'classification');

$columnControl = new UI_Datagrid_Col_Text('control', __('Classification', 'control', 'seekedIssue'));
$datagrid->addCol($columnControl);

$columnDiag = new UI_Datagrid_Col_Bool('diag', __('UI', 'name', 'diagnostic'));
$columnDiag->valueTrue = '<i class="fa fa-check"></i> '.__('UI', 'other', 'ok');
$columnDiag->valueFalse = '<i class="fa fa-times"></i> '.__('UI', 'other', 'nok');
$datagrid->addCol($columnDiag);

$columnFail = new UI_Datagrid_Col_Text('fail', __('Classification', 'control', 'abnormalItems'));
$datagrid->addCol($columnFail);


$datagrid->pagination = false;
$datagrid->display();
