<?php
/**
 * Vue en consultation presentant les predicats dans une datagrid.
 * @author valentin.claras
 * @author bertrand.ferry
 * @package Keyword
 */
?>
    use Keyword\Domain\Keyword_Model_Keyword;

    <div class="page-header">
	<h1><?=__('Keyword', 'list', 'pageTitle')?></h1>
</div>
<?php
    $datagrid = new UI_Datagrid('keywords', 'datagrid_keyword', 'keyword');

    $columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
    $columnLabel->sortName = Keyword_Model_Keyword::QUERY_LABEL;
    $columnLabel->filterName = Keyword_Model_Keyword::QUERY_LABEL;

    $columnRef = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
    $columnRef->sortName = Keyword_Model_Keyword::QUERY_REF;
    $columnRef->filterName = Keyword_Model_Keyword::QUERY_REF;

    $columnNbRelations = new UI_Datagrid_Col_Number('nbRelations', __('Keyword', 'list', 'relationNumberHeader'));
    $columnNbRelations->valueAlignment = UI_Datagrid_Col_Text::DISPLAY_TEXT_CENTER;

    $columnLinkToGraph = new UI_Datagrid_Col_Link('linkToGraph', __('UI', 'name', 'graph'));
    $columnLinkToGraph->defaultValue = '<i class=icon-share-alt></i> '. __('UI', 'name', 'graph');

    $datagrid->addCol($columnLabel);
    $datagrid->addCol($columnRef);
    $datagrid->addCol($columnNbRelations);
    $datagrid->addCol($columnLinkToGraph);

    $datagrid->setDefaultSorting('label');
    $datagrid->display();
