<?php
/**
 * Vue en édition presentant les mots clés dans une datagrid.
 * @author valentin.claras
 * @author bertrand.ferry
 * @package Keyword
 */

use Keyword\Domain\KeywordRepository;
use UI\Datagrid\Datagrid;
use UI\Datagrid\Column\TextColumn;
use UI\Datagrid\Column\NumberColumn;
use UI\Datagrid\Column\LinkColumn;
?>
<div class="page-header">
	<h1><?=__('Keyword', 'list', 'pageTitle')?></h1>
</div>
<?php
    $datagrid = new Datagrid('keywords', 'datagrid_keyword', 'keyword');
    $datagrid->criteriaName = '\Keyword\Domain\KeywordCriteria';

    $columnLabel = new TextColumn('label', __('UI', 'name', 'label'));
    $columnLabel->criteriaAttribute = KeywordRepository::QUERY_LABEL;
    $columnLabel->criteriaOrderEnabled = true;
    $columnLabel->editable = true;

    $columnRef = new TextColumn('ref', __('UI', 'name', 'identifier'));
    $columnRef->criteriaAttribute = KeywordRepository::QUERY_REF;
    $columnRef->criteriaOrderEnabled = true;
    $columnRef->editable = true;

    $columnNbRelations = new NumberColumn('nbRelations', __('Keyword', 'list', 'relationNumberHeader'));
    $columnNbRelations->valueAlignment = UI_Datagrid_Col_Text::DISPLAY_TEXT_CENTER;
    $columnNbRelations->addable = false;

    $columnLinkToGraph = new LinkColumn('linkToGraph', __('UI', 'name', 'graph'));
    $columnLinkToGraph->defaultValue = '<i class=icon-share-alt></i> '. __('UI', 'name', 'graph');

    $datagrid->addCol($columnLabel);
    $datagrid->addCol($columnRef);
    $datagrid->addCol($columnNbRelations);
    $datagrid->addCol($columnLinkToGraph);

    $datagrid->setDefaultSorting('label');
    $datagrid->deleteElements = true;
    $datagrid->addElements = true;
    $datagrid->addPanelTitle = __('Keyword', 'list', 'addPanelTitle');
    $datagrid->display();
