<?php
/**
 * @author valentin.claras
 * @package AF
 * Traduction des aides des Component
 */
?>
    <div class="page-header">
        <h1><?= __('AF', 'translate', 'componentHelps')?> <small><?=__('UI', 'name', 'translations')?></small></h1>
    </div>
<?php
echo $this->translateDatagrid('AF_Model_Family', 'help', 'datagrid_translate_components_help', 'af')
    ->addIdentifierCol()->addLanguagesLongTextCols();