<?php
use AF\Domain\AF;
use MyCLabs\MUIH\GenericTag;

/**
 * @author  matthieu.napoli
 * @package AF
 */
/** @var $af \AF\Domain\AF */
$af = $this->af;

$datagrid = new UI_Datagrid('algoConditionExpression', 'datagrid_edit_algos_condition-expression', 'af');
$datagrid->initialLoading = false;
$datagrid->addParam('id', $af->getId());
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('AF', 'configInteractionDatagrid', 'composedConditionAddPanelTitle');
$datagrid->deleteElements = true;

$refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$refColumn->editable = true;
$datagrid->addCol($refColumn);

$expressionColumn = new UI_Datagrid_Col_LongText('expression', __('TEC', 'name', 'expression'));
$expressionColumn->editable = true;
$expressionColumn->textileEditor = false;
$datagrid->addCol($expressionColumn);

echo $datagrid->render();
