<?php
use AF\Domain\AF;
use Parameter\Domain\Family\Family;
use Parameter\Domain\Family\FamilyReference;
use Parameter\Domain\ParameterLibrary;

/** @var $af AF */
$af = $this->af;

/** @var $parameterLibraries ParameterLibrary[] */
$parameterLibraries = $this->parameterLibraries;

$datagrid = new UI_Datagrid('algoNumericParameter', 'datagrid_edit_algos_numeric-parameter', 'af');
$datagrid->initialLoading = false;
$datagrid->addParam('id', $af->getId());
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('AF', 'configTreatmentDatagrid', 'numericParameterAddPanelTitle');
$datagrid->deleteElements = true;

// Label
$labelColumn = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$labelColumn->editable = true;
$datagrid->addCol($labelColumn);

// Ref
$refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$refColumn->editable = true;
$datagrid->addCol($refColumn);

// Famille
$familyColumn = new UI_Datagrid_Col_List('family', __('Parameter', 'name', 'family'));
$familyColumn->list = [];
foreach ($parameterLibraries as $parameterLibrary) {
    foreach ($parameterLibrary->getFamilies() as $family) {
        $ref = new FamilyReference($parameterLibrary->getId(), $family->getRef());
        /** @var $family Family */
        $familyColumn->list[(string) $ref] = sprintf(
            '%s > %s',
            $this->translate($parameterLibrary->getLabel()),
            $this->translate($family->getLabel())
        );
    }
}
$familyColumn->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
$familyColumn->editable = true;
$datagrid->addCol($familyColumn);

// Coordonnées
$coordinatesColumn = new UI_Datagrid_Col_Popup('coordinates', __('Parameter', 'name', 'coordinates'));
$coordinatesColumn->popup->large();
$datagrid->addCol($coordinatesColumn);

// Context indicator
$contextIndicatorColumn = new UI_Datagrid_Col_List('contextIndicator', __('Classification', 'indicator', 'indicator'));
$contextIndicatorColumn->addable = false;
$contextIndicatorColumn->editable = true;
$contextIndicatorColumn->dynamicList = true;
$contextIndicatorColumn->list = $this->baseUrl(
    'af/datagrid_edit_algos_numeric-parameter/get-context-indicator-list'
);
$contextIndicatorColumn->withEmptyElement = true;
$datagrid->addCol($contextIndicatorColumn);

// Indexation
$resultIndexColumn = new UI_Datagrid_Col_Popup('resultIndex', __('Algo', 'name', 'indexation'));
$resultIndexColumn->popup->large();
$datagrid->addCol($resultIndexColumn);

echo $datagrid->render();
?>

<script>
    $('#algoNumericParameter_addPanel').on('hidden', function() {
        $('#algoNumericParameter_family_addForm').val('').trigger('change');
    });
    $(function() {
        refFromLabel('algoNumericParameter_label_addForm', 'algoNumericParameter_ref_addForm')
    });
</script>
