<?php

use AF\Domain\Algorithm\Numeric\NumericExpressionAlgo;
use TEC\Expression;

/** @var $algo NumericExpressionAlgo */
$algo = $this->algo;

$expression = new Expression($algo->getExpression());
$graphExpression = $expression->getGraph();
?>

<code><?=$algo->getExpression()?></code>

<hr>

<div id="graph_<?=$algo->getRef()?>"></div>

<script>
    $(function() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Feuille');
        data.addColumn('string', 'Noeud');
        data.addColumn('string', 'Attribut');
        data.addRows([<?=$graphExpression?>]);
        var chart = new google.visualization.OrgChart(document.getElementById('graph_<?=$algo->getRef()?>'));
        chart.draw(data, {allowHtml:true, allowCollapse:true});
    });
</script>
