<?php
use AF\Domain\AF;

/** @var $af AF */
$af = $this->af;

$datagrid = new UI_Datagrid('algoSelectionTextkeyExpression', 'datagrid_edit_algos_selection-textkey-expression', 'af');
$datagrid->initialLoading = false;
$datagrid->addParam('id', $af->getId());
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('AF', 'configTreatmentDatagrid', 'expressionTextIdentifierSelectionAddPanelTitle');
$datagrid->deleteElements = true;

// Ref
$refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$refColumn->editable = true;
$datagrid->addCol($refColumn);

// Expression
$expressionColumn = new UI_Datagrid_Col_LongText('expression', __('TEC', 'name', 'expression'));
$expressionColumn->editable = true;
$expressionColumn->textileEditor = false;
$expressionColumn->popup->title = __('TEC', 'name', 'expression');
$datagrid->addCol($expressionColumn);

echo $datagrid->render();
