<?php
use AF\Domain\AF\AF;

/**
 * Datagrid des algos de sélection de mot-clés
 * @author  matthieu.napoli
 * @package AF
 */
/** @var $af AF */
$af = $this->af;

$datagrid = new UI_Datagrid('algoSelectionTextkeyInput', 'datagrid_edit_algos_selection-textkey-input', 'af');
$datagrid->initialLoading = false;
$datagrid->addParam('id', $af->getId());
$datagrid->pagination = false;

// Ref
$refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$datagrid->addCol($refColumn);

// Input
$inputColumn = new UI_Datagrid_Col_Text('input', __('UI', 'name', 'field'));
$datagrid->addCol($inputColumn);

echo $datagrid->render();
