<?php
use AF\Domain\AF;
use AF\Domain\Component\Select\SelectSingle;
use AF\Domain\Component\Select\SelectMulti;
use AF\Domain\Algorithm\Condition\NumericConditionAlgo;
use AF\Domain\Algorithm\Condition\BooleanConditionAlgo;
use AF\Domain\Algorithm\Condition\Select\SelectSingleConditionAlgo;
use AF\Domain\Algorithm\Condition\Select\SelectMultiConditionAlgo;
use AF\Domain\Algorithm\Condition\ElementaryConditionAlgo;

$locale = Core_Locale::loadDefault();

/** @var $af AF */
$af = $this->af;
/** @var $algo ElementaryConditionAlgo */
$algo = $this->algo;

$allRelations = [
    ElementaryConditionAlgo::RELATION_EQUAL       => __('AF', 'configInteractionDatagrid', 'equalOption'),
    ElementaryConditionAlgo::RELATION_NOTEQUAL    => __('AF', 'configInteractionDatagrid', 'differentOption'),
    ElementaryConditionAlgo::RELATION_GT          => __('AF', 'configInteractionDatagrid', 'greaterOption'),
    ElementaryConditionAlgo::RELATION_LT          => __('AF', 'configInteractionDatagrid', 'lowerOption'),
    ElementaryConditionAlgo::RELATION_GE          => __('AF', 'configInteractionDatagrid', 'greaterOrEqualOption'),
    ElementaryConditionAlgo::RELATION_LE          => __('AF', 'configInteractionDatagrid', 'lowerOrEqualOption'),
    ElementaryConditionAlgo::RELATION_CONTAINS    => __('AF', 'configInteractionDatagrid', 'containsOption'),
    ElementaryConditionAlgo::RELATION_NOTCONTAINS => __('AF', 'configInteractionDatagrid', 'doesNotContainOption'),
];
?>

<form class="form-horizontal" method="post"
      action="af/edit_algos/update-condition-elementary-submit?idAF=<?=$af->getId()?>&idAlgo=<?=$algo->getId()?>">

    <?php if ($algo instanceof NumericConditionAlgo) : ?>
        <?php
        /** @var $algo NumericConditionAlgo */
        $relations = [];
        $relations[ElementaryConditionAlgo::RELATION_EQUAL] = $allRelations[ElementaryConditionAlgo::RELATION_EQUAL];
        $relations[ElementaryConditionAlgo::RELATION_NOTEQUAL] = $allRelations[ElementaryConditionAlgo::RELATION_NOTEQUAL];
        $relations[ElementaryConditionAlgo::RELATION_GT] = $allRelations[ElementaryConditionAlgo::RELATION_GT];
        $relations[ElementaryConditionAlgo::RELATION_LT] = $allRelations[ElementaryConditionAlgo::RELATION_LT];
        $relations[ElementaryConditionAlgo::RELATION_GE] = $allRelations[ElementaryConditionAlgo::RELATION_GE];
        $relations[ElementaryConditionAlgo::RELATION_LE] = $allRelations[ElementaryConditionAlgo::RELATION_LE];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputRelation">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" id="inputRelation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                            <?=$algo->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputValue">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <input name="value" id="inputValue" type="text" class="form-control"
                       value="<?=$locale->formatNumberForInput($algo->getValue())?>">
            </div>
        </div>
    <?php endif; ?>


    <?php if ($algo instanceof BooleanConditionAlgo) : ?>
        <?php
        /** @var $algo BooleanConditionAlgo */
        $relations = [];
        $relations[ElementaryConditionAlgo::RELATION_EQUAL] = $allRelations[ElementaryConditionAlgo::RELATION_EQUAL];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputRelation">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" id="inputRelation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                            <?=$algo->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputValue">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <select name="value" id="inputValue" class="form-control">
                    <option value="1" <?=$algo->getValue() ? 'selected' : ''?>>
                        <?=__('UI', 'property', 'checked')?>
                    </option>
                    <option value="0" <?=!$algo->getValue() ? 'selected' : ''?>>
                        <?=__('UI', 'property', 'unchecked')?>
                    </option>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <?php if ($algo instanceof SelectSingleConditionAlgo) : ?>
        <?php
        /** @var $algo SelectSingleConditionAlgo */
        $relations = [];
        $relations[ElementaryConditionAlgo::RELATION_EQUAL] = $allRelations[ElementaryConditionAlgo::RELATION_EQUAL];
        $relations[ElementaryConditionAlgo::RELATION_NOTEQUAL] = $allRelations[ElementaryConditionAlgo::RELATION_NOTEQUAL];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputRelation">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" id="inputRelation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                            <?=$algo->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputValue">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <select name="value" id="inputValue" class="form-control">
                    <?php
                    /** @var $field SelectSingle */
                    $field = SelectSingle::loadByRef($algo->getInputRef(), $af);
                    $selected = $algo->getValue() ? $algo->getValue() : null;
                    ?>
                    <option value="" <?=$selected == null ? 'selected' : ''?>></option>
                    <?php foreach ($field->getOptions() as $option) : ?>
                        <option value="<?=$option->getRef()?>"
                            <?=$option->getRef() == $selected ? 'selected' : ''?>>
                            <?=$option->getRef()?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <?php if ($algo instanceof SelectMultiConditionAlgo) : ?>
        <?php
        /** @var $algo SelectMultiConditionAlgo */
        $relations = [];
        $relations[ElementaryConditionAlgo::RELATION_CONTAINS] = $allRelations[ElementaryConditionAlgo::RELATION_CONTAINS];
        $relations[ElementaryConditionAlgo::RELATION_NOTCONTAINS] = $allRelations[ElementaryConditionAlgo::RELATION_NOTCONTAINS];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputRelation">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" id="inputRelation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                            <?=$algo->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="inputValue">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <select name="value" id="inputValue" class="form-control">
                    <?php
                    /** @var $field SelectMulti */
                    $field = SelectMulti::loadByRef($algo->getInputRef(), $af);
                    $selected = $algo->getValue() ? $algo->getValue() : null;
                    ?>
                    <option value="" <?=$selected == null ? 'selected' : ''?>></option>
                    <?php foreach ($field->getOptions() as $option) : ?>
                        <option value="<?=$option->getRef()?>"
                            <?=$option->getRef() == $selected ? 'selected' : ''?>>
                            <?=$option->getRef()?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary"><?=__('UI', 'verb', 'save')?></button>
        </div>
    </div>

</form>
