<?php
/**
 * @author matthieu.napoli
 * @package Techno
 */

/** @var $family Techno_Model_Family */
$family = $this->family;

$documentation = $family->getDocumentation();

if ($this->edit) {

    // Modification
    $form = new UI_Form('documentationForm');
    $form->setAction($this->baseUrl('techno/family/submit-documentation/id/' . $family->getId()));
    $form->setAjax(true);
    $documentationField = new UI_Form_Element_Textarea('documentation');
    $documentationField->setWithMarkItUp(true);
    $documentationField->setValue($documentation);
    $form->addElement($documentationField);
    $form->addSubmitButton();
    echo $form->render();

} else {

    // Consultation
    if ($documentation) {
        $displayedDocumentation = Core_Tools::textile($documentation);
    } else {
        $displayedDocumentation = '<p class="muted">' . __('Techno', 'familyDetail', 'noDocumentation') . '</p>';
    }
    echo $displayedDocumentation;

}
