<?php
/**
 * @author matthieu.napoli
 * @package Techno
 */
use Keyword\Application\Service\KeywordDTO;

/** @var $family Techno_Model_Family */
$family = $this->family;
?>


<h2><?=__('Techno', 'familyDetail', 'generalDataTitle')?></h2>

<?php
$editFamilyForm = new Techno_Form_EditFamily('editFamily', $family);
echo $editFamilyForm->render();
?>


<h2><?=__('Techno', 'name', 'tags')?></h2>

<?php
// Tags
$datagrid = new UI_Datagrid('tags', 'datagrid_family_tags-datagrid', 'techno');
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('Techno', 'familyDetail', 'descriptionTagAddPanelTitle');
$datagrid->deleteElements = true;
$datagrid->addParam('idFamily', $family->getId());
// Colonne Signification
$meaningColumn = new UI_Datagrid_Col_List('meaning', __('Techno', 'name', 'meaning'));
$meaningColumn->editable = false;
$meaningColumn->list = [];
$meaningColumn->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
foreach ($this->meanings as $meaning) {
    /** @var $meaning Techno_Model_Meaning */
    $meaningColumn->list[$meaning->getId()] = $meaning->getLabel();
}
$datagrid->addCol($meaningColumn);
// Colonne Valeur
$valueColumn = new UI_Datagrid_Col_List('value', __('UI', 'name', 'value'));
$valueColumn->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
$valueColumn->editable = true;
$valueColumn->list = [];
foreach ($this->keywords as $keyword) {
    /** @var $keyword KeywordDTO */
    $valueColumn->list[$keyword->getRef()] = $keyword->getLabel();
}
$datagrid->addCol($valueColumn);

echo $datagrid->render();
?>


<h2><?=__('Techno', 'name', 'dimensions')?></h2>

<?php
// Dimensions
$datagrid = new UI_Datagrid('dimensions', 'datagrid_family_dimensions-datagrid', 'techno');
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('Techno', 'familyDetail', 'dimensionAddPanelTitle');
$datagrid->deleteElements = true;
$datagrid->addParam('idFamily', $family->getId());
// Colonne Orientation
$orientationColumn = new UI_Datagrid_Col_List('orientation', __('Techno', 'name', 'orientation'));
$orientationColumn->editable = true;
$orientationColumn->list = [
    Techno_Model_Family_Dimension::ORIENTATION_HORIZONTAL => __('Techno', 'property', 'horizontalFem'),
    Techno_Model_Family_Dimension::ORIENTATION_VERTICAL   => __('Techno', 'property', 'verticalFem'),
];
$datagrid->addCol($orientationColumn);
// Colonne Signification
$meaningColumn = new UI_Datagrid_Col_List('meaning', __('Techno', 'name', 'meaning'));
$meaningColumn->editable = false;
$meaningColumn->list = [];
foreach ($this->meanings as $meaning) {
    /** @var $meaning Techno_Model_Meaning */
    $meaningColumn->list[$meaning->getId()] = $meaning->getLabel();
}
$datagrid->addCol($meaningColumn);
// Colonne Requête
// $queryColumn = new UI_Datagrid_Col_Text('query', __('UI', 'name', 'query'));
// $queryColumn->addable = false;
// $queryColumn->editable = false;
// $datagrid->addCol($queryColumn);
// Colonne Mots-clés
$membersColumn = new UI_Datagrid_Col_Text('members', __('UI', 'name', 'members'));
$membersColumn->addable = false;
$membersColumn->editable = false;
$datagrid->addCol($membersColumn);
// Colonne Position
$orderColumn = new UI_Datagrid_Col_Order('position');
$orderColumn->labelAdd = 'Position';
$orderColumn->addable = false;
$orderColumn->editable = true;
$datagrid->addCol($orderColumn);
// Colonne Détails
$membersColumn = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$membersColumn->addable = false;
$membersColumn->editable = false;
$datagrid->addCol($membersColumn);

echo $datagrid->render();
?>


<?php
// Delete button
$deleteButton = new UI_HTML_Button(__('Techno', 'familyDetail', 'deleteButtonLabel'));
$deleteButton->id = "deleteFamily";
$deleteButton->addAttribute('class', 'btn-danger');
// $deleteButton->display();
?>

<script>
    $(function() {
        $("#deleteFamily").click(function(e) {
            var url = "<?=$this->baseUrl('techno/family/delete')?>";
            $.post(url, {id: <?=$family->getId()?>}, function(data, textStatus, request) {
                window.location = "<?=$this->baseUrl('techno/family/tree-edit')?>";
            })
            .error(errorHandler);
        });
    });
</script>
