<?php
/**
 * @author matthieu.napoli
 * @package Techno
 */
?>

<div class="page-header">
    <h1><?=__('Techno', 'familyList', 'familyList')?></h1>
</div>

<?php

$datagrid = new UI_Datagrid('familyDatagrid', 'datagrid_family-datagrid', 'techno');
$datagrid->addParam('mode', $this->mode);

$columns = [];

$columns['category'] = new UI_Datagrid_Col_List('category', __('UI', 'name', 'category'));
$list = [];
foreach ($this->categoryList as $category) {
    /** @var $category Techno_Model_Category */
    $list[$category->getId()] = $category->getLabel();
}
$columns['category']->list = $list;
$columns['category']->fieldType = UI_Datagrid_Col_List::FIELD_LIST;
$columns['category']->addable = true;

$columns['label'] = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$columns['label']->addable = true;

$columns['ref'] = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$columns['ref']->addable = true;

$columns['type'] = new UI_Datagrid_Col_List('type', __('UI', 'name', 'type'));
$columns['type']->list = [
    'coeff'   => __('Techno', 'name', 'coefficient'),
    'process' => __('Techno', 'name', 'emissionFactor'),
];
$columns['type']->addable = true;

$columns['unit'] = new UI_Datagrid_Col_Text('unit', __('Unit', 'name', 'unit'));
$columns['unit']->addable = true;

$columns['tags'] = new UI_Datagrid_Col_Text('tags', __('Techno', 'name', 'tags'));
$columns['tags']->addable = false;

$columns['detail'] = new UI_Datagrid_Col_Link('detail', __('UI', 'name', 'details'));
$columns['detail']->addable = false;

foreach ($columns as $key => $column) {
    $column->editable = false;
    $datagrid->addCol($column);
}

if ($this->mode == 'edition') {
    $datagrid->addElements = true;
    $datagrid->addPanelTitle = __('Techno', 'familyList', 'addPanelTitle');
}

$datagrid->display();
