<?php
/**
 * @author valentin.claras
 * @package Techno
 * Traduction des Element
 */
?>
    <div class="page-header">
        <h1><?=__('Techno', 'element', 'translate')?></h1>
    </div>
<?php
$id = 'datagrideTranslate_Techno_Model_Element_documentation';
$datagrid = new UI_Datagrid($id, 'datagrid_translate_elements_documentation', 'techno');
$datagrid->automaticFiltering = false;

$identifierColumn = new UI_Datagrid_Col_Text('identifier', __('UI', 'translate', 'identifier'));
$identifierColumn->editable = false;
$datagrid->addCol($identifierColumn);

foreach (Zend_Registry::get('languages') as $language) {
    $languageColumn = new UI_Datagrid_Col_LongText($language, __('UI', 'translate', 'language'.$language));
    $languageColumn->editable = true;
    $datagrid->addCol($languageColumn);
}

$datagrid->display();