<?php
/**
 * @author valentin.claras
 * @package Techno
 * Traduction des Element
 */
?>
    <div class="page-header">
        <h1><?=__('Techno', 'translate', 'parameterDocumentations')?> <small><?=__('UI', 'name', 'translations')?></small></h1>
    </div>
<?php
echo $this->translateDatagrid(
    'Techno_Model_Element',
    'documentation',
    'datagrid_translate_elements_documentation',
    'techno'
)->addIdentifierCol()->addLanguagesLongTextCols();