<?php
/**
 * @author valentin.claras
 * @package Techno
 * Traduction des Family
 */
?>
    <div class="page-header">
        <h1><?=__('Techno', 'family', 'translate')?></h1>
    </div>
<?php
$id = 'datagrideTranslate_'.Techno_Model_Family::getAlias().'_documentation';
$datagrid = new UI_Datagrid($id, 'datagrid_translate_families_documentation', 'techno');
$datagrid->automaticFiltering = false;

$identifierColumn = new UI_Datagrid_Col_Text('identifier', __('UI', 'translate', 'identifier'));
$identifierColumn->editable = false;
$datagrid->addCol($identifierColumn);

foreach (Zend_Registry::get('languages') as $language) {
    $languageColumn = new UI_Datagrid_Col_LongText($language, __('UI', 'translate', 'language'.$language));
    $languageColumn->editable = true;
    $datagrid->addCol($languageColumn);
}

$datagrid->display();