<?php
use AuditTrail\Domain\Context\OrganizationContext;
use AuditTrail\Domain\Entry;

$locale = Core_Locale::loadDefault();

$idCell = isset($this->idCell) ? $this->idCell : null;

/** @var Entry[] $entries */
$entries = $this->entries;
?>

<?php if (count($entries) === 0) : ?>
    <p class="text-muted">
        <?=__('UI', 'history', 'noHistory')?>
    </p>
<?php endif; ?>

<dl class="dl-horizontal">
    <?php foreach ($entries as $entry) : ?>

        <?php
        if (! isset($dayIterator)) {
            $dayIterator = null;
        }
        $currentDay = clone $entry->getDate();
        $currentDay->setTime(0, 0, 0);

        if ($dayIterator != $currentDay) {
            $showDay = true;
            $dayIterator = $currentDay;
        } else {
            $showDay = false;
        }
        ?>

        <?php if ($showDay) : ?>
            <div class="page-header">
                <h4>
                    <?=$locale->formatDate($currentDay)?>
                </h4>
            </div>
        <?php endif; ?>

        <?php
        $context = $entry->getContext();
        if (!$context instanceof OrganizationContext) {
            continue;
        }
        $entryCell = $context->getCell();
        $user = $entry->getUser();
        if (!$entryCell || !$user) {
            continue;
        }

        $inputUrl = $this->baseUrl('/orga/cell/input/idCell/' . $entryCell->getId() . '/fromIdCell/' . $idCell);
        $inputLabel = $this->translate($entryCell->getLabel());
        $inputLink = "<a href='$inputUrl''>$inputLabel</a>";

        $text = __('Orga', 'auditTrail', $entry->getEventName(),
            [
            'INPUT' => $inputLink,
            'USER'  => $user->getName(),
            ]
        );
        ?>

        <dt>
            <span class="badge badge-info"><?=$locale->formatTime($entry->getDate())?></span>
        </dt>

        <dd>
            <?=$text?>
        </dd>

    <?php endforeach; ?>
</dl>
