<?php
use AuditTrail\Domain\Context\OrganizationContext;
use AuditTrail\Domain\Entry;

$locale = Core_Locale::loadDefault();

/** @var Entry[] $entries */
$entries = $this->entries;
?>

<div class="page-header">
    <h1>Historique</h1>
</div>

<dl class="dl-horizontal">
    <?php foreach ($entries as $entry) : ?>

        <?php
        $context = $entry->getContext();
        if (!$context instanceof OrganizationContext) {
            continue;
        }
        $entryCell = $context->getCell();
        $user = $entry->getUser();
        if (!$entryCell || !$user) {
            continue;
        }

        $inputUrl = $this->baseUrl('/orga/cell/input/idCell/' . $entryCell->getId() . '/fromIdCell/');
        $inputLink = "<a href='$inputUrl''>{$entryCell->getLabel()}</a>";

        $text = __('AF', 'auditTrail', $entry->getEventName(), [
                                                               'INPUT' => $inputLink,
                                                               'USER' => $user->getName(),
                                                               ]);
        ?>

        <dt><?=$locale->formatDateTime($entry->getDate())?></dt>

        <dd><?=$text?></dd>

    <?php endforeach; ?>
</dl>
