<?php
/**
 * @author valentin.claras
 * @author cyril.perraud
 * @package Orga
 * @subpackage View
 */
echo $this->button('<span>'.__('Orga', 'analysis', 'cellDWCubesState').'</span>', 'info-sign', array('id' => 'cellDWCube'));
?>
<script type="text/javascript">
    var checkCellDWCubeState = function() {
        $.get(
            'orga/cell/dwcubestate/idCell/<?=$this->idCell?>',
            function (response) {
                addMessage(response.message, response.status);
            }
        ).fail(function(o) { errorHandler(o); });
    };
    $('#cellDWCube').unbind('click').bind('click', checkCellDWCubeState);
</script>

<?php
$datagrid = new UI_Datagrid('report', 'datagrid_cell_report', 'orga');

$columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$datagrid->addCol($columnLabel);

$columnDetails = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$datagrid->addCol($columnDetails);

$datagrid->addParam('idCell', $this->idCell);
$datagrid->addParam('idCube', $this->idCube);
$datagrid->pagination = false;
$datagrid->deleteElements = true;

echo $datagrid->render();
?>
<div class="wrapper">
    <?=$this->button(__('DW', 'reportList', 'add'), 'plus-sign')->link('orga/tab_celldetails/report/idCell/'.$this->idCell.'/idCube/'.$this->idCube)?>
</div>

<?php if (count($this->specificExports) > 0) { ?>
<fieldset class="wrapper">
    <legend><?=__('Orga', 'analysis', 'specificPDFExports')?></legend>
    <ul>
        <?php foreach ($this->specificExports as $specificExport) { ?>
        <li>
            <a href="<?=$specificExport['link']?>" target="_blank">
                <img alt="pdf" src="images/dw/pdf.png">
                <?=$specificExport['label']?>.pdf
            </a>
        </li>
        <? } ?>
    </ul>
</fieldset>
<?php } ?>
