<?php
/**
 * @author valentin.claras
 * @author cyril.perraud
 * @package Orga
 * @subpackage View
 */
if (!$this->isDWCubeUpToDate) { ?>
<div id="dWCubeNotUpToDate">
    <p>
        <span class="label label-warning"><?=__('UI', 'message', 'titleWarning') ?></span>
        <?=__('DW', 'rebuild', 'analysisTabRebuildAlert') ?>
    </p>
    <?php if ($this->dWCubesCanBeReset) { ?>
    <p><?=__('DW', 'rebuild', 'analysisDataRebuildWarningMessageOrganization') ?></p>
    <p><?=__('DW', 'rebuild', 'cellAdministratorWarningMessage') ?></p>
    <?= $this->button(__('DW', 'rebuild', 'analysisDataRebuildButton'), 'refresh icon-white', array('id' => 'resetDWCube', 'class' => 'btn-primary')) ?>
    <script type="text/javascript">
        $('#resetDWCube').click(function() {
            setMask(true);
            $.post(
                    'orga/cell/resetdws/idCell/<?=$this->idCell?>',
                    function(data, textStatus, jqXHR){
                        setMask(false);
                        addMessage(data.message, 'success');
                        $('#dWCubeNotUpToDate').remove();
                    }
            ).error(
                    function(o) { setMask(false); errorHandler(o); }
            );
        });
    </script>
    <? } else { ?>
    <p><?=__('DW', 'rebuild', 'cellNonAdministratorWarningMessage') ?></p>
    <? } ?>
    <hr/>
</div>
<?php } ?>

<?php
$datagrid = new UI_Datagrid('report', 'datagrid_cell_report', 'orga');

$columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$datagrid->addCol($columnLabel);

$columnDetails = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$datagrid->addCol($columnDetails);

$datagrid->addParam('idCell', $this->idCell);
$datagrid->addParam('idCube', $this->idCube);
$datagrid->pagination = false;
$datagrid->deleteElements = true;

echo $datagrid->render();
?>
<div class="wrapper">
    <?=$this->button(__('DW', 'reportList', 'add'), 'plus-sign')->link('orga/tab_celldetails/report/idCell/'.$this->idCell.'/idCube/'.$this->idCube)?>
</div>

<?php if (count($this->specificExports) > 0) { ?>
<fieldset class="wrapper">
    <legend><?=__('Orga', 'analysis', 'specificPDFExports')?></legend>
    <ul>
        <?php foreach ($this->specificExports as $specificExport) { ?>
        <li>
            <a href="<?=$specificExport['link']?>" target="_blank">
                <img alt="pdf" src="images/dw/pdf.png">
                <?=$specificExport['label']?>.pdf
            </a>
        </li>
        <? } ?>
    </ul>
</fieldset>
<?php } ?>
