<?php
$locale = Core_Locale::loadDefault();
/** @var Orga_Model_InputComment[]|Social_Model_Comment[] $comments */
$comments = $this->comments;
?>

<div>
<?php if (count($comments) === 0) : ?>
    <p class="muted">
        <?=__('Social', 'comment', 'noComment')?>
    </p>
<?php endif; ?>

    <dl class="dl-horizontal">
        <?php foreach ($comments as $comment) : ?>
        <dt>
            <span class="badge badge-info">
                <?=$locale->formatDateTime($comment->getCreationDate())?>
            </span>
        </dt>
        <dd>
            <?=__('Social', 'comment', 'by')?>
            <b>
                <?=$comment->getAuthor()->getName()?>
            </b>
            <?=__('Orga', 'input', 'aboutInput')?>
            <a href="orga/cell/input/idCell/<?=$comment->getCell()->getId()?>/fromIdCell/<?=$this->idCell?>">
                <?=$comment->getCell()->getLabel()?><?=__('UI', 'other', ':')?>
            </a>
            « <?=Core_Tools::truncateString($comment->getText(), 200)?> ».
        </dd>
        <?php endforeach; ?>
    </dl>

</div>