<?php
$locale = Core_Locale::loadDefault();
/** @var Orga_Model_InputComment[]|Social_Model_Comment[] $comments */
$comments = $this->comments;
?>

<?php if (count($comments) === 0) : ?>
    <p class="muted">
        <?=__('Social', 'comment', 'noComment')?>
    </p>
<?php endif; ?>

<ul>
    <?php foreach ($comments as $comment) : ?>
        <li>
            <?=$locale->formatDateTime($comment->getCreationDate())?>

            <?=__('Social', 'comment', 'by')?>
            <?=$comment->getAuthor()->getName()?>

            <?=__('Orga', 'input', 'aboutInput')?>
            <?=$comment->getCell()->getLabel()?><?=__('UI', 'other', ':')?>

            « <?=Core_Tools::truncateString($comment->getText(), 200)?> ».
        </li>
    <?php endforeach; ?>
</ul>
