<?php foreach ($this->exports as $exportRef => $exportArray) : ?>
<fieldset class="wrapper">
    <legend style="cursor:default"><?=$exportArray['label']?></legend>
    <div>
        <form class="form-inline" action="orga/referential/export">
            <div class="input-prepend input-append">
                <span class="add-on format">
                    <img alt="<?=$this->defaultFormat?>" src="images/dw/<?=$this->defaultFormat?>.png">
                </span>
                <input name="export" type="hidden" value="<?=$exportRef?>">
                <?php if (count($this->formats) > 1) : ?>
                <select name="format" class="input format">
                    <?php foreach($this->formats as $formatRef => $formatLabel) : ?>
                        <option value="<?=$formatRef?>"><?=$formatLabel?></option>
                    <?php endforeach; ?>
                </select>
                <?php else: ?>
                <input name="format" type="hidden" value="<?=$this->defaultFormat?>">
                <?php endif; ?>
                <?php if (isset($exportArray['version']) && (count($exportArray['version']) > 0)) : ?>
                    <?php if (count($this->formats) > 1) : ?>
                        <span class="add-on">
                            -
                        </span>
                    <?php endif; ?>
                    <select name="version" >
                        <?php foreach($exportArray['version'] as $versionRef => $versionLabel) : ?>
                            <option value="<?=$versionRef?>"><?=$versionLabel?></option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
                <button class="btn btn-primary" type="submit"><?=__('UI', 'verb', 'export')?></button>
            </div>
        </form>
    </div>
</fieldset>
<?php endforeach; ?>
<script type="text/javascript">
    $('.format').on(
        'change',
        function() {
            var imgAddOn = $(this).parent().children('span.format').children('img');
            imgAddOn.attr('alt', $(this).val());
            imgAddOn.attr('src', 'images/dw/'+$(this).val()+'.png');
        }
    );
</script>

<div id="exportReferentialAsExcelPopup" class="modal hide fade">
    <div class="modal-body">
        <p><?=__('Orga', 'analysis', 'detailedExcelExportPopup')?></p>
        <div class="progress progress-striped active">
            <div class="bar" style="width: 100%;"></div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal"><?=__('UI', 'verb', 'close')?></button>
    </div>
</div>

<script>
    $("button.btn-primary[type=submit]").click(function(e) {
        $('#exportReferentialAsExcelPopup').modal();
    });
</script>