<?php

use Techno\Domain\Family\Family;

UI_Form::addHeader();
UI_Datagrid::addHeader();
UI_TMD::addHeader();

/** @var $family Family */
$family = $this->family;

if ($this->edit) {
    $collapseGeneralData = new UI_HTML_Collapse('collapseGeneralData');
    $collapseGeneralData->title = __('Techno', 'familyDetail', 'generalDataTitle');
    $collapseGeneralData->foldedByDefault = true;
    $collapseGeneralData->body = $this->partial('family/details/general-edit.phtml', [
        'family' => $family,
    ]);
    $generalData = $collapseGeneralData->render();
} else {
    $generalData = $this->partial('family/details/general-view.phtml', [
         'family' => $family,
    ]);
}

?>

<div class="page-header">
    <h1><?=$this->escape($family->getLabel())?></h1>
</div>

<?php
echo $generalData;

// TMD
$collapseTMD = new UI_HTML_Collapse('collapseTMD', __('UI', 'name', 'elements'));
$collapseTMD->body = $this->partial('family/details/tmd.phtml', [
    'family' => $family,
    'edit'   => $this->edit,
]);
$collapseTMD->display();

if ($this->edit) {
    echo $this->partial('family/details/edit.phtml', ['family' => $family]);
}
