<?php
/**
 * @author valentin.claras
 * @package Orga
 * @subpackage View
 */

$action = $this->action;

$datagridACLs = new UI_Datagrid('cellACLs'.$action.$this->idCell, 'datagrid_cell_acls_current', 'orga');

$columnUserFirstName = new UI_Datagrid_Col_Text('userFirstName', __('User', 'user', 'firstName'));
$columnUserFirstName->addable = false;
$datagridACLs->addCol($columnUserFirstName);

$columnUserLastName = new UI_Datagrid_Col_Text('userLastName', __('User', 'user', 'lastName'));
$columnUserLastName->addable = false;
$datagridACLs->addCol($columnUserLastName);

$columnUserEmail = new UI_Datagrid_Col_Text('userEmail', __('UI', 'name', 'emailAddress'));
$datagridACLs->addCol($columnUserEmail);

$columnRole = new UI_Datagrid_Col_List('userRole', __('User', 'role', 'role'));
$columnRole->list = $this->listRoles;
$datagridACLs->addCol($columnRole);

$datagridACLs->addParam('idCell', $this->idCell);

echo $datagridACLs->render();
?>

<script>
    $('#granularityCellACL<?=$this->idGranularity?>_details_popup .modal-header h3').html("<?=$this->labelPopup?>");
</script>