<?php
    // Détail d'un Set.
use MyCLabs\MUIH\Tab;
use MyCLabs\MUIH\Tabs;
?>
<div class="page-header">
    <h1>
        <?=$this->setName?>
        <small><?=$this->aFName?></small>
        <small class="pull-right">
            <?= $this->button(__('UI', 'other', 'backButton'), 'arrow-left')->link('simulation/set/manage') ?>
        </small>
    </h1>
</div>
<?php
    $tabDetailsSet = new Tabs('detailSet', true);

    $tabScenario = new Tab('scenarios');
    $tabScenario->setTitle(__('Simulation', 'name', 'scenarios'));
    $tabScenario->setContent($this->partial(
        'partials/set/scenario.phtml',
        array('idSet' => $this->idSet)
    ));
    if (($this->activatedTab == 'scenario') || ($this->activatedTab !== 'reports')) {
        $tabScenario->active();
    }
    $tabDetailsSet->addTab($tabScenario);

    $tabAnalyse = new Tab('reports');
    $tabAnalyse->setTitle(__('DW', 'name', 'analyses'));
    $tabAnalyse->setContent($this->partial(
        'partials/set/report.phtml',
        array('idSet' => $this->idSet, 'idCube' => $this->idCube, 'isSetDWCubeUpToDate' => $this->isSetDWCubeUpToDate)
    ));
    if ($this->activatedTab == 'reports') {
        $tabAnalyse->active();
    }
    $tabDetailsSet->addTab($tabAnalyse);

    $tabDetailsSet->display();