<?php
    // Détail d'un Set.
?>
<div class="page-header">
    <h1>
        <?=$this->setName?>
        <small><?=$this->aFName?></small>
        <small class="pull-right">
            <?= $this->button(__('UI', 'other', 'backButton'), 'arrow-left')->link('simulation/set/manage') ?>
        </small>
    </h1>
</div>
<?php
    $tabDetailsSet = new UI_Tab_View('detailSet', true);

    $tabScenario = new UI_Tab('scenarios');
    $tabScenario->label = __('Simulation', 'name', 'scenarios');
    $tabScenario->content = $this->partial(
        'partials/set/scenario.phtml',
        array('idSet' => $this->idSet)
    );
    if (($this->activatedTab == 'scenario') || ($this->activatedTab !== 'reports')) {
        $tabScenario->active = true;
    }
    $tabDetailsSet->addTab($tabScenario);

    $tabAnalyse = new UI_Tab('reports');
    $tabAnalyse->label = __('DW', 'name', 'analyses');
    $tabAnalyse->content = $this->partial(
        'partials/set/report.phtml',
        array('idSet' => $this->idSet, 'idCube' => $this->idCube, 'isSetDWCubeUpToDate' => $this->isSetDWCubeUpToDate)
    );
    if ($this->activatedTab == 'reports') {
        $tabAnalyse->active = true;
    }
    $tabDetailsSet->addTab($tabAnalyse);

    $tabDetailsSet->display();