<div class="page-header">
    <h1><?=__('Social', 'name', 'actionTemplates')?></h1>
</div>

<?php
$datagrid = new UI_Datagrid('genericActions', 'datagrid_action_generic-action', 'social');

$labelColumn = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$labelColumn->editable = true;
$datagrid->addCol($labelColumn);

$themeColumn = new UI_Datagrid_Col_List('theme', __('Social', 'name', 'actionTheme'));
$themeColumn->list = [];
foreach ($this->themes as $theme) {
    /** @var $theme Social_Model_Theme */
    $themeColumn->list[$theme->getId()] = $theme->getLabel();
}
$themeColumn->sortName = Social_Model_Theme::QUERY_LABEL;
$themeColumn->entityAlias = Social_Model_Theme::getAlias();
$datagrid->addCol($themeColumn);

$descriptionColumn = new UI_Datagrid_Col_LongText('description', __('UI', 'name', 'description'));
$descriptionColumn->popup->title = __('UI', 'name', 'description');
$descriptionColumn->popup->render();
$datagrid->addCol($descriptionColumn);

$contextActionCountColumn = new UI_Datagrid_Col_Number('contextActionCount',
                                                       __('Social', 'actionTemplate', 'numberOfAssociatedActions'));
$contextActionCountColumn->addable = false;
$datagrid->addCol($contextActionCountColumn);

$detailsColumn = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$datagrid->addCol($detailsColumn);

$datagrid->addElements = true;
$datagrid->addPanelTitle = __('Social', 'actionTemplate', 'addPanelTitle');

$datagrid->deleteElements = true;
$datagrid->pagination = true;
$datagrid->display();
