<div class="page-header">
    <h1><?= __('Social', 'name', 'actionThemes') ?></h1>
</div>

<?php
$datagrid = new UI_Datagrid('theme', 'datagrid_action_theme', 'social');
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('Social', 'actionTheme', 'addPanelTitle');
$datagrid->deleteElements = true;
$datagrid->pagination = true;
$datagrid->paginationRowPerPage = 10;

//Definition des colonnes
$columnLabel = new UI_Datagrid_Col_Text('label', __('Social', 'name', 'actionTheme'));
$columnLabel->editable = true;
$datagrid->addCol($columnLabel);

$columnNumber = new UI_Datagrid_Col_Number('number', __('Social', 'actionTheme', 'numberOfAssociatedActionTemplates'));
$columnNumber->addable = false;
$datagrid->addCol($columnNumber);

$datagrid->display();
