<?php
/**
 * @author  matthieu.napoli
 * @package AF
 */
?>

<div class="page-header">
    <h1><?=__('AF', 'formTree', 'pageTitle')?></h1>
</div>

<?php
$tree = new UI_Tree('afTree', 'tree_af-tree', 'af');
$tree->expandAll = true;
$tree->addParam('mode', $this->mode);

// Ajout
$tree->addNode = true;
$addForm = new AF_Form_AddCategory('addNode');
$tree->addPanelForm = $addForm;
$tree->addPanelTitle = __('AF', 'formTree', 'addPanelTitle');
$tree->addButtonLabel = __('AF', 'formTree', 'addButton');
// Édition
$editLabel = new UI_Form_Element_Text('afTree_labelEdit');
$editLabel->setLabel(__('UI', 'name', 'label'));
$htmlComplement = new UI_Form_Element_HTML('afTree_htmlComplement');
$htmlComplement->setLabel('');
$tree->setEditNode(true, true, [$editLabel, $htmlComplement]);
// Suppression
$tree->deleteNode = true;
$tree->expandAll = false;
$tree->collapseAll = false;

$tree->display();

$script = '';
$script .= '$(\'#afTree_element\').change(function(e) {';
$script .= 'var idNode = $(this).val();';
$script .= '$.get(';
$script .= '\'af/tree_af-tree/getinfoedit?idNode=\' + idNode, ';
$script .= 'function(o){';
$script .= '$(\'#afTree_labelEdit\').val(o.label);';
$script .= '$(\'#afTree_htmlComplement\').html(o.htmlComplement);';
$script .= '$(\'#afTree_editPanel .modal-header h3\').html(o.title);';
$script .= '}';
$script .= ').error(function(o) {';
$script .= 'errorHandler(o);';
$script .= '});';
$script .= '});';

$this->headScript()->appendScript($script);
