<?php
use Account\Domain\Account;
use User\Domain\User;

/** @var Account[] $accountList */
$accountList = $this->accountList;

$user = null;
if (Zend_Auth::getInstance()->hasIdentity()) {
    try {
        /** @var User $user */
        $user = User::load(Zend_Auth::getInstance()->getIdentity());
    } catch (Core_Exception_NotFound $e) {
    }
}

?><!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <title><?= __('Inventory', 'layout', 'title') ?></title>

        <?php
        $server = $_SERVER["SERVER_NAME"];
        if ($_SERVER["SERVER_PORT"] && $_SERVER["SERVER_PORT"] != 80) {
            $server .= ':' . $_SERVER["SERVER_PORT"];
        }
        ?>
        <base href="http://<?= $server ?><?= $this->baseUrl() ?>/"/>

        <!-- Basic Styles -->
        <link rel="stylesheet" type="text/css" media="screen" href="vendor/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="vendor/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="vendor/css/muih.css">

        <!-- SmartAdmin Styles : Please note (smartadmin-production.css) was created using LESS variables -->
        <link rel="stylesheet" type="text/css" media="screen" href="vendor/css/smartadmin-production.css">
        <link rel="stylesheet" type="text/css" media="screen" href="vendor/css/smartadmin-skins.css">
        <link rel="stylesheet" type="text/css" media="screen" href="css/smartadmin-additions.css">

        <?= $this->headLink()->toString(8) ?>
        <?= $this->headStyle()->toString(8) ?>

        <!-- FAVICONS -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <link rel="icon" href="images/favicon.ico" type="image/x-icon">

        <!-- GOOGLE FONT -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

        <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
        <meta content="yes" name="apple-mobile-web-app-capable">
        <meta content="black" name="apple-mobile-web-app-status-bar-style">

        <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <script>
            if (!window.jQuery) {
                document.write('<script src="vendor/js/libs/jquery-2.0.2.min.js"><\/script>');
            }
        </script>

    </head>
    <body class="fixed-navigation fixed-header fixed-ribbon">

        <?= $this->partial('header.phtml', ['user' => $user]) ?>

        <?php
        if ($this->account !== null) {
            echo $this->partial('sidebar.phtml', ['account' => $this->account, 'activeMenu' => $this->activeMenu]);
        } else {
            echo '<aside id="left-panel"></aside>';
        }
        ?>

        <!-- MAIN PANEL -->
        <div id="main">
            <!-- RIBBON -->
<!--            <div id="ribbon">-->
<!--                --><?//= $this->partial('breadcrumb.phtml', ['breadcrumbs' => $this->breadcrumbs]) ?>
<!--            </div>-->

            <div id="messageZone" class="subnav subnav-fixed"><?= UI_Message::renderStatic(false) ?></div>

            <div id="content">
                <?= $this->layout()->content ?>
            </div>
        </div>

        <div id="shortcut">
            <ul>
                <?php foreach ($accountList as $alternativeAccount) : ?>
                    <?php
                    $selected = $alternativeAccount->getId() == $this->account->id ? 'selected' : '';
                    ?>
                    <li>
                        <a href="account/dashboard?id=<?=$alternativeAccount->getId()?>"
                           class="<?=$selected?> jarvismetro-tile big-cubes bg-color-blue">
                            <span class="iconbox">
                                <i class="fa fa-envelope fa-4x"></i>
                                <span><?=$alternativeAccount->getName()?></span>
                            </span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
        <script>
            if (!window.jQuery.ui) {
                document.write('<script src="vendor/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
            }
        </script>

        <script src="vendor/js/bootstrap/bootstrap.min.js"></script>
        <script src="vendor/js/smartwidgets/jarvis.widget.min.js"></script>
        <script src="vendor/js/libs/jquery.form.min.js"></script>
        <script src="vendor/js/libs/jquery.confirm.min.js"></script>

        <script src="vendor/js/app.js"></script>
        <script src="vendor/js/muih.js"></script>
        <script src="scripts/ui/translate.js"></script>
        <script src="scripts/ajax-form.js"></script>

        <script>
            eraseFirstMessage = function (loop) {
                loop = typeof loop !== 'undefined' ? loop - 1 : 0;
                $('#messageZone').children('div:first').alert('close');
                if (loop > 0) {
                    setTimeout(eraseFirstMessage, 300, (loop - 1));
                }
            };
            addMessage = function (text, type) {
                var title, divClass;
                type = typeof type !== 'undefined' ? type : 'alert';
                switch (type) {
                    case 'info':
                        title = '<?=__('UI', 'message', 'titleInfo')?>';
                        divClass = ' alert-info';
                        break;
                    case 'success':
                        title = '<?=__('UI', 'message', 'titleSuccess')?>';
                        divClass = ' alert-success';
                        break;
                    case 'error':
                        title = '<?=__('UI', 'message', 'titleError')?>';
                        divClass = ' alert-danger';
                        break;
                    case 'warning':
                    default :
                        title = '<?=__('UI', 'message', 'titleWarning')?>';
                        divClass = ' alert-warning';
                        break;
                }
                var messageZone = $('#messageZone');
                messageZone.append('<div class="alert' + divClass + ' alert-dismissable fade in" style="display:none;"></div>');
                messageZone.children('div:last').append('<button class="close" data-dismiss="alert">×</button>');
                messageZone.children('div:last').append('<strong>' + title + '</strong> ' + text);
                messageZone.children('div:last').slideDown(100);

                if (messageZone.children('div').size() > 2) {
                    setTimeout(eraseFirstMessage, 500, 2);
                }
            };
            errorHandler = function (jqXHR) {
                // Ignore aborted requests
                if (jqXHR.readyState == 0 || jqXHR.status == 0 || jqXHR.statusText == "abort") {
                    return;
                }
                var response = (typeof(jqXHR.responseText) == 'string') ? $.parseJSON(jqXHR.responseText) : jqXHR;
                addMessage(response.message, response.typeError);
            };
            setMask = function (display) {
                if (typeof(indexStackMask) == "undefined") {
                    indexStackMask = 0;
                }
                if (display) {
                    indexStackMask++;
                    if ($('#loadingMask').is(':not(:visible)')) {
                        $('#loadingMask').slideDown(100);
                    }
                } else {
                    indexStackMask--;
                    if (indexStackMask <= 0) {
                        if ($('#loadingMask').is(':visible')) {
                            $('#loadingMask').slideUp(100);
                        }
                        indexStackMask = 0;
                    }
                }
            };
        </script>

        <?= $this->headScript()->toString() ?>

        <script type="text/javascript">
            $(function() {
                pageSetUp();
            });
        </script>

        <!--[if IE 7]>
        <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
        <![endif]-->

    </body>
</html>
