<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php
    $server = $_SERVER["SERVER_NAME"];
    if ($_SERVER["SERVER_PORT"] && $_SERVER["SERVER_PORT"] != 80) {
        $server .= ':' . $_SERVER["SERVER_PORT"];
    }
    ?>
    <base href="http://<?= $server ?><?= $this->baseUrl() ?>/"/>
    <title><?=__('Inventory', 'layout', 'title')?></title>

    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
    <script type="text/javascript" src="scripts/ui/jquery-1.7.2.min.js"></script>
    <?php
    // Layout de l'application.
    $this->headScript()->prependFile('scripts/ui/translate.js', 'text/javascript');
    $this->headScript()->prependFile('bootstrap/js/bootstrap.min.js', 'text/javascript');
    $this->headScript()->prependFile('scripts/ui/jquery.confirm.js', 'text/javascript');
    $this->headScript()->appendFile('scripts/bootbox.min.js', 'text/javascript');
    $this->headScript()->appendFile('scripts/ui/feedback-form.js', 'text/javascript');
    $this->headLink()->prependStylesheet('css/orga/organizations.css');
    $this->headLink()->prependStylesheet('css/user/login.css');
    $this->headLink()->prependStylesheet('css/ui/layout.css');
    $this->headLink()->prependStylesheet('font-awesome/css/font-awesome.min.css');
    $this->headLink()->prependStylesheet('bootstrap/css/bootstrap-responsive.css');
    $this->headLink()->prependStylesheet('bootstrap/css/bootstrap.css');
    // Ajout des link, et des Styles dynamiques. //  Les scripts sont ajoutés à la fin.
    echo "\n" . $this->headLink()->toString(8) . "\n" . $this->headStyle()->toString(8) . "\n";
    ?>
</head>
<body>
    <?= $this->partial('elements/menu.phtml', array()) ?>
    <?= $this->partial('elements/breadcrumb.phtml', array()) ?>

    <div id="messageZone" class="subnav subnav-fixed"><?= UI_Message::renderStatic(false) ?></div>

    <div id="loadingMask"></div>

    <div class="container-fluid page">
        <div class="row-fluid">
            <div class="span12">
                <?= $this->layout()->content ?>
            </div>
        </div>
    </div>

    <hr/>
    <?= $this->partial('elements/footer.phtml', array()) ?>
    <script>
        eraseFirstMessage = function (loop) {
            loop = typeof loop !== 'undefined' ? loop - 1 : 0;
            $('#messageZone').children('div:first').alert('close');
            if (loop > 0) {
                setTimeout(eraseFirstMessage, 300, (loop - 1));
            }
        };
        addMessage = function (text, type) {
            var title, divClass;
            type = typeof type !== 'undefined' ? type : 'alert';
            switch (type) {
                case 'info':
                    title = '<?=__('UI', 'message', 'titleInfo')?>';
                    divClass = ' alert-info';
                    break;
                case 'success':
                    title = '<?=__('UI', 'message', 'titleSuccess')?>';
                    divClass = ' alert-success';
                    break;
                case 'error':
                    title = '<?=__('UI', 'message', 'titleError')?>';
                    divClass = ' alert-error';
                    break;
                case 'warning':
                default :
                    title = '<?=__('UI', 'message', 'titleWarning')?>';
                    divClass = '';
                    break;
            }
            var messageZone = $('#messageZone');
            messageZone.append('<div class="alert' + divClass + ' fade in" style="display:none;"></div>');
            messageZone.children('div:last').append('<button class="close" data-dismiss="alert">×</button>');
            messageZone.children('div:last').append('<strong>' + title + '</strong> ' + text);
            messageZone.children('div:last').slideDown(100);

            if (messageZone.children('div').size() > 2) {
                setTimeout(eraseFirstMessage, 500, 2);
            }
        };
        errorHandler = function (jqXHR) {
            // Ignore aborted requests
            if (jqXHR.readyState == 0 || jqXHR.status == 0 || jqXHR.statusText == "abort") {
                return;
            }
            var response = (typeof(jqXHR.responseText) == 'string') ? $.parseJSON(jqXHR.responseText) : jqXHR;
            addMessage(response.message, response.typeError);
        };
        setMask = function (display) {
            if (typeof(indexStackMask) == "undefined") {
                indexStackMask = 0;
            }
            if (display) {
                indexStackMask++;
                if ($('#loadingMask').is(':not(:visible)')) {
                    $('#loadingMask').slideDown(100);
                }
            } else {
                indexStackMask--;
                if (indexStackMask <= 0) {
                    if ($('#loadingMask').is(':visible')) {
                        $('#loadingMask').slideUp(100);
                    }
                    indexStackMask = 0;
                }
            }
        };
    </script>
    <?= $this->headScript()->toString() . "\n" ?>
    <script>
        $(document).ready(function () {
            setMask(false);
        });
    </script>
    <script>
        <?=Core_Translate::exportJS('UI', 'verb', 'cancel')?>
        <?=Core_Translate::exportJS('UI', 'verb', 'send')?>
        <?=Core_Translate::exportJS('UI', 'feedback', 'title')?>
        <?=Core_Translate::exportJS('UI', 'feedback', 'unclearContent')?>
        <?=Core_Translate::exportJS('UI', 'feedback', 'bugReport')?>
        <?=Core_Translate::exportJS('UI', 'feedback', 'improvement')?>
        <?=Core_Translate::exportJS('UI', 'feedback', 'moreDetails')?>
        <?=Core_Translate::exportJS('UI', 'feedback', 'thanks')?>
    </script>
</body>
</html>
