<?php
use Account\Domain\Account;
use User\Domain\User;

/** @var Account[] $accountList */
$accountList = $this->accountList;

$user = null;
if (Zend_Auth::getInstance()->hasIdentity()) {
    try {
        /** @var User $user */
        $user = User::load(Zend_Auth::getInstance()->getIdentity());
    } catch (Core_Exception_NotFound $e) {
    }
}

?><!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <title><?= __('Inventory', 'layout', 'title') ?></title>

        <?php
        $server = $_SERVER["SERVER_NAME"];
        if ($_SERVER["SERVER_PORT"] && $_SERVER["SERVER_PORT"] != 80) {
            $server .= ':' . $_SERVER["SERVER_PORT"];
        }
        ?>
        <base href="http://<?= $server ?><?= $this->baseUrl() ?>/"/>

        <link rel="stylesheet" type="text/css" media="screen" href="build/vendors.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="build/app.min.css">

        <?= $this->headLink()->toString(8) ?>
        <?= $this->headStyle()->toString(8) ?>

        <!-- FAVICONS -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <link rel="icon" href="images/favicon.ico" type="image/x-icon">

        <!-- GOOGLE FONT -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

        <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
        <meta content="yes" name="apple-mobile-web-app-capable">
        <meta content="black" name="apple-mobile-web-app-status-bar-style">

        <script src="build/head.min.js"></script>
    </head>
    <body class="fixed-navigation fixed-header fixed-ribbon">

        <?= $this->partial('header.phtml', ['user' => $user]) ?>

        <?php
        if ($this->account !== null) {
            echo $this->partial('sidebar.phtml', ['account' => $this->account, 'activeMenu' => $this->activeMenu]);
        } else {
            echo '<aside id="left-panel"></aside>';
        }
        ?>

        <!-- MAIN PANEL -->
        <div id="main">
            <div id="messageZone" class="subnav subnav-fixed"><?= UI_Message::renderStatic(false) ?></div>

            <div id="content">
                <?= $this->layout()->content ?>
            </div>
        </div>

        <div id="shortcut">
            <ul>
                <?php foreach ($accountList as $alternativeAccount) : ?>
                    <?php
                    $selected = $alternativeAccount->getId() == $this->account->id ? 'selected' : '';
                    ?>
                    <li>
                        <a href="account/dashboard?id=<?=$alternativeAccount->getId()?>"
                           class="<?=$selected?> account-button jarvismetro-tile big-cubes bg-color-blue">
                            <span class="iconbox">
                                <i class="fa fa-institution fa-4x"></i>
                                <span class="text-center"><?=$alternativeAccount->getName()?></span>
                            </span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <script src="build/vendors.min.js"></script>
        <script src="build/app.min.js"></script>

        <script>
            eraseFirstMessage = function (loop) {
                loop = typeof loop !== 'undefined' ? loop - 1 : 0;
                $('#messageZone').children('div:first').alert('close');
                if (loop > 0) {
                    setTimeout(eraseFirstMessage, 300, (loop - 1));
                }
            };
            addMessage = function (text, type) {
                var title, divClass;
                type = typeof type !== 'undefined' ? type : 'warning';
                switch (type) {
                    case 'info':
                        title = '<?=__('UI', 'message', 'titleInfo')?>';
                        divClass = 'alert-info';
                        break;
                    case 'success':
                        title = '<?=__('UI', 'message', 'titleSuccess')?>';
                        divClass = 'alert-success';
                        break;
                    case 'error':
                        title = '<?=__('UI', 'message', 'titleError')?>';
                        divClass = 'alert-danger';
                        break;
                    case 'warning':
                    default :
                        title = '<?=__('UI', 'message', 'titleWarning')?>';
                        divClass = 'alert-warning';
                        break;
                }
                var messageZone = $('#messageZone');
                var message = $('<div class="alert ' + divClass + ' alert-dismissable fade in" style="display:none;"></div>');
                message.append('<button class="close" data-dismiss="alert">×</button>');
                message.append('<strong>' + title + '</strong> ' + text);
                message.fadeIn();
                messageZone.append(message);

                if (messageZone.children('div').size() > 2) {
                    setTimeout(eraseFirstMessage, 500, 1);
                }
                // Auto-close success messages
                if (type === 'success') {
                    setTimeout(function () {
                        message.alert('close');
                    }, 5000);
                }
            };
            errorHandler = function (jqXHR) {
                // Ignore aborted requests
                if (jqXHR.readyState == 0 || jqXHR.status == 0 || jqXHR.statusText == "abort") {
                    return;
                }
                var response = (typeof(jqXHR.responseText) == 'string') ? $.parseJSON(jqXHR.responseText) : jqXHR;
                addMessage(response.message, response.typeError);
            };
            setMask = function (display) {
                if (typeof(indexStackMask) == "undefined") {
                    indexStackMask = 0;
                }
                if (display) {
                    indexStackMask++;
                    if ($('#loadingMask').is(':not(:visible)')) {
                        $('#loadingMask').slideDown(100);
                    }
                } else {
                    indexStackMask--;
                    if (indexStackMask <= 0) {
                        if ($('#loadingMask').is(':visible')) {
                            $('#loadingMask').slideUp(100);
                        }
                        indexStackMask = 0;
                    }
                }
            };
        </script>

        <?= $this->headScript()->toString() ?>

        <script>
            $(function() {
                // Set up from the template
                pageSetUp();

                <?=Core_Translate::exportJS('UI', 'verb', 'cancel')?>
                <?=Core_Translate::exportJS('UI', 'verb', 'send')?>
                <?=Core_Translate::exportJS('UI', 'feedback', 'title')?>
                <?=Core_Translate::exportJS('UI', 'feedback', 'unclearContent')?>
                <?=Core_Translate::exportJS('UI', 'feedback', 'bugReport')?>
                <?=Core_Translate::exportJS('UI', 'feedback', 'improvement')?>
                <?=Core_Translate::exportJS('UI', 'feedback', 'moreDetails')?>
                <?=Core_Translate::exportJS('UI', 'feedback', 'thanks')?>

                // Feedback form
                $('#feedbackButton').click(function(e) {
                    e.preventDefault();
                    <?php
                    if ($user) {
                        $userEmail = $user->getEmail();
                        echo "var data = {user: '$userEmail'};";
                    } else {
                        echo "var data = {};";
                    }
                    ?>
                    feedbackForm("<?=$this->baseUrl('feedback/submit')?>", data);
                });
            });
        </script>

        <!--[if IE 7]>
        <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
        <![endif]-->

        <?php if (APPLICATION_ENV === 'production') : ?>
            <script>
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                ga('create', 'UA-23818673-3', 'myc-sense.com');
                ga('send', 'pageview');
            </script>
        <?php endif; ?>

    </body>
</html>
