<?php
/** @var Account\Application\ViewModel\AccountView $account */
$account = $this->account;
?>

<aside id="left-panel">

    <!-- Account switcher -->
    <div class="login-info">
        <span>
            <!-- User image size is adjusted inside CSS, it should stay as it -->
            <a href="#" id="show-shortcut">
                <img alt="me" class="online" src="images/account-default.png">
                <span><?=$account->name?></span>
                <i class="fa fa-angle-down"></i>
            </a>
        </span>
    </div>

    <nav>
        <ul>
            <li class="<?=$this->activeMenu === 'dashboard' ? 'active' : ''?>">
                <a href="account/dashboard">
                    <i class="fa fa-lg fa-fw fa-home"></i>
                    <span class="menu-item-parent"><?=__('Account', 'name', 'dashboard')?></span>
                </a>
            </li>


            <!-- Workspaces -->
            <?php if (count($account->workspaces) > 0) : ?>
                <li>
                    <a href="#">
                        <i class="fa fa-lg fa-fw fa-inbox"></i>
                        <span class="menu-item-parent">Workspaces</span>
                    </a>
                    <ul>
                        <?php foreach ($account->workspaces as $workspace) : ?>
                            <li class="<?=$this->activeMenu === 'workspace-' . $workspace->id ? 'active' : ''?>">
                                <a href="orga/workspace/view/workspace/<?=$workspace->id?>"
                                    title="<?=$workspace->label?>">
                                    <?=$workspace->label?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>


            <!-- AF libraries -->
            <?php if (count($account->afLibraries) > 0) : ?>
                <li>
                    <a href="#">
                        <i class="fa fa-lg fa-fw fa-edit"></i>
                        <span class="menu-item-parent"><?=__('AF', 'name', 'forms')?></span>
                    </a>
                    <ul>
                        <?php foreach ($account->afLibraries as $library) : ?>
                            <li class="<?=$this->activeMenu === 'af-' . $library->id ? 'active' : ''?>">
                                <a href="af/library/view/id/<?=$library->id?>"
                                   title="<?=$library->label?>">
                                    <?=$library->label?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>


            <!-- Parameter libraries -->
            <?php if (count($account->parameterLibraries) > 0) : ?>
                <li>
                    <a href="#">
                        <i class="fa fa-lg fa-fw fa-table"></i>
                        <span class="menu-item-parent"><?=__('Parameter', 'name', 'parameters')?></span>
                    </a>
                    <ul>
                        <?php foreach ($account->parameterLibraries as $library) : ?>
                            <li class="<?=$this->activeMenu === 'parameter-' . $library->id ? 'active' : ''?>">
                                <a href="parameter/library/view/id/<?=$library->id?>"
                                   title="<?=$library->label?>">
                                    <?=$library->label?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>


            <!-- Classification libraries -->
            <?php if (count($account->classificationLibraries) > 0) : ?>
                <li>
                    <a href="#">
                        <i class="fa fa-lg fa-fw fa-sitemap"></i>
                        <span class="menu-item-parent"><?=__('Classification', 'name', 'classification')?></span>
                    </a>
                    <ul>
                        <?php foreach ($account->classificationLibraries as $library) : ?>
                            <li class="<?=$this->activeMenu === 'classification-' . $library->id ? 'active' : ''?>">
                                <a href="classification/library/view/id/<?=$library->id?>"
                                   title="<?=$library->label?>">
                                    <?=$library->label?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>


            <!-- Members -->
            <?php if ($account->canAllow) : ?>
                <li class="<?=$this->activeMenu === 'members' ? 'active' : ''?>">
                    <a href="account/members?account=<?=$account->id?>">
                        <i class="fa fa-lg fa-fw fa-users"></i>
                        <span class="menu-item-parent"><?=__('Account', 'name', 'members')?></span>
                    </a>
                </li>
            <?php endif; ?>

        </ul>
    </nav>

    <span class="minifyme"> <i class="fa fa-arrow-circle-left hit"></i> </span>
</aside>
