<?php
/**
 * @author matthieu.napoli
 * @package Techno
 */
/** @var $family Techno_Model_Family */
$family = $this->family;
/** @var $dimension Techno_Model_Family_Dimension */
$dimension = $this->dimension;
?>

<div class="page-header">
    <h1><?=__('Techno', 'dimension', 'pageTitle')?></h1>
</div>

<p>
    <a class="btn btn-primary" href="techno/family/edit/id/<?=$family->getId()?>">
        <i class="icon-white icon-arrow-left"></i>
        <?=__('Techno', 'dimension', 'returnToFamily')?></a>
</p>
<p>
    <strong><?=__('Techno', 'name', 'family') . __('UI', 'other', ':')?></strong>
    <?=$family->getLabel()?>
</p>
<p>
    <strong><?=__('Techno', 'name', 'meaning') . __('UI', 'other', ':')?></strong>
    <?=$dimension->getLabel()?>
</p>


<?php
// Formulaire d'édition de la requête
$queryForm = new UI_Form('editQuery');
$queryForm->setAction($this->baseUrl('techno/dimension/edit-query-submit'));
// Requête
$queryField = new UI_Form_Element_Textarea('query');
$queryField->setLabel(__('UI', 'name', 'query'));
$queryField->setValue($dimension->getQuery());
$queryField->setAttrib('rows', 5);
$queryForm->addElement($queryField);
// Id de la famille
$idDimensionField = new UI_Form_Element_Hidden('id');
$idDimensionField->setValue($dimension->getId());
$queryForm->addElement($idDimensionField);
$queryForm->addSubmitButton();
// $queryForm->display();


// Datagrid des membres de la dimension
$datagrid = new UI_Datagrid('membersDatagrid', 'datagrid_dimension_members-datagrid', 'techno');
$datagrid->pagination = false;
$datagrid->addParam('id', $dimension->getId());
$datagrid->deleteElements = true;
// Colonne label
$labelColumn = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$labelColumn->addable = false;
$labelColumn->editable = false;
$datagrid->addCol($labelColumn);
// Colonne ref
$refKeywordColumn = new UI_Datagrid_Col_List('refKeyword', __('UI', 'name', 'identifier'));
$refKeywordColumn->addable = true;
$refKeywordColumn->editable = true;
$refKeywordColumn->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
$refKeywordColumn->list = [];
foreach ($this->keywords as $keyword) {
    /** @var $keyword Keyword_Model_Keyword */
    $refKeywordColumn->list[$keyword->getRef()] = $keyword->getRef();
}
$datagrid->addCol($refKeywordColumn);
// Colonne Position
$orderColumn = new UI_Datagrid_Col_Order('position');
$orderColumn->labelAdd = 'Position';
$orderColumn->addable = false;
$orderColumn->editable = true;
$datagrid->addCol($orderColumn);

$datagrid->addElements = true;
$datagrid->addPanelTitle = __('Techno', 'dimension', 'addPanelTitle');

$datagrid->display();
?>
<script type="text/javascript">
    $('#membersDatagrid_addPanel').on('hidden', function(){
            $('#membersDatagrid_refKeyword_addForm').val('').trigger('change');
        });
</script>