<?php
/**
 * @author valentin.claras
 * @author sidoine.tardieu
 * @package Orga
 */
if ((count($this->listDatagrids) > 1) || !($this->minimize)) {
    foreach ($this->listDatagrids as $labelGranularity => $datagridConfiguration) {
        $datagrid = $datagridConfiguration->datagrid;
        $datagrid->initialLoading = false;

        echo $this->collapse('collapse_'.$datagrid->id, $labelGranularity, $datagrid->getHTML())->collapsed();

        $script = '';
        $script .= '$(\'#'.'collapse_'.$datagrid->id.'\').on(\'show\', function(e) {';
        $script .= 'if ($(e.target).attr(\'id\') == \'collapse_'.$datagrid->id.'_wrapper\') {';
        $script .= $datagrid->id.'.filter();';
        $script .= '}';
        $script .= '});';

        if ($this->display === false) {
            echo '<script type="text/javascript">'.$datagrid->getScript().$script.'</script>';
        } else {
            UI_Datagrid::addHeader($datagrid);
            $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
        }
    }
} else if (count($this->listDatagrids) > 0) {
    $datagrid = array_pop($this->listDatagrids)->datagrid;
    echo $datagrid->getHTML();

    if ($this->display === false) {
        echo '<script type="text/javascript">'.$datagrid->getScript().'</script>';
    } else {
        UI_Datagrid::addHeader($datagrid);
    }
}