<?php
/**
 * vue général de cell
 * @author diana.dragusin
 * @package Orga
 */
?>

<div class="page-header">
    <h1><?=$this->configuration->getPageTitle()?></h1>
</div>
<div class="row-fluid">
    <div class="well span" id="navigationPanel">
<?= $this->partial('cell/navigation.phtml', array('cell' => $this->cell, 'configuration' => $this->configuration))?>
    </div>
    <div id="navigationClose" class="span">
        <i class="icon-indent-right"> </i>
    </div>
    <div id="navigationContent" class="span">
<?php

$tabView = new UI_Tab_View('container');

$baseTabs = array();
// ONGLET ORGANISATION
$baseTabs[Orga_ViewConfiguration::TAB_ORGANISATION] = new UI_Tab('structure');
$baseTabs[Orga_ViewConfiguration::TAB_ORGANISATION]->label = __('Orga', 'name', 'structure');
$baseTabs[Orga_ViewConfiguration::TAB_ORGANISATION]->cacheData  = true;
$baseTabs[Orga_ViewConfiguration::TAB_ORGANISATION]->dataSource = 'orga/cell/organisation?'.
    'idCell='.$this->idCell.'&'.
    'tab='.$this->activatedTab.'&'.
    'outputUrl='.urlencode($this->configuration->getOutputURL()).'&'.
    'display=render';
$organisationTabs = array('axes', 'granularities', 'members', 'childCells', 'relevant', 'consistency', '');
if (in_array($this->activatedTab, $organisationTabs)) {
    $baseTabs[Orga_ViewConfiguration::TAB_ORGANISATION]->active = true;
}
if ($this->configuration->getTabs() != null ) {
    foreach ($this->configuration->getTabs() as $tab) {
        if ($tab instanceof UI_Tab) {
            $tabView->addTab($tab);
        } else {
            $tabView->addTab($baseTabs[$tab]);
        }
    }
}
$tabView->display();

$script = '';
$script .= '$(\'#navigationClose\').click(';
$script .= 'function() {';
$script .= 'if ($(\'#navigationClose i:first-child\').hasClass(\'icon-indent-right\')) {';
$script .= '$(\'#navigationClose i:first-child\').removeClass(\'icon-indent-right\');';
$script .= '$(\'#navigationClose i:first-child\').addClass(\'icon-indent-left\');';
$script .= '$(\'#navigationPanel\').animate({width: "toggle"}, 50, function() {$(\'#navigationContent\').animate({width: "98%"}, \'fast\');});';
$script .= '} else {';
$script .= '$(\'#navigationClose i:first-child\').removeClass(\'icon-indent-left\');';
$script .= '$(\'#navigationClose i:first-child\').addClass(\'icon-indent-right\');';
$script .= '$(\'#navigationContent\').animate({width: "82%"}, 50, function() {$(\'#navigationPanel\').animate({width: "toggle"}, \'fast\');});';
$script .= '}';
$script .= '});';

$this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
?>
    </div>
</div>
