<div class="page-header">
    <h1><?=$this->pageTitle?></h1>
</div>

<div class="row-fluid">

    <? if ($this->displayNavigationPanel !== false) : ?>
        <div class="well span" id="navigationPanel">
            <?= $this->partial('cell/navigation.phtml',
                ['cell' => $this->cell, 'isParentCellReachable' => $this->isParentCellReachable])?>
        </div>
        <div id="navigationClose" class="span">
            <i class="icon-arrow-down"></i>
            <span><?=__('UI', 'verb', 'hide')?></span>
            <i class="icon-arrow-down"></i>
        </div>
    <? endif; ?>

    <div id="navigationContent" class="span">
        <?php
        $this->tabView->display();
        ?>
    </div>

</div>

<script type="text/javascript">
    $('#navigationClose').click(function () {
        var navigationPanel = $('#navigationPanel');
        if (navigationPanel.css('display') == 'none') {
            $(this).find('i')
                .removeClass('icon-arrow-up')
                .addClass('icon-arrow-down');
            $(this).find('span').html('<?=__('UI', 'verb', 'hide')?>');
        } else {
            $(this).find('i')
                .removeClass('icon-arrow-down')
                .addClass('icon-arrow-up');
            $(this).find('span').html('<?=__('UI', 'verb', 'display')?>');
        }
        navigationPanel.animate({width: "toggle"}, 50);
    });
</script>
