<?php
/**
 * Vue générale d'une Cell
 * @author valentin.claras
 * @author diana.dragusin
 * @package Orga
 */
?>

<div class="page-header">
    <h1><?=$this->pageTitle?></h1>
</div>
<div class="row-fluid">
    <div class="well span" id="navigationPanel">
<?= $this->partial('cell/navigation.phtml', array('cell' => $this->cell, 'configuration' => $this->configuration))?>
    </div>
    <div id="navigationClose" class="span">
        <i class="icon-indent-right"> </i>
    </div>
    <div id="navigationContent" class="span">
<?php

$this->tabView->display();

$script = '';
$script .= '$(\'#navigationClose\').click(';
$script .= 'function() {';
$script .= 'if ($(\'#navigationClose i:first-child\').hasClass(\'icon-indent-right\')) {';
$script .= '$(\'#navigationClose i:first-child\').removeClass(\'icon-indent-right\');';
$script .= '$(\'#navigationClose i:first-child\').addClass(\'icon-indent-left\');';
$script .= '$(\'#navigationPanel\').animate({width: "toggle"}, 50);';
$script .= '} else {';
$script .= '$(\'#navigationClose i:first-child\').removeClass(\'icon-indent-left\');';
$script .= '$(\'#navigationClose i:first-child\').addClass(\'icon-indent-right\');';
$script .= '$(\'#navigationPanel\').animate({width: "toggle"}, 50);';
$script .= '}';
$script .= '});';

$this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
?>
    </div>
</div>
