<?php
if ($this->isUserAbleToComment) {
    echo $this->partial(
        'comment/list.phtml',
        'social',
        [
            'currentUser'    => $this->currentUser,
            'endpointGet'    => 'orga/comment/list?idCell=' . $this->idCell,
            'endpointAdd'    => 'orga/comment/new?idCell=' . $this->idCell,
            'endpointEdit'   => 'orga/comment/edit?idCell=' . $this->idCell,
            'endpointDelete' => 'orga/comment/delete?idCell=' . $this->idCell,
        ]
    );
} else {
    echo $this->partial(
        'comment/list.phtml',
        'social',
        [
            'currentUser' => $this->currentUser,
            'endpointGet' => 'orga/comment/comments?idCell=' . $this->idCell,
        ]
    );
}
