<?php
/**
 * Volet navigation
 * @author valentin.claras
 * @author diana.dragusin
 * @package Orga
 */
?>

<!--
<h3>Navigation</h3>
<hr />
 -->
<?php
$parentCells = array_reverse($this->cell->getParentCells());
if (count($parentCells) > 0) {
?>
<ul id="navigationParent">
<?php
    foreach ($parentCells as $parentCell) {
        if ($parentCell->getGranularity()->isNavigable()) {
?>
        <li class="navigationParent">
            <?php if ((!(isset($this->isParentCellReachable[$parentCell->getMembersHashKey()])))
                || ($this->isParentCellReachable[$parentCell->getMembersHashKey()] !== false)) { ?>
            <a href="orga/cell/details/idCell/<?=$parentCell->getId()?>">
                <?= $parentCell->getLabel()?>
            </a>
            <?php } else { ?>
                    <?= $parentCell->getLabel()?>
            <?php } ?>
        </li>
<?php
        }
    }
?>
</ul>
<hr />
<?php
    }
?>
<div id="navigationCurrent">
    <?= $this->cell->getLabel() ?>
</div>
<?php
    foreach ($this->cell->getGranularity()->getNarrowerGranularities() as $narrowerGranularity) {
        if ($narrowerGranularity->isNavigable()) {
            $form = new UI_Form('navigation_'.$narrowerGranularity->getId());
            $form->setAjax(false);
            $form->setAction(
                'orga/forms_navigation/gotocell/idCell/'.$this->cell->getId().'/idGranularity/'.$narrowerGranularity->getId()
            );

            $idAddedAxes = array();
            if ($this->cell->hasMembers()) {
                $childMembers = $this->cell->getChildMembersForGranularity($narrowerGranularity);
                foreach ($narrowerGranularity->getAxes() as $narrowerAxis) {
                    if (!$this->cell->getGranularity()->hasAxis($narrowerAxis)) {
                        $select = new UI_Form_Element_Select($narrowerAxis->getRef());
                        $select->setLabel($narrowerAxis->getLabel());
                        foreach ($childMembers as $childMember) {
                            $option = new UI_Form_Element_Option(
                                $childMember->getCompleteRef(),
                                $childMember->getCompleteRef(),
                                $childMember->getLabel()
                            );
                            $select->addOption($option);
                        }
                        $form->addElement($select);
                    }
                }
            } else {
                foreach ($narrowerGranularity->getAxes() as $narrowerAxis) {
                    $select = new UI_Form_Element_Select($narrowerAxis->getRef());
                    $select->setLabel($narrowerAxis->getLabel());
                    foreach ($narrowerAxis->getMembers() as $childMember) {
                        $option = new UI_Form_Element_Option(
                            $childMember->getCompleteRef(),
                            $childMember->getCompleteRef(),
                            $childMember->getLabel()
                        );
                        $select->addOption($option);
                    }
                    $form->addElement($select);
                }
            }
?>
    <hr />
    <?php
        $submit = new UI_Form_Element_Submit('goTo'.$narrowerGranularity->getId());
        $submit->setLabel(__('UI', 'verb', 'goTo'));
        $form->addElement($submit);
        $form->display();
    ?>
<?php
        }
    }
?>
