
<?php
/**
 * @author valentin.claras
 * @author simon.rieu
 * @package Orga
 */
$tabView = new UI_Tab_View('organisation');

if ($this->isGlobal) {
    $tabAxes = new UI_Tab('axes');
    $tabAxes->label = __('UI', 'name', 'axes');
    $tabAxes->dataSource = 'orga/tab_cell/axis?idCell='.$this->idCell;
    $tabAxes->useCache = true;

    $tabGranularities = new UI_Tab('granularities');
    $tabGranularities->label = __('Orga', 'name', 'levels');
    $tabGranularities->dataSource = 'orga/tab_cell/granularity?idCell='.$this->idCell;
    $tabGranularities->useCache = false;
}

$tabMembers = new UI_Tab('members');
$tabMembers->label = __('UI', 'name', 'members');
$tabMembers->dataSource = 'orga/tab_cell/member?idCell='.$this->idCell;
$tabMembers->useCache = false;

if ($this->hasChildCells) {
    $tabChildCells = new UI_Tab('childCells');
    $tabChildCells->label = __('Orga', 'name', 'subUnits');
    $tabChildCells->dataSource = 'orga/tab_cell/childcells?idCell='.$this->idCell.'&outputUrl='.$this->outputUrl;
    $tabChildCells->useCache = false;

    $tabRelevance = new UI_Tab('relevant');
    $tabRelevance->label = __('Orga', 'name', 'relevance');
    $tabRelevance->dataSource = 'orga/tab_cell/relevantcells?idCell='.$this->idCell;
    $tabRelevance->useCache = false;
}

$tabCoherence = new UI_Tab('consistency');
$tabCoherence->label = __('UI', 'name', 'control');
$tabCoherence->dataSource = 'orga/tab_cell/consistency?idCell='.$this->idCell;
$tabCoherence->useCache = true;

if ((!($this->hasChildCells)) && (in_array($this->activatedTab, array('relevant', 'childCells')))) {
    $this->activatedTab = 'axis';
}
if ((!($this->isGlobal)) && (in_array($this->activatedTab, array('axes', 'granularities', 'consistency')))) {
    $this->activatedTab = 'members';
}
switch ($this->activatedTab) {
    case 'axes':
        $tabAxes->active = true;
        break;
    case 'granularities':
        $tabGranularities->active = true;
        break;
    case 'relevant':
        $tabRelevance->active = true;
        break;
    case 'consistency':
        $tabCoherence->active = true;
        break;
    case 'childCells':
        $tabChildCells->active = true;
        break;
    case 'members':
    default:
        $tabMembers->active = true;
        break;
}

if ($this->isGlobal) {
    $tabView->addTab($tabAxes);
    $tabView->addTab($tabGranularities);
    $tabView->addTab($tabMembers);
    if ($this->hasChildCells) {
        $tabView->addTab($tabChildCells);
        $tabView->addTab($tabRelevance);
    }
    $tabView->addTab($tabCoherence);
} else {
    if ($this->hasChildCells) {
        $tabView->addTab($tabChildCells);
    }
    $tabView->addTab($tabMembers);
    if ($this->hasChildCells) {
        $tabView->addTab($tabRelevance);
    }
}

if ($this->display === false) {
    echo $tabView->render();
} else {
    $tabView->display();
}
