<?php
$cellReports = $this->cellReports;
?>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                <?=___('UI', 'name', 'label')?>
            </th>
            <th>
                <?=___('UI', 'name', 'type')?>
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($cellReports as $cellReport): ?>
        <tr>
            <td>
                <a href="<?=$cellReport['link']?>" target="_blank" >
                    <?=$cellReport['label']?>
                </a>
            </td>
            <td>
                <?=___('DW', 'reportList', 'cellReport_'.$cellReport['type'])?>
            </td>
            <td>
                <?php if (isset($cellReport['delete'])): ?>
                <a href="orga/cell/remove-report/idCell/<?=$this->idCell?>/idReport/<?=$cellReport['delete']?>/" class="deleteReport withTooltip" title="<?=___('UI', 'verb', 'delete')?>">
                    <i class="fa fa-trash-o"></i>
                </a>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script>
    $('#reports<?=$this->idCell?> .withTooltip').tooltip({placement: 'left'});
</script>