<?php
use AF\Domain\AF\InputSet\PrimaryInputSet;
use Orga\ViewModel\CellViewModelFactory;
use Orga\Model\ACL\Role\CellAdminRole;
use Orga\Model\ACL\Role\CellManagerRole;
use Orga\Model\ACL\Role\CellContributorRole;
use Orga\Model\ACL\Role\CellObserverRole;

/** @var CellViewModelFactory $cellVWFactory */
$cellVWFactory = $this->cellVWFactory;
$inventoryStatusFilters = [
    null => ___('Orga', 'view', 'allInventoryStatus'),
    Orga_Model_Cell::STATUS_NOTLAUNCHED => ___('Orga', 'view', 'inventoryNotLaunched'),
    Orga_Model_Cell::STATUS_ACTIVE => ___('Orga', 'view', 'inventoryOpen'),
    Orga_Model_Cell::STATUS_CLOSED => ___('Orga', 'view', 'inventoryClosed'),
];
$inputStatusFilters = [
    null => ___('Orga', 'view', 'allInputStatus'),
    PrimaryInputSet::STATUS_FINISHED => ___('AF', 'inputInput', 'statusFinished'),
    PrimaryInputSet::STATUS_COMPLETE => ___('AF', 'inputInput', 'statusComplete'),
    PrimaryInputSet::STATUS_CALCULATION_INCOMPLETE => ___('AF', 'inputInput', 'statusCalculationIncomplete'),
    PrimaryInputSet::STATUS_INPUT_INCOMPLETE => ___('AF', 'inputInput', 'statusInputIncomplete'),
    \Orga\ViewModel\CellViewModel::AF_STATUS_NOT_STARTED => ___('Orga', 'view', 'statusNotStarted'),
    \Orga\ViewModel\CellViewModel::AF_STATUS_AF_NOT_CONFIGURED => ___('Orga', 'view', 'statusAFNotConfigured'),
    \Orga\ViewModel\CellViewModel::AF_STATUS_INVENTORY_NOT_STARTED => ___('Orga', 'view', 'inventoryNotLaunched'),
];

/** @var \Orga\ViewModel\OrganizationViewModel $organization */
$organization = $this->organization;
/** @var \Orga\ViewModel\CellViewModel $currentCell */
$currentCell = $this->currentCell;
?>

<style>
    .label-danger, .badge-danger { background-color: #b94a48; }
    .label-important[href], .badge-important[href] { background-color: #953B39; }
    .progress { margin-bottom: 5px; margin-top: 5px; }

    .cell-actions a { margin-left: 8px; padding: 5px; }
    .cell-actions a:hover, .users .modal-body a:hover, .reports .modal-body a:hover { opacity: 0.25; }

    .users .user-message { font-weight: bold; }
    .users .modal-body { padding: 0; }
    .users .modal-body table { margin: 0; }
    .users .modal-body tr.user-message td:first-child { text-align: center; }
    .users .modal-body tr.user-message .btn { margin: 0 5px 0 5px; }
    .users .modal-body tr.user-message .close-user-message { float: none; font-size: inherit; opacity: 1; }
    .users .modal-body .delete-user { color: #000000; }
    .users .modal-body .delete-user + .tooltip.left { margin-left: -15px; }
    .users .modal-footer div.user-message { text-align: center; margin-bottom: 5px; }
    .users .modal-footer form { margin: 0; }

    .reports .report-message { font-weight: bold; }
    .reports .modal-body { padding: 0; }
    .reports .modal-body table { margin: 0; }
    .reports .modal-body tr.report-message td:first-child { text-align: center; }
    .reports .modal-body tr.report-message .btn { margin: 0 5px 0 5px; }
    .reports .modal-body tr.report-message .close-report-message { float: none; font-size: inherit; opacity: 1; }
    .reports .modal-body .delete-report + .tooltip.left { margin-left: -15px; }
    .reports .filter-reports { display: inline-block; margin-bottom: 0; }

    .exports .modal-body { text-align: center; }
    .exports .modal-body .alert { margin-bottom: 5px; }
    .exports .modal-body form { margin: 0; }

    .inventory-status .label { font-size: 11.9px; font-weight: normal; padding: 4px 12px; }
    .inventory-status > a { margin: 0 5px; }
    .input-status .badge { font-size: 11.9px; font-weight: normal; line-height: nomal; padding: 4px 12px; }
    .input-status > a { margin: 0 5px; }

    .granularity-wrapper .cells-filter > * { margin-top: 2px; }
    .granularity-wrapper .cells-filter .granularity-info { vertical-align: middle; font-size: 14px; font-weight: normal; line-height: 20px; padding: 4px 12px; }
    .granularity-wrapper .granularity .cell-actions { float: right; }
    .granularity-wrapper .granularity > .cell.firstRowCell { margin-left: 0; }
    .granularity-wrapper .display-more-cells { margin-left: 0; }
    .granularity-wrapper .no-cell { margin-left: 0; text-align: center; vertical-align: middle; padding: 8px 12px; font-size: 14px; font-weight: normal; }

    .history { margin-bottom: 15px; }
    .history > h3 { margin: 0; }
    .history > hr { margin: 0 0 5px; }
    .history > div { text-align: center; }
    .history h4 { margin: 0 0 5px; }
    .history .dl-horizontal { text-align: left; margin-top: 0px; }
    .history .dl-horizontal dt { width: 65px; margin-right: 5px; }
    .history .dl-horizontal dd { margin-left: 25px; }

    .comments { margin-bottom: 15px; }
    .comments > h3 { margin: 0; }
    .comments > hr { margin: 0 0 5px; }
    .comments > div { text-align: center; }
    .comments h4 { margin: 0 0 5px; }
    .comments .dl-horizontal { text-align: left; margin-top: 0px; }
    .comments .dl-horizontal dt { width: 65px; margin-right: 5px; }
    .comments .dl-horizontal dd { margin-left: 25px; }

    #addMember { margin: 0; }
    #addMember .controls { margin-left: 0; float: right; }
    #addMember .subGroup { margin-left: 0; }
    #addMember label { text-align: left; width: auto; }
    #addMember .input { width: auto; }
    #addMember .form-actions { padding: 10px 0 0 0; margin: 0; background-color: inherit; text-align: center; border: none; }
    #addMember .form-actions input { float: right; }
</style>

<div class="organization page-header">
    <h1>
        <?=$organization->label?>
        <?php if ($organization->canBeEdited) : ?>
        <div class="pull-right">
            <small>
                <a class="editOrganization btn btn-small btn-primary"
                   href="orga/organization/edit/idOrganization/<?=$organization->id?>/">
                    <i class="fa fa-wrench"></i>
                    <?=___('UI', 'name', 'configurationOrga')?>
                </a>
            </small>
        </div>
        <?php endif; ?>
    </h1>
</div>

<div class="row-fluid">

<div class="span9" id="cellsView">

    <div class="currentCell well">
        <h2>
            <?php if ($currentCell->showInput) : ?>
            <a href="orga/cell/input/idCell/<?=$currentCell->id?>/fromIdCell/<?=$currentCell->id?>/" title="<?=___('Orga', 'view', 'viewInput')?>" class="withTooltip">
            <?php endif; ?>
            <?=$currentCell->extendedLabel?>
            <?php if ($currentCell->showInput) : ?>
            <small>
                <i class="fa fa-external-link"></i>
                <?=___('Orga', 'view', 'inputLinkDetail')?>
            </small>
            </a>
            <?php endif; ?>
            <small class="cell-actions">
                <a data-toggle="modal" href="#administrators<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'contactAdministrators')?>" class="withTooltip"><i class="fa fa-user-md"></i></a>
                <?php if ($currentCell->showUsers) : ?>
                <a data-toggle="modal" href="#users<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'editUsers')?>" class="withTooltip">(<?=$currentCell->numberUsers?>) <i class="fa fa-users"></i></a>
                <?php endif; ?>
                <?php if ($currentCell->showReports) : ?>
                <a data-toggle="modal" href="#reports<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'analyzeData')?>" class="withTooltip"><i class="fa fa-bar-chart-o"></i></a>
                <a data-toggle="modal" data-target="#exports<?=$currentCell->id?>" href="orga/cell/view-exports/idCell/<?=$currentCell->id?>/" title="<?=___('Orga', 'view', 'exportData')?>" class="withTooltip"><i class="fa fa-download"></i></a>
                <?php endif; ?>
            </small>
        </h2>
        <?php // Inventory ?>
        <?php if ($currentCell->showInventory) : ?>
        <div class="inventory-status">
            <?php if ($currentCell->canEditInventory) : ?>
            <div class="btn-group withTooltip" title="<?=___('Orga', 'view', 'inventoryStatusExplanations')?>">
                <button class="btn btn-small dropdown-toggle btn-<?=$currentCell->inventoryStatusStyle?>" data-toggle="dropdown" data-inventory="<?=$currentCell->inventoryStatus?>">
                    <i class="fa fa-pencil-square-o"></i>
                    <?=$currentCell->inventoryStatusTitle?>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <?php foreach ($cellVWFactory->inventoryStatusList as $inventoryStatusValue => $inventoryStatusLabel) : ?>
                    <li>
                        <a href="orga/cell/edit-inventory-status/idCell/<?=$currentCell->id?>/" data-inventory="<?=$inventoryStatusValue?>">
                            <?=$inventoryStatusLabel?>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php else: ?>
            <span class="label label-<?=$currentCell->inventoryStatusStyle?> withTooltip" title="<?=___('Orga', 'view', 'inventoryStatusExplanations')?>">
                <?=$currentCell->inventoryStatusTitle?>
            </span>
            <?php endif; ?>
            <a href="#" class="withPopover inventoryInputsDetails" title="<?=___('Orga', 'view', 'inventoryInputsDetails')?>" data-toggle="tooltip" data-placement="right" data-trigger="hover" data-html="true" data-content="<?=$currentCell->inventoryNotStartedInputsNumber?> <?=($currentCell->inventoryNotStartedInputsNumber > 1) ? ___('Orga', 'view', 'inputsNotStartedMany') : ___('Orga', 'view', 'inputsNotStartedSingle')?> <br> <?=$currentCell->inventoryStartedInputsNumber?> <?=($currentCell->inventoryStartedInputsNumber > 1) ? ___('Orga', 'view', 'inputsStartedMany') : ___('Orga', 'view', 'inputsStartedSingle')?> <br> <?=$currentCell->inventoryCompletedInputsNumber?> <?=($currentCell->inventoryCompletedInputsNumber > 1) ? ___('Orga', 'view', 'inputsCompletedMany') : ___('Orga', 'view', 'inputsCompletedSingle')?>"><i class="fa fa-tasks"></i></a>
            <a data-toggle="modal" href="#inventoryUsers<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'viewInventoryUsers')?>" class="withTooltip"><i class="fa fa-bullhorn"></i></a>
        </div>
        <div class="progress withTooltip" title="<?=___('Orga', 'view', 'inventoryPercentExplanations')?>" data-toggle="tooltip" data-placement="bottom" data-trigger="hover">
            <div class="bar" style="width: <?=$currentCell->inventoryCompletion?>%">
                <?=$currentCell->inventoryCompletion?> %
            </div>
        </div>
        <?php endif; ?>
        <?php // Input ?>
        <?php if ($currentCell->showInput) : ?>
        <div class="input-status">
            <span class="badge badge-<?=$currentCell->inputStatusStyle?> withTooltip" title="<?=___('Orga', 'view', 'inputStatusExplanations')?>">
                <?=$currentCell->inputStatusTitle?>
            </span>
        </div>
        <div class="progress progress-<?=$currentCell->inputStatusStyle?> withTooltip" title="<?=___('Orga', 'view', 'inputPercentExplanations')?>" data-toggle="tooltip" data-placement="bottom" data-trigger="hover">
            <div class="bar" style="width: <?=$currentCell->inputCompletion?>%"><?=$currentCell->inputCompletion?> %</div>
        </div>
        <?php endif; ?>

        <div id="administrators<?=$currentCell->id?>" class="modal administrators hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="withTooltip" title="<?=___('Orga', 'view', 'administratorExplanations')?>">
                    <?=___('Orga', 'view', 'administratorsFrom')?> <?=$currentCell->shortLabel?>
                    <i class="fa fa-question-circle"></i>
                </h4>
            </div>
            <div class="modal-body">
                <pre><?=implode("\n", $currentCell->administrators)?></pre>
            </div>
        </div>
        <?php if ($currentCell->showUsers) : ?>
        <div id="users<?=$currentCell->id?>" class="modal users hide fade large" data-cell="<?=$currentCell->id?>">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4><?=___('Orga', 'view', 'rolesFrom')?> <?=$currentCell->shortLabel?></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <form class="form-inline addUser" action="orga/cell/add-user/idCell/<?=$currentCell->id?>/">
                    <input type="text" name="userEmail" placeholder="<?=___('User', 'user', 'emailAddress')?>">
                    <select name="userRole">
                        <option value="CellAdminRole"><?=CellAdminRole::getLabel()?></option>
                        <option value="CellManagerRole"><?=CellManagerRole::getLabel()?></option>
                        <option value="CellContributorRole"><?=CellContributorRole::getLabel()?></option>
                        <option value="CellObserverRole"><?=CellObserverRole::getLabel()?></option>
                    </select>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-plus"></i>
                        <?=___('UI', 'verb', 'add')?>
                    </button>
                </form>
            </div>
        </div>
        <?php endif; ?>
        <?php if ($currentCell->showReports) : ?>
        <div id="reports<?=$currentCell->id?>" class="modal reports hide fade large" data-cell="<?=$currentCell->id?>">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4><?=___('Orga', 'view', 'reportsFrom')?> <?=$currentCell->shortLabel?></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <a href="orga/cell/view-report/idCell/<?=$currentCell->id?>/" class="btn btn-primary">
                    <i class="fa fa-plus"></i>
                    <?=___('UI', 'verb', 'add')?>
                </a>
            </div>
        </div>
        <div id="exports<?=$currentCell->id?>" class="modal exports hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4><?=___('Orga', 'view', 'exportsFrom')?> <?=$currentCell->shortLabel?></h4>
            </div>
            <div class="modal-body">
                <div class="granularityCells row-fluid">
                    <i class="fa fa-spinner fa-spin fa-3x"></i>
                    <?=___('UI', 'loading', 'loading')?>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if ($currentCell->showInventory) : ?>
        <div id="inventoryUsers<?=$currentCell->id?>" class="modal inventory-users hide fade" data-cell="<?=$currentCell->id?>">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="withTooltip" title="<?=___('Orga', 'view', 'inventoryUsersExplanations')?>">
                    <?=___('Orga', 'view', 'inventoryUsersFrom')?> <?=$currentCell->shortLabel?>
                    <i class="fa fa-question-circle"></i>
                </h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
        <?php endif; ?>
    </div>

    <?php foreach ($this->narrowerGranularities as $narrowerGranularityArray) :
    /** @var Orga_Model_Granularity $narrowerGranularity */
    $narrowerGranularity = $narrowerGranularityArray['granularity'];
    ?>
    <fieldset class="wrapper granularity-wrapper">
        <legend data-toggle="collapse" data-target="#granularity<?=$narrowerGranularity->getId()?>">
            <span class="withTooltip" title="<?=___('Orga', 'view', 'granularityExplanations')?>" data-placement="right">
                <i class="filterChevron fa fa-chevron-<?=((count($this->narrowerGranularities) === 1)?'down':'right')?>"></i>
                <?=$narrowerGranularityArray['purpose']?>
                <small>
                    <?=$narrowerGranularity->getLabel()?>
                </small>
            </span>
        </legend>

        <div id="granularity<?=$narrowerGranularity->getId()?>"
             <?=$narrowerGranularityArray['isAcl'] ? ' data-acl' : ''?>
             <?=$narrowerGranularityArray['isInventory'] ? ' data-inventory' : ''?>
             <?=$narrowerGranularityArray['isInput'] ? ' data-input' : ''?>
             <?=$narrowerGranularityArray['isAnalyses'] ? ' data-analyses' : ''?>
             class="collapse<?=((count($this->narrowerGranularities) === 1)?' in':'')?>">
            <?php if ($narrowerGranularity->hasAxes() || ($narrowerGranularity->getInputConfigGranularity() !== null)) : ?>
            <form class="form-inline cells-filter">
                <?php foreach ($narrowerGranularityArray['filterAxes'] as $refAxis => $memberOptions) : ?>
                <?php if (count($memberOptions) > 2) : ?>
                <select name="granularity<?=$narrowerGranularity->getId()?>_axis<?=$refAxis?>" data-filter="tag">
                    <?php foreach ($memberOptions as $memberTag => $memberLabel) : ?>
                        <option value="<?=$memberTag?>"><?=$memberLabel?></option>
                    <?php endforeach; ?>
                </select>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($narrowerGranularityArray['isInput']) : ?>
                <select name="granularity<?=$narrowerGranularity->getId()?>_inputStatus" data-filter="input-status">
                    <?php foreach ($inputStatusFilters as $statusValue => $statusLabel) : ?>
                    <option value="<?=$statusValue?>"><?=$statusLabel?></option>
                    <?php endforeach; ?>
                </select>
                <?php endif; ?>
                <?php if ($narrowerGranularityArray['isInventory']) : ?>
                <select name="granularity<?=$narrowerGranularity->getId()?>_inventoryStatus" data-filter="inventory-status">
                    <?php foreach ($inventoryStatusFilters as $statusValue => $statusLabel) : ?>
                    <? if (($statusValue === Orga_Model_Cell::STATUS_ACTIVE) && (!$narrowerGranularityArray['isGranularityForInventoryStatus'])) : ?>
                    <option value="<?=$statusValue?>" selected><?=$statusLabel?></option>
                    <?php else: ?>
                    <option value="<?=$statusValue?>"><?=$statusLabel?></option>
                    <?php endif ?>
                    <?php endforeach ?>
                </select>
                <?php endif; ?>
                <span class="withTooltip" title="<?=___('Orga', 'view', 'filterReverserExplanations')?>">
                    <input type="checkbox" class="filter-reverser">
                </span>
                <button class="btn reset"><i class="fa fa-search-minus"></i> <?=___('UI', 'verb', 'reset')?></button>
                <span class="badge badge-info granularity-info withTooltip" title="<?=___('Orga', 'view', 'ratioNumberFilteredCellsOverTotal')?>" data-toggle="tooltip" data-placement="right" data-trigger="hover"></span>
            </form>
            <?php endif; ?>

            <div class="granularity row-fluid" data-total-cells="">
            </div>
        </div>
    </fieldset>
    <?php endforeach; ?>

</div>

<div class="span3">
    <div class="comments">
        <h3>
            <?=___('Social', 'comment', 'comments')?>
            <small class="pull-right">
                <a href="orga/cell/view-comments/idCell/<?=$currentCell->id?>/" class="refresh">
                    <i class="fa fa-refresh"></i>
                </a>
            </small>
        </h3>
        <hr/>
        <div>
            <?=___('UI', 'loading', 'error')?>
        </div>
    </div>
    <div class="history">
        <h3>
            <?=___('UI', 'history', 'history')?>
            <small class="pull-right">
                <a href="orga/cell/view-history/idCell/<?=$currentCell->id?>/" class="refresh">
                    <i class="fa fa-refresh"></i>
                </a>
            </small>
        </h3>
        <hr/>
        <div>
            <?=___('UI', 'loading', 'error')?>
        </div>
    </div>
    <?php if ($organization->canBeEdited) : ?>
    <div class="addMember">
        <h3>
            <div class="pull-right">
                <small>
                    <a class="editOrganization btn btn-small btn-primary"
                       href="orga/organization/edit/idOrganization/<?=$organization->id?>/tab/members/">
                        <i class="fa fa-wrench"></i>
                        <?=___('UI', 'name', 'configurationOrga')?>
                    </a>
                </small>
            </div>
            <?=___('Orga', 'view', 'addMember')?>
        </h3>
        <hr/>
        <?=$this->addMembersForm->display()?>
    </div>
    <?php endif; ?>
</div>

</div>
<script>
$('.comments a.refresh').on('click', function(e) {
    e.preventDefault();
    $('.comments > h3 i').addClass('fa-spin');
    $('.comments > div').html('<i class="fa fa-spinner fa-spin fa-3x"></i> <?=addslashes(___('Social', 'comment', 'loadingComments'))?>');
    $.ajax({
        url: $(this).attr('href'),
        type: "GET",
        success: function(data) {
            $('.comments > h3 i').removeClass('fa-spin');
            $('.comments > div').html('');
            if (data.length > 0) {
                $.each(data, function() {
                    var date = this.date;
                    $('.comments > div').append('<div data-date="' + date + '"><h4 class="label">' + date + '</h4></div>');
                    var divDate = $('.comments > div > div[data-date="' + date + '"]');
                    divDate.append('<dl class="dl-horizontal"></dl>');
                    var dlDate = $('dl', divDate);
                    $.each(this.comments, function() {
                        dlDate.append('<dt><span class="badge badge-info">' + this.time + '</span></dt>');
                        dlDate.append('<dd>' + this.comment + '</dd>');
                    });
                });
            } else {
                $('.comments > div').html('<p><?=addslashes(___('Social', 'comment', 'noComment'))?></p>');
            }
        },
        error: function(jqXHR) {
            $('.comments > h3 i').removeClass('fa-spin');
            $('.comments > div').html('<?=addslashes(___('Social', 'comment', 'errorWhileLoadingComments'))?>');
        }
    });
});
$('.history a.refresh').on('click', function(e) {
    e.preventDefault();
    $('.history > h3 i').addClass('fa-spin');
    $('.history > div').html('<i class="fa fa-spinner fa-spin fa-3x"></i> <?=addslashes(___('UI', 'history', 'loadingHistory'))?>');
    $.ajax({
        url: $(this).attr('href'),
        type: "GET",
        success: function(data) {
            $('.history > h3 i').removeClass('fa-spin');
            $('.history > div').html('');
            if (data.length > 0) {
                $.each(data, function() {
                    var date = this.date;
                    $('.history > div').append('<div data-date="' + date + '"><h4 class="label">' + date + '</h4></div>');
                    var divDate = $('.history > div > div[data-date="' + date + '"]');
                    divDate.append('<dl class="dl-horizontal"></dl>');
                    var dlDate = $('dl', divDate);
                    $.each(this.events, function() {
                        dlDate.append('<dt><span class="badge badge-info">' + this.time + '</span></dt>');
                        dlDate.append('<dd>' + this.event + '</dd>');
                    });
                });
            } else {
                $('.history > div').html('<p><?=___('UI', 'history', 'noHistory')?></p>');
            }
        },
        error: function(jqXHR) {
            $('.history > h3 i').removeClass('fa-spin');
            $('.history > div').html('<?=addslashes(___('UI', 'loading', 'error'))?>');
        }
    });
});

$('.granularity-wrapper > div').on('show', function(e) {
    if (e.currentTarget == e.target) {
        $('legend > span > i.filterChevron', $(this).parent()).removeClass('fa-chevron-right');
        $('legend > span > i.filterChevron', $(this).parent()).addClass('fa-chevron-down');
    }
});
$('.granularity-wrapper > div').on('hidden', function(e) {
    if (e.currentTarget == e.target) {
        $('legend > span > i.filterChevron', $(this).parent()).removeClass('fa-chevron-down');
        $('legend > span > i.filterChevron', $(this).parent()).addClass('fa-chevron-right');
    }
});

$('div.collapse[id^="granularity"]').on('loadCells', function(e) {
    if (e.target != this) {
        return;
    }
    var granularity = $('.granularity', $(this));
    if (!granularity.attr('data-initialized')) {
        var granularityInfo = $('.granularity-info', granularity.parent());
        granularityInfo[0].className = granularityInfo[0].className.replace(/\bbadge-.*?\b/g, '');
        granularityInfo.addClass('badge-info');
        granularityInfo.html('<i class="fa fa-spinner fa-spin"></i> <?=___('UI', 'loading', 'loading')?>');
        var granularityId = $(this).attr('id').substr(11, $(this).attr('id').length);
        $.ajax({
            url: 'orga/cell/view-children/idCell/<?=$currentCell->id?>/idGranularity/' + granularityId + '/',
            type: "GET",
            success: function(data) {
                console.log('cellsLoaded fired');
                granularity.trigger('cellsLoaded');
                granularity.html('');
                granularity.attr('data-total-cells', data.totalCells);
                $(data.childCells).each(function() {
                    var cellTitle = this.extendedLabel;
                    if (this.showInputLink) {
                        cellTitle =
                        '<a href="orga/cell/input/idCell/' + this.id + '/fromIdCell/<?=$currentCell->id?>/" title="<?=___('Orga', 'view', 'viewInput')?>" class="withTooltip">' +
                            cellTitle +
                            '<small>' +
                            ' <i class="fa fa-external-link"></i> ' +
                            '<?=___('Orga', 'view', 'inputLinkDetail')?>' +
                            '</small>' +
                        '</a>';
                    }
                    var usersP = '';
                    var usersPopup = '';
                    if (this.showUsers) {
                        usersP +=
                            '<a data-toggle="modal" href="#users' + this.id + '" title="<?=___('Orga', 'view', 'editUsers')?>" class="withTooltip">' +
                                '(' + this.numberUsers + ') ' +
                                '<i class="fa fa-users"></i>' +
                            '</a>';
                        usersPopup +=
                            '<div id="users' + this.id + '" class="modal users hide fade large" data-cell="' + this.id + '">' +
                                '<div class="modal-header">' +
                                    '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                    '<h4><?=___('Orga', 'view', 'rolesFrom')?> ' + this.shortLabel + '</h4>' +
                                '</div>' +
                                '<div class="modal-body">' +
                                '</div>' +
                                '<div class="modal-footer">' +
                                    '<form class="form-inline addUser" action="orga/cell/add-user/idCell/' + this.id + '/">' +
                                        '<input type="text" placeholder="<?=___('User', 'user', 'emailAddress')?>" name="userEmail"> ' +
                                        '<select name="userRole">' +
                                            '<option value="CellAdminRole"><?=CellAdminRole::getLabel()?></option>' +
                                            '<option value="CellManagerRole"><?=CellManagerRole::getLabel()?></option>' +
                                            '<option value="CellContributorRole"><?=CellContributorRole::getLabel()?></option>' +
                                            '<option value="CellObserverRole"><?=CellObserverRole::getLabel()?></option>' +
                                        '</select> ' +
                                        '<input type="submit" class="btn btn-primary" value="<?=___('UI', 'verb', 'add')?>"> ' +
                                    '</form>' +
                                '</div>' +
                            '</div>';
                    }
                    var reportsP = '';
                    var reportsPopup = '';
                    if (this.showReports) {
                        reportsP +=
                            '<a data-toggle="modal" href="#reports' + this.id + '" title="<?=___('Orga', 'view', 'analyzeData')?>" class="withTooltip">' +
                                '<i class="fa fa-bar-chart-o"></i>' +
                            '</a>';
                        reportsPopup +=
                            '<div id="reports' + this.id + '" class="modal reports hide fade large" data-cell="' + this.id + '">' +
                                '<div class="modal-header">' +
                                    '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                    '<h4><?=___('Orga', 'view', 'reportsFrom')?>' + this.shortLabel + '</h4>' +
                                '</div>' +
                                '<div class="modal-body">' +
                                '</div>' +
                                '<div class="modal-footer">' +
                                    '<a href="orga/cell/view-report/idCell/' + this.id + '/" class="btn btn-primary">' +
                                        '<i class="fa fa-plus"></i> ' +
                                        '<?=___('UI', 'verb', 'add')?>' +
                                    '</a>' +
                                '</div>' +
                            '</div>';
                    }
                    var exportsP = '';
                    var exportsPopup = '';
                    if (this.showExports) {
                        exportsP +=
                            '<a data-toggle="modal" data-target="#exports' + this.id + '" href="orga/cell/view-exports/idCell/' + this.id + '/" title="<?=___('Orga', 'view', 'exportData')?>" class="withTooltip">' +
                                '<i class="fa fa-download"></i>' +
                            '</a>';
                        exportsPopup +=
                            '<div id="exports' + this.id + '" class="modal exports hide fade">' +
                                '<div class="modal-header">' +
                                    '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                    '<h4><?=___('Orga', 'view', 'exportsFrom')?> ' + this.shortLabel + '</h4>' +
                                '</div>' +
                                '<div class="modal-body">' +
                                    '<i class="fa fa-spinner fa-spin fa-3x"></i> ' +
                                    '<?=___('UI', 'loading', 'loading')?>' +
                                '</div>' +
                            '</div>';
                    }
                    var inventoryP = '';
                    var inventoryPopup = '';
                    if (this.showInventory) {
                        inventoryP +=
                            '<div class="inventory-status">';
                        if (this.canEditInventory) {
                            inventoryP +=
                                '<div class="btn-group withTooltip" title="<?=___('Orga', 'view', 'inventoryStatusExplanations')?>">' +
                                    '<button class="btn btn-small dropdown-toggle btn-' + this.inventoryStatusStyle + '" data-toggle="dropdown" data-inventory="' + this.inventoryStatus + '">' +
                                        '<i class="fa fa-pencil-square-o"></i> ' +
                                        this.inventoryStatusTitle +
                                        ' <span class="caret"></span>' +
                                    '</button>' +
                                    '<ul class="dropdown-menu">' +
                                        <?php foreach ($cellVWFactory->inventoryStatusList as $inventoryStatusValue => $inventoryStatusLabel) : ?>
                                        '<li>' +
                                            '<a href="orga/cell/edit-inventory-status/idCell/' + this.id + '/" data-inventory="<?=$inventoryStatusValue?>">' +
                                                '<?=$inventoryStatusLabel?>' +
                                            '</a>' +
                                        '</li>' +
                                        <?php endforeach; ?>
                                    '</ul>' +
                                '</div>';
                        } else {
                            inventoryP +=
                                '<span class="label label-' + this.inventoryStatusStyle + ' withTooltip" title="<?=___('Orga', 'view', 'inventoryStatusExplanations')?>">' +
                                    this.inventoryStatusTitle +
                                '</span>';
                        }
                        inventoryP +=
                                ' <a href="#" class="withPopover inventoryInputsDetails" title="<?=___('Orga', 'view', 'inventoryInputsDetails')?>"' +
                                    'data-toggle="tooltip" data-placement="bottom" data-trigger="hover" data-html="true"' +
                                    'data-content="' +
                                    this.inventoryNotStartedInputsNumber + ' ' +
                                    ((this.inventoryNotStartedInputsNumber > 1) ? '<?=___('Orga', 'view', 'inputsNotStartedMany')?>' : '<?=___('Orga', 'view', 'inputsNotStartedSingle')?>') +
                                    ' <br> ' +
                                    this.inventoryStartedInputsNumber + ' ' +
                                    ((this.inventoryStartedInputsNumber > 1) ? '<?=___('Orga', 'view', 'inputsStartedMany')?>' : '<?=___('Orga', 'view', 'inputsStartedSingle')?>') +
                                    ' <br> ' +
                                    this.inventoryCompletedInputsNumber + ' ' +
                                    ((this.inventoryCompletedInputsNumber > 1) ? '<?=___('Orga', 'view', 'inputsCompletedMany')?>' : '<?=___('Orga', 'view', 'inputsCompletedSingle')?>') +
                                    '">' +
                                    '<i class="fa fa-tasks"></i>' +
                                '</a>' +
                                '<a data-toggle="modal" href="#inventoryUsers' + this.id + '" title="<?=___('Orga', 'view', 'viewInventoryUsers')?>" class="withTooltip">' +
                                    '<i class="fa fa-bullhorn"></i>' +
                                '</a>' +
                            '</div>' +
                            '<div class="progress withTooltip" title="<?=___('Orga', 'view', 'inventoryPercentExplanations')?>" data-toggle="tooltip" data-placement="bottom" data-trigger="hover">' +
                                '<div class="bar" style="width: ' + this.inventoryCompletion + '%">' + this.inventoryCompletion + '%</div>' +
                            '</div>';
                        inventoryPopup +=
                            '<div id="inventoryUsers' + this.id + '" class="modal inventory-users hide fade" data-cell="' + this.id + '">' +
                                '<div class="modal-header">' +
                                    '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                    '<h4 class="withTooltip" title="<?=___('Orga', 'view', 'inventoryUsersExplanations')?>">' +
                                        '<?=___('Orga', 'view', 'inventoryUsersFrom')?>' + this.shortLabel + ' ' +
                                        '<i class="fa fa-question-circle"></i>' +
                                    '</h4>' +
                                '</div>' +
                                '<div class="modal-body">' +
                                '</div>' +
                            '</div>';
                    }
                    var inputStatusP = '';
                    if (this.showInput) {
                        inputStatusP =
                            '<div class="input-status">' +
                                '<span class="badge badge-' + this.inputStatusStyle + ' withTooltip" title="<?=___('Orga', 'view', 'inputStatusExplanations')?>">' +
                                    this.inputStatusTitle +
                                '</span>' +
                            '</div>' +
                            '<div class="progress progress-' + this.inputStatusStyle + ' withTooltip" title="<?=___('Orga', 'view', 'inputPercentExplanations')?>" data-toggle="tooltip" data-placement="bottom" data-trigger="hover">' +
                                '   <div class="bar" style="width: ' + this.inputCompletion + '%">' + this.inputCompletion + ' %</div>' +
                            '</div>';
                    }
                    granularity.append(
                        '<div class="span4 well cell hide" data-tag="' + this.tag + '" data-input-status="' + this.inputStatus + '" data-inventory-status="' + this.inventoryStatus + '">' +
                            '<h4>'+
                                '<small class="cell-actions">' +
                                    usersP +
                                    reportsP +
                                    exportsP +
                                '</small>' +
                                cellTitle +
                            '</h4>' +
                            inventoryP +
                            inputStatusP +
                            usersPopup +
                            reportsPopup +
                            exportsPopup +
                            inventoryPopup +
                        '</div>'
                    );
                });
                $('.withTooltip', granularity).tooltip();
                $('.withPopover', granularity).popover();
                $('.cells-filter', granularity.parent()).trigger('filterCells');
            },
            error: function(jqXHR) {
                granularityInfo[0].className = granularityInfo[0].className.replace(/\bbadge-.*?\b/g, '');
                var response = $.parseJSON(jqXHR.responseText);
                if (typeof(response.typeError) == 'string') {
                    granularityInfo.addClass('badge-' + response.typeError);
                } else {
                    granularityInfo.addClass('badge-error');
                }
                if (typeof(response.message) == 'string') {
                    granularityInfo.html(response.message);
                } else {
                    granularityInfo.html('<?=___('UI', 'loading', 'error')?>');
                }
            }
        });
    }
});

$('.cells-filter button.reset').on('click', function(e) {
    e.preventDefault();
    var form = $(this).parent();
    form.trigger('resetCellsFilter');
});
$('.cells-filter select').on('keyup change', function(e) {
    var form = $(this).parent();
    form.trigger('filterCells');
});
$('.cells-filter .filter-reverser').on('change', function(e) {
    var form = $(this).parent();
    form.trigger('filterCells');
});
$('.cells-filter').on('resetCellsFilter', function(e) {
    e.preventDefault();
    var form = $(this);
    $('select', form).val('');
    $('.filter-reverser', form).prop('checked', false);
    form.trigger('filterCells');
});
$('.cells-filter').on('filterCells', function(e) {
    e.preventDefault();
    var form = $(this);
    var granularity = $('.granularity', form.parent());
    $('.no-cell', granularity).remove();

    $('.cell', granularity).addClass('hide').removeClass('firstRowCell').removeAttr('data-filtered');

    var inverseFilter = $('.filter-reverser', form).is(':checked');
    var test = '';
    $('select', form).each(function() {
        var filter = $(this).attr('data-filter');
        var filterOperator = (filter == 'tag') ? '*=' : '=';
        var value = $(this).val();
        if (value != '') {
            var testExpression = '[data-' + filter + filterOperator +'\'' + value + '\']';
            if (inverseFilter) {
                test += ':not(' + testExpression + ')';
            } else {
                test += testExpression;
            }
        }
    });

    $('.cell' + test, granularity).attr('data-filtered', '');
    var granularityInfo = $('.granularity-info', form);
    granularityInfo.html($('.cell' + test, granularity).length + ' / ' + granularity.attr('data-total-cells'));
    if ($('.cell' + test, granularity).length == 0) {
        granularity.append('<div class="no-cell span"><?=___('Orga', 'view', 'filterNoResult')?></div>');
    }

    granularity.trigger('showCells');
});
$('div.collapse[id^="granularity"]').on('showCells', function(e) {
    var granularity = $('.granularity', $(this));
    $('.display-more-cells', granularity).remove();

    var numberElement = 0;
    var maxHeight = 0;
    $('.cell[data-filtered]', granularity).each(function() {
        var cell = $(this);
        cell.removeClass('hide');
        cell.removeAttr('data-filtered');
        if ((numberElement % 3) == 0) {
            cell.addClass('firstRowCell');
        }

        var cellTitle = $('h4', cell);
        cellTitle.css('height', 'auto');
        if (cellTitle.height() > maxHeight) {
            maxHeight = cellTitle.height();
        }

        numberElement++;
        if (numberElement > 5) {
            return false;
        }
    });
    $('.cell:not(.hide) h4', granularity).css('height', maxHeight);

    if ($('.cell[data-filtered]', granularity).length > 0) {
        granularity.append(
            '<div class="btn display-more-cells span">' +
                '<?=___('Orga', 'view', 'display-more-cells')?>' +
            '</div>'
        );
    }
});
$('body').on('click', '.display-more-cells', function (e) {
    $(this).parent().trigger('showCells');
});

$('body').on('show', '.users', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.modal-body', popup).html(
        '<i class="fa fa-spinner fa-spin fa-3x"></i> <?=___('UI', 'loading', 'loading')?>'
    );
    $.ajax({
        url: 'orga/cell/view-users/idCell/' + popup.attr('data-cell') + '/',
        type: "GET",
        success: function(data) {
            $('.modal-body', popup).html(data);
        },
        error: function(jqXHR) {
            $('.modal-body', popup).html('<?=___('UI', 'loading', 'error')?>');
        }
    });
});
$('body').on('hidden', '.users', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.user-message', popup).remove();
    $('.modal-footer form input[name="userEmail"]', popup).val('');
});
$('body').on('click', '.delete-user', function(e) {
    e.preventDefault();
    if ($(this).attr('data-submitting') === 'true') {
        return false;
    }
    $('.user-message').remove();
    $(this).parent().parent().after(
        '<tr class="info user-message">' +
            '<td colspan="5">' +
                '<?=___('Orga', 'view', 'askConfirmDeleteUser')?>' +
                $(this).parent().prev().prev().html() +
                '<button class="btn btn-primary confirm"><i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?></button>' +
                '<button class="btn close-user-message"><i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?></button>' +
            '</td>' +
        '</tr>'
    );
});
$('body').on('click', 'tr.user-message .confirm', function(e) {
    e.preventDefault();
    var row = $(this).parent().parent();
    var deleteUser = $('.delete-user', row.prev());
    if (deleteUser.attr('data-submitting') === 'true') {
        return false;
    }
    deleteUser.attr('data-submitting', true);
    row.html('<td colspan="5"><i class="fa fa-spinner fa-spin"></i></td>');
    $.ajax({
        url: $('a.delete-user', row.prev()).attr('href'),
        type: "POST",
        success: function(data) {
            row.prev().remove();
            row.removeClass('info');
            row.addClass('success');
            row.html(
                '<td colspan="4">' + data + '</td>' +
                '<td><button class="close close-user-message"><i class="fa fa-times"></i></button></td>'
            );
        },
        error: function(jqXHR) {
            deleteUser.attr('data-submitting', false);
            row.removeClass('info');
            var response = $.parseJSON(jqXHR.responseText);
            if (typeof(response.typeError) == 'string') {
                row.addClass(response.typeError);
            } else {
                row.addClass('error');
            }
            if (typeof(response.message) == 'string') {
                row.html(
                    '<td colspan="4">' + response.message + '</td>' +
                    '<td><button class="close close-user-message"><i class="fa fa-times"></i></button></td>'
                );
            } else {
                row.html(
                    '<td colspan="4"><?=___('Core', 'exception', 'applicationError')?></td>' +
                    '<td><button class="close close-user-message"><i class="fa fa-times"></i></button></td>'
                );
            }
        }
    });
});
$('body').on('click', 'tr.user-message .close-user-message', function(e) {
    e.preventDefault();
    $(this).parent().parent().remove();
});
$('body').on('submit', '.addUser', function(e) {
    e.preventDefault();
    var form = $(this);
    if (form.attr('data-submitting') === 'true') {
        return false;
    }
    form.attr('data-submitting', true);
    $('.user-message').remove();
    form.before('<div class="user-message alert alert-info"><i class="fa fa-spinner fa-spin"></i></div>')
    $.ajax({
        url: form.attr('action'),
        type: "POST",
        data: form.serialize(),
        success: function(data) {
            form.prev().removeClass('alert-info');
            form.prev().addClass('alert-success');
            form.prev().html(data);
            form.parent().parent().trigger('show');
            form.attr('data-submitting', false);
        },
        error: function(jqXHR) {
            form.prev().removeClass('alert-info');
            var response = $.parseJSON(jqXHR.responseText);
            if (typeof(response.typeError) == 'string') {
                form.prev().addClass('alert-' + response.typeError);
            } else {
                form.prev().addClass('alert-error');
            }
            if (typeof(response.message) == 'string') {
                form.prev().html(response.message);
            } else {
                form.prev().html('<?=___('Core', 'exception', 'applicationError')?>');
            }
            form.attr('data-submitting', false);
        }
    });
});

$('body').on('show', '.reports', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.modal-body', popup).html(
        '<i class="fa fa-spinner fa-spin fa-3x"></i> <?=___('UI', 'loading', 'loading')?>'
    );
    $.ajax({
        url: 'orga/cell/view-reports/idCell/' + popup.attr('data-cell') + '/fromIdCell/<?=$currentCell->id?>/',
        type: "GET",
        success: function(data) {
            $('.modal-body', popup).html(data);
        },
        error: function(jqXHR) {
            $('.modal-body', popup).html('<?=___('UI', 'loading', 'error')?>');
        }
    });
});
$('body').on('hidden', '.reports', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.report-message', popup).remove();
});
$('body').on('click', '.delete-report', function(e) {
    e.preventDefault();
    if ($(this).attr('data-submitting') === 'true') {
        return false;
    }
    $('.report-message').remove();
    $(this).parent().parent().after(
        '<tr class="info report-message">' +
            '<td colspan="3">' +
                '<?=___('Orga', 'view', 'askConfirmDeleteReport')?>' +
                $('a', $(this).parent().prev().prev()).html() +
                '<button class="btn btn-primary confirm"><i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?></button>' +
                '<button class="btn close-report-message"><i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?></button>' +
            '</td>' +
        '</tr>'
    );
});
$('body').on('click', 'tr.report-message .confirm', function(e) {
    e.preventDefault();
    var row = $(this).parent().parent();
    var deleteReport = $('.delete-report', row.prev());
    if (deleteReport.attr('data-submitting') === 'true') {
        return false;
    }
    deleteReport.attr('data-submitting', true);
    row.html('<td colspan="3"><i class="fa fa-spinner fa-spin"></i></td>');
    $.ajax({
        url: $('a.delete-report', row.prev()).attr('href'),
        type: "POST",
        success: function(data) {
            row.prev().remove();
            row.removeClass('info');
            row.addClass('success');
            row.html(
                '<td colspan="2">' + data + '</td>' +
                '<td><button class="close close-report-message"><i class="fa fa-times"></i></button></td>'
            );
        },
        error: function(jqXHR) {
            deleteReport.attr('data-submitting', false);
            row.removeClass('info');
            var response = $.parseJSON(jqXHR.responseText);
            if (typeof(response.typeError) == 'string') {
                row.addClass(response.typeError);
            } else {
                row.addClass('error');
            }
            if (typeof(response.message) == 'string') {
                row.html(
                    '<td colspan="2">' + response.message + '</td>' +
                    '<td><button class="close close-report-message"><i class="fa fa-times"></i></button></td>'
                );
            } else {
                row.html(
                    '<td colspan="2"><?=___('Core', 'exception', 'applicationError')?></td>' +
                    '<td><button class="close close-report-message"><i class="fa fa-times"></i></button></td>'
                );
            }
        }
    });
});
$('body').on('click', 'tr.report-message .close-report-message', function(e) {
    e.preventDefault();
    $(this).parent().parent().remove();
});
$('body').on('keyup change', 'select[name="reportType"]', function(e) {
    var select = $(this);
    var reportsList = $('tbody', select.parent().parent().parent().parent().parent());
    $('tr', reportsList).addClass('hide');

    var selectValue = select.val();
    var selector = '';
    if (selectValue != '') {
        selector += '[data-report-type="' + select.val() + '"]';
        if (selectValue == 'userReport') {
            selector += '[data-report-owner="' + select.find(":selected").attr('data-user') + '"]';
        }
    }
    $('tr' + selector, reportsList).removeClass('hide');
});

$('body').on('click', '.inventory-status .dropdown-menu a', function(e) {
    e.preventDefault();
    var link = $(this);
    var button = link.parent().parent().prev();
    if (link.attr('data-inventory') != button.attr('data-inventory')) {
        button.html('<i class="fa fa-spinner fa-spin"></i>');
        button.attr('class', 'btn btn-small dropdown-toggle');
        $.ajax({
            url: link.attr('href'),
            type: "POST",
            data: { inventoryStatus: link.attr('data-inventory') },
            success: function (data) {
                button.attr('data-inventory', data.status);
                button.addClass('btn-' + data.style);
                button.html('<i class="fa fa-pencil-square-o"></i> ' + data.label + ' <span class="caret"></span>');
                button.parent().parent().parent().attr('data-inventory-status', data.status);
                var collapse = button.parent().parent().parent().parent().parent();
                $('.cells-filter', collapse).trigger('filterCells');
                $('.collapse[data-inventory][id!="' + collapse.attr('id') + '"]').each(function() {
                    $(this).trigger('loadCells');
                });
            },
            error: function (jqXHR) {
                button.attr('data-inventory', null);
                var response = $.parseJSON(jqXHR.responseText);
                if ((typeof(response.typeError) == 'string') && (response.typeError != 'error')) {
                    button.addClass('btn-' + response.typeError);
                } else {
                    button.addClass('btn-danger');
                }
                if (typeof(response.message) == 'string') {
                    button.html(response.message + ' <span class="caret"></span>');
                } else {
                    button.html('<?=___('Core', 'exception', 'applicationError')?> <span class="caret"></span>');
                }
            }
        });
    }
});
$('body').on('click', 'a.inventoryInputsDetails', function(e) {
    e.preventDefault();
});
$('body').on('show', '.inventory-users', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.modal-body', popup).html(
        '<i class="fa fa-spinner fa-spin fa-3x"></i> <?=___('UI', 'loading', 'loading')?>'
    );
    $.ajax({
        url: 'orga/cell/view-inventory-users/idCell/' + popup.attr('data-cell') + '/',
        type: "GET",
        success: function(data) {
            $('.modal-body', popup).html(data);
        },
        error: function(jqXHR) {
            $('.modal-body', popup).html('<?=___('UI', 'loading', 'error')?>');
        }
    });
});

$('.collapse').on({
    shown: function(e) {
        if (e.target == this) {
            $(this).css('overflow','visible');
        }
    },
    hide: function(e) {
        if (e.target == this) {
            $(this).css('overflow','hidden');
        }
    }
});

$(document).ready(function() {
    $('.withTooltip').tooltip();
    $('.withPopover').popover();
    $('div.collapse[id^="granularity"]').trigger('loadCells');
    $('.history > h3 a').trigger('click');
    $('.comments > h3 a').trigger('click');
});
</script>

<?= $this->tutorial('orga'); ?>
