<div class="well well-sm">
    <div class="smart-timeline">
        <ul class="smart-timeline-list">
            <li class="text-center">
                <button class="btn btn-default btn-sm load-more-activity" data-date-from="<?=$this->fromDate?>">
                    <?=___('Orga', 'view', 'displayMoreActivity')?>
                </button>
            </li>
        </ul>
    </div>
</div>

<style>
    .smart-timeline-list li.alert-info:hover { background: none repeat scroll 0 0 #D6DDE7; }
    .smart-timeline-list li.alert-danger:hover { background: none repeat scroll 0 0 #C26565; }
</style>

<script>
    $('.load-more-activity').on('click', function() {
        var button = $(this);
        if (button.hasClass('disabled')) {
            return;
        }
        button.addClass('disabled');
        $('.smart-timeline-list li.alert').remove();
        $('.smart-timeline-list li:last').before(
            '<li class="text-center alert alert-info"><i class="fa fa-spinner fa-fw fa-spin"></i> <?=addslashes(___('Orga', 'view', 'loadingActivity'))?></li>'
        );
        $.ajax({
            url: 'orga/cell/view-more-activity/idCell/<?=$this->idCell?>/from/' + button.attr('data-date-from'),
            data: button.attr('data-date-from'),
            type: "GET",
            success: function(data) {
                button.removeClass('disabled');
                if (data.activity.length > 0) {
                    $.each(data.activity, function() {
                        $('.smart-timeline-list li:last').before(
                            '<li>' +
                                '<div class="smart-timeline-icon bg-color-' + ((this.type == 'comment') ? 'green' : 'orange') + '">' +
                                    '<i class="fa fa-' + ((this.type == 'comment') ? 'comment' : 'history') + ' fa-fw"></i>' +
                                '</div>' +
                                '<div class="smart-timeline-time">' +
                                    '<small>' +
                                        this.dateTime +
                                    '</small>' +
                                '</div>' +
                                '<div class="smart-timeline-content">' +
                                    '<p>' +
                                        '<strong>' +
                                            '<a>' +
                                                this.cell +
                                            '</a>' +
                                        '</strong>' +
                                    '</p>' +
                                    '<p>' +
                                        this.content +
                                    '</p>' +
                                '</div>' +
                            '</li>'
                        );
                    });
                } else {
                    $('.smart-timeline-list li:last').before(
                        '<li class="text-center alert alert-warning"><?=addslashes(___('Orga', 'view', 'noMoreActivity'))?></li>'
                    );
                }
                button.attr('data-date-from', data.dateFrom);
            },
            error: function(jqXHR) {
                button.removeClass('disabled');
                $('.smart-timeline-list li:last').before(
                    '<li class="text-center alert alert-danger"><?=addslashes(___('Orga', 'view', 'errorWhileLoadingActivity'))?></li>'
                );
            },
            complete: function(jqXHR) {
                button.removeClass('disabled');
                $('.smart-timeline-list li.alert-info').remove();
            }
        });
    });
    $(document).ready(function() { $('.load-more-activity').click(); });
</script>
