<?php

use AF\Domain\InputSet\PrimaryInputSet;
use Orga\ViewModel\CellViewModel;
use Orga\Model\ACL\CellAdminRole;
use Orga\Model\ACL\CellManagerRole;
use Orga\Model\ACL\CellContributorRole;
use Orga\Model\ACL\CellObserverRole;
use Account\Application\ViewModel\OrganizationView;

$inventoryStatusFilters = [
    null => ___('Orga', 'view', 'allInventoryStatus'),
    Orga_Model_Cell::STATUS_NOTLAUNCHED => ___('Orga', 'view', 'inventoryNotLaunched'),
    Orga_Model_Cell::STATUS_ACTIVE => ___('Orga', 'view', 'inventoryOpen'),
    Orga_Model_Cell::STATUS_CLOSED => ___('Orga', 'view', 'inventoryClosed'),
];
$inputStatusFilters = [
    null => ___('Orga', 'view', 'allInputStatus'),
    PrimaryInputSet::STATUS_FINISHED => ___('AF', 'inputInput', 'statusFinished'),
    PrimaryInputSet::STATUS_COMPLETE => ___('AF', 'inputInput', 'statusComplete'),
    PrimaryInputSet::STATUS_CALCULATION_INCOMPLETE => ___('AF', 'inputInput', 'statusCalculationIncomplete'),
    PrimaryInputSet::STATUS_INPUT_INCOMPLETE => ___('AF', 'inputInput', 'statusInputIncomplete'),
    CellViewModel::AF_STATUS_NOT_STARTED => ___('Orga', 'view', 'statusNotStarted'),
    CellViewModel::AF_STATUS_AF_NOT_CONFIGURED => ___('Orga', 'view', 'statusAFNotConfigured'),
    CellViewModel::AF_STATUS_INVENTORY_NOT_STARTED => ___('Orga', 'view', 'inventoryNotLaunched'),
];

/** @var OrganizationView $organization */
$organization = $this->organization;
/** @var CellViewModel $currentCell */
$currentCell = $this->currentCell;

$workspaceBanner = null;
$file = glob(APPLICATION_PATH . '/../public/workspaceBanners/' . $organization->id . '.*');
if (count($file) > 0) {
    $workspaceBanner = 'workspaceBanners/' . pathinfo(array_pop($file))['filename'];
}
?>

<style>
    .organization h1 img { max-height: 125px; }

    .users .user-message { font-weight: bold; }
    .users .modal-body { padding: 0; }
    .users .modal-body table { margin: 0; }
    .users .modal-body tr.user-message td:first-child { text-align: center; }
    .users .modal-body tr.user-message .btn { margin: 0 5px 0 5px; }
    .users .modal-body tr.user-message .close-user-message { float: none; font-size: inherit; opacity: 1; }
    .users .modal-body .delete-user { color: #000000; }
    .users .modal-body .delete-user + .tooltip.left { margin-left: -15px; }
    .users .modal-footer div.user-message { text-align: center; margin-bottom: 5px; }
    .users .modal-footer form { margin: 0; }

    .reports .report-message { font-weight: bold; }
    .reports .modal-body { padding: 0; }
    .reports .modal-body table { margin: 0; }
    .reports .modal-body tr.report-message td:first-child { text-align: center; }
    .reports .modal-body tr.report-message .btn { margin: 0 5px 0 5px; }
    .reports .modal-body tr.report-message .close-report-message { float: none; font-size: inherit; opacity: 1; }
    .reports .modal-body .delete-report + .tooltip.left { margin-left: -15px; }
    .reports .filter-reports { display: inline-block; margin-bottom: 0; }

    .exports .modal-body { text-align: center; }
    .exports .modal-body .alert { margin-bottom: 5px; }
    .exports .modal-body form { margin: 0; }

    .cell { padding: 5px; font-size: 16px; }
    .cell h2, .cell h4 { margin: 10px; overflow: hidden; }
    .cell .cell-actions { float: right; }
    .cell .inventory-status { position: relative; border-top: 1px solid #bbbbbb; color: #ffffff; background-color: #dddddd; }
    .cell .inventory-status .inventory-progress { position: absolute; top: 0; left: 0; height: 100%; background-color: #bbbbbb; }
    .cell .inventory-status .inventory-informations { display: inline-block; position: relative; overflow: hidden; vertical-align: top; }
    .cell .inventory-status .inventory-informations .inventory-title { display: inline-block; margin-top: 15px; margin-bottom: 15px; margin-left: 10px; }
    .cell .inventory-status .inventory-informations .inventory-completion { display: inline-block; margin-left: 5px; vertical-align: bottom; color: #222222; opacity: 0.15; font-size: 45px; font-weight: bold; }
    .cell .inventory-status .inventory-actions { display: inline-block; position: relative; float:right; text-align: right; }
    .cell .inventory-status .inventory-actions > a { display: inline-block; margin-top: 10px; margin-right: 10px; text-align: left; }
    .cell .inventory-status .inventory-actions > .btn-group { display: inline-block; margin-top: 10px; margin-right: 5px; text-align: left; }
    .cell[data-inventory-status="<?=Orga_Model_Cell::STATUS_ACTIVE?>"] .inventory-status { background-color: #a4e3f0; }
    .cell[data-inventory-status="<?=Orga_Model_Cell::STATUS_ACTIVE?>"] .inventory-progress { background-color: #49afcd; }
    .cell .inventory-status + .input-status { margin-top: 5px; }
    .cell .input-status { position: relative; border-top: 1px solid #bbbbbb; color: #ffffff; background-color: #dd514c; }
    .cell .input-status .input-actions { display: inline-block; position: relative; float:right; text-align: right; }
    .cell .input-status .input-actions > a { display: inline-block; margin-top: 10px; margin-right: 10px; text-align: left; }
    .cell .input-status .input-title { display: inline-block; margin-top: 15px; margin-bottom: 15px; margin-left: 10px; }
    .cell[data-input-status="<?=PrimaryInputSet::STATUS_FINISHED?>"] .input-status { background-color: #57a957; }
    .cell[data-input-status="<?=PrimaryInputSet::STATUS_COMPLETE?>"] .input-status { background-color: #f0aD4e; }
    .cell[data-input-status="<?=PrimaryInputSet::STATUS_INPUT_INCOMPLETE?>"] .input-status { background-color: #f0aD4e; }

    .granularity-wrapper .cells-filter > * { margin-top: 2px; }
    .granularity-wrapper .cells-filter .granularity-info { vertical-align: middle; font-size: 14px; font-weight: normal; line-height: 20px; padding: 4px 12px; }
    .granularity-wrapper .granularity > .cell.firstRowCell { margin-left: 0; }
    .granularity-wrapper .display-more-cells { margin-left: 0; }
    .granularity-wrapper .no-cell { margin-left: 0; text-align: center; vertical-align: middle; padding: 8px 12px; font-size: 14px; font-weight: normal; }

    .history,
    .comments
    { margin-bottom: 15px; }
    .history > h3,
    .comments > h3
    { margin: 0; }
    .history > h3 small,
    .comments > h3 small
    { margin-top: 15px; }
    .history > hr,
    .comments > hr
    { margin: 0 0 5px; }
    .history h4,
    .comments h4
    { border-bottom: 1px solid #eeeeee; margin-bottom: 20px; margin-top: 0; }
    .history h4 span,
    .comments h4 span
    { position: relative; top: 10px; background-color: #ffffff; padding-right: 5px; color: #999999; }
    .history div.row div.col-md-2,
    .comments div.row div.col-md-2
    { color: #999999; font-size: small; font-weight: normal; text-align: right; }
    .history div.row + div.row,
    .comments div.row + div.row
    { border-top: solid 1px #eeeeee; margin-top: 8px; padding-top: 8px; }
    .history > div > div + div,
    .comments >div > div + div
    { margin-top: 5px;  }

    #addMember { margin: 0; }
    #addMember .controls { margin-left: 0; float: right; }
    #addMember .subGroup { margin-left: 0; }
    #addMember label { text-align: left; width: auto; }
    #addMember .input { width: auto; }
    #addMember .form-actions { padding: 10px 0 0 0; margin: 0; background-color: inherit; text-align: center; border: none; }
    #addMember .form-actions input { float: right; }
</style>

<div class="organization page-header">
    <h1>
        <?php if ($organization->canBeEdited) : ?>
            <div class="pull-right">
                <small>
                    <a class="editOrganization btn btn-small btn-primary"
                       href="orga/organization/edit/idOrganization/<?=$organization->id?>/">
                        <i class="fa fa-wrench"></i>
                        <?=___('UI', 'name', 'configurationOrga')?>
                    </a>
                </small>
            </div>
        <?php endif; ?>
        <?php if ($workspaceBanner === null) : ?>
            <?=$organization->label?>
        <?php else : ?>
            <img src="<?=$workspaceBanner?>">
        <?php endif; ?>
    </h1>
</div>

<div class="row">

<div class="col-md-9" id="cellsView">

    <div class="cell current-cell well" data-inventory-status="<?=$currentCell->inventoryStatus?>" data-input-status="<?=$currentCell->inputStatus?>">
        <h2>
            <?=$currentCell->extendedLabel?>
            <small class="cell-actions btn-group">
                <a class="btn btn-default withTooltip" data-toggle="modal" href="#administrators<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'contactAdministrators')?>" data-container="body"><i class="fa fa-user-md"></i></a>
                <?php if ($currentCell->showUsers) : ?>
                <a class="btn btn-default withTooltip" data-toggle="modal" href="#users<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'editUsers')?>" data-container="body">(<?=$currentCell->numberUsers?>) <i class="fa fa-users"></i></a>
                <?php endif; ?>
                <?php if ($currentCell->showReports) : ?>
                <a class="btn btn-default withTooltip" data-toggle="modal" href="#reports<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'analyzeData')?>" data-container="body"><i class="fa fa-bar-chart-o"></i></a>
                <a class="btn btn-default withTooltip" data-toggle="modal" data-target="#exports<?=$currentCell->id?>" href="orga/cell/view-exports/idCell/<?=$currentCell->id?>/" title="<?=___('Orga', 'view', 'exportData')?>" data-container="body"><i class="fa fa-download"></i></a>
                <?php endif; ?>
            </small>
        </h2>
        <?php // Inventory ?>
        <?php if ($currentCell->showInventory) : ?>
        <div class="inventory-status">
            <div class="inventory-progress" style="width: <?=$currentCell->inventoryCompletion?>%;"></div>
            <div class="inventory-actions">
                <?php if ($currentCell->canEditInventory) : ?>
                <div class="btn-group">
                    <a class="btn btn-default change-inventory-status" href="orga/cell/edit-inventory-status/idCell/<?=$currentCell->id?>/inventoryStatus/<?=($currentCell->inventoryStatus === Orga_Model_Cell::STATUS_ACTIVE) ? Orga_Model_Cell::STATUS_CLOSED : Orga_Model_Cell::STATUS_ACTIVE?>/">
                        <?=($currentCell->inventoryStatus === Orga_Model_Cell::STATUS_NOTLAUNCHED) ? ___('Orga', 'view', 'inventoryNotLaunchedMainAction') : (($currentCell->inventoryStatus == Orga_Model_Cell::STATUS_ACTIVE) ? ___('Orga', 'view', 'inventoryActiveMainAction') : ___('Orga', 'view', 'inventoryClosedMainAction'))?>
                    </a>
                    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="change-inventory-status" href="orga/cell/edit-inventory-status/idCell/<?=$currentCell->id?>/inventoryStatus/<?=($currentCell->inventoryStatus === Orga_Model_Cell::STATUS_NOTLAUNCHED) ? Orga_Model_Cell::STATUS_CLOSED : Orga_Model_Cell::STATUS_NOTLAUNCHED?>/">
                                <?=($currentCell->inventoryStatus === Orga_Model_Cell::STATUS_NOTLAUNCHED) ? ___('Orga', 'view', 'inventoryNotLaunchedOtherAction') : (($currentCell->inventoryStatus == Orga_Model_Cell::STATUS_ACTIVE) ? ___('Orga', 'view', 'inventoryActiveOtherAction') : ___('Orga', 'view', 'inventoryClosedOtherAction'))?>
                            </a>
                        </li>
                    </ul>
                </div>
                <?php endif; ?>
                <a class="btn btn-default withTooltip" data-toggle="modal" href="#inventoryUsers<?=$currentCell->id?>" title="<?=___('Orga', 'view', 'viewInventoryUsers')?>"><i class="fa fa-bullhorn"></i></a>
            </div>
            <div class="inventory-informations withPopover" title="<?=___('Orga', 'view', 'inventoryInputsDetails')?>" data-toggle="tooltip" data-placement="bottom" data-trigger="hover" data-html="true" data-content="<?=$currentCell->inventoryNotStartedInputsNumber?> <?=($currentCell->inventoryNotStartedInputsNumber > 1) ? ___('Orga', 'view', 'inputsNotStartedMany') : ___('Orga', 'view', 'inputsNotStartedSingle')?> <br> <?=$currentCell->inventoryStartedInputsNumber?> <?=($currentCell->inventoryStartedInputsNumber > 1) ? ___('Orga', 'view', 'inputsStartedMany') : ___('Orga', 'view', 'inputsStartedSingle')?> <br> <?=$currentCell->inventoryCompletedInputsNumber?> <?=($currentCell->inventoryCompletedInputsNumber > 1) ? ___('Orga', 'view', 'inputsCompletedMany') : ___('Orga', 'view', 'inputsCompletedSingle')?>" data-container="body">
                <div class="inventory-title">
                    <?=$currentCell->inventoryStatusTitle?>
                </div>
                <div class="inventory-completion">
                    <?=$currentCell->inventoryCompletion?>%
                </div>
            </div>
            <a href="#" class="withPopover inventory-inputs-details"><i class="fa fa-tasks"></i></a>
        </div>
        <?php endif; ?>
        <?php // Input ?>
        <?php if ($currentCell->showInput) : ?>
        <div class="input-status">
            <div class="input-actions">
                <a class="btn btn-default withTooltip" href="orga/cell/input/idCell/<?=$currentCell->id?>/fromIdCell/<?=$currentCell->id?>/" title="<?=___('Orga', 'view', 'viewInput')?>" target="_blank">
                    <?=___('Orga', 'view', 'inputLinkDetail')?>
                </a>
            </div>
            <div class="input-title">
                <?=$currentCell->inputStatusTitle?>
            </div>
        </div>
        <?php endif; ?>

        <div id="administrators<?=$currentCell->id?>" class="modal administrators hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="withTooltip" title="<?=___('Orga', 'view', 'administratorExplanations')?>">
                    <?=___('Orga', 'view', 'administratorsFrom')?> <?=$currentCell->shortLabel?>
                    <i class="fa fa-question-circle"></i>
                </h4>
            </div>
            <div class="modal-body">
                <pre><?=implode("\n", $currentCell->administrators)?></pre>
            </div>
        </div>
        <?php if ($currentCell->showUsers) : ?>
        <div id="users<?=$currentCell->id?>" class="modal users hide fade large" data-cell="<?=$currentCell->id?>">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4><?=___('Orga', 'view', 'rolesFrom')?> <?=$currentCell->shortLabel?></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <form class="form-inline addUser" action="orga/cell/add-user/idCell/<?=$currentCell->id?>/">
                    <input type="text" name="userEmail" placeholder="<?=___('User', 'user', 'emailAddress')?>">
                    <select name="userRole">
                        <option value="CellAdminRole"><?=CellAdminRole::getLabel()?></option>
                        <option value="CellManagerRole"><?=CellManagerRole::getLabel()?></option>
                        <option value="CellContributorRole"><?=CellContributorRole::getLabel()?></option>
                        <option value="CellObserverRole"><?=CellObserverRole::getLabel()?></option>
                    </select>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-plus"></i>
                        <?=___('UI', 'verb', 'add')?>
                    </button>
                </form>
            </div>
        </div>
        <?php endif; ?>
        <?php if ($currentCell->showReports) : ?>
        <div id="reports<?=$currentCell->id?>" class="modal reports hide fade large" data-cell="<?=$currentCell->id?>">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4><?=___('Orga', 'view', 'reportsFrom')?> <?=$currentCell->shortLabel?></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <a href="orga/cell/view-report/idCell/<?=$currentCell->id?>/" class="btn btn-primary">
                    <i class="fa fa-plus"></i>
                    <?=___('UI', 'verb', 'add')?>
                </a>
            </div>
        </div>
        <div id="exports<?=$currentCell->id?>" class="modal exports hide fade">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4><?=___('Orga', 'view', 'exportsFrom')?> <?=$currentCell->shortLabel?></h4>
            </div>
            <div class="modal-body">
                <div class="granularityCells row">
                    <i class="fa fa-spinner fa-spin fa-3x"></i>
                    <?=___('UI', 'loading', 'loading')?>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if ($currentCell->showInventory) : ?>
        <div id="inventoryUsers<?=$currentCell->id?>" class="modal inventory-users hide fade" data-cell="<?=$currentCell->id?>">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="withTooltip" title="<?=___('Orga', 'view', 'inventoryUsersExplanations')?>">
                    <?=___('Orga', 'view', 'inventoryUsersFrom')?> <?=$currentCell->shortLabel?>
                    <i class="fa fa-question-circle"></i>
                </h4>
            </div>
            <div class="modal-body">
            </div>
        </div>
        <?php endif; ?>
    </div>

    <?php foreach ($this->narrowerGranularities as $narrowerGranularityArray) :
    /** @var Orga_Model_Granularity $narrowerGranularity */
    $narrowerGranularity = $narrowerGranularityArray['granularity'];
    ?>
    <fieldset class="wrapper granularity-wrapper">
        <legend data-toggle="collapse" data-target="#granularity<?=$narrowerGranularity->getId()?>">
            <i class="filterChevron fa fa-chevron-<?=((count($this->narrowerGranularities) === 1)?'down':'right')?>"></i>
            <?=$narrowerGranularity->getLabel()?>
            <small>
                <?=___('Orga', 'view', 'granularityExplanations')?><?=$narrowerGranularityArray['purpose']?>
            </small>
        </legend>

        <div id="granularity<?=$narrowerGranularity->getId()?>"
             <?=$narrowerGranularityArray['isAcl'] ? ' data-acl' : ''?>
             <?=$narrowerGranularityArray['isInventory'] ? ' data-inventory' : ''?>
             <?=$narrowerGranularityArray['isInput'] ? ' data-input' : ''?>
             <?=$narrowerGranularityArray['isAnalyses'] ? ' data-analyses' : ''?>
             data-total-cells="<?=$narrowerGranularityArray['totalCells']?>"
             data-first-cell="0"
             data-show-cells="6"
             class="collapse<?=(count($this->narrowerGranularities) === 1) ? ' in': $narrowerGranularityArray['isInput'] ? ' in' : ''?>">
            <?php if ($narrowerGranularity->hasAxes() || ($narrowerGranularity->getInputConfigGranularity() !== null)) : ?>
            <form class="form-inline cells-filter">
                <?php foreach ($narrowerGranularityArray['filterAxes'] as $refAxis => $memberOptions) : ?>
                <?php if (count($memberOptions) > 2) : ?>
                <select name="granularity<?=$narrowerGranularity->getId()?>_axis<?=$refAxis?>" data-filter="tag">
                    <?php foreach ($memberOptions as $memberTag => $memberLabel) : ?>
                        <option value="<?=$memberTag?>"><?=$memberLabel?></option>
                    <?php endforeach; ?>
                </select>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($narrowerGranularityArray['isInventory']) : ?>
                <select name="granularity<?=$narrowerGranularity->getId()?>_inventoryStatus" data-filter="inventory-status">
                    <?php foreach ($inventoryStatusFilters as $statusValue => $statusLabel) : ?>
                        <? if (($statusValue === Orga_Model_Cell::STATUS_ACTIVE) && (!$narrowerGranularityArray['isGranularityForInventoryStatus'])) : ?>
                            <option value="<?=$statusValue?>" selected><?=$statusLabel?></option>
                        <?php else: ?>
                            <option value="<?=$statusValue?>"><?=$statusLabel?></option>
                        <?php endif ?>
                    <?php endforeach ?>
                </select>
                <?php endif; ?>
                <button class="btn reset"><i class="fa fa-search-minus"></i> <?=___('UI', 'verb', 'reset')?></button>
                <span class="badge badge-info granularity-info withTooltip" title="<?=___('Orga', 'view', 'ratioNumberFilteredCellsOverTotal')?>" data-toggle="tooltip" data-placement="right" data-trigger="hover"></span>
            </form>
            <?php endif; ?>

            <div class="granularity row" data-total-cells="0"></div>
        </div>
    </fieldset>
    <?php endforeach; ?>

</div>

<div class="col-md-3">
    <div class="comments">
        <h3>
            <?=___('Social', 'comment', 'comments')?>
            <small class="pull-right">
                <a href="orga/cell/view-comments/idCell/<?=$currentCell->id?>/" class="refresh">
                    <i class="fa fa-refresh"></i>
                </a>
            </small>
        </h3>
        <div>
            <?=___('UI', 'loading', 'error')?>
        </div>
    </div>
    <div class="history">
        <h3>
            <?=___('UI', 'history', 'history')?>
            <small class="pull-right">
                <a href="orga/cell/view-history/idCell/<?=$currentCell->id?>/" class="refresh">
                    <i class="fa fa-refresh"></i>
                </a>
            </small>
        </h3>
        <div>
            <?=___('UI', 'loading', 'error')?>
        </div>
    </div>
    <?php if ($this->canAddMembers) : ?>
    <div class="addMember">
        <h3>
            <div class="pull-right">
                <small>
                    <a class="editOrganization btn btn-small btn-primary"
                       href="orga/organization/edit/idOrganization/<?=$organization->id?>/tab/members/">
                        <i class="fa fa-wrench"></i>
                        <?=___('UI', 'name', 'configurationOrga')?>
                    </a>
                </small>
            </div>
            <?=___('Orga', 'view', 'addMember')?>
        </h3>
        <hr/>
        <?=$this->addMembersForm->display()?>
    </div>
    <?php endif; ?>
</div>

</div>
<script>
$('.comments a.refresh').on('click', function(e) {
    e.preventDefault();
    $('.comments > h3 i').addClass('fa-spin');
    $('.comments > div').html('<i class="fa fa-spinner fa-spin fa-3x"></i> <?=addslashes(___('Social', 'comment', 'loadingComments'))?>');
    $.ajax({
        url: $(this).attr('href'),
        type: "GET",
        success: function(data) {
            $('.comments > h3 i').removeClass('fa-spin');
            $('.comments > div').html('');
            if (data.length > 0) {
                $.each(data, function() {
                    var date = this.date;
                    $('.comments > div').append('<div data-date="' + date + '"><h4><span>' + date + '</span></h4></div>');
                    var divDate = $('.comments > div > div[data-date="' + date + '"]');
                    $.each(this.comments, function() {
                        divDate.append(
                            '<div class="row">' +
                                '<div class="col-md-2">' + this.time + '</div>' +
                                '<div class="col-md-10">' + this.comment + '</div>' +
                            '</div>'
                        );
                    });
                });
            } else {
                $('.comments > div').html('<p><?=addslashes(___('Social', 'comment', 'noComment'))?></p>');
            }
        },
        error: function(jqXHR) {
            $('.comments > h3 i').removeClass('fa-spin');
            $('.comments > div').html('<?=addslashes(___('Social', 'comment', 'errorWhileLoadingComments'))?>');
        }
    });
});
$('.history a.refresh').on('click', function(e) {
    e.preventDefault();
    $('.history > h3 i').addClass('fa-spin');
    $('.history > div').html('<i class="fa fa-spinner fa-spin fa-3x"></i> <?=addslashes(___('UI', 'history', 'loadingHistory'))?>');
    $.ajax({
        url: $(this).attr('href'),
        type: "GET",
        success: function(data) {
            $('.history > h3 i').removeClass('fa-spin');
            $('.history > div').html('');
            if (data.length > 0) {
                $.each(data, function() {
                    var date = this.date;
                    $('.history > div').append('<div data-date="' + date + '"><h4><span>' + date + '</span></h4></div>');
                    var divDate = $('.history > div > div[data-date="' + date + '"]');
                    $.each(this.events, function() {
                        divDate.append(
                            '<div class="row">' +
                                '<div class="col-md-2">' + this.time + '</div>' +
                                '<div class="col-md-10">' + this.event + '</div>' +
                            '</div>'
                        );
                    });
                });
            } else {
                $('.history > div').html('<p><?=___('UI', 'history', 'noHistory')?></p>');
            }
        },
        error: function(jqXHR) {
            $('.history > h3 i').removeClass('fa-spin');
            $('.history > div').html('<?=addslashes(___('UI', 'loading', 'error'))?>');
        }
    });
});

$('.granularity-wrapper > div').on('show', function(e) {
    if (e.currentTarget == e.target) {
        $('legend > span > i.filterChevron', $(this).parent()).removeClass('fa-chevron-right');
        $('legend > span > i.filterChevron', $(this).parent()).addClass('fa-chevron-down');
    }
});
$('.granularity-wrapper > div').on('hidden', function(e) {
    if (e.currentTarget == e.target) {
        $('legend > span > i.filterChevron', $(this).parent()).removeClass('fa-chevron-down');
        $('legend > span > i.filterChevron', $(this).parent()).addClass('fa-chevron-right');
    }
});

$('div.collapse[id^="granularity"]').on('loadCells', function(e) {
    if (e.target != this) {
        return;
    }
    var granularity = $('.granularity', $(this));
    var granularityInfo = $('.granularity-info', granularity.parent());
    granularityInfo[0].className = granularityInfo[0].className.replace(/\bbadge-.*?\b/g, '');
    granularityInfo.addClass('badge-info');
    granularityInfo.html('<i class="fa fa-spinner fa-spin"></i> <?=___('UI', 'loading', 'loading')?>');
    var granularityId = $(this).attr('id').substr(11, $(this).attr('id').length);
    $.ajax({
        url: 'orga/cell/view-children/idCell/<?=$currentCell->id?>/idGranularity/' + granularityId + '/',
        type: "POST",
        data: { firstCell: $(this).attr('data-first-cell'), showCells: $(this).attr('data-show-cells'), filters: $('.cells-filter', $(this)).serializeArray() },
        success: function(data) {
            granularity.attr('data-total-cells', data.totalCells);
            granularityInfo.html(granularity.attr('data-total-cells') + ' / ' + granularity.parents('.collapse').attr('data-total-cells'));
            $(data.childCells).each(function() {
                var cellTitle = this.extendedLabel;
                var usersP = '';
                var usersPopup = '';
                if (this.showUsers) {
                    usersP +=
                        '<a class="btn withTooltip" data-toggle="modal" href="#users' + this.id + '" title="<?=___('Orga', 'view', 'editUsers')?>" data-container="body">' +
                            '(' + this.numberUsers + ') ' +
                            '<i class="fa fa-users"></i>' +
                        '</a>';
                    usersPopup +=
                        '<div id="users' + this.id + '" class="modal users hide fade large" data-cell="' + this.id + '">' +
                            '<div class="modal-header">' +
                                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                '<h4><?=___('Orga', 'view', 'rolesFrom')?> ' + this.shortLabel + '</h4>' +
                            '</div>' +
                            '<div class="modal-body">' +
                            '</div>' +
                            '<div class="modal-footer">' +
                                '<form class="form-inline addUser" action="orga/cell/add-user/idCell/' + this.id + '/">' +
                                    '<input type="text" placeholder="<?=___('User', 'user', 'emailAddress')?>" name="userEmail"> ' +
                                    '<select name="userRole">' +
                                        '<option value="CellAdminRole"><?=CellAdminRole::getLabel()?></option>' +
                                        '<option value="CellManagerRole"><?=CellManagerRole::getLabel()?></option>' +
                                        '<option value="CellContributorRole"><?=CellContributorRole::getLabel()?></option>' +
                                        '<option value="CellObserverRole"><?=CellObserverRole::getLabel()?></option>' +
                                    '</select> ' +
                                    '<input type="submit" class="btn btn-primary" value="<?=___('UI', 'verb', 'add')?>"> ' +
                                '</form>' +
                            '</div>' +
                        '</div>';
                }
                var reportsP = '';
                var reportsPopup = '';
                if (this.showReports) {
                    reportsP +=
                        '<a class="btn withTooltip" data-toggle="modal" href="#reports' + this.id + '" title="<?=___('Orga', 'view', 'analyzeData')?>" data-container="body">' +
                            '<i class="fa fa-bar-chart-o"></i>' +
                        '</a>';
                    reportsPopup +=
                        '<div id="reports' + this.id + '" class="modal reports hide fade large" data-cell="' + this.id + '">' +
                            '<div class="modal-header">' +
                                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                '<h4><?=___('Orga', 'view', 'reportsFrom')?>' + this.shortLabel + '</h4>' +
                            '</div>' +
                            '<div class="modal-body">' +
                            '</div>' +
                            '<div class="modal-footer">' +
                                '<a href="orga/cell/view-report/idCell/' + this.id + '/" class="btn btn-primary">' +
                                    '<i class="fa fa-plus"></i> ' +
                                    '<?=___('UI', 'verb', 'add')?>' +
                                '</a>' +
                            '</div>' +
                        '</div>';
                }
                var exportsP = '';
                var exportsPopup = '';
                if (this.showExports) {
                    exportsP +=
                        '<a class="btn withTooltip" data-toggle="modal" data-target="#exports' + this.id + '" href="orga/cell/view-exports/idCell/' + this.id + '/" title="<?=___('Orga', 'view', 'exportData')?>" data-container="body">' +
                            '<i class="fa fa-download"></i>' +
                        '</a>';
                    exportsPopup +=
                        '<div id="exports' + this.id + '" class="modal exports hide fade">' +
                            '<div class="modal-header">' +
                                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                '<h4><?=___('Orga', 'view', 'exportsFrom')?> ' + this.shortLabel + '</h4>' +
                            '</div>' +
                            '<div class="modal-body">' +
                                '<i class="fa fa-spinner fa-spin fa-3x"></i> ' +
                                '<?=___('UI', 'loading', 'loading')?>' +
                            '</div>' +
                        '</div>';
                }
                var inventoryP = '';
                var inventoryPopup = '';
                if (this.showInventory) {
                    inventoryP +=
                        '<div class="inventory-status">' +
                            '<div class="inventory-progress" style="width: ' + this.inventoryCompletion + '%;">' +
                            '</div>' +
                            '<div class="inventory-actions">';
                    if (this.canEditInventory) {
                        var mainActionStatus = (this.inventoryStatus == '<?=Orga_Model_Cell::STATUS_ACTIVE?>') ? '<?=Orga_Model_Cell::STATUS_CLOSED?>' : '<?=Orga_Model_Cell::STATUS_ACTIVE?>';
                        var mainActionLabel = (this.inventoryStatus == '<?=Orga_Model_Cell::STATUS_NOTLAUNCHED?>') ? '<?=___('Orga', 'view', 'inventoryNotLaunchedMainAction')?>' : (this.inventoryStatus == '<?=Orga_Model_Cell::STATUS_ACTIVE?>') ? '<?=___('Orga', 'view', 'inventoryActiveMainAction')?>' : '<?=___('Orga', 'view', 'inventoryClosedMainAction')?>';
                        var otherActionStatus = (this.inventoryStatus == '<?=Orga_Model_Cell::STATUS_NOTLAUNCHED?>') ? '<?=Orga_Model_Cell::STATUS_CLOSED?>' : '<?=Orga_Model_Cell::STATUS_NOTLAUNCHED?>';
                        var otherActionLabel = (this.inventoryStatus == '<?=Orga_Model_Cell::STATUS_NOTLAUNCHED?>') ? '<?=___('Orga', 'view', 'inventoryNotLaunchedOtherAction')?>' : (this.inventoryStatus == '<?=Orga_Model_Cell::STATUS_ACTIVE?>') ? '<?=___('Orga', 'view', 'inventoryActiveOtherAction')?>' : '<?=___('Orga', 'view', 'inventoryClosedOtherAction')?>';
                        inventoryP +=
                                '<div class="btn-group">' +
                                    '<a class="btn btn-default change-inventory-status" href="orga/cell/edit-inventory-status/idCell/' + this.id + '/inventoryStatus/' + mainActionStatus + '/">' +
                                        mainActionLabel +
                                    '</a>' +
                                    '<button class="btn btn-default dropdown-toggle" data-toggle="dropdown">' +
                                        '<span class="caret"></span>' +
                                    '</button>' +
                                    '<ul class="dropdown-menu">' +
                                        '<li>' +
                                            '<a class="change-inventory-status" href="orga/cell/edit-inventory-status/idCell/' + this.id + '/inventoryStatus/' + otherActionStatus + '/">' +
                                                otherActionLabel +
                                            '</a>' +
                                        '</li>' +
                                    '</ul>' +
                                '</div>';
                    }
                    inventoryP +=
                                '<a class="btn btn-default withTooltip" data-toggle="modal" href="#inventoryUsers' + this.id + '" title="<?=___('Orga', 'view', 'viewInventoryUsers')?>">' +
                                    '<i class="fa fa-bullhorn"></i>' +
                                '</a>' +
                            '</div>' +
                            '<div class="inventory-informations withPopover" title="<?=___('Orga', 'view', 'inventoryInputsDetails')?>"' +
                                'data-toggle="tooltip" data-placement="bottom" data-trigger="hover" data-container="body" data-html="true"' +
                                'data-content="' +
                                this.inventoryNotStartedInputsNumber + ' ' +
                                ((this.inventoryNotStartedInputsNumber > 1) ? '<?=___('Orga', 'view', 'inputsNotStartedMany')?>' : '<?=___('Orga', 'view', 'inputsNotStartedSingle')?>') +
                                ' <br> ' +
                                this.inventoryStartedInputsNumber + ' ' +
                                ((this.inventoryStartedInputsNumber > 1) ? '<?=___('Orga', 'view', 'inputsStartedMany')?>' : '<?=___('Orga', 'view', 'inputsStartedSingle')?>') +
                                ' <br> ' +
                                this.inventoryCompletedInputsNumber + ' ' +
                                ((this.inventoryCompletedInputsNumber > 1) ? '<?=___('Orga', 'view', 'inputsCompletedMany')?>' : '<?=___('Orga', 'view', 'inputsCompletedSingle')?>') +
                                '">' +
                                '<div class="inventory-title">' +
                                    this.inventoryStatusTitle +
                                '</div>' +
                                '<div class="inventory-completion">' +
                                    this.inventoryCompletion + '% ' +
                                '</div>' +
                            '</div> ' +
                        '</div>';
                    inventoryPopup +=
                        '<div id="inventoryUsers' + this.id + '" class="modal inventory-users hide fade" data-cell="' + this.id + '">' +
                            '<div class="modal-header">' +
                                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>' +
                                '<h4 class="withTooltip" title="<?=___('Orga', 'view', 'inventoryUsersExplanations')?>">' +
                                    '<?=___('Orga', 'view', 'inventoryUsersFrom')?>' + this.shortLabel + ' ' +
                                    '<i class="fa fa-question-circle"></i>' +
                                '</h4>' +
                            '</div>' +
                            '<div class="modal-body">' +
                            '</div>' +
                        '</div>';
                }
                var inputStatusP = '';
                if (this.showInput) {
                    inputStatusP =
                        '<div class="input-status">' +
                            '<div class="input-actions">' +
                                '<a class="btn btn-default withTooltip" href="orga/cell/input/idCell/' + this.id + '/fromIdCell/<?=$currentCell->id?>/" title="<?=___('Orga', 'view', 'viewInput')?>" target="_blank">' +
                                    '<?=___('Orga', 'view', 'inputLinkDetail')?>' +
                                '</a>' +
                            '</div>' +
                            '<div class="input-title">' +
                                this.inputStatusTitle +
                            '</div>' +
                        '</div>';
                }
                granularity.append(
                    '<div class="col-md-4 well cell" data-tag="' + this.tag + '" data-input-status="' + this.inputStatus + '" data-inventory-status="' + this.inventoryStatus + '">' +
                        '<h4>'+
                            '<small class="btn-group cell-actions">' +
                                usersP +
                                reportsP +
                                exportsP +
                            '</small>' +
                            cellTitle +
                        '</h4>' +
                        inventoryP +
                        inputStatusP +
                        usersPopup +
                        reportsPopup +
                        exportsPopup +
                        inventoryPopup +
                    '</div>'
                );
            });
            $('.withTooltip', granularity).tooltip();
            $('.withPopover', granularity).popover();
            $(granularity.parents('.collapse')).trigger('showCells');
        },
        error: function(jqXHR) {
            granularityInfo[0].className = granularityInfo[0].className.replace(/\bbadge-.*?\b/g, '');
            var response = $.parseJSON(jqXHR.responseText);
            if (typeof(response.typeError) == 'string') {
                granularityInfo.addClass('badge-' + response.typeError);
            } else {
                granularityInfo.addClass('badge-error');
            }
            if (typeof(response.message) == 'string') {
                granularityInfo.html(response.message);
            } else {
                granularityInfo.html('<?=___('UI', 'loading', 'error')?>');
            }
        }
    });
});
$('div.collapse[id^="granularity"]').on('resizeCells', function(e) {
    var granularity = $('.granularity', $(this));

    var maxHeight = 0;

    var maxHeightInventoryActions = 0;
    var maxWidthInventoryActions = 0;
    var maxWidthInventoryInformations = 0;

    var maxHeightInputActions = 0;
    var maxWidthInputActions = 0;
    var maxWidthInputTitle = 0;

    $('.cell', granularity).each(function() {
        var cellTitle = $('h4', $(this));
        cellTitle.css('height', 'auto');
        if (cellTitle.height() > maxHeight) {
            maxHeight = cellTitle.height();
        }

        var inventoryActions = $('.inventory-actions', $(this));
        inventoryActions.css('height', 'auto');
        if (inventoryActions.height() > maxHeightInventoryActions) {
            maxHeightInventoryActions = inventoryActions.height();
        }
        inventoryActions.css('width', 'auto');
        if (inventoryActions.width() > maxWidthInventoryActions) {
            maxWidthInventoryActions = inventoryActions.width();
        }
        var inventoryInformations = $('.inventory-informations', $(this));
        inventoryInformations.css('width', 'auto');
        if (inventoryInformations.width() > maxWidthInventoryInformations) {
            maxWidthInventoryInformations = inventoryInformations.width();
        }

        var inputActions = $('.input-actions', $(this));
        inputActions.css('height', 'auto');
        if (inputActions.height() > maxHeightInputActions) {
            maxHeightInputActions = inputActions.height();
        }
        inputActions.css('width', 'auto');
        if (inputActions.width() > maxWidthInputActions) {
            maxWidthInputActions = inputActions.width();
        }
        var inputTitle = $('.input-title', $(this));
        inputTitle.css('width', 'auto');
        if (inputTitle.width() > maxWidthInputTitle) {
            maxWidthInputTitle = inputTitle.width();
        }
    });
    $('.cell h4', granularity).css('height', maxHeight);

    $('.cell .inventory-actions', granularity).css('height', maxHeightInventoryActions);
    $('.cell .inventory-actions', granularity).css('width', maxWidthInventoryActions);
    $('.cell .inventory-informations', granularity).css('width', maxWidthInventoryInformations);

    $('.cell .input-actions', granularity).css('height', maxHeightInputActions);
    $('.cell .input-actions', granularity).css('width', maxWidthInputActions);
    $('.cell .input-title', granularity).css('width', maxWidthInputTitle);
});

$('.cells-filter button.reset').on('click', function(e) {
    e.preventDefault();
    var form = $(this).parent();
    form.trigger('resetCellsFilter');
});
$('.cells-filter select').on('keyup change', function(e) {
    var collapse = $(this).parents('.collapse');
    collapse.attr('data-first-cell', 0);
    collapse.attr('data-show-cells', 6);
    $('.granularity', collapse).html('');
    collapse.trigger('loadCells');
});
$('.cells-filter').on('resetCellsFilter', function(e) {
    e.preventDefault();
    $('select', $(this)).val('');
    var collapse = $(this).parents('.collapse');
    collapse.attr('data-first-cell', 0);
    collapse.attr('data-show-cells', 6);
    $('.granularity', collapse).html('');
    collapse.trigger('loadCells');
});
$('div.collapse[id^="granularity"]').on('showCells', function(e) {
    var granularity = $('.granularity', $(this));
    $('.display-more-cells', granularity).remove();
    $('.cell', granularity).removeClass('firstRowCell');

    var numberElement = 0;
    $('.cell', granularity).each(function() {
        var cell = $(this);
        if ((numberElement % 3) == 0) {
            cell.addClass('firstRowCell');
        }

        numberElement++;
    });
    $(this).trigger('resizeCells');

    if ($('.cell', granularity).length == 0) {
        granularity.append('<div class="no-cell span"><?=___('Orga', 'view', 'filterNoResult')?></div>');
    }
    if ($('.cell', granularity).length < granularity.attr('data-total-cells')) {
        $(this).attr('data-show-cells', $('.cell', granularity).length);
        $(this).attr('data-first-cell', $(this).attr('data-show-cells'));
        granularity.append(
            '<div class="btn display-more-cells span">' +
                '<?=___('Orga', 'view', 'display-more-cells')?>' +
            '</div>'
        );
    }
});
$('body').on('click', '.display-more-cells', function (e) {
    $(this).parent().parent().attr('data-show-cells', 6);
    $(this).parent().parent().trigger('loadCells');
    $(this).remove();
});

$('body').on('show', '.users', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.modal-body', popup).html(
        '<i class="fa fa-spinner fa-spin fa-3x"></i> <?=___('UI', 'loading', 'loading')?>'
    );
    $.ajax({
        url: 'orga/cell/view-users/idCell/' + popup.attr('data-cell') + '/',
        type: "GET",
        success: function(data) {
            $('.modal-body', popup).html(data);
        },
        error: function(jqXHR) {
            $('.modal-body', popup).html('<?=___('UI', 'loading', 'error')?>');
        }
    });
});
$('body').on('hidden', '.users', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.user-message', popup).remove();
    $('.modal-footer form input[name="userEmail"]', popup).val('');
});
$('body').on('click', '.delete-user', function(e) {
    e.preventDefault();
    if ($(this).attr('data-submitting') === 'true') {
        return false;
    }
    $('.user-message').remove();
    $(this).parent().parent().after(
        '<tr class="info user-message">' +
            '<td colspan="5">' +
                '<?=___('Orga', 'view', 'askConfirmDeleteUser')?>' +
                $(this).parent().prev().prev().html() +
                '<button class="btn btn-primary confirm"><i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?></button>' +
                '<button class="btn close-user-message"><i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?></button>' +
            '</td>' +
        '</tr>'
    );
});
$('body').on('click', 'tr.user-message .confirm', function(e) {
    e.preventDefault();
    var row = $(this).parent().parent();
    var deleteUser = $('.delete-user', row.prev());
    if (deleteUser.attr('data-submitting') === 'true') {
        return false;
    }
    deleteUser.attr('data-submitting', true);
    row.html('<td colspan="5"><i class="fa fa-spinner fa-spin"></i></td>');
    $.ajax({
        url: $('a.delete-user', row.prev()).attr('href'),
        type: "POST",
        success: function(data) {
            row.prev().remove();
            row.removeClass('info');
            row.addClass('success');
            row.html(
                '<td colspan="4">' + data + '</td>' +
                '<td><button class="close close-user-message"><i class="fa fa-times"></i></button></td>'
            );
        },
        error: function(jqXHR) {
            deleteUser.attr('data-submitting', false);
            row.removeClass('info');
            var response = $.parseJSON(jqXHR.responseText);
            if (typeof(response.typeError) == 'string') {
                row.addClass(response.typeError);
            } else {
                row.addClass('error');
            }
            if (typeof(response.message) == 'string') {
                row.html(
                    '<td colspan="4">' + response.message + '</td>' +
                    '<td><button class="close close-user-message"><i class="fa fa-times"></i></button></td>'
                );
            } else {
                row.html(
                    '<td colspan="4"><?=___('Core', 'exception', 'applicationError')?></td>' +
                    '<td><button class="close close-user-message"><i class="fa fa-times"></i></button></td>'
                );
            }
        }
    });
});
$('body').on('click', 'tr.user-message .close-user-message', function(e) {
    e.preventDefault();
    $(this).parent().parent().remove();
});
$('body').on('submit', '.addUser', function(e) {
    e.preventDefault();
    var form = $(this);
    if (form.attr('data-submitting') === 'true') {
        return false;
    }
    form.attr('data-submitting', true);
    $('.user-message').remove();
    form.before('<div class="user-message alert alert-info"><i class="fa fa-spinner fa-spin"></i></div>')
    $.ajax({
        url: form.attr('action'),
        type: "POST",
        data: form.serialize(),
        success: function(data) {
            form.prev().removeClass('alert-info');
            form.prev().addClass('alert-success');
            form.prev().html(data);
            form.parent().parent().trigger('show');
            form.attr('data-submitting', false);
        },
        error: function(jqXHR) {
            form.prev().removeClass('alert-info');
            var response = $.parseJSON(jqXHR.responseText);
            if (typeof(response.typeError) == 'string') {
                form.prev().addClass('alert-' + response.typeError);
            } else {
                form.prev().addClass('alert-error');
            }
            if (typeof(response.message) == 'string') {
                form.prev().html(response.message);
            } else {
                form.prev().html('<?=___('Core', 'exception', 'applicationError')?>');
            }
            form.attr('data-submitting', false);
        }
    });
});

$('body').on('show', '.reports', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.modal-body', popup).html(
        '<i class="fa fa-spinner fa-spin fa-3x"></i> <?=___('UI', 'loading', 'loading')?>'
    );
    $.ajax({
        url: 'orga/cell/view-reports/idCell/' + popup.attr('data-cell') + '/fromIdCell/<?=$currentCell->id?>/',
        type: "GET",
        success: function(data) {
            $('.modal-body', popup).html(data);
        },
        error: function(jqXHR) {
            $('.modal-body', popup).html('<?=___('UI', 'loading', 'error')?>');
        }
    });
});
$('body').on('hidden', '.reports', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.report-message', popup).remove();
});
$('body').on('click', '.delete-report', function(e) {
    e.preventDefault();
    if ($(this).attr('data-submitting') === 'true') {
        return false;
    }
    $('.report-message').remove();
    $(this).parent().parent().after(
        '<tr class="info report-message">' +
            '<td colspan="3">' +
                '<?=___('Orga', 'view', 'askConfirmDeleteReport')?>' +
                $('a', $(this).parent().prev().prev()).html() +
                '<button class="btn btn-primary confirm"><i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?></button>' +
                '<button class="btn close-report-message"><i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?></button>' +
            '</td>' +
        '</tr>'
    );
});
$('body').on('click', 'tr.report-message .confirm', function(e) {
    e.preventDefault();
    var row = $(this).parent().parent();
    var deleteReport = $('.delete-report', row.prev());
    if (deleteReport.attr('data-submitting') === 'true') {
        return false;
    }
    deleteReport.attr('data-submitting', true);
    row.html('<td colspan="3"><i class="fa fa-spinner fa-spin"></i></td>');
    $.ajax({
        url: $('a.delete-report', row.prev()).attr('href'),
        type: "POST",
        success: function(data) {
            row.prev().remove();
            row.removeClass('info');
            row.addClass('success');
            row.html(
                '<td colspan="2">' + data + '</td>' +
                '<td><button class="close close-report-message"><i class="fa fa-times"></i></button></td>'
            );
        },
        error: function(jqXHR) {
            deleteReport.attr('data-submitting', false);
            row.removeClass('info');
            var response = $.parseJSON(jqXHR.responseText);
            if (typeof(response.typeError) == 'string') {
                row.addClass(response.typeError);
            } else {
                row.addClass('error');
            }
            if (typeof(response.message) == 'string') {
                row.html(
                    '<td colspan="2">' + response.message + '</td>' +
                    '<td><button class="close close-report-message"><i class="fa fa-times"></i></button></td>'
                );
            } else {
                row.html(
                    '<td colspan="2"><?=___('Core', 'exception', 'applicationError')?></td>' +
                    '<td><button class="close close-report-message"><i class="fa fa-times"></i></button></td>'
                );
            }
        }
    });
});
$('body').on('click', 'tr.report-message .close-report-message', function(e) {
    e.preventDefault();
    $(this).parent().parent().remove();
});
$('body').on('keyup change', 'select[name="reportType"]', function(e) {
    var select = $(this);
    var reportsList = $('tbody', select.parent().parent().parent().parent().parent());
    $('tr', reportsList).addClass('hide');

    var selectValue = select.val();
    var selector = '';
    if (selectValue != '') {
        selector += '[data-report-type="' + select.val() + '"]';
        if (selectValue == 'userReport') {
            selector += '[data-report-owner="' + select.find(":selected").attr('data-user') + '"]';
        }
    }
    $('tr' + selector, reportsList).removeClass('hide');
});

$('body').on('click', '.inventory-status .inventory-actions a.change-inventory-status', function(e) {
    e.preventDefault();
    var link = $(this);
    var buttonGroup = link.parents('.btn-group');
    var mainButton = $('> a.change-inventory-status', buttonGroup);
    var otherButton = $('> ul li a.change-inventory-status', buttonGroup);
    $('.inventory-status-message', buttonGroup).remove();
    buttonGroup.prepend('<button class="btn btn-default inventory-status-message"></button>');
    var loadingButton = $('.inventory-status-message', buttonGroup);
    loadingButton.html('<i class="fa fa-spinner fa-spin"></i>');
    mainButton.addClass('hide');
    $('> button.dropdown-toggle', buttonGroup).addClass('hide');
    $.ajax({
        url: link.attr('href'),
        type: "POST",
        success: function (data) {
            buttonGroup.parents('.cell').attr('data-inventory-status', data.status);
            $('.inventory-title', buttonGroup.parents('div.cell')).html(data.label);
            mainButton.html(data.mainActionLabel);
            mainButton.attr('href', mainButton.attr('href').replace(/inventoryStatus\/[a-zA-Z]+/, 'inventoryStatus/' + data.mainActionStatus));
            otherButton.html(data.otherActionLabel);
            otherButton.attr('href', otherButton.attr('href').replace(/inventoryStatus\/[a-zA-Z]+/, 'inventoryStatus/' + data.otherActionStatus));
            var collapse = buttonGroup.parents('.collapse[data-inventory]');
            $('.collapse[data-inventory]').attr('data-first-cell', 0);
            $('.collapse[data-inventory] .granularity').html('');
            $('.collapse[data-inventory]').trigger('loadCells');
            $('button.dropdown-toggle', buttonGroup).removeClass('hide');
            loadingButton.remove();
        },
        error: function (jqXHR) {
            var response = $.parseJSON(jqXHR.responseText);
            if ((typeof(response.typeError) == 'string') && (response.typeError != 'error')) {
                loadingButton.addClass('btn-' + response.typeError);
            } else {
                loadingButton.addClass('btn-danger');
            }
            if (typeof(response.message) == 'string') {
                loadingButton.html(response.message);
            } else {
                loadingButton.html('<?=___('Core', 'exception', 'applicationError')?>');
            }
        },
        complete: function () {
            mainButton.removeClass('hide');
            $('button.dropdown-toggle', buttonGroup).removeClass('hide');
            buttonGroup.parents('div.collapse[id^="granularity"]').trigger('resizeCells');
        }
    });
});
$('body').on('click', '.inventory-status .inventory-actions .inventory-status-message', function(e) {
    $(this).remove();
});
$('body').on('click', 'a.inventory-inputs-details', function(e) {
    e.preventDefault();
});
$('body').on('show', '.inventory-users', function(e) {
    if (e.target != this) {
        return;
    }
    var popup = $(this);
    $('.modal-body', popup).html(
        '<i class="fa fa-spinner fa-spin fa-3x"></i> <?=___('UI', 'loading', 'loading')?>'
    );
    $.ajax({
        url: 'orga/cell/view-inventory-users/idCell/' + popup.attr('data-cell') + '/',
        type: "GET",
        success: function(data) {
            $('.modal-body', popup).html(data);
        },
        error: function(jqXHR) {
            $('.modal-body', popup).html('<?=___('UI', 'loading', 'error')?>');
        }
    });
});

$('.collapse').on({
    shown: function(e) {
        if (e.target == this) {
            $(this).css('overflow','visible');
        }
    },
    hide: function(e) {
        if (e.target == this) {
            $(this).css('overflow','hidden');
        }
    }
});

$(document).ready(function() {
    $('.withTooltip').tooltip();
    $('.withPopover').popover();
    <?php if ($currentCell->showInventory) : ?>
    $('.current-cell .inventory-status').on('mouseenter', function() {
        $('.current-cell .inventory-status .inventory-informations').popover('show');
    });
    $('.current-cell .inventory-status').on('mouseleave', function() {
        $('.current-cell .inventory-status .inventory-informations').popover('hide');
    });
    <?php endif; ?>
    var resizeTimer;
    $(window).resize(function() {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(function() { $('div.collapse[id^="granularity"]').trigger('resizeCells'); }, 500);
    });
    $('.history > h3 a').trigger('click');
    $('.comments > h3 a').trigger('click');
    $('div.collapse[id^="granularity"]').on('show',
        function(e) {
            if ((e.target != this) || ($('.granularity', $(this)).html() != '')) {
                return;
            }
            $(this).attr('data-first-cell', 0);
            $(this).trigger('loadCells');
            $('.granularity', $(this)).html('');
        }
    );
    $('div.collapse[id^="granularity"].in').trigger('loadCells');
});
</script>

<?= $this->tutorial('orga'); ?>
