<?php
use MyCLabs\MUIH\Tab;
use MyCLabs\MUIH\Tabs;
?>
<div class="page-header">
    <h1><?=__('Social', 'contact', 'contacts')?></h1>
</div>

<?php
UI_Datagrid::addHeader();


$tabView = new Tabs();

$tabUser = new Tab('contactsContainer_usersTab');
$tabUser->setTitle(__('User', 'user', 'users'));
$tabUser->setContent($this->partial('message/contacts/users.phtml', 'social'));
$tabUser->active();
$tabView->addTab($tabUser);

$tabUserGroup = new Tab('contactsContainer_userGroupsTab');
$tabUserGroup->setTitle(__('Social', 'userGroup', 'userGroups'));
$tabUserGroup->setContent($this->partial('message/contacts/user-groups.phtml', 'social'));
$tabView->addTab($tabUserGroup);

$tabView->display();
