<div class="page-header">
    <h1><?=__('Social', 'name', 'messages')?></h1>
</div>

<?php
UI_Datagrid::addHeader();

$tabs = new UI_Tab_View('messageContainer');

$tabInbox = new UI_Tab('inbox');
$tabInbox->label = __('Social', 'message', 'inbox');
$tabInbox->dataSource = $this->baseUrl('social/message/list-inbox');
$tabInbox->useCache = true;
$tabInbox->active = true;
$tabs->addTab($tabInbox);

$tabOutbox = new UI_Tab('outbox');
$tabOutbox->label = __('Social', 'message', 'outbox');
$tabOutbox->dataSource = $this->baseUrl('social/message/list-outbox');
$tabOutbox->useCache = true;
$tabs->addTab($tabOutbox);

$tabs->display();
