<?php
use MyCLabs\MUIH\Tab;
use MyCLabs\MUIH\Tabs;
?>
<div class="page-header">
    <h1><?=__('Social', 'name', 'messages')?></h1>
</div>

<?php
UI_Datagrid::addHeader();

$tabs = new Tabs();

$tabInbox = new Tab('messageContainer_inbox');
$tabInbox->setTitle(__('Social', 'message', 'inbox'));
$tabInbox->setContent($this->baseUrl('social/message/list-inbox'));
$tabInbox->setAjax(true, true);
$tabs->addTab($tabInbox);

$tabOutbox = new Tab('messageContainer_outbox');
$tabOutbox->setTitle(__('Social', 'message', 'outbox'));
$tabOutbox->setContent($this->baseUrl('social/message/list-outbox'));
$tabOutbox->setAjax(true, true);
$tabs->addTab($tabOutbox);

$tabs->activeTab($tabInbox);
$tabs->display();
