<?php
use MyCLabs\MUIH\Button;
use MyCLabs\MUIH\GenericTag;

$closeButton = new Button(__('UI', 'verb', 'close'), Button::TYPE_PRIMARY);
$closeButton->setAttribute('data-dismiss', 'modal');

$datagrid = new UI_Datagrid('inbox', 'datagrid_message_inbox', 'social');
$datagrid->pagination = true;

// Auteur
$columnAuthor = new UI_Datagrid_Col_Text('author', __('Social', 'message', 'sender'));
$datagrid->addCol($columnAuthor);

// Objet
$columnObject = new UI_Datagrid_Col_Popup('message', __('Social', 'message', 'message'));
$columnObject->editable = false;
$columnObject->popup->setHeaderContent(new GenericTag('h4', __('Social', 'message', 'inboxDetailMessagePopupTitle')));
$columnObject->popup->setFooterContent($closeButton->render());
$datagrid->addCol($columnObject);

// Destinataire
$columnRecipient = new UI_Datagrid_Col_Popup('recipient', __('Social', 'message', 'recipient'));
$columnRecipient->editable = false;
$columnRecipient->popup->setFooterContent($closeButton->render());
$datagrid->addCol($columnRecipient);

// Date
$columnDate = new UI_Datagrid_Col_Date('date', __('Social', 'message', 'dispatchDate'));
$columnDate->editable = false;
$datagrid->addCol($columnDate);

echo $datagrid->render();
