<?php
$closeButton = new UI_HTML_Button(__('UI', 'verb', 'close'));
$closeButton->addAttribute('class', 'btn-primary');
$closeButton->addAttribute('data-dismiss', 'modal');

$datagrid = new UI_Datagrid('outbox', 'datagrid_message_outbox', 'social');
$datagrid->pagination = true;

// Auteur
$columnAuthor = new UI_Datagrid_Col_Text('author', __('Social', 'message', 'sender'));
$datagrid->addCol($columnAuthor);

// Objet
$columnObject = new UI_Datagrid_Col_Popup('message', __('Social', 'name', 'message'));
$columnObject->editable = false;
$columnObject->popup->title = __('Social', 'message', 'outboxDetailMessagePopupTitle');
$columnObject->popup->footer = $closeButton->render();
$datagrid->addCol($columnObject);

// Destinataire
$columnRecipient = new UI_Datagrid_Col_Popup('recipient', __('Social', 'message', 'recipient'));
$columnRecipient->editable = false;
$columnRecipient->popup->title = __('UI', 'name', 'informations');
$columnRecipient->popup->footer = $closeButton->render();
$datagrid->addCol($columnRecipient);

// Date
$columnDate = new UI_Datagrid_Col_Date('date', __('Social', 'message', 'dispatchDate'));
$columnDate->editable = false;
$datagrid->addCol($columnDate);

echo $datagrid->render();
