<div class="page-header">
    <h1><?=__('Social', 'message', 'newMessage')?></h1>
</div>

<?php
/** @var $recipient User_Model_User|Social_Model_UserGroup */
$recipient = $this->recipient;

$form = new UI_Form('newMessage');
$form->setAction('social/message/new');
$form->setAjax(true, 'sendMessageSuccess');

$recipientField = new UI_Form_Element_HTML('recipient');
$recipientField->setLabel(__('Social', 'message', 'to'));
if ($recipient instanceof User_Model_User) {
    $recipientField->content = $recipient->getName();
} elseif ($recipient instanceof Social_Model_UserGroup) {
    $recipientField->content = $recipient->getLabel();
}
$form->addElement($recipientField);

$recipientIdField = new UI_Form_Element_Hidden('recipientId');
$recipientIdField->setValue($recipient->getId());
$form->addElement($recipientIdField);
$recipientTypeField = new UI_Form_Element_Hidden('recipientType');
if ($recipient instanceof User_Model_User) {
    $recipientTypeField->setValue('user');
} elseif ($recipient instanceof Social_Model_UserGroup) {
    $recipientTypeField->setValue('usergroup');
}
$form->addElement($recipientTypeField);

$titleField = new UI_Form_Element_Text('title');
$titleField->setLabel(__('Social', 'message', 'object'));
$form->addElement($titleField);

$contentField = new UI_Form_Element_Textarea('content');
$contentField->setLabel(__('Social', 'message', 'body'));
$contentField->setAttrib('rows', '20');
$contentField->setAttrib('cols', '100%');
$form->addElement($contentField);

$buttonSave = new UI_Form_Element_Submit(__('Social', 'message', 'send'));
$form->addActionElement($buttonSave);

$buttonCancel = new UI_HTML_Button(__('UI', 'verb', 'cancel'));
$buttonCancel->addAttribute('class', "cancel");
$button = new UI_Form_Element_HTML('button');
$button->content = $buttonCancel->render();
$form->addActionElement($button);

$form->display();
?>

<script>
    $.fn.sendMessageSuccess = function() {
        window.location = "<?=$this->baseUrl()?>/social/message/list";
    };
    $(".cancel").click(function() {
        history.back();
    });
</script>
