<?php
/** @var $message Social_Model_Message */
$message = $this->message;

$recipient = null;
$userRecipients = $message->getUserRecipients();
if (count($userRecipients) > 0) {
    $recipient = $userRecipients[0];
} else {
    $groupRecipients = $message->getGroupRecipients();
    if (count($groupRecipients) > 0) {
        $recipient = $groupRecipients[0];
    }
}

if ($recipient instanceof Social_Model_UserGroup) {
    $recipientName = $recipient->getLabel();
} else {
    if ($recipient === $this->user) {
        $recipientName = __('Social', 'message', 'me');
    } else {
        $recipientName = $recipient->getName();
    }
}

$author = $message->getAuthor();
if ($author === $this->user) {
    $authorName = __('Social', 'message', 'me');
} else {
    $authorName = $author->getName();
}
?>

<dl class="dl-horizontal">
    <dt><?=__('Social', 'message', 'from')?></dt>
    <dd><?=$authorName?></dd>
    <dt><?=__('Social', 'message', 'to')?></dt>
    <dd><?=$recipientName?></dd>
    <dt><?=__('UI', 'name', 'date')?></dt>
    <dd><?=$message->getCreationDate()->format('d M Y - H:m')?></dd>
</dl>

<div class="well well-sm">
    <h4><?=$message->getTitle()?></h4>
    <hr>
    <?=Core_Tools::textile($message->getText())?>
</div>
