<?php
/**
 * @author valentin.claras
 * @package Orga
 * Traduction des Axis
 */
?>
    <div class="page-header">
        <h1><?=___('Orga', 'translate', 'organizationalAxes')?> <small><?=___('UI', 'name', 'translations')?></small></h1>
    </div>
<?php
echo $this->translateDatagrid('Orga_Model_Axis', 'label', 'datagrid_translate_axes', 'orga')->simple()->addParam('idOrganization', $this->idOrganization);
