<?php
/**
 * @author valentin.claras
 * @package Orga
 * Traduction des Report
 */
?>
    <div class="page-header">
        <h1><?=___('Orga', 'translate', 'granularityReports')?> <small><?=___('UI', 'name', 'translations')?></small></h1>
    </div>
<?php
foreach ($this->granularities as $granularity) {
    /** @var $granularity Orga_Model_Granularity */
    if ($granularity->getCellsGenerateDWCubes()) {

        $datagrid = new UI_Datagrid('datagridTranslate_DW_Model_Report_label_'.$granularity->getId(), 'datagrid_translate_granularityreports', 'orga');
        $datagrid->automaticFiltering = false;

        $identifierColumn = new UI_Datagrid_Col_Text('identifier', ___('UI', 'name', 'identifier'));
        $identifierColumn->editable = false;
        $datagrid->addCol($identifierColumn);

        foreach (\Core\ContainerSingleton::getContainer()->get('translation.languages') as $language) {
            $languageColumn = new UI_Datagrid_Col_Text($language, ___('UI', 'translate', 'language' . $language));
            $languageColumn->editable = true;
            $datagrid->addCol($languageColumn);
        }

        $datagrid->addParam('idOrganization', $this->idOrganization);
        $datagrid->addParam('refGranularity', $granularity->getRef());
        $datagrid->initialLoading = false;

        echo $this->collapse('translateGranularityReports'.$granularity->getId(), $granularity->getLabel(), $datagrid->getHTML())->collapsed();

        $script = '';
        $script .= '$(\'#translateGranularityReports'.$granularity->getId().'\').on(\'show\', function(e) {';
        $script .= 'if ($(e.target).attr(\'id\') == \'translateGranularityReports'.$granularity->getId().'_wrapper\') {';
        $script .= 'datagridTranslate_DW_Model_Report_label_'.$granularity->getId().'.filter();';
        $script .= '}';
        $script .= '});';

        UI_Datagrid::addHeader($datagrid);
        $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');

    }
}
