<?php
/**
 * @author valentin.claras
 * @package Orga
 * Traduction des Member
 */
?>
    <div class="page-header">
        <h1><?=___('Orga', 'translate', 'organizationalMembers')?> <small><?=___('UI', 'name', 'translations')?></small></h1>
    </div>
<?php
foreach ($this->axes as $axis) {
    /** @var $axis Orga_Model_Axis */

    $datagrid = new UI_Datagrid('datagridTranslate_Orga_Model_Member_label_'.$axis->getRef(), 'datagrid_translate_members', 'orga');
    $datagrid->automaticFiltering = false;

    $identifierColumn = new UI_Datagrid_Col_Text('identifier', ___('UI', 'name', 'identifier'));
    $identifierColumn->editable = false;
    $datagrid->addCol($identifierColumn);

    foreach (\Core\ContainerSingleton::getContainer()->get('translation.languages') as $language) {
        $languageColumn = new UI_Datagrid_Col_Text($language, ___('UI', 'translate', 'language' . $language));
        $languageColumn->editable = true;
        $datagrid->addCol($languageColumn);
    }

    $datagrid->addParam('idOrganization', $this->idOrganization);
    $datagrid->addParam('refAxis', $axis->getRef());
    $datagrid->initialLoading = false;

    echo $this->collapse('translateMembers'.$axis->getRef(), $axis->getLabel(), $datagrid->getHTML());

    $script = '';
    $script .= '$(\'#translateMembers'.$axis->getRef().'\').on(\'show.bs.collapse\', function(e) {';
    $script .= 'if ($(e.target).attr(\'id\') == \'translateMembers'.$axis->getRef().'\') {';
    $script .= 'datagridTranslate_Orga_Model_Member_label_'.$axis->getRef().'.filter();';
    $script .= '}';
    $script .= '});';

    UI_Datagrid::addHeader($datagrid);
    $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
}
