<?php
/**
 * @author valentin.claras
 * @package Inventory
 * Traduction des Organization
 */
?>
    <div class="page-header">
        <h1><?=___('Orga', 'organization', 'organizations')?> <small><?=___('UI', 'name', 'translations')?></small></h1>
    </div>
<?php
echo $this->translateDatagrid('Orga_Model_Organization', 'label', 'datagrid_translate_organizations', 'orga')->simple()
    ->addCol(new UI_Datagrid_Col_Link('axes', ___('UI', 'name', 'axes')))
    ->addCol(new UI_Datagrid_Col_Link('members', ___('UI', 'name', 'elements')))
    ->addCol(new UI_Datagrid_Col_Link('granularityReports', ___('Orga', 'translate', 'granularityReports')));