<?php
/**
 * @author valentin.claras
 * @package Orga
 * Traduction des Project
 */
?>
    <div class="page-header">
        <h1><?=__('Orga', 'project', 'translate')?></h1>
    </div>
<?php
echo $this->translateDatagrid('Orga_Model_Project', 'label', 'datagrid_translate_projects', 'orga')->simple()
    ->addCol(new UI_Datagrid_Col_Link('axes', __('Orga', 'axis', 'translate')))
    ->addCol(new UI_Datagrid_Col_Link('members', __('Orga', 'member', 'translate')));