<?php
/** @var $family Parameter\Domain\Family\Family */
$family = $this->family;
?>
<form id="editFamily" class="form-horizontal" method="post"
      action="parameter/form_edit-family/submit?id=<?=$family->getId()?>">
    <div class="form-group">
        <label for="inputLabel" class="col-sm-2 control-label">
            <?=__('UI', 'name', 'label')?>
        </label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputLabel" name="label"
                   value="<?=$this->translate($family->getLabel())?>">
        </div>
    </div>
    <div class="form-group">
        <label for="inputRef" class="col-sm-2 control-label">
            <?=__('UI', 'name', 'identifier')?>
        </label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputRef" name="ref" value="<?=$family->getRef()?>">
        </div>
    </div>
    <div class="form-group">
        <label for="inputUnit" class="col-sm-2 control-label">
            <?=__('Unit', 'name', 'unit')?>
        </label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputUnit" name="unit"
                   value="<?=$family->getUnit()->getRef()?>">
        </div>
    </div>
    <div class="form-group">
        <label for="inputDocumentation" class="col-sm-2 control-label">
            <?=__('UI', 'name', 'documentation')?>
        </label>
        <div class="col-sm-10">
            <textarea class="form-control" id="inputDocumentation" name="documentation"
                      rows="4"><?=$this->translate($family->getDocumentation())?></textarea>
        </div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            <?=__('UI', 'verb', 'save')?>
        </button>
        <button type="button" id="deleteFamily" class="btn btn-danger">
            <?=__('Parameter', 'familyDetail', 'deleteButtonLabel')?>
        </button>
    </div>
</form>

<script>
    $(function() {
        new AjaxForm('#editFamily');

        $('#deleteFamily').confirm({
            text: <?=json_encode(__('Parameter', 'familyDetail', 'deleteConfirm'))?>,
            confirm: function () {
                var url = "<?=$this->baseUrl('parameter/family/delete')?>";

                $.post(url, {id: <?=$family->getId()?>}, function() {
                    window.location = "<?= $this->baseUrl('parameter/library/view/id/' . $family->getLibrary()->getId()) ?>";
                })
                .error(errorHandler);
            },
            confirmButton: <?=json_encode(__('UI', 'verb', 'delete'))?>,
            cancelButton: <?=json_encode(__('UI', 'verb', 'cancel'))?>,
            post: true
        });
    });
</script>
