<?php

use Parameter\Application\Form\EditFamilyForm;
use Parameter\Domain\Family\Family;

/** @var $family Family */
$family = $this->family;

// Delete button
$deleteButton = new UI_HTML_Button(__('Parameter', 'familyDetail', 'deleteButtonLabel'));
$deleteButton->id = "deleteFamily";
$deleteButton->addAttribute('class', 'btn-danger');

// Edit form
$editFamilyForm = new EditFamilyForm('editFamily', $family);
$deleteElement = new UI_Form_Element_HTML('deleteElement', $deleteButton->render());
$editFamilyForm->addActionElement($deleteElement);

echo $editFamilyForm->render();
?>

<script>
    $(function() {
        $('#deleteFamily').confirm({
            text: <?=json_encode(__('Parameter', 'familyDetail', 'deleteConfirm'))?>,
            confirm: function(button) {
                var url = "<?=$this->baseUrl('parameter/family/delete')?>";

                $.post(url, {id: <?=$family->getId()?>}, function() {
                    window.location = "<?=$this->baseUrl('parameter/family/tree-edit')?>";
                })
                    .error(errorHandler);
            },
            confirmButton: <?=json_encode(__('UI', 'verb', 'delete'))?>,
            cancelButton: <?=json_encode(__('UI', 'verb', 'cancel'))?>,
            post: true
        });
    });
</script>
