<?php
// Liste des Project.
?>
<div class="page-header">
    <h1>
        <?=__('Orga', 'name', 'organizations')?>
    </h1>
</div>

<?php
$datagridProject = new UI_Datagrid('listProjects', 'datagrid_project', 'inventory');

$columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$columnLabel->addable = true;
$columnLabel->editable = true;
$datagridProject->addCol($columnLabel);

$columnOrgaGranularityForInventoryStatus = new UI_Datagrid_Col_List('orgaGranularityForInventoryStatus', __('Inventory', 'projectList', 'orgaGranularityForInventoryStatus'));
$columnOrgaGranularityForInventoryStatus->list = 'inventory/datagrid_project/getlistgranularities';
$columnOrgaGranularityForInventoryStatus->dynamicList = true;
$columnOrgaGranularityForInventoryStatus->editable = $this->isConnectedUserAbleToEditProjects;
$columnOrgaGranularityForInventoryStatus->addable = false;
$datagridProject->addCol($columnOrgaGranularityForInventoryStatus);

if ($this->isConnectedUserAbleToEditProjects) {
    $columnResetDWCubesAndDatasUpToDate = new UI_Datagrid_Col_Popup('resetDWCubesAndDatasUpToDate', __('Inventory', 'projectList', 'statusRebuildHeader'));
    $columnResetDWCubesAndDatasUpToDate->popup->title = __('Inventory', 'projectList', 'statusRebuildPopupTitle');
    $datagridProject->addCol($columnResetDWCubesAndDatasUpToDate);
}

$columnDetails = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$columnDetails->addable = false;
$datagridProject->addCol($columnDetails);

//$datagridProject->deleteElements = $this->isConnectedUserAbleToDeleteProjects;
$datagridProject->pagination = false;
$datagridProject->addElements = $this->isConnectedUserAbleToCreateProjects;
$datagridProject->addPanelTitle = __('Inventory', 'projectList', 'addPanelTitle');

$datagridProject->display();