<?php
use AF\Domain\AF\AF;

/**
 * @author  matthieu.napoli
 * @package AF
 */
/** @var $af AF */
$af = $this->af;

$datagrid = new UI_Datagrid('conditionsExpression', 'datagrid_edit_conditions_expression', 'af');
$datagrid->initialLoading = false;
$datagrid->addParam('id', $af->getId());
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('AF', 'configInteractionDatagrid', 'composedConditionAddPanelTitle');
$datagrid->deleteElements = true;

// Identifiant
$refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$refColumn->editable = true;
$datagrid->addCol($refColumn);

// Expression
$expressionColumn = new UI_Datagrid_Col_LongText('expression', __('TEC', 'name', 'expression'));
$expressionColumn->editable = true;
$expressionColumn->textileEditor = false;
$expressionColumn->popup->addAttribute('class', 'large');
$expressionColumn->popup->title = __('TEC', 'name', 'expression');
$datagrid->addCol($expressionColumn);

echo $datagrid->render();
