<?php
use AF\Domain\Component\Select\SelectMulti;
use AF\Domain\Component\Select\SelectSingle;
use AF\Domain\Condition\ElementaryCondition;
use AF\Domain\Condition\NumericFieldCondition;
use AF\Domain\Condition\CheckboxCondition;
use AF\Domain\Condition\Select\SelectSingleCondition;
use AF\Domain\Condition\Select\SelectMultiCondition;

/** @var $condition ElementaryCondition */
$condition = $this->condition;
$af = $condition->getAf();

$locale = Core_Locale::loadDefault();

$allRelations = [
    ElementaryCondition::RELATION_EQUAL     => __('AF', 'configInteractionDatagrid', 'equalOption'),
    ElementaryCondition::RELATION_NEQUAL    => __('AF', 'configInteractionDatagrid', 'differentOption'),
    ElementaryCondition::RELATION_GT        => __('AF', 'configInteractionDatagrid', 'greaterOption'),
    ElementaryCondition::RELATION_LT        => __('AF', 'configInteractionDatagrid', 'lowerOption'),
    ElementaryCondition::RELATION_GE        => __('AF', 'configInteractionDatagrid', 'greaterOrEqualOption'),
    ElementaryCondition::RELATION_LE        => __('AF', 'configInteractionDatagrid', 'lowerOrEqualOption'),
    ElementaryCondition::RELATION_CONTAINS  => __('AF', 'configInteractionDatagrid', 'containsOption'),
    ElementaryCondition::RELATION_NCONTAINS => __('AF', 'configInteractionDatagrid', 'doesNotContainOption'),
]
?>

<form class="form-horizontal" method="post"
      action="af/edit_conditions/update-condition-submit?idAF=<?=$af->getId()?>&idCondition=<?=$condition->getId()?>">

    <?php if ($condition instanceof NumericFieldCondition) : ?>
        <?php
        /** @var $condition NumericFieldCondition */
        $relations = [];
        $relations[ElementaryCondition::RELATION_EQUAL] = $allRelations[ElementaryCondition::RELATION_EQUAL];
        $relations[ElementaryCondition::RELATION_NEQUAL] = $allRelations[ElementaryCondition::RELATION_NEQUAL];
        $relations[ElementaryCondition::RELATION_GT] = $allRelations[ElementaryCondition::RELATION_GT];
        $relations[ElementaryCondition::RELATION_LT] = $allRelations[ElementaryCondition::RELATION_LT];
        $relations[ElementaryCondition::RELATION_GE] = $allRelations[ElementaryCondition::RELATION_GE];
        $relations[ElementaryCondition::RELATION_LE] = $allRelations[ElementaryCondition::RELATION_LE];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                                <?=$condition->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <input name="value" type="text" class="form-control"
                       value="<?=$locale->formatNumberForInput($condition->getValue())?>">
            </div>
        </div>
    <?php endif; ?>


    <?php if ($condition instanceof CheckboxCondition) : ?>
        <?php
        /** @var $condition CheckboxCondition */
        $relations = [];
        $relations[ElementaryCondition::RELATION_EQUAL] = $allRelations[ElementaryCondition::RELATION_EQUAL];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                            <?=$condition->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <select name="value" class="form-control">
                    <option value="1" <?=$condition->getValue() ? 'selected' : ''?>>
                        <?=__('UI', 'property', 'checked')?>
                    </option>
                    <option value="0" <?=!$condition->getValue() ? 'selected' : ''?>>
                        <?=__('UI', 'property', 'unchecked')?>
                    </option>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <?php if ($condition instanceof SelectSingleCondition) : ?>
        <?php
        /** @var $condition SelectSingleCondition */
        $relations = [];
        $relations[ElementaryCondition::RELATION_EQUAL] = $allRelations[ElementaryCondition::RELATION_EQUAL];
        $relations[ElementaryCondition::RELATION_NEQUAL] = $allRelations[ElementaryCondition::RELATION_NEQUAL];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                            <?=$condition->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <select name="value" class="form-control">
                    <?php
                    /** @var $selectComponent SelectSingle */
                    $selectComponent = $condition->getField();
                    $selected = $condition->getOption() ? $condition->getOption()->getId() : null;
                    ?>
                    <option value="" <?=$selected == null ? 'selected' : ''?>></option>
                    <?php foreach ($selectComponent->getOptions() as $option) : ?>
                        <option value="<?=$option->getId()?>"
                                <?=$option->getId() == $selected ? 'selected' : ''?>>
                            <?=$option->getLabel()?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <?php if ($condition instanceof SelectMultiCondition) : ?>
        <?php
        /** @var $condition SelectSingleCondition */
        $relations = [];
        $relations[ElementaryCondition::RELATION_CONTAINS] = $allRelations[ElementaryCondition::RELATION_CONTAINS];
        $relations[ElementaryCondition::RELATION_NCONTAINS] = $allRelations[ElementaryCondition::RELATION_NCONTAINS];
        ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'relation')?>
            </label>
            <div class="col-sm-10">
                <select name="relation" class="form-control">
                    <?php foreach ($relations as $relation => $label) : ?>
                        <option value="<?=$relation?>"
                            <?=$condition->getRelation() == $relation ? 'selected' : ''?>>
                            <?=$label?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">
                <?=__('UI', 'name', 'referenceValue')?>
            </label>
            <div class="col-sm-10">
                <select name="value" class="form-control">
                    <?php
                    /** @var $selectComponent SelectMulti */
                    $selectComponent = $condition->getField();
                    $selected = $condition->getOption() ? $condition->getOption()->getId() : null;
                    ?>
                    <option value="" <?=$selected == null ? 'selected' : ''?>></option>
                    <?php foreach ($selectComponent->getOptions() as $option) : ?>
                        <option value="<?=$option->getId()?>"
                            <?=$option->getId() == $selected ? 'selected' : ''?>>
                            <?=$option->getLabel()?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary"><?=__('UI', 'verb', 'save')?></button>
        </div>
    </div>

</form>
