<?php
/**
 * @author valentin.claras
 * @author cyril.perraud
 * @package Simulation
 * @subpackage View
 */
if (!$this->isSetDWCubeUpToDate) {
?>
<div id="dWCubeNotUpToDate">
    <p>
        <span class="label label-warning"><?=__('UI', 'message', 'titleWarning') ?></span>
        <?=__('DW', 'rebuild', 'analysisTabRebuildAlert') ?>
        <?=__('DW', 'rebuild', 'analysisDataRebuildWarningMessageSimulation') ?>
    </p>
    <?= $this->button(__('DW', 'rebuild', 'analysisDataRebuildButton'), 'refresh icon-white', array('id' => 'resetDWCube', 'class' => 'btn-primary')) ?>
    <script type="text/javascript">
        $('#resetDWCube').click(function() {
            setMask(true);
            $.post(
                'simulation/set/resetdw/idSet/<?=$this->idSet?>',
                function(data, textStatus, jqXHR){
                    setMask(false);
                    addMessage(data.message, 'success');
                    $('#dWCubeNotUpToDate').remove();
                }
            ).error(
                function(o) { setMask(false); errorHandler(o); }
            );
        });
    </script>
    <hr>
</div>
<?php } ?>

<a id="exportAsExcel" href="dw/cube/export?idCube=<?=$this->idCube?>" class="btn">
    <img src="images/dw/xls.png" alt="xls" />
    <?=__('UI','verb','exportToExcel')?>
</a>
<?php
$datagrid = new UI_Datagrid('report', 'datagrid_report', 'simulation');

$columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$datagrid->addCol($columnLabel);

$columnDetails = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$datagrid->addCol($columnDetails);

$datagrid->addParam('idSet', $this->idSet);
$datagrid->addParam('idCube', $this->idCube);
$datagrid->pagination = false;
$datagrid->deleteElements = true;
$datagrid->display();
?>
<div>
    <?=$this->button(__('DW', 'reportList', 'add'), 'plus-sign')->link('simulation/set/report?idSet='.$this->idSet.'&idCube='.$this->idCube)?>
</div>