<?php
// Liste des Simulation d'un Set.
use AF\Domain\InputSet\PrimaryInputSet;

$datagridListScenarios = new UI_Datagrid('listScenarios', 'datagrid_scenario', 'simulation');

$colLabelScenario = new UI_Datagrid_Col_Text('labelScenario', __('UI', 'name', 'label'));
$colLabelScenario->editable = true;
$colLabelScenario->addable = true;
$datagridListScenarios->addCol($colLabelScenario);

$colAdvancementInput = new UI_Datagrid_Col_Percent('advancementInput', __('UI', 'name', 'progress'));
$datagridListScenarios->addCol($colAdvancementInput);

$colStateInput = new UI_Datagrid_Col_List('stateInput', __('UI', 'name', 'status'));
$colStateInput->withEmptyElement = false;
$colStateInput->editable = false;
$colStateInput->addable = false;
$imageFinished = new UI_HTML_Image('images/af/bullet_green.png', 'finish');
$imageComplete = new UI_HTML_Image('images/af/bullet_orange.png', 'complet');
$imageCalculationIncomplete = new UI_HTML_Image('images/af/bullet_red.png', 'incompletecomplete');
$imageInputIncomplete = new UI_HTML_Image('images/af/bullet_red.png', 'incomplet');
$colStateInput->list = array(
    PrimaryInputSet::STATUS_FINISHED => $imageFinished->render() . ' ' . __('AF', 'inputInput', 'statusFinished'),
    PrimaryInputSet::STATUS_COMPLETE => $imageComplete->render() . ' ' . __('AF', 'inputInput', 'statusComplete'),
    PrimaryInputSet::STATUS_CALCULATION_INCOMPLETE => $imageCalculationIncomplete->render() . ' ' . __('AF', 'inputInput', 'statusCalculationIncomplete'),
    PrimaryInputSet::STATUS_INPUT_INCOMPLETE => $imageInputIncomplete->render() . ' ' . __('AF', 'inputInput', 'statusInputIncomplete'),
);
$datagridListScenarios->addCol($colStateInput);

$colLinkEdit = new UI_Datagrid_Col_Link('link', __('UI', 'name', 'input'));
$colLinkEdit->addable = false;
$datagridListScenarios->addCol($colLinkEdit);

$datagridListScenarios->pagination = false;
$datagridListScenarios->addElements = true;
$datagridListScenarios->addPanelTitle = __('Simulation', 'setSingle', 'addPanelTitle');
$datagridListScenarios->deleteElements = true;
$datagridListScenarios->addParam('idSet', $this->idSet);

$datagridListScenarios->display();
