<?php
/**
 * @author matthieu.napoli
 * @package Techno
 */
use Keyword\Domain\Keyword;
?>

<div class="page-header">
    <h1><?=__('Techno', 'name', 'meanings')?></h1>
</div>

<?php
$datagrid = new UI_Datagrid('meaningDatagrid', 'datagrid_meaning-datagrid', 'techno');
$datagrid->deleteElements = true;

// Colonne libellé
$labelColumn = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$labelColumn->addable = false;
$labelColumn->editable = false;
$datagrid->addCol($labelColumn);
// Colonne identifiant
$refColumn = new UI_Datagrid_Col_List('ref', __('UI', 'name', 'identifier'));
$refColumn->addable = true;
$refColumn->editable = true;
$refColumn->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
$refColumn->list = [];
foreach ($this->keywords as $keyword) {
    /** @var $keyword Keyword */
    $refColumn->list[$keyword->getRef()] = $keyword->getRef();
}
$datagrid->addCol($refColumn);
// Colonne Position
$orderColumn = new UI_Datagrid_Col_Order('position');
$orderColumn->labelAdd = 'Position';
$orderColumn->addable = false;
$orderColumn->editable = true;
$datagrid->addCol($orderColumn);

$datagrid->addElements = true;
$datagrid->addPanelTitle = __('Techno', 'meaning', 'addPanelTitle');

$datagrid->display();

?>
<script type="text/javascript">
    $('#meaningDatagrid_addPanel').on('hidden', function(){
        $('#meaningDatagrid_ref_addForm').val('').trigger('change');
    });
</script>
