<script>
    function startIntro(){
        var intro = introJs();
        intro.setOptions({
            steps: [
                {
                    element: '.tab-content',
                    intro: "Ce formulaire vous permet de saisir vos données comptables.",
                    position: 'top'
                },
                {
                    element: '.form-actions',
                    intro: "Vous pouvez cliquer à tout moment sur le bouton \"Enregistrer\" pour sauvegarder vos saisies.<br>"
                           + "Pour revenir à la page des saisies, cliquez sur le bouton \"Quitter\"",
                    position: 'top'
                },
                {
                    element: '.nav-tabs',
                    intro: "Après avoir enregistré votre formulaire vous pouvez voir les résultats des calculs, ajouter un commentaire ou voir le détail des calculs."
                }
            ],
            showBullets: false,
            showStepNumbers: false,
            nextLabel: "Suivant",
            prevLabel: "Précédent",
            doneLabel: "Terminer",
            skipLabel: "Passer"
        });
        var stepCompleted = function () {
            $.ajax({
                url: 'user/profile/dismiss-tutorial/tutorial/<?=\User\Application\ViewHelper\TutorialHelper::AF ?>/',
                type: "GET"
            });
        };
        intro.onexit(stepCompleted);
        intro.oncomplete(stepCompleted);
        intro.start();
    }
    $(function () {
        $(document).ready(function () {
            setTimeout(startIntro, 700);
        });
    });
    $("#tabs_tabInput").on("loadTab.muih", function () {
        startIntro();
    });
</script>