<script>
    function startIntro(){
        var intro = introJs();
        intro.setOptions({
            steps: [
                {
                    element: '.granularity-wrapper:last-child',
                    intro: "Dans cette zone sont listés les différents formulaires de saisies de vos données comptables pour chaque année.",
                    position: 'top'
                },
                {
                    element: '.granularity-wrapper:last-child .cells-filter',
                    intro: "Vous pouvez filtrer les formulaires de saisies par catégorie, année, statut de saisie et d'inventaires."
                },
                {
                    element: '#currentGranularity .btn:nth-child(3)',
                    intro: "Ce bouton vous permet d'accéder à la liste des analyses de vos données."
                },
                {
                    element: '#currentGranularity .btn:nth-child(4)',
                    intro: "Celui-ci vous permet d'exporter vos saisies."
                },
                {
                    element: '#cellsView',
                    intro: "Vous pouvez maintenant commencer à saisir des données et accéder aux analyses.",
                    position: 'top'
                }
            ],
            showBullets: false,
            showStepNumbers: false,
            nextLabel: "Suivant",
            prevLabel: "Précédent",
            doneLabel: "Terminer",
            skipLabel: "Passer"
        });
        var stepCompleted = function () {
            $.ajax({
                url: 'user/profile/dismiss-tutorial/tutorial/<?=\User\Application\ViewHelper\TutorialHelper::ORGA ?>/',
                type: "GET"
            });
        };
        intro.onchange(function (targetElement) {
            if ($(targetElement).attr('id') == 'cellsView') {
                stepCompleted();
            }
        })
        intro.onexit(stepCompleted);
        intro.oncomplete(function () {
            stepCompleted();
        });
        intro.start();
    }
    $(function () {
        $(document).ready(function () {
            //
        });
        $('div.collapse.in:last-child').on('showCells', function(e) {
            setTimeout(startIntro, 200);
        });
    });
</script>
