<div class="text-center error-box">
    <h2 class="font-xl">
        <strong>
            <i class="fa fa-fw fa-warning fa-lg text-warning"></i>
            <?=__('UI', 'name', 'error')?>
            <?= $this->httpStatus ?>
        </strong>
    </h2>
    <p>
        <strong>
            <?= $this->errorMessage ?>
        </strong>
    </p>
    <?php
    echo $this->button(
        __('UI', 'button', 'previousPage'),
        'arrow-circle-left',
        ['class' => 'btn-warning', 'onclick' => 'history.back();']
    );
    ?>
</div>

<?php if ((APPLICATION_ENV == 'testsunitaires') || (APPLICATION_ENV == 'developpement') || (APPLICATION_ENV == 'test')) : ?>

    <h2>Information complémentaire pour l'environnement : <?= APPLICATION_ENV ?></h2>

    <p>
        <code><?= $this->exception->getMessage() ?></code>
    </p>

    <pre><?= $this->exception->getTraceAsString() ?></pre>

    <hr/>

    <h3>Paramètres de la requête HTTP :</h3>
    <pre><?= var_export($this->requestParams, true) ?></pre>

<?php endif; ?>
