<?php
/**
 * Vue presentant l'arbres des mots-cles.
 * @author valentin.claras
 * @author bertrand.ferry
 * @package Keyword
 */
?>
<div class="page-header">
    <h1><?=__('Keyword', 'graph', 'pageTitle')?></h1>
</div>

<div class="navbar">
    <div class="navbar-inner">
        <form class="navbar-form pull-left" method="post" action="keyword/graph/gotokeyword">
            <?=$this->autocomplete('keywordGoTo', 'keyword/graph/autocompleteprovider')
                ->addOption('width', '"350px"')
                ->addOption('containerCss', '{"vertical-align": "bottom"}');?>
            <input class="btn btn-success" type="submit" value="<?=__('UI', 'other', 'ok')?>" name="ok">
        </form>
    </div>
</div>

<div>
    <div class="span3">
    </div>

    <div class="span2"></div>

    <div class="span2">
    </div>

    <div class="span2"></div>

    <div class="span3">
        <div style="text-align: center;">
            <h3><?=__('Keyword', 'graph', 'rootKeywords')?></h3>
        </div>
        <ul>
        <?php foreach($this->rootKeywords as $keyword) { ?>
            <li>
                <a href="keyword/graph/consult?ref=<?=$keyword->getRef()?>">
                    <?=$keyword->getLabel()?>
                    <i>(<?=$keyword->getRef()?>)</i>
                </a>
            </li>
        <?php } ?>
        </ul>
    </div>
</div>