<?php
/**
 * @author valentin.claras
 * @author sidoine.tardieu
 * @package Orga
 */

$columnControl = new UI_Datagrid_Col_Text('control', __('Orga', 'control', 'seekedIssue'));
$columnControl->multiple = true;

$columnDiag = new UI_Datagrid_Col_Bool('diagnostic', __('UI', 'name', 'diagnostic'));
$columnDiag->valueTrue = '<i class="icon-ok"></i> '.__('UI', 'other', 'ok');
$columnDiag->valueFalse = '<i class="icon-remove"></i> '.__('UI', 'other', 'nok');

$columnEchec = new UI_Datagrid_Col_Text('failure', __('Orga', 'control', 'abnormalItems'));
$columnEchec->multiple = true;

$datagrid = new UI_Datagrid('consistency', 'datagrid_consistency', 'orga');
$datagrid->addCol($columnControl);
$datagrid->addCol($columnDiag);
$datagrid->addCol($columnEchec);

$datagrid->pagination = false;
$datagrid->addParam('idOrganization', $this->idOrganization);
if ($this->display === false) {
    echo $datagrid->render();
} else {
    $datagrid->display();
}

$controlButton = new UI_HTML_Button(__('Orga', 'control', 'renewControl'));
$controlButton->addAttribute('onclick', 'consistency.filter();');
$controlButton->addAttribute('class', 'btn-primary');
$controlButton->display();
