<?php
$columnControl = new UI_Datagrid_Col_Text('control', __('Orga', 'control', 'seekedIssue'));

$columnDiag = new UI_Datagrid_Col_Bool('diagnostic', __('UI', 'name', 'diagnostic'));
$columnDiag->valueTrue = '<i class="fa fa-check"></i> '.__('UI', 'other', 'ok');
$columnDiag->valueFalse = '<i class="fa fa-times"></i> '.__('UI', 'other', 'nok');

$columnEchec = new UI_Datagrid_Col_Text('failure', __('Orga', 'control', 'abnormalItems'));

$datagrid = new UI_Datagrid('consistency'.$this->idOrganization, 'datagrid_organization_consistency', 'orga');
$datagrid->addCol($columnControl);
$datagrid->addCol($columnDiag);
$datagrid->addCol($columnEchec);
$datagrid->addParam('idOrganization', $this->idOrganization);
$datagrid->pagination = false;

if ($this->display === false) {
    echo $datagrid->render();
} else {
    $datagrid->display();
}

$controlButton = new UI_HTML_Button(__('Orga', 'control', 'renewControl'));
$controlButton->addAttribute('onclick', 'consistency'.$this->idOrganization.'.filter();');
$controlButton->addAttribute('class', 'btn-primary');
$controlButton->display();
