<?php
/**
 * Vue générale d'un organization
 * @author valentin.claras
 * @package Orga
 */

/** @var \Orga\ViewModel\OrganizationViewModel $organization */
$organization = $this->organization;
?>
<div class="organization page-header">
    <h1>
        <?=$organization->label?>
        <?php if ($organization->canBeEdited) : ?>
            <div class="pull-right">
                <small>
                    <a class="editOrganization btn btn-small btn-primary"
                       href="orga/organization/edit/idOrganization/<?=$organization->id?>">
                        <i class="icon-cog icon-white"></i>
                        <?=__('UI', 'verb', 'edit')?>
                    </a>
                </small>
            </div>
        <?php endif; ?>
    </h1>
</div>
<?php
$this->tabView->display();

