<?php
/**
 * Vue générale d'un organization
 * @author valentin.claras
 * @package Orga
 */

/** @var \Orga\ViewModel\OrganizationViewModel $organization */
$organization = $this->organization;
?>
<div class="organization well alert-info">
    <div class="pull-right">
        <a class="viewOrganization btn btn-small btn-primary"
           href="orga/organization/view/idOrganization/<?=$organization->id?>">
            <i class="icon-share-alt icon-white"></i>
            <?=__('UI', 'verb', 'consult')?>
        </a>
    </div>

    <h1>
        <?=$organization->label?>
    </h1>
</div>
<?php
$this->tabView->display();

