<?php
/**
 * Vue générale d'un organization
 * @author valentin.claras
 * @package Orga
 */

/** @var \Account\Application\ViewModel\OrganizationView $organization */
$organization = $this->organization;
$workspaceBanner = null;
$file = glob(APPLICATION_PATH . '/../public/workspaceBanners/' . $organization->id . '.*');
if (count($file) > 0) {
    $workspaceBanner = 'workspaceBanners/' . pathinfo(array_pop($file))['filename'];
}
?>
<style>
    .organization h1 img { max-height: 125px; }
    .organization h1 .pull-right small a { letter-spacing: normal; }
</style>

<div class="organization page-header">
    <h1>
        <?php if ($organization->canBeEdited) : ?>
            <div class="pull-right">
                <small>
                    <a class="editOrganization btn btn-sm btn-default"
                       href="orga/organization/view/idOrganization/<?=$organization->id?>">
                        <i class="fa fa-external-link"></i>
                        <?=___('UI', 'name', 'data')?>
                    </a>
                </small>
            </div>
        <?php endif; ?>
        <?php if ($workspaceBanner === null) : ?>
            <?=$organization->label?>
        <?php else : ?>
            <img src="<?=$workspaceBanner?>">
        <?php endif; ?>
    </h1>
</div>
<?php
$this->tabView->display();
?>

<script>
    $('#relevance').on('granularityAdded', $('#addGranularity<?=$this->organization->id?>_relevance'), function(e, data) {
        addMessage(data.message, 'success');
        $('#relevance').html($('#relevance').attr('data-loading'));
        $('#relevance').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
    $('#afs').on('granularityAdded', $('#addGranularity<?=$this->organization->id?>_afs'), function(e, data) {
        addMessage(data.message, 'success');
        $('#afs').html($('#afs').attr('data-loading'));
        $('#afs').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
    $('#acl').on('granularityAdded', $('#addGranularity<?=$this->organization->id?>_acl'), function(e, data) {
        addMessage(data.message, 'success');
        $('#acl').html($('#acl').attr('data-loading'));
        $('#acl').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
    $('#reports').on('granularityAdded', $('#addGranularity<?=$this->organization->id?>_reports'), function(e, data) {
        addMessage(data.message, 'success');
        $('#reports').html($('#reports').attr('data-loading'));
        $('#reports').trigger('loadTab.muih', [$('#content ul.nav-tabs li.active a').attr('data-src')]);
    });
</script>
