<?php

foreach ($this->granularities as $granularity) :
    /** @var $granularity Orga_Model_Granularity */

    $datagridGranularityReports = new UI_Datagrid(
        'datagridCellReports'.$granularity->getId(),
        'datagrid_organization_reports',
        'orga'
    );

    $columnReport = new UI_Datagrid_Col_Text('report', ___('UI', 'name', 'label'));
    $datagridGranularityReports->addCol($columnReport);

    $columnLink = new UI_Datagrid_Col_Link('link', ___('UI', 'name', 'details'));
    $datagridGranularityReports->addCol($columnLink);

    $datagridGranularityReports->addParam('idOrganization', $this->organization->getId());
    $datagridGranularityReports->addParam('idGranularity', $granularity->getId());
    $datagridGranularityReports->initialLoading = false;
    $datagridGranularityReports->deleteElements = true;


    $addButton = new UI_HTML_Button(___('UI', 'verb', 'add'));
    $addButton->icon = 'plus-circle';
    $addButton->link = 'orga/granularity/view-report/idGranularity/' . $granularity->getId() . '/';

    echo $this->collapse(
        'cellReports'.$granularity->getId(),
        $granularity->getLabel(),
        $datagridGranularityReports->getHTML() . $addButton->getHTML()
    )->collapsed();

    $script = '';
    $script .= '$(\'#cellReports'.$granularity->getId().'\').on(\'show\', function(e) {';
    $script .= 'if ($(e.target).attr(\'id\') == \'cellReports'.$granularity->getId().'_wrapper\') {';
    $script .= 'datagridCellReports'.$granularity->getId().'.filter();';
    $script .= '}';
    $script .= '});';

    if ($this->display === false) :
        echo '<script type="text/javascript">'.$datagridGranularityReports->getScript().$script.'</script>';
    else :
        UI_Datagrid::addHeader($datagridGranularityReports);
        $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
    endif;
endforeach;

if (count($this->granularities) > 0) :
    echo '<hr>';
endif;
echo $this->partial(
    'granularity/add.phtml',
    [
        'organization' => $this->organization,
        'purpose' => 'reports',
        'complementaryFields' => ''
    ]
);
if ($this->display === true) :
?>
<script>
    $('#addGranularity<?=$this->organization->getId()?>_reports').on('granularityAdded', function(e) {
        location.reload(true);
    });
</script>
<?php
endif;
?>
