<?php
use Orga\ViewModel\OrganizationViewModel;

/** @var OrganizationViewModel[] $organizations */
$organizations = $this->organizations;
?>

<style>
    .deleteOrganization { margin-left: 15px; }
</style>

<div class="page-header">
    <h1>
        <?=__('Orga', 'organization', 'organizations')?>
    </h1>
</div>

<div class="organizationList">
    <?php foreach ($organizations as $organization) : ?>

        <div class="organization well">
            <?php if ($organization->canBeDeleted) : ?>
                <div class="pull-right">
                    <a class="deleteOrganization btn btn-small btn-warning"
                       href="orga/organization/delete/idOrganization/<?=$organization->id?>">
                        <i class="icon-trash icon-white"></i>
                        <?=__('UI', 'verb', 'delete')?>
                    </a>
                </div>
            <?php endif; ?>
            <?php if ($organization->canBeEdited) : ?>
                <div class="pull-right">
                    <a class="editOrganization btn btn-small btn-primary"
                       href="orga/organization/edit/idOrganization/<?=$organization->id?>">
                        <i class="icon-cog icon-white"></i>
                        <?=__('UI', 'name', 'configurationOrga')?>
                    </a>
                </div>
            <?php endif; ?>

            <h3>
                <a href="orga/organization/view/idOrganization/<?=$organization->id?>">
                    <?=$organization->label?>
                    <small>
                        <i class="icon-share-alt"></i>
                        <?=__('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>

            <p>
                <strong><?=__('Orga', 'axis', 'rootAxes').__('UI', 'other', ':')?></strong>
                <?=implode(', ', $organization->rootAxesLabels)?>
            </p>

            <p>
                <strong><?=__('Orga', 'inventory', 'inventories').__('UI', 'other', ':')?></strong>
                <?=$organization->inventory?>
            </p>
        </div>

    <?php endforeach; ?>

    <?php if ($this->canCreateOrganization) : ?>
        <p>
            <a href="orga/organization/add" class="btn">
                <i class="icon-plus-sign"></i>
                <?=__('UI', 'verb', 'add')?>
            </a>
        </p>
    <?php endif; ?>
</div>

<?php if ($organization->canBeDeleted) : ?>
<script>
    $(function() {
        $(".deleteOrganization").confirm({
            text: "<?=__('UI', 'message', 'areYouSure')?>",
            confirmButton: "<?=__('UI', 'verb', 'confirm')?>",
            cancelButton: "<?=__('UI', 'verb', 'cancel')?>",
            post: true
        });
    });
</script>
<?php endif; ?>
