<?php
// Liste des Organization.
?>
<div class="page-header">
    <h1>
        <?=__('Orga', 'organization', 'organizations')?>
    </h1>
</div>

<?php
$datagridOrganization = new UI_Datagrid('organizations', 'datagrid_organization', 'orga');

$columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$columnLabel->addable = true;
$datagridOrganization->addCol($columnLabel);

$columnRootAxes = new UI_Datagrid_Col_Text('rootAxes', __('Orga', 'axis', 'rootAxes'));
$columnRootAxes->addable = false;
$datagridOrganization->addCol($columnRootAxes);

$columnGranularityForInventoryStatus = new UI_Datagrid_Col_Text('granularityForInventoryStatus', __('Orga', 'inventory', 'inventories'));
$columnGranularityForInventoryStatus->addable = false;
$datagridOrganization->addCol($columnGranularityForInventoryStatus);

$columnDetails = new UI_Datagrid_Col_Link('details', __('UI', 'name', 'details'));
$columnDetails->addable = false;
$datagridOrganization->addCol($columnDetails);

$datagridOrganization->deleteElements = $this->isConnectedUserAbleToCreateOrganizations;
$datagridOrganization->pagination = false;
$datagridOrganization->addElements = $this->isConnectedUserAbleToCreateOrganizations;
$datagridOrganization->addPanelTitle = __('Orga', 'organization', 'addPanelTitle');

$datagridOrganization->display();