<fieldset class="wrapper">
    <legend style="cursor:default"><?=___('DW', 'rebuild', 'analysisDataRebuildCollapse')?></legend>
<p><?=___('DW', 'rebuild', 'analysisDataRebuildWarningMessageOrganization')?></p>
<div>
    <form action="orga/organization/rebuild-data/idOrganization/<?=$this->organization->getId()?>/" class="rebuild-data">
        <div class="input-group">
            <?php if (count($this->cellsData) > 1) : ?>
                <select name="cell" class="form-control">
                    <?php foreach ($this->cellsData as $cellIndex => $cellData) : ?>
                        <?php if ($cellData instanceof Orga_Model_Organization) : ?>
                            <option value=""><?=$cellData->getLabel()?></option>
                        <?php else : ?>
                            <option value="<?=$cellData->getId()?>"><?=$cellData->getLabel()?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            <?php else : ?>
                <input type="text" name="cell" class="disabled" disabled value="<?=reset($this->cellsData)->getLabel()?>" class="form-control">
            <?php endif; ?>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary dw-action">
                        <i class="fa fa-refresh"></i>
                        <span>
                            <?=___('DW', 'rebuild', 'analysisDataRebuildButton')?>
                        </span>
                    </button>
                </span>
            <?php if (count($this->cellsData) > 1) : ?>
            <?php endif; ?>
        </div>
    </form>
    <script type="text/javascript">
        $('body').on('submit', '.rebuild-data', function(e) {
            e.preventDefault();
            var form = $(this);
            if (this.hasAttribute('data-processing')) {
                return false;
            }
            form.attr('data-processing', 'true');
            var infoButton = $('.dw-action', form);
            infoButton.removeClass('btn-primary');
            infoButton.addClass('btn-info');
            infoButton.addClass('disabled');
            $('i.fa', infoButton).addClass('fa-spin');
            $('span', infoButton).html(
                '<?=___('DW', 'rebuild', 'analysisDataRebuilding')?>'
            );
            $.ajax({
                type: 'post',
                url: form.attr('action'),
                data: form.serialize(),
                success: function (data) {
                    addMessage(data.message, 'success');
                },
                error: function(jqXHR) {
                    errorHandler(jqXHR);
                },
                complete: function () {
                    form.removeAttr('data-processing');
                    infoButton.removeClass('btn-info');
                    infoButton.removeClass('disabled');
                    $('i.fa', infoButton).removeClass('fa-spin');
                    infoButton.addClass('btn-primary');
                    $('span', infoButton).html(
                        '<?=___('DW', 'rebuild', 'analysisDataRebuildButton')?>'
                    );
                }
            });
        });
    </script>
</div>
</fieldset>

<?php if ($this->canEditOrganization) : ?>
<fieldset class="wrapper">
    <legend style="cursor: default"><?=___('DW', 'rebuild', 'outputDataRebuildCollapse') ?></legend>
    <p><?=___('DW', 'rebuild', 'outputDataRebuildWarningMessageOrganization') ?></p>
    <form action="orga/organization/rebuild-results/idOrganization/<?=$this->organization->getId()?>/" class="rebuild-results">
        <div class="input-group">
            <?php if (count($this->cellsResults) > 1) : ?>
                <select name="cell" class="form-control">
                    <?php foreach ($this->cellsResults as $cellResults) : ?>
                        <option value="<?=$cellResults->getId()?>"><?=$cellResults->getLabel()?></option>
                    <?php endforeach; ?>
                </select>
            <?php else : ?>
                <input type="text" name="cell" class="disabled" disabled value="<?=reset($this->cellsResults)->getLabel()?>" class="form-control">
            <?php endif; ?>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary dw-action">
                        <i class="fa fa-refresh"></i>
                        <span>
                            <?=___('DW', 'rebuild', 'outputDataRebuildButton')?>
                        </span>
                    </button>
                </span>
            <?php if (count($this->cellsResults) > 1) : ?>
            <?php endif; ?>
        </div>
    </form>
    <script type="text/javascript">
        $('body').on('submit', '.rebuild-results', function(e) {
            e.preventDefault();
            var form = $(this);
            if (this.hasAttribute('data-processing')) {
                return false;
            }
            form.attr('data-processing', 'true');
            var infoButton = $('.dw-action', form);
            infoButton.removeClass('btn-primary');
            infoButton.addClass('btn-info');
            infoButton.addClass('disabled');
            $('i.fa', infoButton).addClass('fa-spin');
            $('span', infoButton).html(
                '<?=___('DW', 'rebuild', 'outputDataRebuilding')?>'
            );
            $.ajax({
                type: 'post',
                url: form.attr('action'),
                data: form.serialize(),
                success: function (data) {
                    addMessage(data.message, 'success');
                },
                error: function(jqXHR) {
                    errorHandler(jqXHR);
                },
                complete: function () {
                    form.removeAttr('data-processing');
                    infoButton.removeClass('btn-info');
                    infoButton.removeClass('disabled');
                    $('i.fa', infoButton).removeClass('fa-spin');
                    infoButton.addClass('btn-primary');
                    $('span', infoButton).html(
                        '<?=___('DW', 'rebuild', 'outputDataRebuildButton')?>'
                    );
                }
            });
        });
    </script>
</fieldset>
<?php endif; ?>