<?php
/** @var \Orga\ViewModel\OrganizationViewModel $organization */
$organization = $this->organization;
/** @var \Orga\ViewModel\CellViewModel[] $cells */
$cells = $this->cells;
?>
<div class="organization page-header">
    <?php if ($organization->canBeEdited) : ?>
        <div class="pull-right">
            <a class="editOrganization btn btn-small btn-primary"
               href="orga/organization/edit/idOrganization/<?=$organization->id?>">
                <i class="icon-cog icon-white"></i>
                <?=__('UI', 'verb', 'edit')?>
            </a>
        </div>
    <?php endif; ?>

    <h1>
        <?=$organization->label?>
    </h1>
</div>

<?php foreach ($cells as $cell) : ?>
<div class="well">
    <h2>
        <a href="orga/cell/view/idCell/<?=$cell->id?>">
            <?=$this->cellsAccess[$cell->id]?>
            <?=$cell->extendedLabel?>
            <small>
                <i class="icon-share-alt"></i>
                <?=__('Orga', 'view', 'linkDetails')?>
            </small>
        </a>
    </h2>
</div>
<?php endforeach; ?>
<?php if (count($this->cells) === 0) : ?>
<p><?=__('UI', 'message', 'noAccess')?></p>
<?php endif; ?>