<div class="page-header">
    <h1><?=__('Classification', 'context', 'pageTitle')?></h1>
</div>

<?
$datagrid = new UI_Datagrid('editContexts', 'datagrid_context', 'classification');
$datagrid->addParam('library', $this->library->getId());

$columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$columnLabel->editable = true;
$datagrid->addCol($columnLabel);

$columnRef = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$columnRef->editable = true;
$datagrid->addCol($columnRef);

$columnPosition = new UI_Datagrid_Col_Order('position');
$columnPosition->editable = true;
$columnPosition->addable = false;
$columnPosition->sortName = Classification\Domain\Context::QUERY_POSITION;
$datagrid->addCol($columnPosition);

$datagrid->deleteElements = true;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('Classification', 'context', 'addPanelTitle');
$datagrid->setDefaultSorting($columnPosition->id);
$datagrid->display();

$script = 'refFromLabel(\'editContexts_label_addForm\', \'editContexts_ref_addForm\');';
$this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
