<?php
use Account\Application\ViewModel\AccountView;

/** @var AccountView $account */
$account = $this->account;
?>

<style>
    .deleteOrganization { margin-left: 15px; }
</style>

<h1 class="page-title txt-color-blueDark">
    <i class="fa fa-fw fa-home"></i>
    Dashboard
</h1>

<h2>Workspaces</h2>

<div class="organizationList">
    <?php foreach ($account->organizations as $organization) : ?>

        <div class="organization well well-small">
            <?php if ($organization->canBeDeleted) : ?>
                <div class="pull-right">
                    <a class="deleteOrganization btn btn-small btn-warning"
                       href="orga/organization/delete/idOrganization/<?=$organization->id?>">
                        <i class="fa fa-trash-o"></i>
                        <?=___('UI', 'verb', 'delete')?>
                    </a>
                </div>
            <?php endif; ?>
            <?php if ($organization->canBeEdited) : ?>
                <div class="pull-right">
                    <a class="editOrganization btn btn-small btn-primary"
                       href="orga/organization/edit/idOrganization/<?=$organization->id?>">
                        <i class="fa fa-wrench"></i>
                        <?=___('UI', 'name', 'configurationOrga')?>
                    </a>
                </div>
            <?php endif; ?>

            <h3>
                <a href="orga/organization/view/idOrganization/<?=$organization->id?>">
                    <?=$organization->label?>
                    <small>
                        <i class="fa fa-external-link"></i>
                        <?=___('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>
        </div>

    <?php endforeach; ?>

    <?php if (empty($account->organizations)) : ?>
        <p class="text-muted">
            Aucun workspace.
        </p>
    <?php endif; ?>

    <?php if ($this->canCreateOrganization) : ?>
        <p>
            <a href="orga/organization/add" class="btn">
                <i class="fa fa-plus"></i>
                Créer un nouveau workspace
            </a>
        </p>
    <?php endif; ?>
</div>

<script>
    $(function() {
        $(".deleteOrganization").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
    });
</script>


<h2>Bibliothèques</h2>

<h3>Formulaires</h3>

<div>
    <?php foreach ($account->afLibraries as $library) : ?>

        <div class="afLibrary well well-small">
            <h3>
                <a href="af/library/view/id/<?=$library->id?>">
                    <?=$library->label?>
                    <small>
                        <i class="fa fa-external-link"></i>
                        <?=___('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>
        </div>

    <?php endforeach; ?>

    <?php if (empty($account->afLibraries)) : ?>
        <p class="text-muted">
            Aucune bibliothèque de formulaires.
        </p>
    <?php endif; ?>
</div>

<h3>Paramètres</h3>

<div>
    <?php foreach ($account->parameterLibraries as $library) : ?>

        <div class="parameterLibrary well well-small">
            <h3>
                <a href="parameter/library/view/id/<?=$library->id?>">
                    <?=$library->label?>
                    <small>
                        <i class="fa fa-external-link"></i>
                        <?=___('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>
        </div>

    <?php endforeach; ?>

    <?php if (empty($account->parameterLibraries)) : ?>
        <p class="text-muted">
            Aucune bibliothèque de paramètres.
        </p>
    <?php endif; ?>
</div>
