<?php
/** @var Account\Application\ViewModel\AccountView $account */
$account = $this->account;
?>

<div class="page-header">
    <h1>
        <i class="fa fa-fw fa-home"></i>
        <?=__('Account', 'name', 'dashboard')?>
    </h1>
</div>

<div class="well">

    <table class="table table-hover table-forum">
        <thead>
        <tr>
            <th colspan="2">Workspaces</th>
            <th class="col-button hidden-xs">
                <?php if ($this->canEditAccount) : ?>
                    <a href="orga/organization/add/account/<?=$account->id?>" class="btn btn-default btn-xs pull-right"
                       title="<?=__('Orga', 'workspace', 'createNewWorkspace')?>">
                        <i class="fa fa-lg fa-plus"></i>
                    </a>
                <?php endif; ?>
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($account->organizations as $organization) : ?>
            <tr class="organization">
                <td class="col-icon">
                    <i class="fa fa-inbox fa-2x text-muted"></i>
                </td>
                <td>
                    <h4>
                        <a href="orga/organization/view/idOrganization/<?=$organization->id?>">
                            <?=$organization->label?>
                        </a>
                        <small><?=___('Orga', 'organizationList', 'goToData')?></small>
                    </h4>
                </td>
                <td class="col-button hidden-xs">
                    <div class="btn-group pull-right">
                        <?php if ($organization->canBeEdited) : ?>
                            <a class="editOrganization btn btn-sm btn-default"
                               href="orga/organization/edit/idOrganization/<?=$organization->id?>">
                                <i class="fa fa-wrench"></i>
                                <?=___('UI', 'name', 'configurationOrga')?>
                            </a>
                        <?php endif; ?>
                        <?php if ($organization->canBeDeleted) : ?>
                            <a class="deleteOrganization btn btn-sm btn-warning"
                               href="orga/organization/delete/idOrganization/<?=$organization->id?>">
                                <i class="fa fa-trash-o"></i>
                                <?=___('UI', 'verb', 'delete')?>
                            </a>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php if (empty($account->organizations)) : ?>
            <tr>
                <td class="text-muted" colspan="4">
                    Aucun workspace
                </td>
            </tr>
        <?php endif; ?>

        </tbody>
    </table>



    <table class="table table-hover table-forum">
        <thead>
        <tr>
            <th colspan="2"><?=__('AF', 'name', 'formLibraries')?></th>
            <th class="col-button hidden-xs">
                <?php if ($this->canEditAccount) : ?>
                    <a id="createAFLibrary" href="af/library/new?account=<?=$account->id?>"
                       class="btn btn-default btn-xs pull-right"
                       title="<?=__('AF', 'library', 'createNewLibrary')?>">
                        <i class="fa fa-lg fa-plus"></i>
                    </a>
                <?php endif; ?>
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($account->afLibraries as $library) : ?>
            <tr class="afLibrary">
                <td class="col-icon">
                    <i class="fa fa-edit fa-2x text-muted"></i>
                </td>
                <td>
                    <h4>
                        <a href="af/library/view/id/<?=$library->id?>">
                            <?=$library->label?>
                        </a>
                        <small><?=___('Orga', 'organizationList', 'goToData')?></small>
                    </h4>
                </td>
                <?php if ($library->canDelete) : ?>
                    <td class="col-button hidden-xs">
                        <a class="deleteAFLibrary btn btn-sm btn-warning pull-right"
                           href="af/library/delete/id/<?=$library->id?>">
                            <i class="fa fa-trash-o"></i>
                            <?=___('UI', 'verb', 'delete')?>
                        </a>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>

        <?php if (empty($account->afLibraries)) : ?>
            <tr>
                <td class="text-muted" colspan="3">
                    Aucune bibliothèque de formulaires
                </td>
            </tr>
        <?php endif; ?>

        </tbody>
    </table>



    <table class="table table-hover table-forum">
        <thead>
        <tr>
            <th colspan="2"><?=__('Parameter', 'name', 'parameterLibraries')?></th>
            <th class="col-button hidden-xs">
                <?php if ($this->canEditAccount) : ?>
                    <a id="createParameterLibrary" href="parameter/library/new?account=<?=$account->id?>"
                       class="btn btn-default btn-xs pull-right"
                       title="<?=__('Parameter', 'library', 'createNewLibrary')?>">
                        <i class="fa fa-lg fa-plus"></i>
                    </a>
                <?php endif; ?>
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($account->parameterLibraries as $library) : ?>
            <tr class="parameterLibrary">
                <td class="col-icon">
                    <i class="fa fa-table fa-2x text-muted"></i>
                </td>
                <td>
                    <h4>
                        <a href="parameter/library/view/id/<?=$library->id?>">
                            <?=$library->label?>
                        </a>
                        <small><?=___('Orga', 'organizationList', 'goToData')?></small>
                    </h4>
                </td>
                <?php if ($library->canDelete) : ?>
                    <td class="col-button hidden-xs">
                        <a class="deleteParameterLibrary btn btn-sm btn-warning pull-right"
                           href="parameter/library/delete/id/<?=$library->id?>">
                            <i class="fa fa-trash-o"></i>
                            <?=___('UI', 'verb', 'delete')?>
                        </a>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>

        <?php if (empty($account->parameterLibraries)) : ?>
            <tr>
                <td class="text-muted" colspan="3">
                    Aucune bibliothèque de paramètres
                </td>
            </tr>
        <?php endif; ?>

        </tbody>
    </table>




    <table class="table table-hover table-forum">
        <thead>
        <tr>
            <th colspan="2"><?=__('Classification', 'name', 'classificationLibraries')?></th>
            <th class="col-button hidden-xs">
                <?php if ($this->canEditAccount) : ?>
                    <a id="createClassificationLibrary" href="classification/library/new?account=<?=$account->id?>"
                       class="btn btn-default btn-xs pull-right"
                       title="<?=__('Classification', 'library', 'createNewLibrary')?>">
                        <i class="fa fa-lg fa-plus"></i>
                    </a>
                <?php endif; ?>
            </th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($account->classificationLibraries as $library) : ?>
            <tr class="classificationLibrary">
                <td class="col-icon">
                    <i class="fa fa-sitemap fa-2x text-muted"></i>
                </td>
                <td>
                    <h4>
                        <a href="classification/library/view/id/<?=$library->id?>">
                            <?=$library->label?>
                        </a>
                        <small><?=___('Orga', 'organizationList', 'goToData')?></small>
                    </h4>
                </td>
                <?php if ($library->canDelete) : ?>
                    <td class="col-button hidden-xs">
                        <a class="deleteClassificationLibrary btn btn-sm btn-warning pull-right"
                           href="classification/library/delete/id/<?=$library->id?>">
                            <i class="fa fa-trash-o"></i>
                            <?=___('UI', 'verb', 'delete')?>
                        </a>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>

        <?php if (empty($account->parameterLibraries)) : ?>
            <tr>
                <td class="text-muted" colspan="3">
                    Aucune bibliothèque de classification
                </td>
            </tr>
        <?php endif; ?>

        </tbody>
    </table>


</div>


<script>
    $(function() {
        $(".deleteOrganization").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
        $(".deleteAFLibrary").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
        $(".deleteParameterLibrary").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
        $(".deleteClassificationLibrary").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });

        // Tooltips
        $('th .btn').tooltip();
    });
</script>
