<?php
use Account\Application\ViewModel\AccountView;

/** @var AccountView $account */
$account = $this->account;
?>

<div class="page-header">
    <h1>
        <i class="fa fa-fw fa-home"></i>
        <?=__('Account', 'name', 'dashboard')?>
    </h1>
</div>

<h2>Workspaces</h2>

<div class="organizationList">
    <?php foreach ($account->organizations as $organization) : ?>

        <div class="organization well well-sm">
            <?php if ($organization->canBeDeleted) : ?>
                <div class="pull-right">
                    <a class="deleteOrganization btn btn-sm btn-warning"
                       href="orga/organization/delete/idOrganization/<?=$organization->id?>">
                        <i class="fa fa-trash-o"></i>
                        <?=___('UI', 'verb', 'delete')?>
                    </a>
                </div>
            <?php endif; ?>
            <?php if ($organization->canBeEdited) : ?>
                <div class="pull-right">
                    <a class="editOrganization btn btn-sm btn-primary"
                       href="orga/organization/edit/idOrganization/<?=$organization->id?>">
                        <i class="fa fa-wrench"></i>
                        <?=___('UI', 'name', 'configurationOrga')?>
                    </a>
                </div>
            <?php endif; ?>

            <h3>
                <a href="orga/organization/view/idOrganization/<?=$organization->id?>">
                    <?=$organization->label?>
                    <small>
                        <i class="fa fa-external-link"></i>
                        <?=___('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>
        </div>

    <?php endforeach; ?>

    <?php if (empty($account->organizations)) : ?>
        <p class="text-muted">
            Aucun workspace.
        </p>
    <?php endif; ?>

    <?php if ($this->canEditAccount) : ?>
        <p>
            <a href="orga/organization/add" class="btn btn-default">
                <i class="fa fa-plus"></i>
                Créer un nouveau workspace
            </a>
        </p>
    <?php endif; ?>
</div>


<h2>Bibliothèques</h2>

<h3><?=__('AF', 'name', 'forms')?></h3>

<div>
    <?php foreach ($account->afLibraries as $library) : ?>

        <div class="afLibrary well well-sm">
            <?php if ($library->canDelete) : ?>
                <div class="pull-right">
                    <a class="deleteAFLibrary btn btn-sm btn-warning"
                       href="af/library/delete/id/<?=$library->id?>">
                        <i class="fa fa-trash-o"></i>
                        <?=___('UI', 'verb', 'delete')?>
                    </a>
                </div>
            <?php endif; ?>

            <h3>
                <a href="af/library/view/id/<?=$library->id?>">
                    <?=$library->label?>
                    <small>
                        <i class="fa fa-external-link"></i>
                        <?=___('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>
        </div>

    <?php endforeach; ?>

    <?php if (empty($account->afLibraries)) : ?>
        <p class="text-muted">
            Aucune bibliothèque de formulaires.
        </p>
    <?php endif; ?>

    <?php if ($this->canEditAccount) : ?>
        <p>
            <a id="createAFLibrary" href="af/library/new?account=<?=$account->id?>" class="btn btn-default">
                <i class="fa fa-plus"></i>
                <?=__('UI', 'verb', 'add')?>
            </a>
        </p>
    <?php endif; ?>
</div>


<h3><?=__('Parameter', 'name', 'parameters')?></h3>

<div>
    <?php foreach ($account->parameterLibraries as $library) : ?>

        <div class="parameterLibrary well well-sm">
            <?php if ($library->canDelete) : ?>
                <div class="pull-right">
                    <a class="deleteParameterLibrary btn btn-sm btn-warning"
                       href="parameter/library/delete/id/<?=$library->id?>">
                        <i class="fa fa-trash-o"></i>
                        <?=___('UI', 'verb', 'delete')?>
                    </a>
                </div>
            <?php endif; ?>

            <h3>
                <a href="parameter/library/view/id/<?=$library->id?>">
                    <?=$library->label?>
                    <small>
                        <i class="fa fa-external-link"></i>
                        <?=___('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>
        </div>

    <?php endforeach; ?>

    <?php if (empty($account->parameterLibraries)) : ?>
        <p class="text-muted">
            Aucune bibliothèque de paramètres.
        </p>
    <?php endif; ?>

    <?php if ($this->canEditAccount) : ?>
        <p>
            <a href="parameter/library/new?account=<?=$account->id?>" class="btn btn-default">
                <i class="fa fa-plus"></i>
                <?=__('UI', 'verb', 'add')?>
            </a>
        </p>
    <?php endif; ?>
</div>


<h3><?=__('Classification', 'name', 'classification')?></h3>

<div>
    <?php foreach ($account->classificationLibraries as $library) : ?>

        <div class="classificationLibrary well well-sm">
            <?php if ($library->canDelete) : ?>
                <div class="pull-right">
                    <a class="deleteClassificationLibrary btn btn-sm btn-warning"
                       href="classification/library/delete/id/<?=$library->id?>">
                        <i class="fa fa-trash-o"></i>
                        <?=___('UI', 'verb', 'delete')?>
                    </a>
                </div>
            <?php endif; ?>

            <h3>
                <a href="classification/library/view/id/<?=$library->id?>">
                    <?=$library->label?>
                    <small>
                        <i class="fa fa-external-link"></i>
                        <?=___('Orga', 'organizationList', 'goToData')?>
                    </small>
                </a>
            </h3>
        </div>

    <?php endforeach; ?>

    <?php if (empty($account->classificationLibraries)) : ?>
        <p class="text-muted">
            Aucune bibliothèque de classification.
        </p>
    <?php endif; ?>

    <?php if ($this->canEditAccount) : ?>
        <p>
            <a href="classification/library/new?account=<?=$account->id?>" class="btn btn-default">
                <i class="fa fa-plus"></i>
                <?=__('UI', 'verb', 'add')?>
            </a>
        </p>
    <?php endif; ?>
</div>


<script>
    $(function() {
        $(".deleteOrganization").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
        $(".deleteAFLibrary").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
        $(".deleteParameterLibrary").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
        $(".deleteClassificationLibrary").confirm({
            text: '<?=___('UI', 'message', 'areYouSure')?>',
            confirmButton: '<i class="fa fa-check"></i> <?=___('UI', 'verb', 'confirm')?>',
            cancelButton: '<i class="fa fa-times"></i> <?=___('UI', 'verb', 'cancel')?>',
            post: true
        });
    });
</script>
