<div class="jarviswidget">

    <header>
        <h2><?=__('User', 'resetPassword', 'pageTitle')?></h2>
    </header>

    <div>
        <div class="widget-body no-padding">

            <form class="smart-form" action="user/password/forgotten" method="post">
                <header>
                    1.
                    <?=__('User', 'resetPassword', 'captchaFormDescriptionSentence')?>
                </header>

                <fieldset>
                    <section>
                        <label class="input"> <i class="icon-append fa fa-envelope-o"></i>
                            <input type="email" name="email" required
                                   placeholder="<?=__('User', 'user', 'emailAddress')?>">
                            <b class="tooltip tooltip-bottom-right"><?=__('User', 'user', 'emailAddress')?></b>
                        </label>
                    </section>

                    <section>
                        <?php
                        $captcha = new UI_Form_Element_Captcha('captcha', 'user/captcha/newimage');
                        $captcha->setLabel(__('User', 'resetPassword', 'captchaFieldLabel'));
                        $captcha->setRequired();
                        echo $captcha->render();
                        ?>
                    </section>
                </fieldset>

                <footer>
                    <button type="submit" class="btn btn-primary">
                        <?=__('UI', 'verb', 'validate')?>
                    </button>
                </footer>
            </form>

            <form class="smart-form" action="user/password/reset" method="post">
                <header>
                    2.
                    <?=__('User', 'resetPassword', 'confirmationFormDescriptionSentence')?>
                </header>

                <fieldset>
                    <section>
                        <label class="input"> <i class="icon-append fa fa-lock"></i>
                            <input type="text" name="code" required value="<?=$this->code?>"
                                   placeholder="<?=__('User', 'resetPassword', 'confirmationCodeLabel')?>">
                            <b class="tooltip tooltip-bottom-right">
                                <?=__('User', 'resetPassword', 'confirmationCodeLabel')?>
                            </b>
                        </label>
                    </section>
                </fieldset>

                <footer>
                    <button type="submit" class="btn btn-primary">
                        <?=__('UI', 'verb', 'validate')?>
                    </button>
                </footer>
            </form>

        </div>

    </div>

</div>
