<?php
use MyCLabs\MUIH\GenericTag;
use MyCLabs\MUIH\GenericVoidTag;

/**
 * @author valentin.claras
 * @author sidoine.tardieu
 * @package Orga
 * Arbre des axes d'un organization.
 */
$editLabelInput = new GenericVoidTag('input');
$editLabelInput->setAttribute('name', 'editAxis_label');
$editLabelInput->setAttribute('type', 'text');
$editLabelInput->setAttribute('id', 'editAxis_label');
$editLabelInput->addClass('form-control');
$editLabelWrapper = new GenericTag('div', $editLabelInput);
$editLabelWrapper->addClass('col-xs-10');
$editLabelLabel = new GenericTag('label', ___('UI', 'name', 'label'));
$editLabelLabel->setAttribute('for', 'editAxis_label');
$editLabelLabel->addClass('control-label');
$editLabelLabel->addClass('col-xs-2');
$editLabelGroup = new GenericTag('div');
$editLabelGroup->addClass('form-group');
$editLabelGroup->appendContent($editLabelLabel);
$editLabelGroup->appendContent($editLabelWrapper);

$editRefInput = new GenericVoidTag('input');
$editRefInput->setAttribute('name', 'editAxis_ref');
$editRefInput->setAttribute('type', 'text');
$editRefInput->setAttribute('id', 'editAxis_ref');
$editRefInput->addClass('form-control');
$editRefWrapper = new GenericTag('div', $editRefInput);
$editRefWrapper->addClass('col-xs-10');
$editRefLabel = new GenericTag('label', ___('UI', 'name', 'identifier'));
$editRefLabel->setAttribute('for', 'editAxis_ref');
$editRefLabel->addClass('control-label');
$editRefLabel->addClass('col-xs-2');
$editRefGroup = new GenericTag('div');
$editRefGroup->addClass('form-group');
$editRefGroup->appendContent($editRefLabel);
$editRefGroup->appendContent($editRefWrapper);

// $editContextualizingField = new UI_Form_Element_Radio('editAxis_contextualizing');
// $editContextualizingField->setLabel(___('Orga', 'axis', 'contextualizingLabel'));
// $optionContextualizing = new UI_Form_Element_Option('editAxis_contextualizing', 'contextualizing', ___('Orga', 'axis', 'contextualizingOption'));
// $editContextualizingField->addOption($optionContextualizing);
// $optionNoneContextualizing = new UI_Form_Element_Option('editAxis_noneContextualizing', 'noneContextualizing', ___('Orga', 'axis', 'notContextualizingOption'));
// $editContextualizingField->addOption($optionNoneContextualizing);
// $editContextualizingField->setValue('noneContextualizing');

$addLabelInput = new GenericVoidTag('input');
$addLabelInput->setAttribute('name', 'addAxis_label');
$addLabelInput->setAttribute('type', 'text');
$addLabelInput->setAttribute('id', 'addAxis_label');
$addLabelInput->addClass('form-control');
$addLabelWrapper = new GenericTag('div', $addLabelInput);
$addLabelWrapper->addClass('col-xs-10');
$addLabelLabel = new GenericTag('label', ___('UI', 'name', 'label'));
$addLabelLabel->setAttribute('for', 'addAxis_label');
$addLabelLabel->addClass('control-label');
$addLabelLabel->addClass('col-xs-2');
$addLabelGroup = new GenericTag('div');
$addLabelGroup->addClass('form-group');
$addLabelGroup->appendContent($addLabelLabel);
$addLabelGroup->appendContent($addLabelWrapper);

$addRefInput = new GenericVoidTag('input');
$addRefInput->setAttribute('name', 'addAxis_ref');
$addRefInput->setAttribute('type', 'text');
$addRefInput->setAttribute('id', 'addAxis_ref');
$addRefInput->addClass('form-control');
$addRefWrapper = new GenericTag('div', $addRefInput);
$addRefWrapper->addClass('col-xs-10');
$addRefLabel = new GenericTag('label', ___('UI', 'name', 'identifier'));
$addRefLabel->setAttribute('for', 'addAxis_ref');
$addRefLabel->addClass('control-label');
$addRefLabel->addClass('col-xs-2');
$addRefGroup = new GenericTag('div');
$addRefGroup->addClass('form-group');
$addRefGroup->appendContent($addRefLabel);
$addRefGroup->appendContent($addRefWrapper);

// $addContextualizingField = new UI_Form_Element_Radio('addAxis_contextualizing');
// $addContextualizingField->setLabel(___('Orga', 'axis', 'contextualizingLabel'));
// $optionContextualizing = new UI_Form_Element_Option('addAxis_contextualizing', 'contextualizing', ___('Orga', 'axis', 'contextualizingOption'));
// $addContextualizingField->addOption($optionContextualizing);
// $optionNoneContextualizing = new UI_Form_Element_Option('addAxis_noneContextualizing', 'noneContextualizing', ___('Orga', 'axis', 'notContextualizingOption'));
// $addContextualizingField->addOption($optionNoneContextualizing);
// $addContextualizingField->setValue('noneContextualizing');

$addParentInput = new GenericTag('select');
$addParentInput->setAttribute('name', 'addAxis_parent');
$addParentInput->setAttribute('type', 'text');
$addParentInput->setAttribute('id', 'addAxis_parent');
$addParentInput->addClass('form-control');
$optionParent = new GenericTag('option');
$optionParent->setAttribute('value', '');
$addParentInput->appendContent($optionParent);
foreach ($this->eligibleParents as $parentAxis) {
    /** @var Orga_Model_Axis $parentAxis */
    $optionParent = new GenericTag('option', $this->translate($parentAxis->getLabel()));
    $optionParent->setAttribute('value', $parentAxis->getRef());
    $addParentInput->appendContent($optionParent);
}
$addParentWrapper = new GenericTag('div', $addParentInput);
$addParentWrapper->addClass('col-xs-10');
$addParentLabel = new GenericTag('label', ___('Orga', 'axis', 'parentAxisLabel'));
$addParentLabel->setAttribute('for', 'addAxis_parent');
$addParentLabel->addClass('control-label');
$addParentLabel->addClass('col-xs-2');
$addParentGroup = new GenericTag('div');
$addParentGroup->addClass('form-group');
$addParentGroup->appendContent($addParentLabel);
$addParentGroup->appendContent($addParentWrapper);

$addForm = new GenericTag('form');
$addForm->appendContent($addLabelGroup);
$addForm->appendContent($addRefGroup);
//$addForm->appendContent($addContextualizingGroup);
$addForm->appendContent($addParentGroup);

$treeManage = new UI_Tree('editAxis', 'tree_axis', 'orga');
if ($this->idCell !== null) {
    $treeManage->addParam('idCell', $this->idCell);
}
$treeManage->addParam('idOrganization', $this->idOrganization);
$treeManage->addNode = true;
$treeManage->addPanelForm = $addForm;
$treeManage->addPanelTitle = ___('Orga', 'axis', 'addPanelTitle');
$treeManage->editPanelTitle = ___('Orga', 'axis', 'editPanelTitle');
$treeManage->setEditNode(false, true, [$editLabelGroup, $editRefGroup]);
$treeManage->deleteNode = true;
$treeManage->expandAll = false;
$treeManage->collapseAll = false;
if ($this->display === false) {
    echo $treeManage->render();
} else {
    $treeManage->display();
}

$script = '';
$script .= '$(\'#editAxis_element\').change(function(e) {';
$script .= 'var idNode = $(this).val();';
$script .= '$.get(';
$script .= '\'orga/tree_axis/getinfoedit?idOrganization='.$this->idOrganization.'&idNode=\' + idNode, ';
$script .= 'function(o){';
$script .= '$(\'#editAxis_label\').val(o.label);';
$script .= '$(\'#editAxis_ref\').val(o.ref);';
$script .= 'if (o.contextualizing === "contextualizing") {';
$script .= '$(\'#editAxis_contextualizing_contextualizing\').attr(\'checked\', true);';
$script .= '$(\'#editAxis_contextualizing_noneContextualizing\').attr(\'checked\', false);';
$script .= '} else {';
$script .= '$(\'#editAxis_contextualizing_contextualizing\').attr(\'checked\', false);';
$script .= '$(\'#editAxis_contextualizing_noneContextualizing\').attr(\'checked\', true);';
$script .= '}';
$script .= '}';
$script .= ').error(function(o) {';
$script .= 'errorHandler(o);';
$script .= '});';
$script .= '});';
$script .= '$(\'#editAxis_addPanel\').on(\'show.bs.modal\', function(e) {';
$script .= '$.get(';
$script .= '\'orga/tree_axis/getlistparents?idOrganization='.$this->idOrganization.'&idNode=\', ';
$script .= 'function(o){';
$script .= '$(\'#addAxis_parent\').formActionSetOptions(o);';
$script .= '}';
$script .= ').error(function(o) {';
$script .= 'errorHandler(o);';
$script .= '});';
$script .= '});';
$script .= 'refFromLabel(\'addAxis_label\', \'addAxis_ref\');';
if ($this->display === false) {
    echo '<script type="text/javascript">'.$script.'</script>';
} else {
    $this->headScript()->appendFile('scripts/ui/refRefactor.js', 'text/javascript');
    $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
}
