<?php
/**
 * @author valentin.claras
 * @author sidoine.tardieu
 * @package Orga
 * Arbre des axes d'un organization.
 */
$editLabelField = new UI_Form_Element_Text('editAxis_label');
$editLabelField->setLabel(___('UI', 'name', 'label'));

$editRefField = new UI_Form_Element_Text('editAxis_ref');
$editRefField->setLabel(___('UI', 'name', 'identifier'));

// $editContextualizingField = new UI_Form_Element_Radio('editAxis_contextualizing');
// $editContextualizingField->setLabel(___('Orga', 'axis', 'contextualizingLabel'));
// $optionContextualizing = new UI_Form_Element_Option('editAxis_contextualizing', 'contextualizing', ___('Orga', 'axis', 'contextualizingOption'));
// $editContextualizingField->addOption($optionContextualizing);
// $optionNoneContextualizing = new UI_Form_Element_Option('editAxis_noneContextualizing', 'noneContextualizing', ___('Orga', 'axis', 'notContextualizingOption'));
// $editContextualizingField->addOption($optionNoneContextualizing);
// $editContextualizingField->setValue('noneContextualizing');

$addLabelField = new UI_Form_Element_Text('addAxis_label');
$addLabelField->setLabel(___('UI', 'name', 'label'));

$addRefField = new UI_Form_Element_Text('addAxis_ref');
$addRefField->setLabel(___('UI', 'name', 'identifier'));

// $addContextualizingField = new UI_Form_Element_Radio('addAxis_contextualizing');
// $addContextualizingField->setLabel(___('Orga', 'axis', 'contextualizingLabel'));
// $optionContextualizing = new UI_Form_Element_Option('addAxis_contextualizing', 'contextualizing', ___('Orga', 'axis', 'contextualizingOption'));
// $addContextualizingField->addOption($optionContextualizing);
// $optionNoneContextualizing = new UI_Form_Element_Option('addAxis_noneContextualizing', 'noneContextualizing', ___('Orga', 'axis', 'notContextualizingOption'));
// $addContextualizingField->addOption($optionNoneContextualizing);
// $addContextualizingField->setValue('noneContextualizing');

$addParentField = new UI_Form_Element_Select('addAxis_parent');
$addParentField->setLabel(___('Orga', 'axis', 'parentAxisLabel'));
$addParentField->addNullOption('');
foreach ($this->eligibleParents as $parentAxis) {
    $optionParent = new UI_Form_Element_Option($parentAxis->getRef(), $parentAxis->getRef(), $parentAxis->getLabel());
    $addParentField->addOption($optionParent);
}

$addForm = new UI_Form('editAxis_addForm');
$addForm->addElement($addLabelField);
$addForm->addElement($addRefField);
// $addForm->addElement($addContextualizingField);
$addForm->addElement($addParentField);

$treeManage = new UI_Tree('editAxis', 'tree_axis', 'orga');
if ($this->idCell !== null) {
    $treeManage->addParam('idCell', $this->idCell);
}
$treeManage->addParam('idOrganization', $this->idOrganization);
$treeManage->addNode = true;
$treeManage->addPanelForm = $addForm;
$treeManage->addPanelTitle = ___('Orga', 'axis', 'addPanelTitle');
$treeManage->editPanelTitle = ___('Orga', 'axis', 'editPanelTitle');
$treeManage->setEditNode(false, true, array($editLabelField, $editRefField));
$treeManage->deleteNode = true;
$treeManage->expandAll = false;
$treeManage->collapseAll = false;
if ($this->display === false) {
    echo $treeManage->render();
} else {
    $treeManage->display();
}

$script = '';
$script .= '$(\'#editAxis_element\').change(function(e) {';
$script .= 'var idNode = $(this).val();';
$script .= '$.get(';
$script .= '\'orga/tree_axis/getinfoedit?idOrganization='.$this->idOrganization.'&idNode=\' + idNode, ';
$script .= 'function(o){';
$script .= '$(\'#editAxis_label\').val(o.label);';
$script .= '$(\'#editAxis_ref\').val(o.ref);';
$script .= 'if (o.contextualizing === "contextualizing") {';
$script .= '$(\'#editAxis_contextualizing_contextualizing\').attr(\'checked\', true);';
$script .= '$(\'#editAxis_contextualizing_noneContextualizing\').attr(\'checked\', false);';
$script .= '} else {';
$script .= '$(\'#editAxis_contextualizing_contextualizing\').attr(\'checked\', false);';
$script .= '$(\'#editAxis_contextualizing_noneContextualizing\').attr(\'checked\', true);';
$script .= '}';
$script .= '}';
$script .= ').error(function(o) {';
$script .= 'errorHandler(o);';
$script .= '});';
$script .= '});';
$script .= '$(\'#editAxis_addPanel\').on(\'show\', function(e) {';
$script .= '$.get(';
$script .= '\'orga/tree_axis/getlistparents?idOrganization='.$this->idOrganization.'&idNode=\', ';
$script .= 'function(o){';
$script .= '$(\'#addAxis_parent\').formActionSetOptions(o);';
$script .= '}';
$script .= ').error(function(o) {';
$script .= 'errorHandler(o);';
$script .= '});';
$script .= '});';
$script .= 'refFromLabel(\'addAxis_label\', \'addAxis_ref\');';
if ($this->display === false) {
    echo '<script type="text/javascript">'.$script.'</script>';
} else {
    $this->headScript()->appendFile('scripts/ui/refRefactor.js', 'text/javascript');
    $this->headScript()->appendScript('$(document).ready(function(){'.$script.'});');
}
