<?php
if ($this->isUserAbleToComment) {
    echo $this->partial('comment/list.phtml',
        'social',
        array(
            'comments' => $this->comments,
            'endpointAdd' => 'inventory/tab_input/comment-add/idCell/'.$this->idCell,
        )
    );
} else {
    echo $this->partial('comment/list.phtml',
        'social',
        array(
            'comments' => $this->comments,
        )
    );
}