<?php
use AF\Domain\AF;
use AF\Domain\Component\Select;
use AF\Domain\Component\Select\SelectMulti;
use Parameter\Domain\Family\Family;

/** @var $selectField Select */
$selectField = $this->selectField;
/** @var $af AF */
$af = $this->af;
/** @var Family[] $families */
$families = $this->families;

//Datagrid des options de select
$optionDatagrid = new UI_Datagrid('optionDatagrid', 'datagrid_edit_components_select-options', 'af');
$optionDatagrid->pagination = false;
$optionDatagrid->addParam('idAF', $af->getId());
$optionDatagrid->addParam('idSelect', $selectField->getId());
$optionDatagrid->addElements = true;
$optionDatagrid->addButtonLabel = __('AF', 'configComponentDatagrid', 'optionSelectAddPanelTitle');
$optionDatagrid->addPanelTitle = __('AF', 'configComponentDatagrid', 'optionSelectAddPanelTitle');
$optionDatagrid->deleteElements = true;

$labelColumn = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$labelColumn->editable = true;
$optionDatagrid->addCol($labelColumn);

$refColumn = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$refColumn->editable = true;
$optionDatagrid->addCol($refColumn);

// Si il s'agit d'une selection multiple on précise si l'option fait partie de la séléction par défaut
if ($selectField instanceof SelectMulti) {
    $defaultValueColumn = new UI_Datagrid_Col_Bool('defaultValue', __('AF', 'configComponentDatagrid', 'initialValueHeader'));
    $defaultValueColumn->editable = true;
    $defaultValueColumn->textTrue = __('UI', 'property', 'selectedFem');
    $defaultValueColumn->textFalse = __('UI', 'property', 'notSelectedFem');
    $defaultValueColumn->valueTrue = __('UI', 'property', 'selectedFem');
    $defaultValueColumn->valueFalse = __('UI', 'property', 'notSelectedFem');
    $optionDatagrid->addCol($defaultValueColumn);
}

$orderColumn = new UI_Datagrid_Col_Order('order');
$orderColumn->addable = false;
$orderColumn->editable = true;
$optionDatagrid->addCol($orderColumn);

echo $optionDatagrid->render();
?>

<hr>
<p><?=___('AF', 'configComponentDatagrid', 'copyTechnoMembersAsOptions')?></p>

<form class="form-inline" id="copyTechnoMembersAsOptions"
      action="af/edit_components/copy-techno-members-as-options?idSelect=<?=$selectField->getId()?>&idAF=<?=$af->getId()?>">
    <div class="input-append">
        <select name="dimension" class="form-control">
            <?php foreach ($families as $family) : ?>
                <?php foreach ($family->getDimensions() as $dimension) : ?>
                    <option value="<?=$dimension->getId()?>">
                        <?=$this->translate($family->getLibrary()->getLabel())?>
                        >
                        <?=$this->translate($family->getLabel())?>
                        >
                        <?=$this->translate($dimension->getLabel())?>
                    </option>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </select>
        <button type="submit" class="btn btn-default"><i class="fa fa-plus-circle"></i> Ajouter</button>
    </div>
</form>
