<?php
use AF\Domain\AF;
use AF\Domain\Component\SubAF;
use AF\Domain\Component\SubAF\RepeatedSubAF;

/**
 * Sous-AF de l'onglet "Composants"
 * @author  matthieu.napoli
 * @author  yoann.croizer
 * @package AF
 */
/** @var $af AF */
$af = $this->af;

// Datagrid
$datagrid = new UI_Datagrid('subAfRepeatedDatagrid', 'datagrid_edit_components_sub-af-repeated', 'af');
$datagrid->initialLoading = false;
$datagrid->addParam('id', $af->getId());
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('AF', 'configComponentDatagrid', 'repeatedSubformAddPanelTitle');
$datagrid->deleteElements = true;

// Label
$subafLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$subafLabel->editable = true;
$datagrid->addCol($subafLabel);
// Ref
$subafRef = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$subafRef->editable = true;
$datagrid->addCol($subafRef);
// Ref du formulaire associé
$targetAF = new UI_Datagrid_Col_List('targetAF', __('AF', 'configComponentDatagrid', 'associatedFormHeader'));
$targetAF->list = [];
foreach (AF::loadList() as $currentAf) {
    /** @var $currentAf AF */
    if ($currentAf->getId() != $af->getId()) {
        $targetAF->list[$currentAf->getId()] = $currentAf->getLabel();
    }
}
$targetAF->withEmptyElement = false;
$targetAF->editable = true;
$datagrid->addCol($targetAF);
// Help
$help = new UI_Datagrid_Col_LongText('help', __('UI', 'name', 'help'));
$help->editable = true;
$help->popup->title = __('UI', 'name', 'help');
$datagrid->addCol($help);
// Hidden / Show
$isVisible = new UI_Datagrid_Col_Bool('isVisible', __('AF', 'configComponentDatagrid', 'initialVisibilityHeader'));
$isVisible->editable = true;
$isVisible->defaultAddValue = true;
$isVisible->textTrue = __('UI', 'property', 'visible');
$isVisible->textFalse = __('UI', 'property', 'masked');
$isVisible->valueTrue = '<i class="fa fa-check"></i> '.__('UI', 'property', 'visible');
$isVisible->valueFalse = '<i class="fa fa-times"></i> '.__('UI', 'property', 'masked');
$datagrid->addCol($isVisible);
// Foldaway / Unfodaway
$foldaway = new UI_Datagrid_Col_List('foldaway', __('AF', 'configComponentDatagrid', 'foldawayHeader'));
$foldaway->editable = true;
$foldaway->defaultAddValue = SubAF::FOLDAWAY;
$foldaway->withEmptyElement = false;
$foldaway->list = [
    SubAF::UNFOLDAWAY => __('UI', 'property', 'nonFoldaway'),
    SubAF::FOLDAWAY   => __('UI', 'property', 'foldaway'),
    SubAF::FOLDED     => __('UI', 'property', 'folded'),
];
//$datagrid->addCol($foldaway);
// Repeated or Not
$isRepeated = new UI_Datagrid_Col_List('repetition', __('AF', 'configComponentDatagrid', 'numberInitialRepetitionHeader'));
$isRepeated->editable = true;
$isRepeated->withEmptyElement = false;
$isRepeated->list = array(
    RepeatedSubAF::MININPUTNUMBER_0               => __(
        'AF',
        'configComponentDatagrid',
        'zeroItemOption'
    ),
    RepeatedSubAF::MININPUTNUMBER_1_NOT_DELETABLE => __(
        'AF',
        'configComponentDatagrid',
        'oneSuppressibleItemOption'
    ),
    RepeatedSubAF::MININPUTNUMBER_1_DELETABLE     => __(
        'AF',
        'configComponentDatagrid',
        'oneUnsuppressibleItemOption'
    )
);
$datagrid->addCol($isRepeated);
// Has Free Label
$hasFreeLabel = new UI_Datagrid_Col_Bool('hasFreeLabel', __('AF', 'configComponentDatagrid', 'freeLabelHeader'));
$hasFreeLabel->editable = true;
$hasFreeLabel->textTrue = __('UI', 'other', 'yes');
$hasFreeLabel->textFalse = __('UI', 'other', 'no');
$hasFreeLabel->valueTrue = '<i class="fa fa-check"></i> '.__('UI', 'other', 'yes');
$hasFreeLabel->valueFalse = '<i class="fa fa-times"></i> '.__('UI', 'other', 'no');
$datagrid->addCol($hasFreeLabel);

echo $datagrid->render();
?>
<script type="text/javascript">
    $(document).ready(function() { refFromLabel('subAfRepeatedDatagrid_label_addForm', 'subAfRepeatedDatagrid_ref_addForm') });
</script>
