<?php
use AF\Domain\AF;

/**
 * @author matthieu.napoli
 * @author hugo.charbonnier
 * @package AF
 */
/** @var $af \AF\Domain\AF */
$af = $this->af;
$script = '';


// Groupes
$groups = new UI_HTML_Collapse('groups');
$groups->foldedByDefault = true;
$groups->title = __('AF', 'configComponentCollapse', 'groupCollapse');
$groups->body = $this->partial('edit/components/groups.phtml', array('af' => $this->af));
echo $groups->render();

$script .= <<<JS
$('#groups').on('show', function(e) {
    if ($(e.target).attr('id') == 'groups_wrapper') {
        groupDatagrid.filter();
    }
});
JS;


// Sous-formulaires non répétés
$subAFNotRepeated = new UI_HTML_Collapse('subAFNotRepeated');
$subAFNotRepeated->foldedByDefault = true;
$subAFNotRepeated->title = __('AF', 'configComponentCollapse', 'nonRepeatedSubFormCollapse');
$subAFNotRepeated->body = $this->partial('edit/components/sub-af-not-repeated.phtml', array('af' => $this->af));
echo $subAFNotRepeated->render();

$script .= <<<JS
$('#subAFNotRepeated').on('show', function(e) {
    if ($(e.target).attr('id') == 'subAFNotRepeated_wrapper') {
        subAfNotRepeatedDatagrid.filter();
    }
});
JS;


// Sous-formulaires répétés
$subAFRepeated = new UI_HTML_Collapse('subAFRepeated');
$subAFRepeated->foldedByDefault = true;
$subAFRepeated->title = __('AF', 'configComponentCollapse', 'repeatedSubFormCollapse');
$subAFRepeated->body = $this->partial('edit/components/sub-af-repeated.phtml', array('af' => $this->af));
echo $subAFRepeated->render();

$script .= <<<JS
$('#subAFRepeated').on('show', function(e) {
    if ($(e.target).attr('id') == 'subAFRepeated_wrapper') {
        subAfRepeatedDatagrid.filter();
    }
});
JS;


// Champs numériques
$numericFields = new UI_HTML_Collapse('numericFields');
$numericFields->foldedByDefault = true;
$numericFields->title = __('AF', 'configComponentCollapse', 'numericInputFieldCollapse');
$numericFields->body = $this->partial('edit/components/numeric-fields.phtml', array('af' => $this->af));
echo $numericFields->render();

$script .= <<<JS
$('#numericFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'numericFields_wrapper') {
        numericFieldDatagrid.filter();
    }
});
JS;


// Champs de sélection simple
$selectSingleFields = new UI_HTML_Collapse('selectSingleFields');
$selectSingleFields->foldedByDefault = true;
$selectSingleFields->title = __('AF', 'configComponentCollapse', 'singleSelectionFieldCollapse');
$selectSingleFields->body = $this->partial('edit/components/select-single-fields.phtml', array('af' => $this->af));
echo $selectSingleFields->render();

$script .= <<<JS
$('#selectSingleFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'selectSingleFields_wrapper') {
        selectSingleFieldDatagrid.filter();
    }
});
JS;


// Champs de sélection multiple
$selectMultiFields = new UI_HTML_Collapse('selectMultiFields');
$selectMultiFields->foldedByDefault = true;
$selectMultiFields->title = __('AF', 'configComponentCollapse', 'multipleSelectionFieldCollapse');
$selectMultiFields->body = $this->partial('edit/components/select-multi-fields.phtml', array('af' => $this->af));
echo $selectMultiFields->render();

$script .= '$(\'#selectMultiFields\').on(\'show\', function(e) {';
$script .= 'if ($(e.target).attr(\'id\') == \'selectMultiFields_wrapper\') {';
$script .= 'selectMultiFieldDatagrid.filter();';
$script .= '}';
$script .= '});';

$script .= <<<JS
$('#selectSingleFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'selectSingleFields_wrapper') {
        selectSingleFieldDatagrid.filter();
    }
});
JS;


// Checkbox
$checkboxFields = new UI_HTML_Collapse('checkboxFields');
$checkboxFields->foldedByDefault = true;
$checkboxFields->title = __('AF', 'configComponentCollapse', 'booleanFieldCollapse');
$checkboxFields->body = $this->partial('edit/components/checkbox-fields.phtml', array('af' => $this->af));
echo $checkboxFields->render();

$script .= <<<JS
$('#checkboxFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'checkboxFields_wrapper') {
        checkboxFieldDatagrid.filter();
    }
});
JS;


// Text
$textFields = new UI_HTML_Collapse('textFields');
$textFields->foldedByDefault = true;
$textFields->title = __('AF', 'configComponentCollapse', 'textFieldCollapse');
$textFields->body = $this->partial('edit/components/text-fields.phtml', array('af' => $this->af));
echo $textFields->render();

$script .= <<<JS
$('#textFields').on('show', function(e) {
    if ($(e.target).attr('id') == 'textFields_wrapper') {
        textFieldDatagrid.filter();
    }
});
JS;


echo '<script type="text/javascript">/*<![CDATA[*/'.$script.'/*]]>*/</script>';
