<?php
use AF\Domain\AF;
use MyCLabs\MUIH\Button;

/**
 * @author  matthieu.napoli
 * @author  hugo.charbonnier
 * @package AF
 */
/** @var $af AF */
$af = $this->af;

$controlButton = new Button(__('UI', 'verb', 'control'));
$controlButton->addClass('doControl');

?>

<p>
    <?=$controlButton->render();?>
</p>

<div id="controlResults"></div>

<script type="text/javascript">
    $(".doControl").click(function () {
        $("#controlResults")
                .empty()
                .load('af/edit/control-results/id/' + <?=$af->getId()?>);
    });
</script>
