<?php
/** @var $af \AF\Domain\AF */
$af = $this->af;
?>

<form id="editAF" class="form-horizontal" action="af/edit/general-submit?id=<?=$af->getId()?>" method="post">
    <div class="form-group">
        <label for="inputLabel" class="col-sm-2 control-label">
            <?=__('UI', 'name', 'label')?>
        </label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="inputLabel" name="label" value="<?=$this->translate($af->getLabel())?>">
        </div>
    </div>
    <div class="form-group">
        <label for="inputDocumentation" class="col-sm-2 control-label">
            <?=__('UI', 'name', 'documentation')?>
        </label>
        <div class="col-sm-10">
            <textarea class="form-control" id="inputDocumentation" name="documentation"
                      rows="4"><?=$af->getDocumentation()?></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-primary">
                <?=__('UI', 'verb', 'save')?>
            </button>
        </div>
    </div>
</form>

<script>
    $(function() {
        new AjaxForm('#editAF');
    });
</script>
