<?php
use AF\Domain\AF;
use MyCLabs\MUIH\Collapse;

/** @var $af AF */
$af = $this->af;

$script = '';


$actionsSetState = new Collapse('actionsSetState', __('AF', 'configInteractionCollapse', 'componentStateModificationCollapse'));
$actionsSetState->setContent($this->partial('edit/actions/set-state.phtml', [
    'af'            => $af,
    'componentList' => $this->componentList,
    'conditionList' => $this->conditionList
]));
echo $actionsSetState->render();

// FML
$script .= '$(\'#actionsSetState\').on(\'show.bs.collapse\', function(e) {';
$script .= 'if ($(e.target).attr(\'id\') == \'actionsSetState\') {';
$script .= 'actionsSetState.filter();';
$script .= '}';
$script .= '});';


$actionsSetValue = new Collapse('actionsSetValue', __('AF', 'configInteractionCollapse', 'fixedValueOrAlgorithmResultAssignmentCollapse'));
$actionsSetValue->setContent($this->partial('edit/actions/set-value.phtml', [
    'af'            => $af,
    'componentList' => $this->componentList,
    'conditionList' => $this->conditionList
]));
echo $actionsSetValue->render();

// FML
$script .= '$(\'#actionsSetValue\').on(\'show.bs.collapse\', function(e) {';
$script .= 'if ($(e.target).attr(\'id\') == \'actionsSetValue\') {';
$script .= 'actionsSetValue.filter();';
$script .= '}';
$script .= '});';


$conditionsExpression = new Collapse('conditionsExpression', __('AF', 'configInteractionCollapse', 'composedConditionCollapse'));
$conditionsExpression->setContent($this->partial('edit/conditions/expression.phtml', ['af' => $this->af]));
echo $conditionsExpression->render();

// FML
$script .= '$(\'#conditionsExpression\').on(\'show.bs.collapse\', function(e) {';
$script .= 'if ($(e.target).attr(\'id\') == \'conditionsExpression\') {';
$script .= 'conditionsExpression.filter();';
$script .= '}';
$script .= '});';


$conditionsElementary = new Collapse('conditionsElementary', __('AF', 'configInteractionCollapse', 'elementaryConditionCollapse'));
$conditionsElementary->setContent($this->partial('edit/conditions/elementary.phtml', ['af' => $af, 'componentList' => $this->componentList]));
echo $conditionsElementary->render();

// FML
$script .= '$(\'#conditionsElementary\').on(\'show.bs.collapse\', function(e) {';
$script .= 'if ($(e.target).attr(\'id\') == \'conditionsElementary\') {';
$script .= 'conditionsElementary.filter();';
$script .= '}';
$script .= '});';
?>

<script type="text/javascript">
    <?=$script?>
</script>
