<?php
// API Google pour les charts
use AF\Domain\AF;
use MyCLabs\MUIH\Button;
use MyCLabs\MUIH\Tab;
use MyCLabs\MUIH\Tabs;

$this->headScript()->appendFile('https://www.google.com/jsapi?autoload={"modules":[{"name":"visualization","version":"1","packages":["orgchart"]}]}', 'text/javascript');

/** @var $af AF */
$af = $this->af;
?>

<div class="navbar navbar-default">
    <div class="container">

        <div class="navbar-header">
            <a class="navbar-brand" href="#"><?=$af->getLabel()?></a>
        </div>

        <ul class="nav">
            <li class="active">
                <a href="#"><?= __('UI', 'name', 'configuration');?></a>
            </li>
            <li>
                <a href="<?=$this->baseUrl()?>/af/af/test/id/<?=$af->getId()?>">
                    <?= __('UI', 'name', 'test');?></a>
            </li>
        </ul>

    </div>
</div>

<?php
UI_Datagrid::addHeader();
UI_Popup_Generic::addHeader();
UI_Form::addHeader();
UI_Tree::addHeader();

$tabView = new Tabs();

// Général
$general = new Tab('container_general');
$general->setTitle(__('AF', 'configTab', 'general'));
$general->setContent('af/edit/general-tab/id/' . $af->getId());
$general->setAjax(true, true);
if (!isset($this->onglet)) {
    $general->active();
}

// Structure
$structure = new Tab('container_structure');
$structure->setTitle(__('AF', 'configTab', 'structure'));
$structure->setContent('af/edit/structure/id/' . $af->getId());
$structure->setAjax(true, false);

// Composants
$element = new Tab('container_component');
if (isset($this->onglet) && $this->onglet == 'component') {
    $element->active();
}
$element->setTitle(__('AF', 'configTab', 'components'));
$element->setContent('af/edit/components/id/' . $af->getId());
$element->setAjax(true, true);

// Interactions
$interaction = new Tab('container_interaction');
if (isset($this->onglet) && $this->onglet == 'interaction') {
    $interaction->active();
}
$interaction->setTitle(__('AF', 'configTab', 'interactions'));
$interaction->setContent('af/edit/interactions/id/' . $af->getId());
$interaction->setAjax(true, true);

// Traitements
$traitement = new Tab('container_traitement');
$traitement->setTitle(__('AF', 'configTab', 'treatment'));
$traitement->setContent('af/edit/traitement/id/' . $af->getId());
$traitement->setAjax(true, true);
if (isset($this->onglet) && $this->onglet == 'traitement') {
    $traitement->active();
}

// Controle
$control = new Tab('container_control');
$control->setTitle(__('AF', 'configTab', 'control'));
$control->setContent('af/edit/control/id/' . $af->getId());
$control->setAjax(true, true);
if (isset($this->onglet) && $this->onglet == 'control') {
    $control->active();
}

// Ajout des tabs à l'ensemble.
$tabView->addTab($general);
$tabView->addTab($structure);
$tabView->addTab($element);
$tabView->addTab($interaction);
$tabView->addTab($traitement);
$tabView->addTab($control);

// Affichage du TabView.
$tabView->display();
?>

<div class="well">
    <?php
    $quitButton = new Button(__('UI', 'verb', 'quit'));
    $quitButton->link('af/af/list');
    $quitButton->display();
    ?>
</div>
