<?php
use AF\Domain\AF;
use MyCLabs\MUIH\Tab;
use MyCLabs\MUIH\Tabs;

// API Google pour les charts
$this->headScript()->appendFile('https://www.google.com/jsapi?autoload={"modules":[{"name":"visualization","version":"1","packages":["orgchart"]}]}', 'text/javascript');

/** @var $af AF */
$af = $this->af;
?>

<div class="navbar navbar-default">
    <div class="container">

        <div class="navbar-header">
            <a class="navbar-brand" href="#"><?=$af->getLabel()?></a>
        </div>

        <ul class="nav navbar-nav">
            <li class="active">
                <a href="#"><?= __('UI', 'name', 'configuration');?></a>
            </li>
            <li>
                <a href="<?=$this->baseUrl()?>/af/af/test/id/<?=$af->getId()?>">
                    <?= __('UI', 'name', 'test');?></a>
            </li>
        </ul>

    </div>
</div>

<?php
UI_Datagrid::addHeader();
UI_Popup_Generic::addHeader();
UI_Form::addHeader();
UI_Tree::addHeader();

$tabView = new Tabs();

// Général
$general = new Tab('container_general');
$general->setTitle(__('AF', 'configTab', 'general'));
$general->setContent($this->partial('edit/general-tab.phtml', ['af' => $af]));

// Structure
$structure = new Tab('container_structure');
$structure->setTitle(__('AF', 'configTab', 'structure'));
$structure->setContent($this->partial('edit/structure.phtml', ['af' => $af]));

// Composants
$element = new Tab('container_component');
$element->setTitle(__('AF', 'configTab', 'components'));
$element->setContent($this->partial('edit/components.phtml', ['af' => $af]));

// Interactions
$interaction = new Tab('container_interaction');
$interaction->setTitle(__('AF', 'configTab', 'interactions'));
$interaction->setContent('af/edit/interactions/id/' . $af->getId());
$interaction->setAjax(true, true);

// Traitements
$traitement = new Tab('container_traitement');
$traitement->setTitle(__('AF', 'configTab', 'treatment'));
$traitement->setContent('af/edit/traitement/id/' . $af->getId());
$traitement->setAjax(true, true);

// Controle
$control = new Tab('container_control');
$control->setTitle(__('AF', 'configTab', 'control'));
$control->setContent($this->partial('edit/control.phtml', ['af' => $af]));

// Ajout des tabs à l'ensemble.
$tabView->addTab($general);
$tabView->addTab($structure);
$tabView->addTab($element);
$tabView->addTab($interaction);
$tabView->addTab($traitement);
$tabView->addTab($control);
if (!isset($this->onglet)) {
    $tabView->activeTab($general);
} else {
    switch ($this->onglet) {
        case 'component':
            $tabView->activeTab($element);
            break;
        case 'interaction':
            $tabView->activeTab($interaction);
            break;
        case 'traitement':
            $tabView->activeTab($traitement);
            break;
        case 'control':
            $tabView->activeTab($control);
            break;
    }
}

// Affichage du TabView.
$tabView->display();
