<?php
/**
 * @author valentin.claras
 * @author cyril.perraud
 * @package Classif
 * Contenu de l'onglet des membres
 */
use Classif\Domain\Context;

?>
<div class="page-header">
	<h1><?=__('Classif', 'context', 'pageTitle')?></h1>
</div>
<?
    $datagrid = new UI_Datagrid('editContexts', 'datagrid_context', 'classif');

    $columnLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
    $columnLabel->editable = true;
    $datagrid->addCol($columnLabel);

    $columnRef = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
    $columnRef->editable = true;
    $datagrid->addCol($columnRef);

    $columnPosition = new UI_Datagrid_Col_Order('position');
    $columnPosition->editable = true;
    $columnPosition->addable = false;
    $columnPosition->sortName = Context::QUERY_POSITION;
    $datagrid->addCol($columnPosition);

    $datagrid->deleteElements = true;
    $datagrid->addElements = true;
    $datagrid->addPanelTitle = __('Classif', 'context', 'addPanelTitle');
    $datagrid->setDefaultSorting($columnPosition->id);
    $datagrid->display();
