<?php
/**
 * Vue en consultation presentant les association dans une datagrid.
 * @author valentin.claras
 * @author bertrand.ferry
 * @package Keyword
 */

use Keyword\Domain\KeywordRepository;
use Keyword\Domain\PredicateRepository;
use Keyword\Domain\AssociationRepository;
?>
<div class="page-header">
	<h1><?=__('Keyword', 'relation', 'pageTitle')?></h1>
</div>
<?php
    $datagrid = new UI_Datagrid('association', 'datagrid_association', 'keyword');

    $columnSubject = new UI_Datagrid_Col_List('subject', __('Keyword', 'name', 'subject'));
    $columnSubject->list = $this->listKeywords;
    $columnSubject->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
    $columnSubject->sortName = KeywordRepository::QUERY_LABEL;
    $columnSubject->filterName = KeywordRepository::QUERY_REF;
    $columnSubject->filterOperator = Core_Model_Filter::OPERATOR_CONTAINS;
    $columnSubject->keywordFilterEqual = __('UI', 'datagridFilter', 'ColTextEqual');
    $columnSubject->entityAlias = AssociationRepository::QUERY_KEYWORD_SUBJECT;

    $columnObject = new UI_Datagrid_Col_List('object', __('Keyword', 'name', 'object'));
    $columnObject->list = $this->listKeywords;
    $columnObject->fieldType = UI_Datagrid_Col_List::FIELD_AUTOCOMPLETE;
    $columnObject->sortName = KeywordRepository::QUERY_LABEL;
    $columnObject->filterName = KeywordRepository::QUERY_REF;
    $columnObject->filterOperator = Core_Model_Filter::OPERATOR_CONTAINS;
    $columnObject->keywordFilterEqual = __('UI', 'datagridFilter', 'ColTextEqual');
    $columnObject->entityAlias = AssociationRepository::QUERY_KEYWORD_OBJECT;

    $columnPredicate = new UI_Datagrid_Col_List('predicate', __('Keyword', 'name', 'predicate'));
    $columnPredicate->list = $this->listPredicates;
    $columnPredicate->sortName = PredicateRepository::QUERY_LABEL;
    $columnPredicate->filterName = PredicateRepository::QUERY_REF;
    $columnPredicate->entityAlias = AssociationRepository::QUERY_PREDICATE;

    $datagrid->addCol($columnSubject);
    $datagrid->addCol($columnPredicate);
    $datagrid->addCol($columnObject);

    $datagrid->setDefaultSorting('predicate');
    $datagrid->display();
