<?php
/**
 * Popup d'affichage d'une expression
 * @author  matthieu.napoli
 * @author  yoann.croizer
 * @package AF
 */

/** @var $algo Algo_Model_Numeric_Expression */
$algo = $this->algo;

$expression = new TEC_Model_Expression($algo->getExpression(), TEC_Model_Expression::TYPE_NUMERIC);
$graphExpression = $expression->getGraph();
?>

<code><?=$algo->getExpression()?></code>

<hr>

<div id="graph_<?=$algo->getRef()?>"></div>

<script>
    $(function() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Feuille');
        data.addColumn('string', 'Noeud');
        data.addColumn('string', 'Attribut');
        data.addRows([<?=$graphExpression?>]);
        var chart = new google.visualization.OrgChart(document.getElementById('graph_<?=$algo->getRef()?>'));
        chart.draw(data, {allowHtml:true, allowCollapse:true});
    });
</script>
