<?php
/**
 * Vue en consultation presentant les predicats dans une datagrid.
 * @author valentin.claras
 * @author bertrand.ferry
 * @package Keyword
 */

use Keyword\Domain\Predicate;
?>
<div class="page-header">
	<h1><?=__('Keyword', 'name', 'predicates')?></h1>
</div>
<?php
    $datagrid = new UI_Datagrid('predicates', 'datagrid_predicate', 'keyword');

    $columnLabel = new UI_Datagrid_Col_Text('label', __('Keyword', 'predicate', 'directPredicateLabelHeader'));
    $columnLabel->sortName = Predicate::QUERY_LABEL;
    $columnLabel->filterName = Predicate::QUERY_LABEL;

    $columnRef = new UI_Datagrid_Col_Text('ref', __('Keyword', 'predicate', 'directPredicateIdentifierHeader'));
    $columnRef->sortName = Predicate::QUERY_REF;
    $columnRef->filterName = Predicate::QUERY_REF;
    $columnRef->editable = true;

    $columnReverseLabel = new UI_Datagrid_Col_Text('reverseLabel', __('Keyword', 'predicate', 'reversePredicateLabelHeader'));
    $columnReverseLabel->sortName = Predicate::QUERY_REVERSE_LABEL;
    $columnReverseLabel->filterName = Predicate::QUERY_REVERSE_LABEL;

    $columnReverseRef = new UI_Datagrid_Col_Text('reverseRef', __('Keyword', 'predicate', 'reversePredicateIdentifierHeader'));
    $columnReverseRef->sortName = Predicate::QUERY_REVERSE_REF;
    $columnReverseRef->filterName = Predicate::QUERY_REVERSE_REF;

    $columnDescription = new UI_Datagrid_Col_LongText('predicateDescription', __('UI', 'name', 'description'));
    $columnDescription->popup->title = __('UI', 'name', 'description');
    $columnDescription->defaultValue = '<i class="icon-zoom-in"></i> ' . __('UI', 'name', 'description');

    $datagrid->addCol($columnLabel);
    $datagrid->addCol($columnRef);
    $datagrid->addCol($columnReverseLabel);
    $datagrid->addCol($columnReverseRef);
    $datagrid->addCol($columnDescription);

    $datagrid->setDefaultSorting('label');
    $datagrid->display();
