<?php
$datagrid = new UI_Datagrid('users', 'datagrid_message_contact_user', 'social');
$datagrid->pagination = true;

// Prénom
$firstNameColumn = new UI_Datagrid_Col_Text('firstName', __('User', 'name', 'firstName'));
$firstNameColumn->filterName = User_Model_User::QUERY_FIRSTNAME;
$datagrid->addCol($firstNameColumn);

// Nom
$lastNameColumn = new UI_Datagrid_Col_Text('lastName', __('User', 'name', 'lastName'));
$lastNameColumn->filterName = User_Model_User::QUERY_LASTNAME;
$datagrid->addCol($lastNameColumn);

// Adresse mail
$emailColumn = new UI_Datagrid_Col_Text('email', __('UI', 'name', 'emailAddress'));
$emailColumn->filterName = User_Model_User::QUERY_EMAIL;
$datagrid->addCol($emailColumn);

// Infos
$detailsColumn = new UI_Datagrid_Col_Popup('details', __('UI', 'name', 'informations'));
$detailsColumn->popup->title = __('UI', 'name', 'informations');
$datagrid->addCol($detailsColumn);

// Nouveau message
$newMessageColumn = new UI_Datagrid_Col_Link('newMessage', __('Social', 'contact', 'sendMessageTo'));
$datagrid->addCol($newMessageColumn);

echo $datagrid->render();
