<?php
use MyCLabs\MUIH\GenericTag;

$datagrid = new UI_Datagrid('usergroups', 'datagrid_message_contact_user-group', 'social');
$datagrid->pagination = true;

// Nom
$labelColumn = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$labelColumn->sortName = Social_Model_UserGroup::QUERY_LABEL;
$labelColumn->filterName = Social_Model_UserGroup::QUERY_LABEL;
$datagrid->addCol($labelColumn);

// Détails
$detailsColumn = new UI_Datagrid_Col_Popup('details', __('UI', 'name', 'members'));
$detailsColumn->editable = false;
$detailsColumn->filterName = Social_Model_Message::QUERY_USER_RECIPIENTS;
$detailsColumn->popup->setHeaderContent(new GenericTag('h4', __('UI', 'name', 'members')));
$datagrid->addCol($detailsColumn);

// Nouveau message
$newMessageColumn = new UI_Datagrid_Col_Link('newMessage', __('Social', 'contact', 'sendMessageTo'));
$datagrid->addCol($newMessageColumn);

echo $datagrid->render();
