<?php
/**
 * Configuration des groupes d'un AF
 * @author  matthieu.napoli
 * @author  yoann.croizer
 * @package AF
 */
/** @var $af AF_Model_AF */
$af = $this->af;

// Datagrid
$groupDatagrid = new UI_Datagrid('groupDatagrid', 'datagrid_edit_components_groups', 'af');
$groupDatagrid->initialLoading = false;
$groupDatagrid->addParam('id', $af->getId());
$groupDatagrid->pagination = false;
$groupDatagrid->addElements = true;
$groupDatagrid->addPanelTitle = __('AF', 'configComponentDatagrid', 'groupAddPanelTitle');
$groupDatagrid->deleteElements = true;

// Label
$groupLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$groupLabel->editable = true;
$groupDatagrid->addCol($groupLabel);
// Ref
$groupRef = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$groupRef->editable = true;
$groupDatagrid->addCol($groupRef);
// Help
$groupHelp = new UI_Datagrid_Col_LongText('help', __('UI', 'name', 'help'));
$groupHelp->editable = true;
$groupHelp->popup->title = __('UI', 'name', 'help');
$groupDatagrid->addCol($groupHelp);
// Hidden / Show
$isVisible = new UI_Datagrid_Col_Bool('isVisible', __('AF', 'configComponentDatagrid', 'initialVisibilityHeader'));
$isVisible->editable = true;
$isVisible->defaultAddValue = true;
$isVisible->textTrue = __('UI', 'property', 'visible');
$isVisible->textFalse = __('UI', 'property', 'masked');
$isVisible->valueTrue = '<i class="icon-ok"></i> '.__('UI', 'property', 'visible');
$isVisible->valueFalse = '<i class="icon-remove"></i> '.__('UI', 'property', 'masked');
$groupDatagrid->addCol($isVisible);
// Foldaway / Unfoldaway
$isFoldawayGroup = new UI_Datagrid_Col_List('foldaway', __('AF', 'configComponentDatagrid', 'foldawayHeader'));
$isFoldawayGroup->editable = true;
$isFoldawayGroup->defaultAddValue = AF_Model_Component_Group::FOLDAWAY;
$isFoldawayGroup->withEmptyElement = false;
$isFoldawayGroup->list = array(
    AF_Model_Component_Group::FOLDAWAY => __('UI', 'property', 'foldaway'),
    AF_Model_Component_Group::UNFOLDAWAY => __('UI', 'property', 'nonFoldaway'),
    AF_Model_Component_Group::FOLDED => __('UI', 'property', 'folded'),
);
$groupDatagrid->addCol($isFoldawayGroup);

echo $groupDatagrid->render();
