<?php
/** @var $af AF_Model_AF */
$af = $this->af;

// Datagrid
$datagrid = new UI_Datagrid('textFieldDatagrid', 'datagrid_edit_components_text-fields', 'af');
$datagrid->initialLoading = false;
$datagrid->addParam('id', $af->getId());
$datagrid->pagination = false;
$datagrid->addElements = true;
$datagrid->addPanelTitle = __('AF', 'configComponentDatagrid', 'textAddPanelTitle');
$datagrid->deleteElements = true;

// Label
$checkboxLabel = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$checkboxLabel->editable = true;
$datagrid->addCol($checkboxLabel);

// Ref
$checkboxRef = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$checkboxRef->editable = true;
$datagrid->addCol($checkboxRef);

// Help
$help = new UI_Datagrid_Col_LongText('help', __('UI', 'name', 'help'));
$help->editable = true;
$help->popup->title = __('UI', 'name', 'help');
$datagrid->addCol($help);

// Hidden / Show
$isVisibleCheckbox = new UI_Datagrid_Col_Bool('isVisible', __('AF', 'configComponentDatagrid', 'initialVisibilityHeader'));
$isVisibleCheckbox->editable = true;
$isVisibleCheckbox->defaultAddValue = true;
$isVisibleCheckbox->textTrue = __('UI', 'property', 'visible');
$isVisibleCheckbox->textFalse = __('UI', 'property', 'masked');
$isVisibleCheckbox->valueTrue = '<i class="fa fa-check"></i> '.__('UI', 'property', 'visible');
$isVisibleCheckbox->valueFalse = '<i class="fa fa-times"></i> '.__('UI', 'property', 'masked');
$datagrid->addCol($isVisibleCheckbox);

// Enable / Disable
$enabledColumn = new UI_Datagrid_Col_Bool('enabled', __('AF', 'configComponentDatagrid', 'initialActivationHeader'));
$enabledColumn->editable = true;
$enabledColumn->defaultAddValue = true;
$enabledColumn->textTrue = __('UI', 'property', 'enabled');
$enabledColumn->textFalse = __('UI', 'property', 'disabled');
$enabledColumn->valueTrue = '<i class="fa fa-check"></i> '.__('UI', 'property', 'enabled');
$enabledColumn->valueFalse = '<i class="fa fa-times"></i> '.__('UI', 'property', 'disabled');
$datagrid->addCol($enabledColumn);

// Required
$requiredColumn = new UI_Datagrid_Col_Bool('required', __('AF', 'configComponentDatagrid', 'requiredHeader'));
$requiredColumn->editable = true;
$requiredColumn->defaultAddValue = false;
$requiredColumn->textTrue = __('UI', 'property', 'required');
$requiredColumn->textFalse = __('UI', 'property', 'optional');
$requiredColumn->valueTrue = '<i class="fa fa-check"></i> '.__('UI', 'property', 'required');
$requiredColumn->valueFalse = '<i class="fa fa-times"></i> '.__('UI', 'property', 'optional');
$datagrid->addCol($requiredColumn);

// Type
$typeColumn = new UI_Datagrid_Col_List('type', __('UI', 'name', 'type'));
$typeColumn->editable = true;
$typeColumn->list = [
    AF_Model_Component_Text::TYPE_SHORT => __('AF', 'configComponentDatagrid', 'textFieldTypeShort'),
    AF_Model_Component_Text::TYPE_LONG => __('AF', 'configComponentDatagrid', 'textFieldTypeLong'),
];
$datagrid->addCol($typeColumn);

echo $datagrid->render();
