<div class="page-header">
    <h1><?=__('User', 'login', 'connection')?></h1>
</div>

<?php
if ($this->user) {
    ?>
    <p>
        <?=__('User', 'login', 'youAreConnected')?>
        <?=$this->user->getName()?>.
    </p>
    <?php
} else {
    ?>
    <p>
        <?=__('User', 'login', 'youAreNotConnected')?>
    </p>
    <?php

    $form = new UI_Form("login");
    $form->setAction('user/action/login');
    $form->setAjax(true, 'loginSuccess');

    $email = new UI_Form_Element_Text('email');
    $email->setLabel(__('UI', 'name', 'emailAddress'));
    $form->addElement($email);

    $password = new UI_Form_Element_Password('password');
    $password->setLabel(__('User', 'login', 'password'));
    $form->addElement($password);

    $forgotPassword = new UI_Form_Element_HTML('forgotPasswordLogin');
    $forgotPassword->content = '<a class="fieldForgotPassword" href="user/password/forgotten">'
        . __('User', 'login', 'forgottenPassword')
        . '</a>';
    $form->addElement($forgotPassword);

    $form->addSubmitButton(__('User', 'login', 'connection'), 'connection');
    $form->display();
}

// Partial de création d'un compte.
// Recherche du partial de l'application.
if (Zend_Registry::isRegistered('user_actionlogin_forgotpassword')) {
    $path = Zend_Registry::get('user_actionlogin_forgotpassword');
    $this->setScriptPath(APPLICATION_PATH.'/views/scripts');
    $patialForgotPassword = $this->partial($path, []);
} else {
    $patialForgotPassword = null;
}

// Si le partial fournit une vue, elle est affichée dans un onglet.
if ($patialForgotPassword !== '') {
    ?>
    <div>
        <?=$patialForgotPassword?>
    </div>
    <?php
}
?>

<script>
    $.fn.loginSuccess = function () {
        var referer = '<?=$this->referer?>';
        if (referer != null && referer != '') {
            window.location.assign(referer);
        } else {
            window.location.reload();
        }
    };
</script>
