<div class="well no-padding">
    <form action="user/action/login" method="post" class="smart-form client-form">
        <header>
            <?=__('User', 'login', 'connection')?>
        </header>

        <fieldset>

            <section>
                <label class="input"> <i class="icon-append fa fa-user"></i>
                    <input type="email" name="email" required
                           placeholder="<?=__('User', 'user', 'emailAddress')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-user txt-color-teal"></i>
                        <?=__('User', 'user', 'emailAddress')?>
                    </b>
                </label>
            </section>

            <section>
                <label class="input"> <i class="icon-append fa fa-lock"></i>
                    <input type="password" name="password" required
                           placeholder="<?=__('User', 'login', 'password')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-lock txt-color-teal"></i>
                        <?=__('User', 'login', 'password')?>
                    </b>
                </label>
                <div class="note">
                    <a href="user/password/forgotten">
                        <?=__('User', 'login', 'forgottenPassword')?>
                    </a>
                </div>
            </section>

        </fieldset>

        <footer>

            <button type="submit" id="connection" class="btn btn-primary">
                <?=__('User', 'login', 'connection')?>
            </button>

            <?php if ($this->enableRegister) : ?>
                <a href="user/register" class="btn btn-default">
                    <?=__('User', 'register', 'register')?>
                </a>
            <?php endif; ?>

        </footer>
    </form>

</div>
