<div class="login-form">

    <h3><?=__('User', 'login', 'connection')?></h3>


    <?php
    if ($this->user) {
        ?>
        <p>
            <?=__('User', 'login', 'youAreConnected')?>
            <?=$this->user->getName()?>.
        </p>
        <?php
    } else {
        ?>
        <p>
            <?=__('User', 'login', 'youAreNotConnected')?>
        </p>
        <form action="user/action/login" method="post">
            <input type="text" name="email" class="input-block-level"
                   placeholder="<?= __('User', 'user', 'emailAddress')?>">
            <input type="password" name="password" class="input-block-level"
                   placeholder="<?=__('User', 'login', 'password')?>">

            <input type="submit" id="connection" class="btn btn-primary btn-block"
                   value="<?=__('User', 'login', 'connection')?>">

            <?php if ($this->enableRegister) : ?>
                <a href="user/action/register" class="btn btn-block">
                    <?=__('User', 'login', 'register')?></a>
            <?php endif; ?>

            <p>
                <a class="fieldForgotPassword" href="user/password/forgotten">
                    <?=__('User', 'login', 'forgottenPassword')?></a>
            </p>
        </form>
        <?php
    }
    ?>

</div>

<script>
    $.fn.loginSuccess = function () {
        var referer = '<?=$this->referer?>';
        if (referer != null && referer != '') {
            window.location.assign(referer);
        } else {
            window.location.reload();
        }
    };
</script>
