<div class="login-form">

    <h3><?=__('User', 'login', 'register')?></h3>

    <form action="user/action/register" method="post">
        <input type="text" name="email" class="input-block-level"
               placeholder="<?=__('User', 'user', 'emailAddress')?>"
               value="<?=$this->email?>">
        <input type="password" name="password" class="input-block-level"
               placeholder="<?=__('User', 'login', 'password')?>">
        <input type="password" name="password2" class="input-block-level"
               placeholder="<?=__('User', 'login', 'passwordAgain')?>">

        <input type="submit" id="connection" class="btn btn-primary btn-block"
               value="<?=__('User', 'login', 'register')?>">

        <p>
            <?=__('User', 'login', 'alreadyRegistered')?>
        </p>

        <a href="user/action/login" class="btn btn-block">
            <?=__('User', 'login', 'connection')?></a>
    </form>

</div>
