<div class="well no-padding">
    <form action="user/register" method="post" class="smart-form client-form">
        <header>
            <?=__('User', 'register', 'register')?>
        </header>

        <fieldset>

            <section>
                <label class="input">
                    <i class="icon-append fa fa-inbox"></i>

                    <input type="text" name="projectName" required
                           placeholder="<?=__('User', 'register', 'projectName')?>"
                           value="<?=$this->projectName?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-user txt-color-teal"></i>
                        <?=__('User', 'register', 'projectName')?>
                    </b>
                </label>
            </section>

            <section>
                <label class="input">
                    <i class="icon-append fa fa-user"></i>
                    <input type="email" name="email"
                           placeholder="<?=__('User', 'user', 'emailAddress')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-user txt-color-teal"></i>
                        <?=__('User', 'user', 'emailAddress')?>
                    </b>
                </label>
            </section>

            <section>
                <label class="input">
                    <i class="icon-append fa fa-lock"></i>
                    <input type="password" name="password"
                           placeholder="<?=__('User', 'register', 'password')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-lock txt-color-teal"></i>
                        <?=__('User', 'register', 'password')?>
                    </b>
                </label>
            </section>

            <section>
                <label class="input">
                    <i class="icon-append fa fa-lock"></i>
                    <input type="password" name="password2"
                           placeholder="<?=__('User', 'register', 'passwordAgain')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-lock txt-color-teal"></i>
                        <?=__('User', 'register', 'passwordAgain')?>
                    </b>
                </label>
            </section>

            <section>
                <?php
                $captcha = new UI_Form_Element_Captcha('captcha', 'user/captcha/newimage');
                $captcha->setLabel(__('User', 'register', 'captchaFieldLabel'));
                $captcha->setRequired();
                echo $captcha->render();
                ?>
            </section>

        </fieldset>

        <footer>

            <button type="submit" id="connection" class="btn btn-primary">
                <?=__('User', 'register', 'register')?>
            </button>

        </footer>

        <footer>

            <p>
                <?=__('User', 'register', 'alreadyRegistered')?>
            </p>

            <a href="user/action/login" class="btn btn-default">
                <?=__('User', 'login', 'connection')?>
            </a>

        </footer>
    </form>

</div>
