<div class="well no-padding">
    <form action="user/register" method="post" class="smart-form client-form">
        <header>
            <?=__('User', 'register', 'register')?>
        </header>

        <fieldset>

            <section>
                <label class="select">
                    <select name="projectType" required>
                        <option value=""<?php if (empty($this->projectType)) : ?> selected<?php endif; ?> disabled>
                            <?=__('User', 'register', 'projectType')?>
                        </option>
                        <?php if ($this->registerIndividual) : ?>
                            <option value="pme"<?php if ($this->projectType === 'individual') : ?> selected<?php endif; ?>>
                                <?=__('User', 'register', 'projectTypeIndividual')?>
                            </option>
                        <?php endif; ?>
                        <?php if ($this->registerCollectivity) : ?>
                            <option value="collectivity"<?php if ($this->projectType === 'collectivity') : ?> selected<?php endif; ?>>
                                <?=__('User', 'register', 'projectTypeCollectivity')?>
                            </option>
                        <?php endif; ?>
                        <?php if ($this->registerSMEs) : ?>
                            <option value="pme"<?php if ($this->projectType === 'pme') : ?> selected<?php endif; ?>>
                                <?=__('User', 'register', 'projectTypeSMEs')?>
                            </option>
                        <?php endif; ?>
                    </select>
                    <i></i>
                </label>
            </section>

            <section>
                <label class="input">
                    <i class="icon-append fa fa-user"></i>
                    <input type="email" name="email"
                           value="<?=$this->email?>"
                           placeholder="<?=__('User', 'user', 'emailAddress')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-user txt-color-teal"></i>
                        <?=__('User', 'user', 'emailAddress')?>
                    </b>
                </label>
            </section>

            <section>
                <label class="input">
                    <i class="icon-append fa fa-lock"></i>
                    <input type="password" name="password"
                           placeholder="<?=__('User', 'register', 'password')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-lock txt-color-teal"></i>
                        <?=__('User', 'register', 'password')?>
                    </b>
                </label>
            </section>

            <section>
                <label class="input">
                    <i class="icon-append fa fa-lock"></i>
                    <input type="password" name="password2"
                           placeholder="<?=__('User', 'register', 'passwordAgain')?>">
                    <b class="tooltip tooltip-top-right">
                        <i class="fa fa-lock txt-color-teal"></i>
                        <?=__('User', 'register', 'passwordAgain')?>
                    </b>
                </label>
            </section>

            <section>
                <?php
                $captcha = new UI_Form_Element_Captcha('captcha', 'user/captcha/newimage');
                $captcha->setLabel(__('User', 'register', 'captchaFieldLabel'));
                $captcha->setRequired();
                echo $captcha->render();
                ?>
            </section>

        </fieldset>

        <footer>

            <button type="submit" id="connection" class="btn btn-primary">
                <?=__('User', 'register', 'register')?>
            </button>

        </footer>

        <footer>

            <p>
                <?=__('User', 'register', 'alreadyRegistered')?>
            </p>

            <a href="user/action/login" class="btn btn-default">
                <?=__('User', 'login', 'connection')?>
            </a>

        </footer>
    </form>

</div>
