<?php

use Parameter\Domain\Family\Family;

UI_Form::addHeader();
UI_Datagrid::addHeader();
UI_TMD::addHeader();

/** @var $family Family */
$family = $this->family;

if ($this->edit) {
    $collapseGeneralData = new UI_HTML_Collapse('collapseGeneralData');
    $collapseGeneralData->title = __('Parameter', 'familyDetail', 'generalDataTitle');
    $collapseGeneralData->foldedByDefault = true;
    $collapseGeneralData->body = $this->partial('family/details/general-edit.phtml', [
        'family' => $family,
    ]);
    $generalData = $collapseGeneralData->render();
} else {
    $generalData = $this->partial('family/details/general-view.phtml', [
         'family' => $family,
    ]);
}

?>

<div class="page-header">
    <h1><?=$this->escape($family->getLabel())?></h1>
</div>

<?php
echo $generalData;

// TMD
$tmd = $this->partial('family/details/tmd.phtml', [
    'family' => $family,
    'edit'   => $this->edit,
]);
if ($this->edit) {
    $collapseTMD = new UI_HTML_Collapse('collapseTMD', __('Parameter', 'element', 'elements'));
    $collapseTMD->body = $tmd;
    $collapseTMD->display();
} else {
    echo "<legend>" . __('UI', 'name', 'elements') . "</legend>";
    echo $tmd;
}

// Edition
if ($this->edit) {
    $collapseEditDimensions = new UI_HTML_Collapse('collapseEditDimensions');
    $collapseEditDimensions->title = __('Parameter', 'name', 'dimensions');
    $collapseEditDimensions->body = $this->partial('family/details/edit-dimensions.phtml', ['family' => $family]);
    echo $collapseEditDimensions->render();
}
