<div class="page-header">
    <h1><?=__('Parameter', 'familyList', 'familyList')?></h1>
</div>

<?php

$datagrid = new UI_Datagrid('familyDatagrid', 'datagrid_family-datagrid', 'parameter');
$datagrid->addParam('mode', $this->mode);

$columns = [];

$columns['category'] = new UI_Datagrid_Col_List('category', __('UI', 'name', 'category'));
$list = [];
foreach ($this->categoryList as $category) {
    /** @var $category Parameter\Domain\Category */
    $list[$category->getId()] = $category->getLabel();
}
$columns['category']->list = $list;
$columns['category']->fieldType = UI_Datagrid_Col_List::FIELD_LIST;
$columns['category']->addable = true;

$columns['label'] = new UI_Datagrid_Col_Text('label', __('UI', 'name', 'label'));
$columns['label']->addable = true;

$columns['ref'] = new UI_Datagrid_Col_Text('ref', __('UI', 'name', 'identifier'));
$columns['ref']->addable = true;

$columns['unit'] = new UI_Datagrid_Col_Text('unit', __('Unit', 'name', 'unit'));
$columns['unit']->addable = true;

$columns['detail'] = new UI_Datagrid_Col_Link('detail', __('UI', 'name', 'details'));
$columns['detail']->addable = false;

foreach ($columns as $key => $column) {
    $column->editable = false;
    $datagrid->addCol($column);
}

if ($this->mode == 'edition') {
    $datagrid->addElements = true;
    $datagrid->addPanelTitle = __('Parameter', 'familyList', 'addPanelTitle');
}

$datagrid->display();
