<?php
use Parameter\Application\Form\AddNodeForm;
?>
<div class="page-header">
    <h1><?=__('Parameter', 'familyTree', 'familyTree')?></h1>
</div>

<?php
$tree = new UI_Tree('familyTree', 'tree_family-tree', 'parameter');
$tree->expandAll = false;
$tree->collapseAll = false;
$tree->addParam('mode', $this->mode);

if ($this->mode == 'edition') {
    // Ajout.
    $tree->addNode = true;
    $addForm = new AddNodeForm('addNode');
    $tree->addPanelForm = $addForm;
    $tree->addPanelTitle = __('Parameter', 'familyTree', 'addCategoryPopupTitle');
    $tree->addButtonLabel = __('Parameter', 'familyTree', 'addCategoryButton');
    // Édition.
    $editLabel = new UI_Form_Element_Text('familyTree_labelEdit');
    $editLabel->setLabel(__('UI', 'name', 'label'));
    $htmlComplement = new UI_Form_Element_HTML('familyTree_htmlComplement');
    $htmlComplement->setLabel('');
    $tree->setEditNode(true, true, [$editLabel, $htmlComplement]);
    $tree->editPanelTitle = __('Parameter', 'familyTree', 'editCategoryPopupTitle');
    // Suppression.
    $tree->deleteNode = true;
}

$tree->display();


if ($this->mode == 'edition') {
    ?>
    <script>
        $(function() {
            $('#familyTree_element').change(function(e) {
                var idNode = $(this).val();
                $.get('parameter/tree_family-tree/getinfoedit?idNode=' + idNode,
                    function(o){
                        $('#familyTree_labelEdit').val(o.label);
                        $('#familyTree_htmlComplement').html(o.htmlComplement);
                        $('#familyTree_editPanel > div.modal-header > h3').html(o.titlePopup);
                    }
                ).error(function(o) {
                    errorHandler(o);
                });
            });
            $('#familyTree_addPanel').on('show', function(e) {
                $.get('parameter/tree_family-tree/getlistparents?idNode=',
                    function(o){
                        $('#addAxis_parent').formActionSetOptions(o);
                    }
                ).error(function(o) {
                    errorHandler(o);
                });
            });
        });
    </script>
    <?php
}
