<script type="text/javascript">
    window.af = <?=json_encode($this->serializedAF)?>;
    window.inputSet = <?=json_encode($this->serializedInputSet)?>;
    window.afUrlParams = <?=json_encode($this->urlParams)?>;

    // Traductions
    // Statut avancement saisie
    <?=Core_Translate::exportJS('AF', 'inputInput', 'statusInProgress')?>
    <?=Core_Translate::exportJS('AF', 'inputInput', 'statusInputIncomplete')?>
    <?=Core_Translate::exportJS('AF', 'inputInput', 'statusCalculationIncomplete')?>
    <?=Core_Translate::exportJS('AF', 'inputInput', 'statusComplete')?>
    <?=Core_Translate::exportJS('AF', 'inputInput', 'statusFinished')?>
    // Validation de la saisie
    <?=Core_Translate::exportJS('AF', 'inputInput', 'emptyRequiredField')?>
    <?=Core_Translate::exportJS('UI', 'formValidation', 'invalidNumber')?>
    <?=Core_Translate::exportJS('UI', 'formValidation', 'invalidUncertainty')?>
    // Popups de confirmation au clic sur « Réinitialiser » ou « Quitter »
    <?=Core_Translate::exportJS('AF', 'inputInput', 'confirmReinitializeInput')?>
    <?=Core_Translate::exportJS('AF', 'inputInput', 'confirmExitInput')?>
    <?=Core_Translate::exportJS('UI', 'verb', 'cancel')?>
    <?=Core_Translate::exportJS('UI', 'verb', 'confirm')?>
    <?=Core_Translate::exportJS('Core', 'exception', 'applicationError')?>
    // Historique de la saisie
    <?=Core_Translate::exportJS('UI', 'history', 'valueHistory')?>
</script>

<div ng-app="AF" ng-controller="InputController">

    <div class="inputProgress row">

        <div class="col-md-9">
            <div class="progress">
                <div class="progress-bar" ng-style="{ width: inputSet.completion + '%' }">
                    {{ inputSet.completion }} %
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <img class="completionIcon" src="">
            <span class="completionMessage" ng-bind="inputStatuses[inputSet.status] || inputStatuses['input_incomplete']"></span>
        </div>

    </div>

    <form class="af form-horizontal">

        <af-fieldset components="af.components" input-set="inputSet"></af-fieldset>

        <div class="form-actions">
            <div class="row">
                <div class="col-md-12">

                    <button type="button" class="btn btn-default" ng-click="preview()"
                            btn-loading="previewIsLoading"
                            data-loading-text="<i class='fa-spin fa fa-spinner'></i> <?= __('AF', 'inputInput', 'resultsPreview') ?>">
                        <?= __('AF', 'inputInput', 'resultsPreview') ?>
                    </button>

                    <button type="button" class="btn btn-default" ng-click="save()"
                            btn-loading="saving"
                            data-loading-text="<i class='fa-spin fa fa-spinner'></i> <?= __('UI', 'verb', 'save') ?>">
                        <?= __('UI', 'verb', 'save') ?>
                    </button>

                    <button type="button" class="btn btn-default" ng-click="finish()"
                            btn-loading="markingInputAsFinished"
                            data-loading-text="<i class='fa-spin fa fa-spinner'></i> <?= __('AF', 'inputInput', 'finish') ?>">
                        <?= __('AF', 'inputInput', 'finish') ?>
                    </button>

                    <button type="button" class="btn btn-default">
                        <i class="fa fa-sign-out"></i>
                        <?= __('UI', 'verb', 'quit') ?>
                    </button>

                </div>
            </div>
        </div>

    </form>

    <div class="resultsPreview" ng-if="resultsPreview">
        <div class="alert alert-info">
            <?=__('AF', 'inputInput', 'resultsPreview')?>
        </div>
        <div class="resultsPreviewContent" ng-bind-html="resultsPreview | rawHtml"></div>
    </div>

    <pre ng-bind="inputSet | debug"></pre>
    <pre ng-bind="af | debug"></pre>

</div>
