<form id="duplicateAF" class="form-horizontal" method="post"
      action="af/af/duplicate?idAF=<?=$this->id?>&library=<?=$this->library->getId()?>">
    <div class="form-group">
        <label class="col-sm-2 control-label">
            <?=__('UI', 'name', 'label')?>
        </label>
        <div class="col-sm-10">
            <input name="label" type="text" class="form-control">
        </div>
    </div>
</form>

<script>
    $(function() {
        $("#submit").click(function () {
            $("#duplicateAF").submit();
        });
    });
</script>
